### ISSUE TITLE
是否考虑把视频预览插件使用dplayer？

### ISSUE THREAD

**Issue by FaintGhost** [reruin/sharelist#100]
用过其他的OneDrive列表程序，觉得dplayer的播放能力和兼容性很强

**Comment by DragonFSKY** [comment]
+! 目前mp4有播放黑屏的问题

**Comment by reruin** [comment]
已添加。更新后，在后台管理 -> 视频预览播放器 选择DPlayer.

**Comment by DragonFSKY** [comment]
> 已添加。更新后，在后台管理->视频预览播放器选择DPlayer。

请问如何更新呢 直接覆盖安装吗

**Comment by FaintGhost** [comment]
大佬给力啊！！！
