### ISSUE TITLE
如何挂载谷歌团队盘

### ISSUE THREAD

**Issue by DragonFSKY** [reruin/sharelist#102]
用googledriveAPI一路挂载下去并没有出现团队盘的选择,团队盘支持api

**Comment by chinatengjie** [comment]
目录ID啊

**Comment by loveqianool** [comment]
我的团队盘是别人共用给我的，我没有权限取得共用 id 。
我用 https://github.com/donwa/goindex 可以直接使用 目录id 挂载，但是 sharelist 使用目录id 会出现 Not Found。

**Comment by zyk445971319** [comment]
直接添加默认的目录加完之后在后台里面修改挂载目录root为你的共享盘的id保存就可以了 我就是这么做的

**Comment by loveqianool** [comment]
> 直接添加默认的目录加完之后在后台里面修改挂载目录root为你的共享盘的id保存就可以了 我就是这么做的

能详细说一下吗？我这边尝试了一下，没有成功。

**Comment by zyk445971319** [comment]
搭建完挂载谷歌drive 这时候是你本身的15g，进管理界面最下面虚拟路径修改apps.googleusercontent.com/root?client_secret=这一段中间的root改成你的团队盘目录id   我搭建的kalus.cf:33001

**Comment by zyk445971319** [comment]
我是api挂载的

**Comment by zongxinqian** [comment]
> 搭建完挂载谷歌drive 这时候是你本身的15g，进管理界面最下面虚拟路径修改apps.googleusercontent.com/root?client_secret=这一段中间的root改成你的团队盘目录id 我搭建的kalus.cf:33001

thank you

**Comment by ventusoon** [comment]
> 搭建完挂载谷歌drive 这时候是你本身的15g，进管理界面最下面虚拟路径修改apps.googleusercontent.com/root?client_secret=这一段中间的root改成你的团队盘目录id 我搭建的kalus.cf:33001

太感谢了，一步到位！
