### ISSUE TITLE
Google Docs files 不能直接打開或下載，能否解決?

### ISSUE THREAD

**Issue by ericishere** [reruin/sharelist#104]
thx

**Comment by ericishere** [comment]
{
  "error": {
    "errors": [
      {
        "domain": "global",
        "reason": "fileNotDownloadable",
        "message": "Only files with binary content can be downloaded. Use Export with Google Docs files.",
        "locationType": "parameter",
        "location": "alt"
      }
    ],
    "code": 403,
    "message": "Only files with binary content can be downloaded. Use Export with Google Docs files."
  }
}

**Comment by reruin** [comment]
能否发下具体链接以供定位。

**Comment by MOeric10y** [comment]
http://www.cnrobot.best/20192020/2019/%E5%85%B6%E4%BB%96/1_RoboMaster%2B2019%E6%BE%B3%E9%96%80%E9%9D%92%E5%B0%91%E5%B9%B4%E6%A9%9F%E6%A2%B0%E4%BA%BA%E5%A4%A7%E8%B3%BD%E6%AF%94%E8%B3%BD%E8%A6%8F%E5%89%87%E6%89%8B%E5%86%8AV1.0

**Comment by reruin** [comment]
这似乎不是一个有效的文件。

**Comment by MOeric10y** [comment]
好吧
