### ISSUE TITLE
OneDrive通过应用机密和appid挂载出现错误。

### ISSUE THREAD

**Issue by jonnyq** [reruin/sharelist#109]
Error
Looks like something broke!

        
TypeError: Cannot read property 'map' of undefined
    at Object.folder (/sharelist/plugins/drive.od.api.js:397:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by reruin** [comment]
请拉取最新版的代码试试。

**Comment by msn1983aa** [comment]
> 请拉取最新版的代码试试。

今天试最新的代码，出现一样的错误，gd、od、天翼云都是类似的报错

**Comment by reruin** [comment]
> > 请拉取最新版的代码试试。
> 
> 今天试最新的代码，出现一样的错误，gd、od、天翼云都是类似的报错

能否提供更多的挂载信息。

**Comment by svlic** [comment]
遇到同样错误，onedrive edu/个人版
