### ISSUE TITLE
可以开发宝塔安装吗？

### ISSUE THREAD

**Issue by FemalePresident** [reruin/sharelist#112]
大佬，你好：

该程序可以开发宝塔安装么？目前一直在用 https://www.moerats.com/archives/594/ 搭建的教程，安装完后发现网站无法打开，错误提示为：dial tcp IP:33001: connect: connection refused。参考评论里给出的解决方法：cd /root/sharelist && pm2 start app.js 仍然无效。
而宝塔安装对新手比较友好，希望大佬可以开发一下。

谢谢。

**Comment by reruin** [comment]
前面有几次提交，默认端口被改成了51221。你重新安装一遍就可以了。

**Comment by FemalePresident** [comment]
是重新安装该教程中的脚本吗？ 脚本用caddy反代，需要变更反代的端口吗？

**Comment by reruin** [comment]
不需要做任何更改，直接按照教程重装一遍就行。

**Comment by FemalePresident** [comment]
好的 我去试试

大佬 该程序能可以开发用宝塔搭建么？下载文件出错后想重装系统，又不想重新配置该程序。如果用宝塔搭建后会更稳定。 大佬，可以考虑一下么？

**Comment by reruin** [comment]
你指的是宝塔应用吗？

**Comment by FemalePresident** [comment]
宝塔面板 https://www.bt.cn/

萌新都喜欢这个。只要教程详细，无脑上手。

**Comment by reruin** [comment]
支持的。宝塔面板里有PM2管理器，具体安装过程可自行搜索下”宝塔面板 部署 nodejs“。

**Comment by FemalePresident** [comment]
谢谢！

**Comment by FemalePresident** [comment]
大佬 已成功搭建，参考该教程前半部分 https://www.bwmelon.com/archives/27/

但是发现个问题，在该 https://www.moerats.com/archives/594/ 教程中所使用是翻墙的流量，而用宝塔搭建后，观看视频的流量是服务器本身的上传速度。我是用阿里云试用机搭建，上传只有1M，导致视频无法观看。这个问题有解决的办法么？

**Comment by reruin** [comment]
目前 gd挂载方式都需要强制服务器中转，会受限于服务器的带宽。

**Comment by FemalePresident** [comment]
大佬 ，经过一天的测试发现如下问题：

电脑端：小视频无问题，大视频文件无法观看，硬盘空间好像有增加
手机端：大小视频都无法观看

反代参数：
server
{
    listen 80;
	listen 443 ssl http2;
    server_name xxx;
    proxy_set_header Host  $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    
    proxy_set_header Range $http_range;
    proxy_set_header If-Range $http_if_range;
    proxy_no_cache $http_range $http_if_range;
    index index.php index.html index.htm default.php default.htm default.html;
    root /www/wwwroot/xxx;
    
    #SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
    #error_page 404/404.html;
    #HTTP_TO_HTTPS_START
    if ($server_port !~ 443){
        rewrite ^(/.*)$ https://$host$1 permanent;
    }
    #HTTP_TO_HTTPS_END
    ssl_certificate    /www/server/panel/vhost/cert/xxx/fullchain.pem;
    ssl_certificate_key    /www/server/panel/vhost/cert/xxx/privkey.pem;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    error_page 497  https://$host$request_uri;

    #SSL-END
    
    #ERROR-PAGE-START  错误页配置，可以注释、删除或修改
    #error_page 404 /404.html;
    #error_page 502 /502.html;
    #ERROR-PAGE-END
    
    #PHP-INFO-START  PHP引用配置，可以注释或修改
    #清理缓存规则

    location ~ /purge(/.*) {
        proxy_cache_purge cache_one $host$1$is_args$args;
        #access_log  /www/wwwlogs/xxx_purge_cache.log;
    }
	#引用反向代理规则，注释后配置的反向代理将无效
	include /www/server/panel/vhost/nginx/proxy/xxx/*.conf;

	include enable-php-00.conf;
    #PHP-INFO-END
    
    #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
    include /www/server/panel/vhost/rewrite/xxx.conf;
    #REWRITE-END
    
    #禁止访问的文件或目录
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }
    
    #一键申请SSL证书验证目录相关设置
    location ~ \.well-known{
        allow all;
    }
    
    access_log  /www/wwwlogs/xxx.log;
    error_log  /www/wwwlogs/xxx.error.log;
}

通过控制面板强制开启SSL，访问正常。

**Comment by FemalePresident** [comment]
大佬 你好：
按照 https://www.moerats.com/archives/594/ 安装完成后 仍然无法打开安装页面。
app.js运行正常，发现npm报错，错误如下：
root@debian:~# npm run start
npm ERR! path /root/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/root/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-28T07_30_27_883Z-debug.log

能帮忙看下吗？

**Comment by reruin** [comment]
执行命令的路径不对吧...

**Comment by FemalePresident** [comment]
root@ubuntu:~# cd /root/sharelist
root@ubuntu:~/sharelist# npm run start

> sharelist@0.1.0 start /root/sharelist
> node app.js

module.js:550
    throw err;
    ^

Error: Cannot find module 'koa'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/sharelist/app/index.js:1:75)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharelist@0.1.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharelist@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-28T12_39_52_359Z-debug.log

大佬 快被折磨疯了...  caddy的日志还是提示33001端口没打开，网页显示502错误...

**Comment by reruin** [comment]
在 /root/sharelist 下执行 bash install.sh
