### ISSUE TITLE
有隐藏目录的功能吗?

### ISSUE THREAD

**Issue by iLaoDi** [reruin/sharelist#113]
感谢大佬的项目

可以隐藏目录吗? 不显示或者直接不读取.

**Comment by iLaoDi** [comment]
遇到一个新问题...
世纪互联的配置按照教程所填写的.一开始列表可以正常使用
过了一段时间后 无法登陆提示表达式“me/drive/items/getByPath('/odc')/****(应用id)///children”无效。 
检测配置 发生变动,再次还原又可以正常使用.

**Comment by reruin** [comment]
> 感谢大佬的项目
> 
> 可以隐藏目录吗? 不显示或者直接不读取.

后台管理中可设置 忽略文件路径。

**Comment by iLaoDi** [comment]
虚拟路径 OD API和GD API中的的第一配置 都异常。 再生产一个相同的配置再前端可以显示正常，而第一个会报错。 OD显示为 无法登陆提示表达式，GD显示为 NOT FOUND.
大概情况就是配置 前面会生成 一个配置。
OD好像是应用ID。
GD好像是一个网址。

**Comment by reruin** [comment]
修改了保存配置的策略，你拉取最新代码试一下。

**Comment by iLaoDi** [comment]
好的..

**Comment by iLaoDi** [comment]
> 修改了保存配置的策略，你拉取最新代码试一下。

我拉去了最新的代码 好像还是一样的.
https://i.loli.net/2020/02/27/wsrAPzXhdDVWOoF.png
保存配置的时候是这样 可以正常的显示.

https://i.loli.net/2020/02/27/CspM4yrgLEXx32u.png
保存配置后过一会就变成这个样子了. 

https://i.loli.net/2020/02/27/HSihTXE2nbjGVvC.png
https://i.loli.net/2020/02/27/vH5Em7JAuSMFfP6.png
前端打开世纪互联和谷歌网盘就报错.

是我哪里设置错误了吗?

**Comment by reruin** [comment]
这里不要填 ```协议名:```，odc，gda直接以```//```
