### ISSUE TITLE
能否添加为onedrive/gdrive分别设置代理与否

### ISSUE THREAD

**Issue by BOBMASRER** [reruin/sharelist#114]
感谢大佬的项目，非常的好用。如题，能否为onedrive不代理网址，gdrive代理网址，将两者分开，因为同时这样搞，服务器流量消耗有点大。

**Comment by reruin** [comment]
更新后，在 ```后台管理--中转路径``` 处可设置对应的路径，如若全局中转，留空即可。  
此外，gd默认是强制代理的，故禁用中转也能满足要求。

**Comment by BOBMASRER** [comment]
谢谢谢谢！
