### ISSUE TITLE
作者能否增加天翼云盘支持

### ISSUE THREAD

**Issue by xiewenxuan** [reruin/sharelist#116]
因为天翼云盘良好的速度和不限文件大小，又不用翻墙，能否增加这个网盘的支持，非常感谢。

**Comment by reruin** [comment]
暂缺稳定的app_key 和 app_secret 用于测试。如果你有的话 能否 分享一个。

**Comment by xiewenxuan** [comment]
我网上找了一个你看能不能用。
app_secret="93c6a3491a5e1d93af0e44b470798148"
app_key="600102343"

Ting <notifications@github.com> 于 2020年2月27日周四 上午9:29写道：

**Comment by reruin** [comment]
这个早前试了不行。

**Comment by xiewenxuan** [comment]
那就没有了，据说是github上搜cloud.189.cn说有几个开源的。

Ting <notifications@github.com> 于 2020年2月28日周五 下午8:34写道：

**Comment by liangxinlin** [comment]
这个api是可以用的，要增加一个FD=safebox参数，然后在我的云盘-我的应用下建立一个safebox文件夹,原因是这个API只能访问我的应用下的safebox文件夹，绝版key

**Comment by reruin** [comment]
是的。插件已经写好了。

**Comment by reruin** [comment]
天翼云插件已完成，支持API挂载 和 账号密码（cookie）方式挂载。

**Comment by xiewenxuan** [comment]
明白了，怪不得呢

lostknife <notifications@github.com> 于 2020年3月3日周二 下午3:33写道：

**Comment by iwestlin** [comment]
> 93c6a3491a5e1d93af0e44b470798148

这个key今天好像失效了，大家谁还有能用的吗。。
