### ISSUE TITLE
webdav密码能否不跟后台管理密码一样

### ISSUE THREAD

**Issue by whyun1** [reruin/sharelist#117]
如果可以的话，要在哪里修改代码?
密码不一样分享的话比较安全。
谢谢

**Comment by reruin** [comment]
修改此处https://github.com/reruin/sharelist/blob/a7809738c215b42dfc14062d0c1ef2093bd9374f/app/middleware/koa-paths.js#L120

**Comment by whyun1** [comment]
已解决，感谢！
