### ISSUE TITLE
世纪互联的中转地址也是用官方api的那个吗？

### ISSUE THREAD

**Issue by whyun1** [reruin/sharelist#118]
世纪互联的中转地址也是用官方api的那个吗？

**Comment by whyun1** [comment]
试了，可以。但怎么显示不了目录和文件？

**Comment by whyun1** [comment]
重新绑定出现问题，“挂载 OneDrive 失败
没有收到返回结果。”

**Comment by reruin** [comment]
你看看后台管理，虚拟路径处是否已经生成了配置。类似以下的形式：
```
//应用ID/路径?client_secret=应用机钥&redirect_uri=回调地址&refresh_token=refresh_token&tenant=组织名   
```

**Comment by whyun1** [comment]
//应用ID/?client_secret=应用机钥&redirect_uri=回调地址&refresh_token=refresh_token&tenant=组织名  
?clent_secret前面没有东西

**Comment by reruin** [comment]
截图看以下。

**Comment by whyun1** [comment]
![1](https://user-images.githubusercontent.com/61374470/75507613-8f6b9d00-5a1c-11ea-95ab-a40c1ee78f4c.jpg)
![2](https://user-images.githubusercontent.com/61374470/75507616-909cca00-5a1c-11ea-8399-dd5913a476da.jpg)
![3](https://user-images.githubusercontent.com/61374470/75507623-91cdf700-5a1c-11ea-9fdb-f7882fa0d61d.jpg)

**Comment by whyun1** [comment]
搞定了，权限问题。谢谢
