### ISSUE TITLE
部署在HeroApp会定期自动初始化 ，需要重新配置

### ISSUE THREAD

**Issue by chian0sen** [reruin/sharelist#119]
感觉像是Hreo没有保存配置一样，希望大佬能够修复

**Comment by reruin** [comment]
初始化后，从后台导出配置信息，并赋给CONFIG这个环境变量，可在对应App 的 Settings->Reveal Config Vars 下找到此变量。

**Comment by mildredborchert** [comment]
赋予变量就行了？

**Comment by mildredborchert** [comment]
![image](https://user-images.githubusercontent.com/63134858/78750333-9d5cf800-79a2-11ea-9628-6aae6ab29aae.png)

**Comment by mildredborchert** [comment]
这样是不是不用赋予变量了？
