### ISSUE TITLE
OneDriveAPI-上传超过4MB的文件报错 undefined

### ISSUE THREAD

**Issue by Amarillys** [reruin/sharelist#121]
请问一下，上传失败，报错undefined是为什么呢
在edge和chrome测试了

前端JavaScript status: 500
pm2查看后台日志(具体放在附件，为了安全删去了jwt部分):
```
body: {
  error: {
    code: '-1, Microsoft.SharePoint.Client.InvalidClientQueryException',
    message: 'JSON 流的格式不正确。',
    innerError: [Object]
  }
}
```

[sharelist.log](https://github.com/reruin/sharelist/files/4280277/sharelist.log)

感谢

**Comment by reruin** [comment]
报错时，页面的进度条走有没有走到100%？

**Comment by Amarillys** [comment]
> 报错时，页面的进度条走有没有走到100%？

走完了，上传100%之后报的

**Comment by reruin** [comment]
了解了，稍后我去测试下。

**Comment by reruin** [comment]
更新下代码试试。

**Comment by Amarillys** [comment]
测试通过，问题解决了，感谢！
