### ISSUE TITLE
GoogleDrive挂载无法预览播放

### ISSUE THREAD

**Issue by wekingchen** [reruin/sharelist#122]
GoogleDrive使用分享ID挂载的目录，最近两个版本更新后，无法预览播放了，但目录读取正常。使用官方API挂载的播放正常。

**Comment by reruin** [comment]
你更新下试试，近期gd修改了匿名下载文件的策略。

**Comment by wekingchen** [comment]
你好，抓取最新代码后可以了，谢谢
