### ISSUE TITLE
直接访问下级子目录可以跳过密码

### ISSUE THREAD

**Issue by chian0sen** [reruin/sharelist#123]
比如设置“/01”文件夹有密码，“/01“下有文件夹”/02“,可以直接在地址栏访问”/01/02“,不要密码，如果在每个子文件夹下都设置密码文件就会显得很繁琐，希望大佬能够改进

**Comment by emengweb** [comment]
同发现这个问题，希望后台可以增加个选项，类似于“同步加密子目录”

**Comment by reruin** [comment]
密码功能已增强，可嵌套加密。
