### ISSUE TITLE
挂载后，转成WebDav输出有问题

### ISSUE THREAD

**Issue by lostknife** [reruin/sharelist#124]
网址直接访问webDav显示404，但是在Windows添加网络位置可以添加，可以显示文件列表，打开、复制则显示文件不存在或已删除

**Comment by reruin** [comment]
1. webdav屏蔽了浏览器直接访问。
2. 目前的webdav只支持列表、查看（打开），不支持其他操作。
3. 最近修复过一个无法查看的bug（部分挂载盘存在判定ua策略），你可拉取最新代码试试。
