### ISSUE TITLE
世纪互联该怎么绑定？

### ISSUE THREAD

**Issue by vbqgyy** [reruin/sharelist#127]
用新版本输入的/，自动按引导输入密码和id，修改了n次回调地址以后，用了回调地址https://reruin.github.io/redirect/onedrive.html，终于没有报错，但是进去文件夹却没有显示里面的文件，该怎么解决？

**Comment by reruin** [comment]
回调地址是默认的。方便发一下链接么。

**Comment by vbqgyy** [comment]
http://putilu.fun/yussj

**Comment by reruin** [comment]
先清一下缓存

**Comment by vbqgyy** [comment]
清除缓存和重启都试了 还是一样的问题

**Comment by reruin** [comment]
方便的话，去后台管理处，将配置导出，发我邮箱看下。

**Comment by vbqgyy** [comment]
已经发送

Ting <notifications@github.com> 于2020年3月10日周二 下午8:28写道：
