### ISSUE TITLE
挂载 OneDrive 失败

### ISSUE THREAD

**Issue by Omoinemie** [reruin/sharelist#128]
这回调地址到底是什么东西，挂载5T网盘总是失败！
挂载 OneDrive 失败
AADSTS500112: The reply address 'http://yun.vomiku.com/' does not match the reply address 'https://reruin.github.io/redirect/onedrive.html' provided when requesting Authorization code. Trace ID: fb4ba0d0-becd-450c-a71cCorrelation ID: 45f8df0d-527e-4612-a0Timestamp: 2020-03-11 11:18:58Z

**Comment by Mit2g** [comment]
可以参考这个 https://github.com/reruin/sharelist/issues/160#issuecomment-619952865

**Comment by reruin** [comment]
更新代码。

1. 如果使用 http 的访问地址，请在重定向那里填写```https://reruin.github.io/redirect/onedrive.html```。
2. 如果使用 https ，则填实际地址，比如https://yun.vomiku.com/A。
