### ISSUE TITLE
关于天翼云

### ISSUE THREAD

**Issue by qingchenmowang** [reruin/sharelist#131]
挂载天翼云盘
1. 账号密码挂载（Cookie方式）
由drive.189cloud.js插件实现。
挂载标示：ctcc
挂载内容：  
    //用户名/初始文件夹ID?password=密码 
    /
建议填写/，ShareList将自动开启挂载向导，按指示填写用户名密码即可。
按照这个方法弄成功了，但是它在天翼的根目录，所以我根据//用户名/初始文件夹ID?password=密码 改了虚拟目录中间加了个文件夹id，保存后第一次访问时刚才设置的这个文件夹，但是刷新一次后又变成了根目录下，去后台一看，我刚设置的那个又变成初始的了。
请教下，初始文件夹id是我弄错了，还是我设置不对，
![HINTS427Z$HF`4 KYQ4%FNQ](https://user-images.githubusercontent.com/56811087/77241152-3fea4c80-6c29-11ea-806d-ea9ef4e7d007.png)
![~($Y_IK}W%HU@VVB )HG3A2](https://user-images.githubusercontent.com/56811087/77241201-cacb4700-6c29-11ea-8141-721dbedccf1e.png)

**Comment by zngcg** [comment]
我也是

**Comment by reruin** [comment]
挂载路径处填写 / 
之后按照导航操作即可。

**Comment by reruin** [comment]
此插件已调整，请更新后再试试。

**Comment by demoxia** [comment]
初始文件夹id指的是文件夹的名称吗？

**Comment by reruin** [comment]
地址栏中 folder 后面的部分。
![image](https://user-images.githubusercontent.com/7403780/83382080-e4042700-a414-11ea-8744-7e2af0f24c37.png)

**Comment by kettly1260** [comment]
> 地址栏中 folder 后面的部分。 ![image](https://user-images.githubusercontent.com/7403780/83382080-e4042700-a414-11ea-8744-7e2af0f24c37.png)

我天翼云上填写根目录对应的编号（-11）显示的是错误500.只能填子目录对应的id才能访问，请问怎么访问根目录啊？直接填“/”或者不填都不行
