### ISSUE TITLE
onedrive商业版api无法挂载

### ISSUE THREAD

**Issue by q240627995** [reruin/sharelist#136]
onedrive商业版api无法挂载 授权之后跳到这个网站 报错
![QQ截图20200327120135](https://user-images.githubusercontent.com/30516698/77720401-c5536f80-7022-11ea-9e68-0385fa097515.png)

**Comment by reruin** [comment]
Nginx反代时，请添加以下配置。
```
  proxy_set_header Host  $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  proxy_set_header Range $http_range;
  proxy_set_header If-Range $http_if_range;
  proxy_no_cache $http_range $http_if_range;
```

**Comment by q240627995** [comment]
> Nginx反代时，请添加以下配置。
> 
> ```
>   proxy_set_header Host  $host;
>   proxy_set_header X-Real-IP $remote_addr;
>   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>   proxy_set_header X-Forwarded-Proto $scheme;
> 
>   proxy_set_header Range $http_range;
>   proxy_set_header If-Range $http_if_range;
>   proxy_no_cache $http_range $http_if_range;
> ```

你好，我没有绑定域名，是直接通过ip加端口进行访问的。请问使用od api一定要反代吗？

**Comment by reruin** [comment]
不需要反代。IP直接访问时，你先确认下初始访问地址是否带有端口号，例如 ```http://127.0.0.1:33001```。

**Comment by q240627995** [comment]
> 不需要反代。IP直接访问时，你先确认下初始访问地址是否带有端口号，例如 `http://127.0.0.1:33001`。

你好！是的，带有端口33001
![QQ截图20200327115036](https://user-images.githubusercontent.com/30516698/77719821-372ab980-7021-11ea-908a-b5c6f4359183.png)

**Comment by reruin** [comment]
可在回调到```http://127.0.0.1/e5?code=xxxx```这个页面时，手动补一下端口33001，```http://127.0.0.1:33001/e5?code=xxxx```，并访问此地址。

**Comment by q240627995** [comment]
> 可在回调到`http://127.0.0.1/e5?code=xxxx`这个页面时，手动补一下端口33001，`http://127.0.0.1:33001/e5?code=xxxx`，并访问此地址。

还是不行，主要是用域名好像要备案，太麻烦了。算了，国际od也慢，老老实实用天翼云。麻烦你了！谢谢！！
