### ISSUE TITLE
大佬这个怎么填？

### ISSUE THREAD

**Issue by crts233** [reruin/sharelist#137]
![2020-3-26 20-38-52](https://user-images.githubusercontent.com/61039040/77647751-f63f9000-6fa1-11ea-997b-47996bd7da43.png)

**Comment by crts233** [comment]
https://ftp.bmp.ovh/imgs/2020/03/8c984ef4c40a7f08.png

**Comment by reruin** [comment]
填 {} , 初始化 挂载完毕后，参考 https://github.com/reruin/sharelist/issues/119 此条更新该值。

**Comment by crts233** [comment]
好的，谢谢


| |
reveriesky
|
|
a2258447359@163.com
|
签名由网易邮箱大师定制
在2020年3月27日 10:06，Ting<notifications@github.com> 写道：

填 {} , 初始化 挂载完毕后，参考 #119 此条更新该值。
