### ISSUE TITLE
天翼云盘dplayer怎么视频加载不了

### ISSUE THREAD

**Issue by qazwse4541** [reruin/sharelist#139]
favicon.ico在哪添加

**Comment by qazwse4541** [comment]
dplayer怎么视频加载不了好了

**Comment by whyun1** [comment]
你好，请问解决了吗？怎么解决的？

**Comment by reruin** [comment]
dplayer无法跨域播放，需启用中转模式。

**Comment by Bonperfect** [comment]
在开发下吧，狸猫盘都可以播放，中转，用个1Mb的VPS卡的要崩溃。

**Comment by reruin** [comment]
@Bonperfect 此问题已修复，造成的影响是：在直连模式下DPlayer无法加载字幕文件。
https://github.com/MoePlayer/DPlayer/issues/426
