### ISSUE TITLE
中转的视频文件不支持进度条拖动

### ISSUE THREAD

**Issue by phbai** [reruin/sharelist#14]
在管理中打开`启用下载中转（包括预览）`选项，可以用直链播放视频也可以进行下载，但是无法拖动视频进度条

**Comment by reruin** [comment]
原先 中转下载时无法获取 Responese Headers 里的 content-length 及 content-range。  
现已 增加实验性功能，可在 管理中 启用 ```中转视频预览允许拖拽``` 选项。

**Comment by phbai** [comment]
我本地wget试验了下 中转的视频文件是没有缓存功能的吧  这个功能能加么。。

**Comment by phbai** [comment]
虽然中转能拖动进度条 但是没中转前下载能达到22MB/s 中转后只有100KB/s 看起来有点卡卡的 不知道是什么原因。。

**Comment by reruin** [comment]
dockerhub 晚点更。  
中转缓存... 短期不考虑 。

**Comment by reruin** [comment]
dockerhub 已更。

**Comment by cloudfly23** [comment]
为什么现在的版本没用拖动选项
