### ISSUE TITLE
天翼云盘账号密码登陆一直有问题

### ISSUE THREAD

**Issue by qingchenmowang** [reruin/sharelist#140]
刚开始账号密码登陆就可以了，昨天我刷新了下缓存，突然就错误了，打不开，我今天装了好多遍都提示密码错误，我是以手机号加密码登陆的，，后来又试了邮箱加密码都不行，账号密码肯定是没错的，大佬看看是不是插件哪里有问题还是天翼搞得这种方法不让登陆了

**Comment by reruin** [comment]
账号密码有概率出现验证码，暂时不要用此插件，等待后续方案。

**Comment by 2131411** [comment]
重启后账户密码就提示错误。
