### ISSUE TITLE
google drive 到底怎么搞啊。。。

### ISSUE THREAD

**Issue by coolsd** [reruin/sharelist#141]
上传文件然后自动出来应用机密跟ID  然后点击验证，又跳回之前的页面 
疯了 试了好多次了。

**Comment by reruin** [comment]
上传后，注意有 还需要点击第三步【3. 获取验证code】，点击后进入页面获取code填入第三个输入框中。

![image](https://user-images.githubusercontent.com/7403780/78473647-e0398880-7774-11ea-9f35-62a2d526e45f.png)

**Comment by coolsd** [comment]
点击后直接提示我 要我上传文件呢，文件明明已经传了

**Comment by coolsd** [comment]
![QQ截图20200405194006](https://user-images.githubusercontent.com/7413058/78473718-5a6a0d00-7775-11ea-978f-bc29e92fde0a.png)

**Comment by coolsd** [comment]
onedrive 也是有些问题 不知道怎么解
![Q11Q截图20200405194520](https://user-images.githubusercontent.com/7413058/78473808-03b10300-7776-11ea-853d-06aefd56b108.png)

**Comment by coolsd** [comment]
这个咋办呢大佬，有大佬指点下吗

**Comment by coolsd** [comment]
换了N个浏览器了，都是一样的，换了好几个系统了也是一样

**Comment by Mit2g** [comment]
> 点击后直接提示我 要我上传文件呢，文件明明已经传了

凭证无法上传可以使用其他浏览器 例如Edge
Onedrive部分建议参考置顶issue中 个人Onedrive挂载方法 成功生成相关`app_id`及`app_secret`后 手动填入向导 获取token 即可正常挂载

**Comment by reruin** [comment]
> 换了N个浏览器了，都是一样的，换了好几个系统了也是一样

更新下代码，已更新gd挂载向导。
