### ISSUE TITLE
天翼云直链可以下载，视频播放不了

### ISSUE THREAD

**Issue by whyun1** [reruin/sharelist#143]
显示视频加载失败，但下载可以下载。请教是什么原因？
用api挂载

**Comment by whyun1** [comment]
换成默认播放器就可以，dplayer不行。但在挂载的od中就没有这个问题。

**Comment by reruin** [comment]
dplayer无法跨域播放，需要启用中转模式。

**Comment by whyun1** [comment]
nginx中设置跨域有用吗？

**Comment by reruin** [comment]
从sharelist后台设置中转。

**Comment by reruin** [comment]
已修复，由于 dplayer 挂载字幕导致 跨域问题。
