### ISSUE TITLE
google drive  第二步上传文件后第三步点验证老提示文件没上传

### ISSUE THREAD

**Issue by coolsd** [reruin/sharelist#145]
![QQ截图20200405194006](https://user-images.githubusercontent.com/7413058/78638133-573e6080-78de-11ea-96ac-d8a5a7ad9863.png)

求大佬指点啊 是什么情况

**Comment by reruin** [comment]
能否私发下 credentials.json ，可能redirect_uris没符合要求。

**Comment by coolsd** [comment]
已经发到你邮箱了。

**Comment by reruin** [comment]
已为gd使用新的挂载向导，更新后再试试。
