### ISSUE TITLE
package组件安装过程中报错

### ISSUE THREAD

**Issue by beckball** [reruin/sharelist#146]
根据install.sh中似乎使用的Node 8.x 在heroku上安装正常 实机上安装正常
~~但因某平台提供的Nodejs环境包最低为10.x 似乎因为对依赖的版本有所要求 导致报错~~
已成功配置nodejs 8.x 但是报错依然如下
```Installing node modules (package.json)
   > core-js@2.6.11 postinstall /tmp/app/node_modules/core-js
   > node -e "try{require('./postinstall')}catch(e){}"
   added 316 packages from 366 contributors and audited 5244 packages in 38.024s
   5 packages are looking for funding
     run `npm fund` for details
   found 8 vulnerabilities (3 low, 4 moderate, 1 high)
     run `npm audit fix` to fix them, or `npm audit` for details
          **WARNING** Unmet dependencies don't fail npm install but may cause runtime issues
          See: https://github.com/npm/npm/issues/7494
          Contrast Security no credentials found. Will not write environment files.
   Exit status 0 
``
请问有方法解决吗？是应该更改依赖中的版本为具体还是另有方法？感谢

**Comment by reruin** [comment]
install.sh 默认是按最低要求安装的8.x 的nodejs，但实际没有此限制。安装依赖出现WARNING不会影响正常使用。

**Comment by beckball** [comment]
> install.sh 默认是按最低要求安装的8.x 的nodejs，但实际没有此限制。安装依赖出现WARNING不会影响正常使用。

是在IBM Cloud上的Cloudy Foundry搭建的 已经加了mainfest.yml补充前置条件 但是执行起来只看到了如上错误 我再排查一下 感谢

**Comment by reruin** [comment]
或者删除node_modules，手动安装dependencies，devDependencies里只需要安装pm2用作进程管理。
使用如下空的package.json。
```
{
  "name": "sharelist",
  "version": "0.1.0",
  "bin": "app.js",
  "repository": "https://github.com/reruin/sharelist",
  "license": "Apache-2.0",
  "scripts": {
    "start": "node app.js",
    "prd": "pm2 start app.js --name sharelist --env prod"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

**Comment by beckball** [comment]
> 或者删除node_modules，手动安装dependencies，devDependencies里只需要安装pm2用作进程管理。
> 使用如下空的package.json。
> 
> ```
> {
>   "name": "sharelist",
>   "version": "0.1.0",
>   "bin": "app.js",
>   "repository": "https://github.com/reruin/sharelist",
>   "license": "Apache-2.0",
>   "scripts": {
>     "start": "node app.js",
>     "prd": "pm2 start app.js --name sharelist --env prod"
>   },
>   "dependencies": {},
>   "devDependencies": {}
> }
> ```

这个cf也是类似于Heroku一样的封闭环境 无法手动 可能还是需要在package.json里补充依赖
`      -----> Building dependencies
          Installing node modules (package.json)
   up to date in 0.968s
found 0 vulnerabilities
          Contrast Security no credentials found. Will not write environment files.
   Exit status 0
   Uploading droplet, build artifacts cache...
   Uploading build artifacts cache...
   Uploading droplet...
   Uploaded build artifacts cache (16.4M)
   Uploaded droplet (19.8M)
   Uploading complete
   Cell 容器编号 stopping instance 容器编号
   Cell 容器编号 destroying container for instance 容器编号

Waiting for app to start...
Application instances '容器编号' not found.
FAILED`
