### ISSUE TITLE
🍻我又来啦~提个改善使用体验的建议，希望增加PDF在线预览

### ISSUE THREAD

**Issue by emengweb** [reruin/sharelist#147]
之前在另一个项目上看到过PDS.JS的预览模块，感觉很实用，建议增加到sharelist中，增加对pdf格式的预览。
最近升级到了最新版，感觉项目的功能越来越强大了，大佬辛苦了！为你点赞！👍👍👍

**Comment by whyun1** [comment]
着急的话可以先在/plugins/preview.document.js文件下增加下面代码，只试过小文件可以加载。不着急的话等待大佬的更新。建议等待大佬的更新。  

const pdf = async (data, req) => {
    return {
      ...data,
      body: `
        <iframe src="https://owa-box.vips100.com/op/view.aspx?src=${encodeURIComponent(req.origin+decodeUrl(req))}"></iframe>
      `
    }
  }

  ['pdf'].forEach(ext => {
    preview[ext] = pdf
  });

**Comment by emengweb** [comment]
多谢~

**Comment by kexuebin** [comment]
@reruin

**Comment by emengweb** [comment]
刚刚试用了新版，已经支持pdf预览啦！👍 
发现在开启防盗链的“下载链接有效期(秒)”设置后，pdf预览时没有自动加上t参数，导致预览失败呢

**Comment by reruin** [comment]
> 刚刚试用了新版，已经支持pdf预览啦！👍
> 发现在开启防盗链的“下载链接有效期(秒)”设置后，pdf预览时没有自动加上t参数，导致预览失败呢

已实现。
