### ISSUE TITLE
目录加密功能有问题

### ISSUE THREAD

**Issue by q240627995** [reruin/sharelist#148]
目录加密功能有问题
具体是：目录下加入.password文件后 会要求验证，但是输入正确的账号密码后点确认没反应。但是点管理，输入管理密码后成功进入管理页面，再尝试进入被加密的目录就不用验证，可以直接进入。

通过宝塔的pm2部署

**Comment by emengweb** [comment]
前端是否有反代？反代参照说明的文件配置，也许可以解决

**Comment by q240627995** [comment]
> 前端是否有反代？反代参照说明的文件配置，也许可以解决

并没有设置反代，直接ip访问，

**Comment by zngcg** [comment]
> > 前端是否有反代？反代参照说明的文件配置，也许可以解决
> 
> 并没有设置反代，直接ip访问，

我也发现了

**Comment by reruin** [comment]
1.```输入正确的账号密码后点确认没反应```有可能是网络原因。
2. 设计如此，登录状态下可访问任何加密目录。

**Comment by reruin** [comment]
密码文件需命名为 .passwd。
