### ISSUE TITLE
如何卸载bash安装的版本后安装docker版本

### ISSUE THREAD

**Issue by ye61123** [reruin/sharelist#149]
大佬你好，请问怎么卸载bash安装的版本呢，没有看到uninstall.sh，我想重新安装docker的版本，因为想把容器端口映射到我本机想要的设置的端口

**Comment by ye61123** [comment]
我看了下安装脚本，好像是通过pm2进行安装管理的，直接用pm2卸载这个nodejs服务就可以了吗？

**Comment by ye61123** [comment]
是不是先pm2 stop sharelist，然后用npm卸载pm2，再yum卸载npm就卸载干净了吗

**Comment by ye61123** [comment]
已成功切换到docker版本，谢谢！

**Comment by reruin** [comment]
pm2停掉服务，然后卸载 pm2 和 nodejs，最后删除sharelist 目录。
