### ISSUE TITLE
google drive教育版挂载后无法拉取文件列表

### ISSUE THREAD

**Issue by ZvonimirSun** [reruin/sharelist#15]
如题，经测试，无限容量的google drive教育版挂载后无法拉取文件列表，一直显示为空。普通的个人版google drive和OneDive均能够正常挂载。望修复

**Comment by reruin** [comment]
方便分享个链接么，我这没有教育版的gd。

**Comment by ZvonimirSun** [comment]
已经通过邮件发送给你，我好像知道原因了，不知道咋解决。教育版似乎不能完全公开，只能公开到那个学校的范围。
[image: image.png]


Ting <notifications@github.com> 于2018年7月17日周二 下午8:23写道：

**Comment by reruin** [comment]
不能匿名访问的目录是无法挂载的。

**Comment by reruin** [comment]
教育版似乎也可修改权限。方法见邮件。

**Comment by Cloudiver** [comment]
@reruin 教育版GD应该是有限制的，看管理员有没有给权限。
我之前撸的一个就不能公开共享，只能给内部成员分享。这种自己无法修改权限，也不能挂载。

**Comment by reruin** [comment]
如果没有公开权限，那确实是不能挂载。

**Comment by kentcc88** [comment]
> @reruin 教育版GD应该是有限制的，看管理员有没有给权限。
> 我之前撸的一个就不能公开共享，只能给内部成员分享。这种自己无法修改权限，也不能挂载。

是的，我现在用的也只是限于学校内部的账号之间共享或者分享！取决于该校的管理账号设置的规则！

**Comment by sontjer** [comment]
老大，用你的sharelist我最多读取google drive里共享文件夹中49个文件，多了就不显示了。这是bug还是啥？
<img width="1920" alt="屏幕快照 2019-07-23 下午10 41 10" src="https://user-images.githubusercontent.com/43029800/61728734-5beed300-ada8-11e9-8998-7091f909407c.png">

**Comment by reruin** [comment]
@sontjer 已修复。

**Comment by sontjer** [comment]
> @sontjer 已修复。

群晖docker镜像里的还是只能读取49个文件~~~
