### ISSUE TITLE
天翼云盘的文件夹ID如何获取

### ISSUE THREAD

**Issue by 14907471** [reruin/sharelist#150]
天翼云盘的文件夹ID如何获取？

**Comment by whyun1** [comment]
登录天翼云盘网页版，点击相应的目录，文件夹id就在网址里面。

**Comment by reruin** [comment]
如@whyun1 所述。
![image](https://user-images.githubusercontent.com/7403780/79421460-695e8400-7fed-11ea-88e6-27c10dc5a2e4.png)
