### ISSUE TITLE
API挂载的google drive访问文件时报错

### ISSUE THREAD

**Issue by Super-pixle** [reruin/sharelist#151]
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}

**Comment by Super-pixle** [comment]
如果使用cloudflare的中转，google drive就只能预览一些文本文件，大文件就报错，api挂载的onedrive是正常的；中转地址留空，使用本机的中转是正常的。总结就是用cloudflare中转google drive有一些问题。

**Comment by Mit2g** [comment]
> {
> "error": {
> "errors": [
> {
> "domain": "usageLimits",
> "reason": "dailyLimitExceededUnreg",
> "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
> "extendedHelp": "https://code.google.com/apis/console"
> }
> ],
> "code": 403,
> "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
> }
> }

这个问题与后面你的是否中转没有关系 仅仅因为你打开的文件在Google drive上仅仅是“添加到我的云端硬盘” 而不是转存到你的硬盘上占用你的空间 前者会受到每日访问次数的限制但不占用你的云盘空间 后者反之 请尝试转存到你的云盘后再试

**Comment by Super-pixle** [comment]
我尝试打开的文件都是占用了我的15g的储存空间的,但是也不行。
![image](https://user-images.githubusercontent.com/44594408/80440976-6abc7480-893c-11ea-8a5e-9d1976d30267.png)

**Comment by reruin** [comment]
@Super-pixle 此问题已修复，cf代理时丢失关键的验证信息，你需要更新下 cf-worker。
@Mit2g 感谢你的提醒，ID挂载版 确实存在此问题，匿名访问时会存在超出配额。

**Comment by Super-pixle** [comment]
嗯，问题解决了。感谢开发者。
