### ISSUE TITLE
建议增强密码功能，可以部署到管理页面，毕竟放到网络上安全问题很重要。

### ISSUE THREAD

**Issue by Bonperfect** [reruin/sharelist#155]
现在密码功能太不好用，添加了文件，一点效果都没有，或者输入完，无反应。

**Comment by reruin** [comment]
此功能早先设计的并不完善，除了验证密码时延迟很高以外，多层级密码功能也没有实际实现 如 https://github.com/reruin/sharelist/issues/123 。

等后续完善吧。

**Comment by reruin** [comment]
此功能已完善，新增多层级密码功能。

**Comment by emengweb** [comment]
用来做图床和下载站时，不想要普通用户对目录进行浏览，但是允许访问文件并下载。
密码自动对子目录进行加密，这个可否在后台放置开关呢？

**Comment by reruin** [comment]
> 用来做图床和下载服务器时，不想要普通用户对目录进行浏览，但是允许访问文件并下载。
> 多层级密码功能，能否在后台放置开关？现在设置密码后的子目录、文件，都需要先经过验证，不然就无法下载，导致提供后端下载服务时面临两难的选择，忧桑 T。T

稍后加控制开关 “允许跳过密码验证访问文件”

**Comment by emengweb** [comment]
👍👍👍作者大大威武！
