### ISSUE TITLE
无法挂载onedrive

### ISSUE THREAD

**Issue by MasterOfStar** [reruin/sharelist#156]
AADSTS500112: The reply address 'http://pan.mdos.win/' does not match the reply address 'https://reruin.github.io/redirect/onedrive.html' provided when requesting Authorization code. Trace ID: 845207bd-73d5-460b-a70b-90ebcb3f4500 Correlation ID: 4f68f3a3-0570-4efc-9070-3baeda72521b Timestamp: 2020-04-24 06:31:07Z

**Comment by reruin** [comment]
回调页面是怎么填写的？

**Comment by Mit2g** [comment]
可以参考这个更改回调地址
https://github.com/reruin/sharelist/issues/160#issuecomment-619952865

**Comment by MasterOfStar** [comment]
> 回调页面是怎么填写的？


填写的https://我的域名/one

(one是onedrive挂载的域名) 然后在登录微软账户确认的过程中 微软提示如图
![image](https://user-images.githubusercontent.com/21274896/80377988-96a11100-88ce-11ea-9460-4eb4fac3429f.png)

nginx设置正常 域名走了cf的cdn https是cf带的 服务器端为nginx配置https后访问会出现重定向过多的错误提示 故nginx设置为http  
![image](https://user-images.githubusercontent.com/21274896/80378240-f3043080-88ce-11ea-9289-c42cfee936de.png)
![image](https://user-images.githubusercontent.com/21274896/80378282-01eae300-88cf-11ea-9a83-ebd95f7ea37e.png)

**Comment by reruin** [comment]
> https://我的域名/

请访问此地址，重新开启挂载过程，并按照 https://github.com/reruin/sharelist/issues/75 进行配置。
重定向URI处只填写 ```https://我的域名/one```

若仍出现 AADSTS50011 ，请将此时浏览器地址栏内的地址复制下来。

**Comment by MasterOfStar** [comment]
> > [https://我的域名/](https://%E6%88%91%E7%9A%84%E5%9F%9F%E5%90%8D/)
> 
> 请访问此地址，重新开启挂载过程，并按照 #75 进行配置。
> 重定向URI处只填写 `https://我的域名/one`
> 
> 若仍出现 AADSTS50011 ，请将此时浏览器地址栏内的地址复制下来。

https://login.microsoftonline.com/common/reprocess?ctx=rQIIAdNiNtIzsFIxNzM1MU5NTNVNTkk20TWxTDLXTTJNSdZNMTVNM002MzFNTU4sEuIS6D6wQ_7VlEOOG7c-e7i8Y93CHYyMFxgZbzHx-zuWlmQYgYj8osyq1FnM4hklJQVW-voFiXl6uSn5xXrlmXn6-Xmpq5hVDCDAWBdEQohkGAsGNjGzJefn5ubnnWJWyk9Ly8nMS41PTE5OLS5WSMvMSS3WK0pNTCkvyixJ1UvMybnBzHiBhfEVC48BsxUHB5cAgwSDAsMPFsZFrEA3yz5XO3Tmyi-nNbuupy9PFmU4xaqfl5YSmaSd5ZdUlBlQbpIeXlBRaOFZmZmW75aVVeboneSl7VOZZ-rsn5LhamtiZTiBjfEDG2MHO8MuTn2Qt4qB_ipKLSrNzNNLzyzJKE3Sy8wHCqRkFqUml4A8mVKUWZaql1GSmwMA0&sessionid=e9e3325f-afe2-4323-9c8d-23e3a7c9a7f4

**Comment by reruin** [comment]
拉取最新代码后再试下。

1. 如果使用http 的访问地址，请在重定向那里填写```https://reruin.github.io/redirect/onedrive.html```。
2. 如果使用 https ，则填你实际地址，比如```https://zz.danmujia.com/A```。
