### ISSUE TITLE
有没有方法可以挂载天翼家庭云？

### ISSUE THREAD

**Issue by MasterOfStar** [reruin/sharelist#157]
例如通过这个接口？
![image](https://user-images.githubusercontent.com/21274896/80190563-161caf00-8647-11ea-8a41-ba386dcee103.png)

**Comment by MasterOfStar** [comment]
授权地址http://api.cloud189.cf/oauth

**Comment by MasterOfStar** [comment]
那位写接口的大佬给了方案

> ShareList接入教程
修改plugins\drive.189cloud.api.js文件
将第50、51行中的cloud.189.cn替换为cloud189.cf
再将第365行中的api.cloud.189.cn替换为api.cloud189.cf
修改完毕需重启ShareList(前端管理页面或命令pm2 restart all)
后续使用按官方教程配置即可，应用机密和应用ID随意填写，但不可为空
(附件中亦有修改好的插件，可直接上传，新增插件名多了"PRO"二字)

![image](https://user-images.githubusercontent.com/21274896/80467794-eafccd00-8970-11ea-89dc-221c6a8a6c7e.png)

**Comment by MasterOfStar** [comment]
悲 提供服务的老哥被封了

**Comment by reruin** [comment]
> 悲 提供服务的老哥被封了

家庭云用 账号密码方式是否可行？

**Comment by MasterOfStar** [comment]
> > 悲 提供服务的老哥被封了
> 
> 家庭云用 账号密码方式是否可行？

现有的方式并不能挂载家庭云
天翼云盘PC客户端通过账户密码方式可以操作家庭云 网页版天翼云盘似乎不行

**Comment by reruin** [comment]
> > > 悲 提供服务的老哥被封了
> > 
> > 
> > 家庭云用 账号密码方式是否可行？
> 
> 现有的方式并不能挂载家庭云
> 天翼云盘PC客户端通过账户密码方式可以操作家庭云 网页版天翼云盘似乎不行

抓包应该能分析出请求，目前没有账号做分析。

**Comment by MasterOfStar** [comment]
> > > > 悲 提供服务的老哥被封了
> > > 
> > > 
> > > 家庭云用 账号密码方式是否可行？
> > 
> > 
> > 现有的方式并不能挂载家庭云
> > 天翼云盘PC客户端通过账户密码方式可以操作家庭云 网页版天翼云盘似乎不行
> 
> 抓包应该能分析出请求，目前没有账号做分析。

可以提供一个小号供研究
