### ISSUE TITLE
onedrive挂载时一直提示这个

### ISSUE THREAD

**Issue by sxxcb** [reruin/sharelist#160]
挂载OneDrive失败
AADSTS500112：请求授权代码时，答复地址'http://zz.danmujia.com/'与提供的答复地址'https://reruin.github.io/redirect/onedrive.html'不匹配。跟踪ID：f47350fe-79d4-460d-8305-6f30a02c3d00相关ID：323b5dca-433b-4c25-aa07-61c9be5bfa1e时间戳：2020-04-25 09：04：56Z

**Comment by reruin** [comment]
请参考 https://github.com/reruin/sharelist/issues/75 进行挂载，特别注意回调页面的填写。

**Comment by Mit2g** [comment]
> 挂载OneDrive失败
> AADSTS500112：请求授权代码时，答复地址'[http://zz.danmujia.com/'与提供的答复地址'https://reruin.github.io/redirect/onedrive.html'不匹配。跟踪ID：f47350fe-79d4-460d-8305-6f30a02c3d00相关ID：323b5dca-433b-4c25-aa07-61c9be5bfa1e时间戳：2020-04-25](http://zz.danmujia.com/'%E4%B8%8E%E6%8F%90%E4%BE%9B%E7%9A%84%E7%AD%94%E5%A4%8D%E5%9C%B0%E5%9D%80'https://reruin.github.io/redirect/onedrive.html'%E4%B8%8D%E5%8C%B9%E9%85%8D%E3%80%82%E8%B7%9F%E8%B8%AAID%EF%BC%9Af47350fe-79d4-460d-8305-6f30a02c3d00%E7%9B%B8%E5%85%B3ID%EF%BC%9A323b5dca-433b-4c25-aa07-61c9be5bfa1e%E6%97%B6%E9%97%B4%E6%88%B3%EF%BC%9A2020-04-25) 09：04：56Z

如果你是使用 / 并且根据向导来授权挂载的 需要在获取AppID和Sercet后 再自行修改回调页面
![向导绑定后应该怎么做](https://user-images.githubusercontent.com/50163397/80371680-dbc04580-88c4-11ea-924a-ffde94da5b42.png)
![向导绑定后应该怎么做2](https://user-images.githubusercontent.com/50163397/80371691-e084f980-88c4-11ea-9730-b4953389c90d.png)
在图2中删除默认的URL 再添加自己的URL 而后尝试挂载

**Comment by sxxcb** [comment]
> 请参考 #75 进行挂载，特别注意回调页面的填写。
还是无法，我现在使用IP:33001绑定回复
AADSTS500112: The reply address 'http://xxx:33001/a' does not match the reply address 'https://reruin.github.io/redirect/onedrive.html' provided when requesting Authorization code. Trace ID: 87552f91-2184-4e07-9d05-988635ff8300 Correlation ID: e3f5f080-1766-4d18-9529-5e3f1edf4aeb Timestamp: 2020-04-27 12:22:07Z
这是因为应用注册里面重定向是https://reruin.github.io/redirect/onedrive.html。
修改重定向为http://localhost/a提示
抱歉，登录时遇到问题。

AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: '240f532a-e2b8-4d46-bed1-b2c10a6fbd4e'.
后台虚拟路径是  odapi版 名称 a 挂载/a

我用域名的也试过，重定向那里是我的域名https://xxx/a，还是显示上面的内容。
反代那里
  proxy_set_header Host  $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  proxy_set_header Range $http_range;
  proxy_set_header If-Range $http_if_range;
  proxy_no_cache $http_range $http_if_range;
也填了，不知道哪里错误，一直绑定不上

**Comment by Mit2g** [comment]
> > 请参考 #75 进行挂载，特别注意回调页面的填写。
> > 还是无法，我现在使用IP:33001绑定回复
> > AADSTS500112: The reply address 'http://xxx:33001/a' does not match the reply address 'https://reruin.github.io/redirect/onedrive.html' provided when requesting Authorization code. Trace ID: 87552f91-2184-4e07-9d05-988635ff8300 Correlation ID: e3f5f080-1766-4d18-9529-5e3f1edf4aeb Timestamp: 2020-04-27 12:22:07Z
> > 这是因为应用注册里面重定向是[https://reruin.github.io/redirect/onedrive.html。](https://reruin.github.io/redirect/onedrive.html%E3%80%82)
> > 修改重定向为[http://localhost/a提示](http://localhost/a%E6%8F%90%E7%A4%BA)
> > 抱歉，登录时遇到问题。
> 
> AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: '240f532a-e2b8-4d46-bed1-b2c10a6fbd4e'.
> 后台虚拟路径是 odapi版 名称 a 挂载/a
> 
> 我用域名的也试过，重定向那里是我的域名[https://xxx/a，还是显示上面的内容。](https://xxx/a%EF%BC%8C%E8%BF%98%E6%98%AF%E6%98%BE%E7%A4%BA%E4%B8%8A%E9%9D%A2%E7%9A%84%E5%86%85%E5%AE%B9%E3%80%82)
> 反代那里
> proxy_set_header Host $host;
> proxy_set_header X-Real-IP $remote_addr;
> proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> proxy_set_header X-Forwarded-Proto $scheme;
> 
> proxy_set_header Range $http_range;
> proxy_set_header If-Range $http_if_range;
> proxy_no_cache $http_range $http_if_range;
> 也填了，不知道哪里错误，一直绑定不上

nginx只反代端口 不要对其他path做定义 而后将回调地址填写为主目录试试 即为 http://xxx.com/

**Comment by sxxcb** [comment]
> > > 请参考 #75 进行挂载，特别注意回调页面的填写。
> > > 还是无法，我现在使用IP:33001绑定回复
> > > AADSTS500112: The reply address 'http://xxx:33001/a' does not match the reply address 'https://reruin.github.io/redirect/onedrive.html' provided when requesting Authorization code. Trace ID: 87552f91-2184-4e07-9d05-988635ff8300 Correlation ID: e3f5f080-1766-4d18-9529-5e3f1edf4aeb Timestamp: 2020-04-27 12:22:07Z
> > > 这是因为应用注册里面重定向是[https://reruin.github.io/redirect/onedrive.html。](https://reruin.github.io/redirect/onedrive.html%E3%80%82)
> > > 修改重定向为[http://localhost/a提示](http://localhost/a%E6%8F%90%E7%A4%BA)
> > > 抱歉，登录时遇到问题。
> > 
> > 
> > AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: '240f532a-e2b8-4d46-bed1-b2c10a6fbd4e'.
> > 后台虚拟路径是 odapi版 名称 a 挂载/a
> > 我用域名的也试过，重定向那里是我的域名[https://xxx/a，还是显示上面的内容。](https://xxx/a%EF%BC%8C%E8%BF%98%E6%98%AF%E6%98%BE%E7%A4%BA%E4%B8%8A%E9%9D%A2%E7%9A%84%E5%86%85%E5%AE%B9%E3%80%82)
> > 反代那里
> > proxy_set_header Host $host;
> > proxy_set_header X-Real-IP $remote_addr;
> > proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> > proxy_set_header X-Forwarded-Proto $scheme;
> > proxy_set_header Range $http_range;
> > proxy_set_header If-Range $http_if_range;
> > proxy_no_cache $http_range $http_if_range;
> > 也填了，不知道哪里错误，一直绑定不上
> 
> nginx只反代端口 不要对其他path做定义
> 例如你的网盘叫A 域名为xxx.com 那么在sharelist后台应该填写
> 
> 挂载条目	名称	路径
> OD API版	A	/
> 之后回到主目录 进入A文件夹 根据向导获得App ID和sercet 回调地址填写https://xxx.com/A 再尝试挂载

刚刚从新试了下，后台设置按照您上面填的，回调地址写的https://xxx.com/a,还是显示的错误

抱歉，登录时遇到问题。

AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: '76176cf7-28bd-45bb-b393-c69c3e7d1bf9'.

**Comment by Mit2g** [comment]
> > > > 请参考 #75 进行挂载，特别注意回调页面的填写。
> > > > 还是无法，我现在使用IP:33001绑定回复
> > > > AADSTS500112: The reply address 'http://xxx:33001/a' does not match the reply address 'https://reruin.github.io/redirect/onedrive.html' provided when requesting Authorization code. Trace ID: 87552f91-2184-4e07-9d05-988635ff8300 Correlation ID: e3f5f080-1766-4d18-9529-5e3f1edf4aeb Timestamp: 2020-04-27 12:22:07Z
> > > > 这是因为应用注册里面重定向是[https://reruin.github.io/redirect/onedrive.html。](https://reruin.github.io/redirect/onedrive.html%E3%80%82)
> > > > 修改重定向为[http://localhost/a提示](http://localhost/a%E6%8F%90%E7%A4%BA)
> > > > 抱歉，登录时遇到问题。
> > > 
> > > 
> > > AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: '240f532a-e2b8-4d46-bed1-b2c10a6fbd4e'.
> > > 后台虚拟路径是 odapi版 名称 a 挂载/a
> > > 我用域名的也试过，重定向那里是我的域名[https://xxx/a，还是显示上面的内容。](https://xxx/a%EF%BC%8C%E8%BF%98%E6%98%AF%E6%98%BE%E7%A4%BA%E4%B8%8A%E9%9D%A2%E7%9A%84%E5%86%85%E5%AE%B9%E3%80%82)
> > > 反代那里
> > > proxy_set_header Host $host;
> > > proxy_set_header X-Real-IP $remote_addr;
> > > proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> > > proxy_set_header X-Forwarded-Proto $scheme;
> > > proxy_set_header Range $http_range;
> > > proxy_set_header If-Range $http_if_range;
> > > proxy_no_cache $http_range $http_if_range;
> > > 也填了，不知道哪里错误，一直绑定不上
> > 
> > 
> > nginx只反代端口 不要对其他path做定义
> > 例如你的网盘叫A 域名为xxx.com 那么在sharelist后台应该填写
> > 挂载条目	名称	路径
> > OD API版	A	/
> > 之后回到主目录 进入A文件夹 根据向导获得App ID和sercet 回调地址填写https://xxx.com/A 再尝试挂载
> 
> 刚刚从新试了下，后台设置按照您上面填的，回调地址写的[https://xxx.com/a,还是显示的错误](https://xxx.com/a,%E8%BF%98%E6%98%AF%E6%98%BE%E7%A4%BA%E7%9A%84%E9%94%99%E8%AF%AF)
> 
> 抱歉，登录时遇到问题。
> 
> AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: '76176cf7-28bd-45bb-b393-c69c3e7d1bf9'.

那可能需要手动创建应用

**Comment by reruin** [comment]
@sxxcb 所有非标准的uri都不能作为重定向的地址，因而你需要：
1. 务必使用 https://xxx.com/a 地址开启挂载过程（而非 http://ip:33001/a）。
2. Azure应用注册界面里，把 ```https://xxx.com/a```作为重定向URI。

**Comment by cheliox** [comment]
一 样

**Comment by sxxcb** [comment]
> @sxxcb 所有非标准的uri都不能作为重定向的地址，因而你需要：
> 
> 1. 务必使用 `https://xxx.com/a` 地址开启挂载过程（而非 `http://ip:33001/a`）。
> 2. Azure应用注册界面里，把 `https://xxx.com/a`作为重定向URI。

所有的都这样填， 都绑定不上，我以前绑定过很多类似的程序，重定向那里也都是填的我自己的https域名，但是就是死活绑不上sharelist。大佬有机会可以自己测试一下吗？实在是没办法了

**Comment by reruin** [comment]
拉取最新代码后再试下。

1. 如果使用http 的访问地址，请在重定向那里填写```https://reruin.github.io/redirect/onedrive.html```。
2. 如果使用 https ，则填你实际地址，比如```https://zz.danmujia.com/A```。

**Comment by ricardomlee** [comment]
依旧是AADSTS50011

**Comment by sxxcb** [comment]
> 拉取最新代码后再试下。
> 
> 1. 如果使用http 的访问地址，请在重定向那里填写`https://reruin.github.io/redirect/onedrive.html`。
> 2. 如果使用 https ，则填你实际地址，比如`https://zz.danmujia.com/A`。

重新拉取代码绑定成功了，谢谢。
