### ISSUE TITLE
配置中转失败，中途会重定向到微软登录页

### ISSUE THREAD

**Issue by superxxl** [reruin/sharelist#161]
输入微软账户显示查找无效，看请求显示了地区，不知道各位是怎么样的，我不设置代理无法访问到cf，而设置代理地区变成代理的地区，或许就是这样登不上吧

**Comment by superxxl** [comment]
哦，不是，有时不代理也能上cf，但是微软的就是登不上，地区显示US

**Comment by reruin** [comment]
不是很明白你的问题。
中转选线仅适用下载（预览），挂载时并不依赖。

**Comment by superxxl** [comment]
意思是，点击预览，重定向到微软登录页，无法预览

**Comment by reruin** [comment]
请具体描述下挂载方式，并提供下你的站点地址（可私法我）。
