### ISSUE TITLE
在线播放能否添加flv支持？

### ISSUE THREAD

**Issue by MasterOfStar** [reruin/sharelist#162]
传上去的文件基本上都是flv格式 以前用oneindex的时候用上面的dplayer也可以播放flv来着 仔细看了下console的报错，是不是没有添加flv.js支持?

**Comment by MasterOfStar** [comment]
另：dplayer版本已更新至v1.25.1

**Comment by zngcg** [comment]
还需要增加MKV格式

**Comment by Mit2g** [comment]
> 传上去的文件基本上都是flv格式 以前用oneindex的时候用上面的dplayer也可以播放flv来着 仔细看了下console的报错，是不是没有添加flv.js支持?

flv支持的PR已被合并 拉取最新代码安装后 在后台管理中`支持视频格式`中添加flv保存后即可使用

> 另：dplayer版本已更新至v1.25.1

跟随上方支持一并更新了

**Comment by reruin** [comment]
> 还需要增加MKV格式

mkv只是容器格式，如果你确定当前设备可以解码，可在【后台管理】->【插件设置】，【支持预览的视频后缀】处添加 mkv。
