### ISSUE TITLE
Redirect uri

### ISSUE THREAD

**Issue by mohitjoshi155** [reruin/sharelist#164]
what do i write in redirect uri field for googledrive api if i have deployed on heroku?
also it would be appreciated if u release english version of read.md

**Comment by Mit2g** [comment]
Find "管理" which is in the bottom of ur sharelist page 
Suppose ur gogole drive path in your sharelist is A and set "虚拟路径" like below
| 挂载条目  | 名称  | 路径 |
|:--------- | :-----: | -----:|
|  GD API版  |  A   |  /    |
After u did that, go back to main page and click A folder
Follow the guideline then get everything sharelist needed , u would make ur GD mounted

Use google translate temporarily. Hope someone would translate readme into English. That muse be a huge project!
