### ISSUE TITLE
请教如何重置管理员登录密码

### ISSUE THREAD

**Issue by barrysimker** [reruin/sharelist#166]
哎，刚开始安装用密码生成器自动生成了密码，还没体验呢，结果把管理密码搞丢了。
想要找回密码却找不到入口。

把程序目录删掉再重装发现还是需要密码，找了半天也没有发现管理密码文件存在哪里，实在是没有办法了，遂来求助大佬。

谢谢！

**Comment by Mit2g** [comment]
修改 `sharelist/app/cache/config.json`  找到token字段 就可以看到你的登录密码 修改之后重新启动sharelist

**Comment by 2131411** [comment]
> 修改`sharelist/app/cache/config.json` 找到`token`之前就可以看到你的登录密码修改之后重新启动

千万别重启，一旦重启，账户密码就提示错误。
