### ISSUE TITLE
vercel可以搭建吗？

### ISSUE THREAD

**Issue by lv9002** [reruin/sharelist#169]
![H75531867a4d141abbe407187ab4ca3b0E](https://user-images.githubusercontent.com/63894358/81757374-48585880-94f1-11ea-9df8-c7a7eb7bc287.jpg)

不知道 怎么填写  请指点指点

选择 
Docusaurus1  可以访问  出来3个文件 
Docusaurus2    404错误
lonic react        404错误

其他全是 部署失败

**Comment by lv9002** [comment]
@reruin reruin
/
我发现已经有这个的 安装链接了
十分感谢

但是一路下一步   还是 部署失败

是不是 需要修改哪里？

**Comment by reruin** [comment]
不好意思，暂未完成适配工作，目前无法在vercel部署。
