### ISSUE TITLE
heroku搭建完总初始化

### ISSUE THREAD

**Issue by lv9002** [reruin/sharelist#170]
用heroku搭建完  过一段时间  （几分钟   几个小时）
就初始化了

搭建的天翼云  使用的账号密码的方式

而且速度  超级慢

**Comment by Mit2g** [comment]
> 用heroku搭建完 过一段时间 （几分钟 几个小时）
> 就初始化了
#duplicate
https://github.com/reruin/sharelist/issues/90#issuecomment-571860129

> 搭建的天翼云 使用的账号密码的方式
> 而且速度 超级慢
有人在别的地方反应被限速 检查是否速度为128K/s

**Comment by lv9002** [comment]
> > 用heroku建造完过一次（几分钟几个小时）
> > 就初始化了
> 
> [＃](https://github.com/reruin/sharelist/issues/90#issuecomment-571860129)重复
> [＃90（评论）](https://github.com/reruin/sharelist/issues/90#issuecomment-571860129)
> 
> > 建造的天翼云使用的账号密码的方式以及
> > 速度超级慢
> 
> 有人在网络上反应账户被限速检查是否下载速度为128K / s

没限速     是访问heroku  速度慢

**Comment by Mit2g** [comment]
> > > 用heroku建造完过一次（几分钟几个小时）
> > > 就初始化了
> > 
> > 
> > [＃](https://github.com/reruin/sharelist/issues/90#issuecomment-571860129)重复
> > [＃90（评论）](https://github.com/reruin/sharelist/issues/90#issuecomment-571860129)
> > > 建造的天翼云使用的账号密码的方式以及
> > > 速度超级慢
> > 
> > 
> > 有人在网络上反应账户被限速检查是否下载速度为128K / s
> 
> 没限速 是访问heroku 速度慢

访问Heroku速度慢无解 如果对速度有追求请购买适合你当地网络的服务器或者使用cdn加速 下载应该是直接调用API所以不会慢 慢了就是被限速

**Comment by lv9002** [comment]
> > > > 用heroku建造完过一次（几分钟几个小时）
> > > > 就初始化了
> > > 
> > > 
> > > [＃](https://github.com/reruin/sharelist/issues/90#issuecomment-571860129)重复
> > > [＃90（评论）](https://github.com/reruin/sharelist/issues/90#issuecomment-571860129)
> > > > 建造的天翼云使用的账号密码的方式以及
> > > > 速度超级慢
> > > 
> > > 
> > > 有人在网络上反应账户被限速检查是否下载速度为128K / s
> > 
> > 
> > 没限速是访问heroku速度慢
> 
> 访问Heroku速度慢无解如果对速度有追求请购买适合您当地网络的服务器或使用cdn加速下载应该是直接调用API所以不会慢慢了就是被限速

访问Heroku速度慢 
有没有  代替品？
