### ISSUE TITLE
天翼提示账户密码错误

### ISSUE THREAD

**Issue by 2131411** [reruin/sharelist#172]
点击重启或者清除缓存，再次登录就会提示账户或密码错误。换账号也不行。
再次登录出现验证码，这个极小概率，基本是100％。

**Comment by reruin** [comment]
验证码问题导致。近期会优化。

**Comment by iwang499** [comment]
提示你账号密码错误其实是天翼云盘认为你的服务器IP地址登陆是异常操作，需要输入验证码。而脚本暂时还没有绕过验证码和自动识别填写验证码的功能，两种解决方法，一是等大佬优化。二是自己手动用服务器登陆天翼云盘，让系统认为这个ip地址是你常用的，且在这个ip地址上的操作是安全常规的操作。就不会出现验证码从而就不会提示你账号密码错误。
如果你不急的话建议你等大佬优化。

**Comment by reruin** [comment]
优化完成，已添加[自动打码](https://github.com/reruin/sharelist#%E9%AA%8C%E8%AF%81%E7%A0%81%E7%9B%B8%E5%85%B3)。

**Comment by 2131411** [comment]
这就很奈斯，非常感谢

**Comment by iwang499** [comment]
> 优化完成，已添加[自动打码](https://github.com/reruin/sharelist#%E9%AA%8C%E8%AF%81%E7%A0%81%E7%9B%B8%E5%85%B3)。

感谢大佬
