### ISSUE TITLE
终于API挂载OneDrive的商业版成功，E5挂载成功。但是我想问，怎么挂载GoogleDrive？并且能挂载Google的团队盘吗？

### ISSUE THREAD

**Issue by pirately** [reruin/sharelist#173]
终于会弄OneDrive的商业版了，E5挂载成功。但是我想问，怎么挂载GoogleDrive？并且能挂载Google的团队盘吗？
OneDrive的API重点是https，必须要域名，不能本机IP。如果是白群晖的话，可以用群晖自带的ddns那个域名，再反代HTTPS，这样的话，利用sharelist的快速挂载可以成功。
但是，我挂载Google的api，第三步获取code为啥老让我上传credentials.json？我已经上传了，并且sharelist也可以自动读取ID和Secret，还是认为没有上传，这是为何？
Google Drive挂载的是个人盘，还是挂载的是无限的团队盘？

**Comment by Mit2g** [comment]
可以挂载个人 团队没有试过
遇到上传credentials 无法识别的可以尝试换浏览器

**Comment by pirately** [comment]
> 可以挂载个人 团队没有试过
> 遇到上传credentials 无法识别的可以尝试换浏览器
> 团队应该可以使用分享ID挂载 例如你的团队盘为`folders/XXXXXXXXXXX` 分享ID即为XXXXXXXXXXX

换了浏览器果然可以。团队盘不行，只能是个人盘。团队盘单个文件分享，好像没用，用sharelist的分享ID来挂载，显示notfound。

**Comment by Mit2g** [comment]
> > 可以挂载个人 团队没有试过
> > 遇到上传credentials 无法识别的可以尝试换浏览器
> > 团队应该可以使用分享ID挂载 例如你的团队盘为`folders/XXXXXXXXXXX` 分享ID即为XXXXXXXXXXX
> 
> 换了浏览器果然可以。团队盘不行，只能是个人盘。团队盘单个文件分享，好像没用，用sharelist的分享ID来挂载，显示notfound。

抱歉ID方法不可行 只是这个问题之前有人提问过了 https://github.com/reruin/sharelist/issues/102#issuecomment-601244387
亲测可行 即为API挂载得到的 ` //应用ID/root?client_secret=应用机钥&redirect_uri=回调地址&refresh_token=refresh_token` 修改其中 `root` 为你的团队盘ID 即可实现挂载

**Comment by pirately** [comment]
> > > 可以挂载个人 团队没有试过
> > > 遇到上传credentials 无法识别的可以尝试换浏览器
> > > 团队应该可以使用分享ID挂载 例如你的团队盘为`folders/XXXXXXXXXXX` 分享ID即为XXXXXXXXXXX
> > 
> > 
> > 换了浏览器果然可以。团队盘不行，只能是个人盘。团队盘单个文件分享，好像没用，用sharelist的分享ID来挂载，显示notfound。
> 
> 抱歉ID方法不可行 只是这个问题之前有人提问过了 [#102 (comment)](https://github.com/reruin/sharelist/issues/102#issuecomment-601244387)
> 亲测可行 即为API挂载得到的 ` //应用ID/root?client_secret=应用机钥&redirect_uri=回调地址&refresh_token=refresh_token` 修改其中 `root` 为你的团队盘ID 即可实现挂载

可以了，非常感谢。现在就只有WebDAV还有点问题
