### ISSUE TITLE
中转出现问题

### ISSUE THREAD

**Issue by whyun1** [reruin/sharelist#175]
{"error":{"code":"unauthenticated","message":"Unauthenticated"}}
很抱歉，出现了问题
发生意外错误。
技术详细信息

Microsoft SharePoint Foundation 疑难解答。 

服务器中转，列目录可以，播放和下载都出现这个问题。

**Comment by whyun1** [comment]
把nginx的auth_basic去掉就正常了。
但如果去掉就没密码保护了。
请问如何解决？谢谢

**Comment by Mit2g** [comment]
> 把nginx的auth_basic去掉就正常了。
> 但如果去掉就没密码保护了。
> 请问如何解决？谢谢

参考[此处](https://github.com/reruin/sharelist#%E7%9B%AE%E5%BD%95%E5%8A%A0%E5%AF%86)的加密方法 而非nginx的加密组件

**Comment by whyun1** [comment]
> > 把nginx的auth_basic去掉就正常了。
> > 但如果去掉就没密码保护了。
> > 请问如何解决？谢谢
> 
> 参考[此处](https://github.com/reruin/sharelist#%E7%9B%AE%E5%BD%95%E5%8A%A0%E5%AF%86)的加密方法 而非nginx的加密组件

此处的加密方法有局限性。

**Comment by reruin** [comment]
> > > 把nginx的auth_basic去掉就正常了。
> > > 但如果去掉就没密码保护了。
> > > 请问如何解决？谢谢
> > 
> > 
> > 参考[此处](https://github.com/reruin/sharelist#%E7%9B%AE%E5%BD%95%E5%8A%A0%E5%AF%86)的加密方法 而非nginx的加密组件
> 
> 此处的加密方法有局限性。

加密功能已增强，支持多层加密。
