### ISSUE TITLE
在老大帮助下webdav解决了。还有两个问题，1.本地目录挂载；2.mkv播放没有声音

### ISSUE THREAD

**Issue by pirately** [reruin/sharelist#176]
1.本地目录挂载能否返回到实际的目录，而不是sharelist在docker里面的目录？
我是通过docker装的sharelist，但是本地目录就算是/这种根目录，也是sharelist在docker下面的目录，用../再往上好像不行。也就是不能挂载我实际硬盘里面的其他目录。
2.mkv播放没有声音
mkv播放，没有声音，有图像

**Comment by Mit2g** [comment]
1我认为无法挂载的是因为容器无法访问外部存储 参考[此处](https://blog.csdn.net/yangzhenping/article/details/43667785) 挂载下你的存储 但是我没有docker环境无法进行测试
2可能是相应解码能力或者片源问题 更换一个小体积mkv再试

**Comment by reruin** [comment]
1. 需要手动映射下磁盘。
2. mkv只是容器格式，是否能完全播放在于其音视频的编码方式是否被播放器支持。

**Comment by pirately** [comment]
> 1我认为无法挂载的是因为容器无法访问外部存储 参考[此处](https://blog.csdn.net/yangzhenping/article/details/43667785) 挂载下你的存储 但是我没有docker环境无法进行测试
> 2可能是相应解码能力或者片源问题 更换一个小体积mkv再试
1. 这是linux命令行拷贝吧，我是说dokcer里面直接挂载外部目录
2. 好像和封装形式有关系。

> 1. 需要手动映射下磁盘。
> 2. mkv只是容器格式，是否能完全播放在于其音视频的编码方式是否被播放器支持。

1.请问怎么映射磁盘？
docker安装说明里面 
docker build -t yourname/sharelist .
docker run -d -v /etc/sharelist:/app/cache -p 33001:33001 --name="sharelist" yourname/sharelist

/sharelist/cache，是配置文件目录。
能否再设置一个参数，用于挂载本地目录？比如/sharelist/file。那我在docker镜像设置里面，指定宿主本地目录和docker的sharelist的/sharelist/file就能进行挂载了。

2. 好像是的。

**Comment by reruin** [comment]
> > 1我认为无法挂载的是因为容器无法访问外部存储 参考[此处](https://blog.csdn.net/yangzhenping/article/details/43667785) 挂载下你的存储 但是我没有docker环境无法进行测试
> > 2可能是相应解码能力或者片源问题 更换一个小体积mkv再试
> 
> 1. 这是linux命令行拷贝吧，我是说dokcer里面直接挂载外部目录
> 2. 好像和封装形式有关系。
> 
> > 1. 需要手动映射下磁盘。
> > 2. mkv只是容器格式，是否能完全播放在于其音视频的编码方式是否被播放器支持。
> 
> 1.请问怎么映射磁盘？
> docker安装说明里面
> docker build -t yourname/sharelist .
> docker run -d -v /etc/sharelist:/app/cache -p 33001:33001 --name="sharelist" yourname/sharelist
> 
> /sharelist/cache，是配置文件目录。
> 能否再设置一个参数，用于挂载本地目录？比如/sharelist/file。那我在docker镜像设置里面，指定宿主本地目录和docker的sharelist的/sharelist/file就能进行挂载了。
> 
> 1. 好像是的。

在Dockerfile 里加上 一条 VOLUME /sharelist/disk，然后docker run 时覆盖这个挂载设置，多加个 -v /宿主路径:/sharelist/disk

**Comment by Mit2g** [comment]
> > 1我认为无法挂载的是因为容器无法访问外部存储 参考[此处](https://blog.csdn.net/yangzhenping/article/details/43667785) 挂载下你的存储 但是我没有docker环境无法进行测试
> > 2可能是相应解码能力或者片源问题 更换一个小体积mkv再试
> 
> 1. 这是linux命令行拷贝吧，我是说dokcer里面直接挂载外部目录
> 2. 好像和封装形式有关系。

1以上提供的参考想要告诉你 使用-v 挂载目录 如果以上不能使你满意 请[参见]
(https://blog.csdn.net/supermao1013/article/details/83057223)
2我测试的mkv可以在dplayer下正常播放

**Comment by pirately** [comment]
> 
> 1以上提供的参考想要告诉你 使用-v 挂载目录 如果以上不能使你满意 请[参见]
> (https://blog.csdn.net/supermao1013/article/details/83057223)
> 2我测试的mkv可以在dplayer下正常播放

我比较小白，这种，我有点不明白。不太会😓。


> > 
> > 1. 好像是的。
> 
> 在Dockerfile 里加上 一条 VOLUME /sharelist/disk，然后docker run 时覆盖这个挂载设置，多加个 -v /宿主路径:/sharelist/disk
老大，这种，我在本机试的，应该是可以的。所以能否请您把reruin/sharelist的dockfile改一下？

**Comment by reruin** [comment]
> > 1以上提供的参考想要告诉你 使用-v 挂载目录 如果以上不能使你满意 请[参见]
> > (https://blog.csdn.net/supermao1013/article/details/83057223)
> > 2我测试的mkv可以在dplayer下正常播放
> 
> 我比较小白，这种，我有点不明白。不太会😓。
> 
> > > 1. 好像是的。
> > 
> > 
> > 在Dockerfile 里加上 一条 VOLUME /sharelist/disk，然后docker run 时覆盖这个挂载设置，多加个 -v /宿主路径:/sharelist/disk
> 
> 老大，这种，我在本机试的，应该是可以的。所以能否请您把reruin/sharelist的dockfile改一下？

Dockerfile 不需要修改。
启动时```docker run -d -v /etc/sharelist:/sharelist/cache -v /宿主机目录:/sharelist/disk -p 33001:33001 --name="sharelist" reruin/sharelist```。

如果你使用 docker-compose，就在 docker-compose.yml 的```volumes```下追加一条
```- /宿主机目录:/sharelist/disk```

**Comment by pirately** [comment]
> 
> Dockerfile 不需要修改。
> 启动时`docker run -d -v /etc/sharelist:/sharelist/cache -v /宿主机目录:/sharelist/disk -p 33001:33001 --name="sharelist" reruin/sharelist`。
> 
> 如果你使用 docker-compose，就在 docker-compose.yml 的`volumes`下追加一条
> `- /宿主机目录:/sharelist/disk`

应该是可以了
