### ISSUE TITLE
cf-worker问题

### ISSUE THREAD

**Issue by waynesg** [reruin/sharelist#177]
gd通过cf-worker中转
通过群晖反代了443端口,将host和token填入proxy/cf-worker.js,修改了app/config.js的端口为443,再将代码填入cf-worker项目,部署后，直接打开页面显示404.请大佬帮忙解决下。

**Comment by pirately** [comment]
群晖是本地吧？国内的环境，443就算反代了，是不是也不通？可以用frp试试，不管有没有公网的IP，都可以用frp试试，找找免费的frp服务器。

**Comment by waynesg** [comment]
> 群晖是本地吧？国内的环境，443就算反代了，是不是也不通？可以用frp试试，不管有没有公网的IP，都可以用frp试试，找找免费的frp服务器。

sharelist页面可以正常打开。就是通过打开xxx.xxxx.workers.dev这个地址显示404 not found.

**Comment by reruin** [comment]
cf-worker是用于中转流量，而非反代sharelist站点，故 访问 xxx.xxxx.workers.dev 不会有响应。

**Comment by waynesg** [comment]
> cf-worker是用于中转流量，而非反代sharelist站点，故 访问 xxx.xxxx.workers.dev 不会有响应。

明白，已经可以中转了。谢谢

**Comment by reruin** [comment]
能否发下访问地址

**Comment by waynesg** [comment]
> 能否发下访问地址

详情已发至邮箱。

**Comment by hulifox** [comment]
同样的问题，打开worker404，视频无法播放，一直显示等待响应，用的最新的worker。不知作者解决了吗？谢谢
