### ISSUE TITLE
onedrive/世纪互联 重定向url必须用https才行么

### ISSUE THREAD

**Issue by BrunuhVille** [reruin/sharelist#178]
置顶的issue里用的http://localhost/a，
我按这个尝试了几次都是，AADSTS500112错误
不知道是不是我在sharelist后台填写不对导致的。

我想问的是，如果我在sharelist后台填写
挂载条目 | 名称 | 路径
——————————
OD API版 |    abc   |    /

那么我在azure里的重定向url，应该填写什么？可以用http么

**Comment by reruin** [comment]
先更新下代码。

1. 应填写为 ```https://域名/abc```
2. 如果只是在本地使用，填写 ```http://localhost/abc``` 
3. 如果只有http的地址，填写 ```https://reruin.github.io/redirect/onedrive.html```
