### ISSUE TITLE
centos7 64bit上安装成功之后，访问IP+33001无法访问，提示拒绝连接

### ISSUE THREAD

**Issue by 1405040117** [reruin/sharelist#18]
![image](https://user-images.githubusercontent.com/9691891/47254867-18261080-d49a-11e8-96ed-5ef5782013d9.png)
![image](https://user-images.githubusercontent.com/9691891/47254876-3c81ed00-d49a-11e8-87d2-19ede41fdae2.png)
![image](https://user-images.githubusercontent.com/9691891/47254878-49064580-d49a-11e8-93f9-2075bb851d60.png)
一开始以为是没启动的原因，启动服务之后还是没用，关闭了防火墙也还是拒绝访问，检测端口发现33001端口并未开放。

**Comment by reruin** [comment]
进到 安装目录运行 npm run prod 试试。
