### ISSUE TITLE
作者，你好，希望增加禁止文档下载功能，网盘的东西只能看，不能被盗下载

### ISSUE THREAD

**Issue by kexuebin** [reruin/sharelist#180]
作者，你好，希望增加禁止文档下载功能，网盘的东西只能看，不能被盗下载

**Comment by reruin** [comment]
文档 是指 word pdf 这类文件么？

**Comment by kexuebin** [comment]
> 文档是指word pdf种类文件么？

是的，因为网盘点东西都是珍藏品，只能看，不让别人下载。取消pdf，ppt下载功能。谢谢

**Comment by reruin** [comment]
此功能目前无法支持，需要将office转成html输出。

**Comment by kexuebin** [comment]
> 
> 
> 此功能目前无法支持，需要将office转成html输出。

pdf2svg

**Comment by reruin** [comment]
除pdf，还需处理doc ppt xls等文档类型。
欢迎贡献代码，建议使用unoconv搭建文档转换接口。

**Comment by kexuebin** [comment]
> 除pdf，还需处理doc ppt xls等文档类型。
> 欢迎贡献代码，建议使用unoconv构建文档转换接口。

Libreoffice(或Openoffice)是也可以的

**Comment by reruin** [comment]
借ms的接口实现了 转码功能。

**Comment by kexuebin** [comment]
> 借ms的接口实现了转码功能。

如何体验实现了的功能。

**Comment by reruin** [comment]
此功能自动启用，你需要后台设置【匿名下载限制】 禁止office类下载即可，参考 https://github.com/reruin/sharelist/issues/191 。
