### ISSUE TITLE
希望可以增加禁止匿名用户浏览目录的功能，杜绝文件被遍历

### ISSUE THREAD

**Issue by emengweb** [reruin/sharelist#181]
昨天更新了下，发现新的密码增强功能，导致子目录下所有文件在未输入密码时，不能被正常下载T.T

考虑再三后，建议增加后台设置项"禁止匿名用户浏览目录"，或者是增加类似“.htaccess”这样目录权限文件，可以自定义是否允许列目录文件。
这样不需设置密码，也可以杜绝文件被遍历，同时还不会影响文件的正常下载，还望考虑下支持类似的功能，感谢🙏

**Comment by reruin** [comment]
你说的【禁止匿名用户浏览目录】  是否等同于 【强制登录后浏览】？

**Comment by emengweb** [comment]
有部分差异，情况如下：
**强制登录后浏览**：匿名用户无法浏览目录、无法下载文档；
**禁止匿名用户浏览目录**：用户无法浏览目录，但可以下载文档（前提是文件名&&防盗链码校验正确时）；

**Comment by reruin** [comment]
已实现。后台管理 -> 目录索引 设置为 禁用。

**Comment by emengweb** [comment]
刚刚更新到最新版本，已经完美实现了！太赞了👍👍👍
