### ISSUE TITLE
作者您好，文件无法预览是什么问题？视频和文档图片都无法预览

### ISSUE THREAD

**Issue by ziyuand** [reruin/sharelist#182]
视频预览点击后未播放直接新建窗口还是跳转原目录
onedrive无法进入二级目录
这个是文档预览的错误提示：
An error occurred
We're sorry, but for some reason we can't open this for you.

**Comment by ziyuand** [comment]
检查出来好像是加密的原因，不加密则可以正常播放 正常预览文件 加密则无法播放视频无法进入下级目录

**Comment by emengweb** [comment]
运行update.sh升级到最新版本试下，我这里是正常的，视频和pdf否可以正常预览。但是如果网站是https，pdf会无法正常预览。这块可能需要补充下预览插件的逻辑，根据协议选择对应的http或https作为预览链接起始字符。

**Comment by reruin** [comment]
> 运行update.sh升级到最新版本试下，我这里是正常的，视频和pdf否可以正常预览。但是如果网站是https，pdf会无法正常预览。这块可能需要补充下预览插件的逻辑，根据协议选择对应的http或https作为预览链接起始字符。
pdf.js 是自适应的，无法预览可能是跨域的问题，已更新pdf为强制代理。





> 检查出来好像是加密的原因，不加密则可以正常播放 正常预览文件 加密则无法播放视频无法进入下级目录

.passwd加密不影响视频预览。
