### ISSUE TITLE
重启之后，部分配置没有保存

### ISSUE THREAD

**Issue by TingyiChen** [reruin/sharelist#187]
在管理界面配置完后，重启
天翼云的挂载目录配置会变成默认的根目录
视频预览部分也会变成默认的配置

**Comment by flyvicky** [comment]
我也是挂载全部失效，要重新部署

**Comment by reruin** [comment]
请提供下页面地址。

**Comment by TingyiChen** [comment]
https://dbg.isaacchen.cn

**Comment by reruin** [comment]
> 在管理界面配置完后，重启
> 天翼云的挂载目录配置会变成默认的根目录
> 视频预览部分也会变成默认的配置

已修复。请更新代码。
