### ISSUE TITLE
能否支持OneDrive for business

### ISSUE THREAD

**Issue by ZvonimirSun** [reruin/sharelist#19]
如题，onedrive for business是可以公开文件夹权限的，但是共享链接和普通的OneDrive差别较大。尝试像OneDrive那样添加，似乎会报错。希望能够添加支持。

**Comment by reruin** [comment]
能否提供一个公开链接供我测试。

**Comment by ZvonimirSun** [comment]
https://caomsacid0-my.sharepoint.com/:f:/g/personal/sunziyang97_caoms_ac_id/EhZ8FLdHSyRIhrwstXOMUGgBhD19WuBPZFqLvWl5jXuisw?e=oYmNY3


Ting <notifications@github.com>于2018年10月23日 周二23:46写道：

**Comment by reruin** [comment]
已更新支持，暂有使用限制。 
1. 每个目录下的 文件/文件夹 数量不能超过30个，此问题后续再解决。  
2. 由于cookie的关系，强制使用中转模式输出（无需在管理页配置），会消耗服务器流量。 
 
使用方式： 
```odb:链接url``` 例如 
```odb:https://caomsacid0-my.sharepoint.com/:f:/g/personal/sunziyang97_caoms_ac_id/EhZ8FLdHSyRIhrwstXOMUGgBhD19WuBPZFqLvWl5jXuisw?e=oYmNY3```

**Comment by ZvonimirSun** [comment]
十分感谢。

**Comment by ZvonimirSun** [comment]
https://caomsacid0-my.sharepoint.com/:f:/g/personal/sunziyang97_caoms_ac_id/Eq3WZR7u8q1LnIDa3miPQOoB1yqrkZEwBjYYcRsS8dGgtg?e=t4MufS

前面那个文件夹一不小心给我散了，不知道还需不需要，我又创建了一个。

**Comment by reruin** [comment]
可以私发一个链接到我邮箱。

**Comment by Joyace** [comment]
同求 
```
https://mytccd-my.sharepoint.com/:f:/g/personal/edgyvyouu_npqmygc_my_tccd_edu/Eq__Gc-Mj85JvX2LwUMIRK0B4Trv4Hb038uCi8FQhYuGiQ?e=NWsdei
```
