### ISSUE TITLE
群晖无法通过webdav挂载sharelist

### ISSUE THREAD

**Issue by waynesg** [reruin/sharelist#190]
在macOS和win10上都可以顺利挂载sharelist.
在群晖filestation上，挂载报错“连接被服务器拒绝”
在群晖通过rclone将sharelist映射到共享文件夹，会出现如下错误：
ERROR : webdav root '': Statfs failed: about call failed: Propfind ps://xxx.xxxxx.xxx/webdav/: unsupported protocol scheme "ps"
请问有无解决办法？

**Comment by Mit2g** [comment]
地址协议有问题 请参照[说明](https://github.com/reruin/sharelist#%E6%8C%82%E8%BD%BDwebdav)挂载

**Comment by waynesg** [comment]
> 地址协议有问题 请参照[说明](https://github.com/reruin/sharelist#%E6%8C%82%E8%BD%BDwebdav)挂载

不是用sharelist挂载webdav，是通过webdav挂载sharelist,通过webdav导出挂载源

**Comment by reruin** [comment]
> 在macOS和win10上都可以顺利挂载sharelist.
> 在群晖filestation上，挂载报错“连接被服务器拒绝”
> 在群晖通过rclone将sharelist映射到共享文件夹，会出现如下错误：
> ERROR : webdav root '': Statfs failed: about call failed: Propfind ps://xxx.xxxxx.xxx/webdav/: unsupported protocol scheme "ps"
> 请问有无解决办法？

缺少群晖调试环境，如果方便的话是否可将服务反代出来，私发我以提调试。

**Comment by waynesg** [comment]
> > 在macOS和win10上都可以顺利挂载sharelist.
> > 在群晖filestation上，挂载报错“连接被服务器拒绝”
> > 在群晖通过rclone将sharelist映射到共享文件夹，会出现如下错误：
> > ERROR : webdav root '': Statfs failed: about call failed: Propfind ps://xxx.xxxxx.xxx/webdav/: unsupported protocol scheme "ps"
> > 请问有无解决办法？
> 
> 缺少群晖调试环境，如果方便的话是否可将服务反代出来，私发我以提调试。

已发至邮箱

**Comment by lwn2004** [comment]
我在群晖上也遇到这个问题，请问是怎么解决的？
