### ISSUE TITLE
建议后台增加禁止下载开关，特殊文件只能阅读不能下载

### ISSUE THREAD

**Issue by kexuebin** [reruin/sharelist#191]
建议后台增加禁止下载开关，特殊文件只能阅读不能下载。
pdf等文件前台有下载按钮，希望后台增加隐藏这个下载功能。

**Comment by reruin** [comment]
后台管理 已添加“匿名下载配置”，允许填写 正则表达式，符合规则的路径方可下载。

例如 禁止 doc 下载：```(?<!(doc|docx))$```

**Comment by kexuebin** [comment]
> 
> 
> 后台管理 已添加“匿名下载配置”，允许填写 正则表达式，符合规则的路径方可下载。
> 
> 例如 禁止 doc 下载：`(?<!(doc|docx))$`

我在网站执行了update.sh，怎么没看到这个功能。只多了一个index_enable和anonymous_download功能

**Comment by kexuebin** [comment]
> 
> 
> 后台管理 已添加“匿名下载配置”，允许填写 正则表达式，符合规则的路径方可下载。
> 
> 例如 禁止 doc 下载：`(?<!(doc|docx))$`

输入这个(?<!(doc|docx))$，清楚缓存，又没了。

**Comment by reruin** [comment]
> > 后台管理 已添加“匿名下载配置”，允许填写 正则表达式，符合规则的路径方可下载。
> > 例如 禁止 doc 下载：`(?<!(doc|docx))$`
> 
> 输入这个(?<!(doc|docx))$，清楚缓存，又没了。

你指的是这个配置项没了，还是说不起作用了。

**Comment by kexuebin** [comment]
> > > 后台管理已添加“匿名下载配置”，允许填充正则表达式，符合规则的路径方可下载。
> > > 例如，禁止doc下载：`(?<!(doc|docx))$`
> > 
> > 
> > 输入这个（？<！（doc | docx））$，清楚缓存，又没了。
> 
> 你指的是这个配置项没了，还是说不起作用了。

配置有，可以设置，但是设置了保存不了，清除缓存和重启都丢失了配置。

**Comment by reruin** [comment]
没有发现此问题，你要不更新代码看看。

**Comment by kexuebin** [comment]
> 
> 
> 没有发现此问题，你要不更新代码看看。

已解决
