### ISSUE TITLE
天翼网盘账号登录无法挂载，提示验证码识别接口无法使用

### ISSUE THREAD

**Issue by flyvicky** [reruin/sharelist#193]
天翼网盘账号登录无法挂载，提示验证码识别接口无法使用

**Comment by qz919** [comment]
https://api.moeclub.org/SampleCode
用这个接口吧，测试了一下，可用。

**Comment by flyvicky** [comment]
接口可用，但是还是抱

> https://api.moeclub.org/SampleCode
> 用这个接口吧，测试了一下，可用。

接口可用，但是还提示验证码识别接口无法使用

**Comment by qz919** [comment]
> > https://api.moeclub.org/SampleCode
> > 用这个接口吧，测试了一下，可用。
> 
> 接口可用，但是还提示验证码识别接口无法使用
你搭建完之后，登陆之前进管理再改一下接口地址。

**Comment by flyvicky** [comment]
> > > https://api.moeclub.org/SampleCode
> > > 用这个接口吧，测试了一下，可用。
> > 
> > 
> > 接口可用，但是还提示验证码识别接口无法使用
> > 你搭建完之后，登陆之前进管理再改一下接口地址。

![image](https://user-images.githubusercontent.com/55944584/83117168-54eacc80-a0ff-11ea-81a3-556dab2df46e.png)
后台已更新，但是还提示验证码识别接口无法使用

**Comment by qz919** [comment]
> > > > https://api.moeclub.org/SampleCode
> > > > 用这个接口吧，测试了一下，可用。
> > > 
> > > 
> > > 接口可用，但是还提示验证码识别接口无法使用
> > > 你搭建完之后，登陆之前进管理再改一下接口地址。
> 
> ![image](https://user-images.githubusercontent.com/55944584/83117168-54eacc80-a0ff-11ea-81a3-556dab2df46e.png)
> 后台已更新，但是还提示验证码识别接口无法使用

重新搭建试试，我刚刚又试了一下，接口没有问题的，修改接口之后要点击保存才会生效。

**Comment by flyvicky** [comment]
> > > > > https://api.moeclub.org/SampleCode
> > > > > 用这个接口吧，测试了一下，可用。
> > > > 
> > > > 
> > > > 接口可用，但是还提示验证码识别接口无法使用
> > > > 你搭建完之后，登陆之前进管理再改一下接口地址。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/55944584/83117168-54eacc80-a0ff-11ea-81a3-556dab2df46e.png)
> > 后台已更新，但是还提示验证码识别接口无法使用
> 
> 重新搭建试试，我刚刚又试了一下，接口没有问题的，修改接口之后要点击保存才会生效。

每次修改我都会保存，我重搭试试

**Comment by flyvicky** [comment]
从搭也一样

**Comment by NUSC** [comment]
试过，这个接口也不行。

> https://api.moeclub.org/SampleCode
> 用这个接口吧，测试了一下，可用。

**Comment by reruin** [comment]
> https://api.moeclub.org/SampleCode
> 用这个接口吧，测试了一下，可用。

moeclub接口参数不一致，没法直接使用。
请更新代码，并将接口配置为 ```https://api.moeclub.org/SampleCode#Base64=image&Type=Default&$noscheme=1&$output=raw```

**Comment by ninmoe** [comment]
> > https://api.moeclub.org/SampleCode
> > 用这个接口吧，测试了一下，可用。
> 
> moeclub接口参数不一致，没法直接使用。
> 请更新代码，并将接口配置为 `https://api.moeclub.org/SampleCode#Base64=image&Type=Default&$noscheme=1&$output=raw`

更新后可以登录，但是，虽然可以显示目录和文件，但是预览视频和图片会提示Unauthorized

**Comment by NUSC** [comment]
> > https://api.moeclub.org/SampleCode
> > 用这个接口吧，测试了一下，可用。
> 
> moeclub接口参数不一致，没法直接使用。
> 请更新代码，并将接口配置为 `https://api.moeclub.org/SampleCode#Base64=image&Type=Default&$noscheme=1&$output=raw`

这个可以用。
大佬顺便看看这个 issue，https://github.com/reruin/sharelist/issues/192

**Comment by dwf135** [comment]
> > https://api.moeclub.org/SampleCode 
> > 用这个接口吧，测试了一下，可用。
> 
> moeclub接口参数不一致，没法直接使用。
> 请更新代码，关联接口配置为`https://api.moeclub.org/SampleCode#Base64=image&Type=Default&$noscheme=1&$output=raw`

我用这个接口也是提示接口无法使用 腾讯云广州  不知道为啥

**Comment by reruin** [comment]
> > > https://api.moeclub.org/SampleCode
> > > 用这个接口吧，测试了一下，可用。
> > 
> > 
> > moeclub接口参数不一致，没法直接使用。
> > 请更新代码，关联接口配置为`https://api.moeclub.org/SampleCode#Base64=image&Type=Default&$noscheme=1&$output=raw`
> 
> 我用这个接口也是提示接口无法使用 腾讯云广州 不知道为啥

更新下代码 再用。

**Comment by dwf135** [comment]
> > > > https://api.moeclub.org/SampleCode
> > > > 用这个接口吧，测试了一下，可用。
> > > 
> > > 
> > > moeclub接口参数不一致，没法直接使用。
> > > 请更新代码，关联接口配置为`https://api.moeclub.org/SampleCode#Base64=image&Type=Default&$noscheme=1&$output=raw`
> > 
> > 
> > 我用这个接口也是提示接口无法使用 腾讯云广州 不知道为啥
> 
> 更新下代码 再用。

可以了  感谢
