### ISSUE TITLE
天翼不能挂载

### ISSUE THREAD

**Issue by qingchencjg** [reruin/sharelist#195]
![Y{6NMT7)IU((1`6B{{5B%JO](https://user-images.githubusercontent.com/65435648/83319635-d9119100-a272-11ea-9232-779f5911f55d.png)
我别的账号可以，就只有这个账号密码不能登录，账号密码是正确的
作者有没有qq群啥的，发下群，这里交流太费劲了，我打开GitHub不怎么给力

**Comment by reruin** [comment]
更新下代码 再试试。

**Comment by dwf135** [comment]
我的天翼账号被限速100K  别人下载也是100K   换新号正常  好坑

**Comment by reruin** [comment]
天翼网盘会根据下载文件的ip数量来识别盗链机制，多个ip下载文件，会被限速。

**Comment by qingchencjg** [comment]
> 更新下代码 再试试。

Error
Looks like something broke!

        
Error: options.uri is a required argument
    at Request.init (/www/wwwroot/v.qcxitong.top/sharelist/node_modules/request/request.js:234:31)
    at new Request (/www/wwwroot/v.qcxitong.top/sharelist/node_modules/request/request.js:130:8)
    at request (/www/wwwroot/v.qcxitong.top/sharelist/node_modules/request/index.js:54:10)
    at /www/wwwroot/v.qcxitong.top/sharelist/app/utils/http.js:13:7
    at new Promise (<anonymous>)
    at http (/www/wwwroot/v.qcxitong.top/sharelist/app/utils/http.js:12:12)
    at fetchData (/www/wwwroot/v.qcxitong.top/sharelist/plugins/drive.189cloud.js:327:20)
    at Object.file (/www/wwwroot/v.qcxitong.top/sharelist/plugins/drive.189cloud.js:419:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
        
      我更新了，还是那样，别的账号没有问题。有别的解决办法没有。
我觉的可能性是，我差不多2个月前用的就是这个程序，那时候账号登录用着用着不能用了，问了作者，有回复说是验证码问题，会不会是那个时候遗留的问题。

**Comment by reruin** [comment]
> > 更新下代码 再试试。
> 
> Error
> Looks like something broke!
> 
> Error: options.uri is a required argument
> at Request.init (/www/wwwroot/v.qcxitong.top/sharelist/node_modules/request/request.js:234:31)
> at new Request (/www/wwwroot/v.qcxitong.top/sharelist/node_modules/request/request.js:130:8)
> at request (/www/wwwroot/v.qcxitong.top/sharelist/node_modules/request/index.js:54:10)
> at /www/wwwroot/v.qcxitong.top/sharelist/app/utils/http.js:13:7
> at new Promise ()
> at http (/www/wwwroot/v.qcxitong.top/sharelist/app/utils/http.js:12:12)
> at fetchData (/www/wwwroot/v.qcxitong.top/sharelist/plugins/drive.189cloud.js:327:20)
> at Object.file (/www/wwwroot/v.qcxitong.top/sharelist/plugins/drive.189cloud.js:419:22)
> at
> at process._tickCallback (internal/process/next_tick.js:189:7)
> 
> ```
>   我更新了，还是那样，别的账号没有问题。有别的解决办法没有。
> ```
> 
> 我觉的可能性是，我差不多2个月前用的就是这个程序，那时候账号登录用着用着不能用了，问了作者，有回复说是验证码问题，会不会是那个时候遗留的问题。

验证码的问题在之前的版本里 已经解决了。你拉取新代码再试试。

**Comment by qingchencjg** [comment]
> > > 更新下代码 再试试。
> > 
> > 
> > Error
> > Looks like something broke!
> > Error: options.uri is a required argument
> > at Request.init (/www/wwwroot/v.qcxitong.top/sharelist/node_modules/request/request.js:234:31)
> > at new Request (/www/wwwroot/v.qcxitong.top/sharelist/node_modules/request/request.js:130:8)
> > at request (/www/wwwroot/v.qcxitong.top/sharelist/node_modules/request/index.js:54:10)
> > at /www/wwwroot/v.qcxitong.top/sharelist/app/utils/http.js:13:7
> > at new Promise ()
> > at http (/www/wwwroot/v.qcxitong.top/sharelist/app/utils/http.js:12:12)
> > at fetchData (/www/wwwroot/v.qcxitong.top/sharelist/plugins/drive.189cloud.js:327:20)
> > at Object.file (/www/wwwroot/v.qcxitong.top/sharelist/plugins/drive.189cloud.js:419:22)
> > at
> > at process._tickCallback (internal/process/next_tick.js:189:7)
> > ```
> >   我更新了，还是那样，别的账号没有问题。有别的解决办法没有。
> > ```
> > 
> > 
> > 我觉的可能性是，我差不多2个月前用的就是这个程序，那时候账号登录用着用着不能用了，问了作者，有回复说是验证码问题，会不会是那个时候遗留的问题。
> 
> 验证码的问题在之前的版本里 已经解决了。你拉取新代码再试试。

我刚删除了，重新安装的，应该是最新版本吧，不用更新了吧

**Comment by reruin** [comment]
> > > > 更新下代码 再试试。
> > > 
> > > 
> > > Error
> > > Looks like something broke!
> > > Error: options.uri is a required argument
> > > at Request.init (/www/wwwroot/v.qcxitong.top/sharelist/node_modules/request/request.js:234:31)
> > > at new Request (/www/wwwroot/v.qcxitong.top/sharelist/node_modules/request/request.js:130:8)
> > > at request (/www/wwwroot/v.qcxitong.top/sharelist/node_modules/request/index.js:54:10)
> > > at /www/wwwroot/v.qcxitong.top/sharelist/app/utils/http.js:13:7
> > > at new Promise ()
> > > at http (/www/wwwroot/v.qcxitong.top/sharelist/app/utils/http.js:12:12)
> > > at fetchData (/www/wwwroot/v.qcxitong.top/sharelist/plugins/drive.189cloud.js:327:20)
> > > at Object.file (/www/wwwroot/v.qcxitong.top/sharelist/plugins/drive.189cloud.js:419:22)
> > > at
> > > at process._tickCallback (internal/process/next_tick.js:189:7)
> > > ```
> > >   我更新了，还是那样，别的账号没有问题。有别的解决办法没有。
> > > ```
> > > 
> > > 
> > > 我觉的可能性是，我差不多2个月前用的就是这个程序，那时候账号登录用着用着不能用了，问了作者，有回复说是验证码问题，会不会是那个时候遗留的问题。
> > 
> > 
> > 验证码的问题在之前的版本里 已经解决了。你拉取新代码再试试。
> 
> 我刚删除了，重新安装的，应该是最新版本吧，不用更新了吧

 是最新的。还有问题么。

**Comment by qingchencjg** [comment]
> > > > > 更新下代码 再试试。
> > > > 
> > > > 
> > > > Error
> > > > Looks like something broke!
> > > > Error: options.uri is a required argument
> > > > at Request.init (/www/wwwroot/v.qcxitong.top/sharelist/node_modules/request/request.js:234:31)
> > > > at new Request (/www/wwwroot/v.qcxitong.top/sharelist/node_modules/request/request.js:130:8)
> > > > at request (/www/wwwroot/v.qcxitong.top/sharelist/node_modules/request/index.js:54:10)
> > > > at /www/wwwroot/v.qcxitong.top/sharelist/app/utils/http.js:13:7
> > > > at new Promise ()
> > > > at http (/www/wwwroot/v.qcxitong.top/sharelist/app/utils/http.js:12:12)
> > > > at fetchData (/www/wwwroot/v.qcxitong.top/sharelist/plugins/drive.189cloud.js:327:20)
> > > > at Object.file (/www/wwwroot/v.qcxitong.top/sharelist/plugins/drive.189cloud.js:419:22)
> > > > at
> > > > at process._tickCallback (internal/process/next_tick.js:189:7)
> > > > ```
> > > >   我更新了，还是那样，别的账号没有问题。有别的解决办法没有。
> > > > ```
> > > > 
> > > > 
> > > > 我觉的可能性是，我差不多2个月前用的就是这个程序，那时候账号登录用着用着不能用了，问了作者，有回复说是验证码问题，会不会是那个时候遗留的问题。
> > > 
> > > 
> > > 验证码的问题在之前的版本里 已经解决了。你拉取新代码再试试。
> > 
> > 
> > 我刚删除了，重新安装的，应该是最新版本吧，不用更新了吧
> 
> 是最新的。还有问题么。

Error
Looks like something broke!

        
Error: options.uri is a required argument
    at Request.init (/www/wwwroot/v.qcxitong.top/sharelist/node_modules/request/request.js:234:31)
    at new Request (/www/wwwroot/v.qcxitong.top/sharelist/node_modules/request/request.js:130:8)
    at request (/www/wwwroot/v.qcxitong.top/sharelist/node_modules/request/index.js:54:10)
    at /www/wwwroot/v.qcxitong.top/sharelist/app/utils/http.js:13:7
    at new Promise (<anonymous>)
    at http (/www/wwwroot/v.qcxitong.top/sharelist/app/utils/http.js:12:12)
    at fetchData (/www/wwwroot/v.qcxitong.top/sharelist/plugins/drive.189cloud.js:327:20)
    at Object.file (/www/wwwroot/v.qcxitong.top/sharelist/plugins/drive.189cloud.js:419:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
        
      还是这样啊

**Comment by reruin** [comment]
@qingchencjg 这是解析readme 出错，已修复，请更新代码。相关 #189 。

**Comment by qingchencjg** [comment]
> @qingchencjg 这是解析readme 出错，已修复，请更新代码。相关 #189 。

好了，多谢
