### ISSUE TITLE
目前遇到的问题汇总（已更新最新版）

### ISSUE THREAD

**Issue by kexuebin** [reruin/sharelist#201]
你好作者，感谢你对shareliat做出的贡献，目前我是天翼云账户密码挂载的，今天更新最新版，还是遇到了以前的问题，不知道是不是我不会操作，请指教，十分感谢。
1、README.md放在那个文件夹，那个文件夹出现500错误。（测试已解决）
2、下载了源码中的.passwd，放在任意文件夹下，无加密功能。
3、pdf后台按照#191的方法：(?<!(doc|docx|pdf))$不能禁止下载，依然可以点击下载按钮下载。
4、pdf在线预览报错，
An error occurred while loading the PDF，PDF.js v2.6.4 (build: 96ad60f1)
Message: NetworkError when attempting to fetch resource. 不知道是不是因为pdf.js跨域的问题，如果是跨域问题，需要把pdfjs里面的viewer.js里面验证跨域的代码注释掉，if (fileOrigin !== viewerOrigin) {throw new Error('file origin does not match viewer\'s');}
5、打开txt文件报５００错误，
Looks like something broke!  
Error: options.uri is a required argument
    at Request.init (/www/wwwroot/pan.xxx.com/node_modules/request/request.js:234:31)
    at new Request (/www/wwwroot/pan.xxx.com/node_modules/request/request.js:130:8)
    at request (/www/wwwroot/pan.xxx.com/node_modules/request/index.js:54:10)
    at /www/wwwroot/pan.xxx.com/app/utils/http.js:13:7
    at new Promise (<anonymous>)
    at http (/www/wwwroot/pan.xxx.com/app/utils/http.js:12:12)
    at fetchData (/www/wwwroot/pan.xxx.com/plugins/drive.189cloud.js:327:20)
    at Object.file (/www/wwwroot/pan.xxx.com/plugins/drive.189cloud.js:419:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
6、刷新文件目录之后，后面就访问不了文件了，会出现Unauthorized或者forbidden的错误提示。
注：我已经更新的最新代码，2-6还是有问题。

**Comment by emengweb** [comment]
如果你已经登录过“管理”账号，那目录的.passwd以及(?<!(doc|docx|pdf))$的限制，对管理员是不生效的。最佳的测试方法，复制文件链接，新建无痕窗口打开，就可以看到效果了:d

**Comment by kexuebin** [comment]
> 
> 
> 如果你已经登录过“管理”账号，那目录的.passwd以及(?<!(doc|docx|pdf))$的限制，对管理员是不生效的。最佳的测试方法，复制文件链接，新建无痕窗口打开，就可以看到效果了:d

换了一个浏览器还是不行，另个清除缓存以及cookie也不行

**Comment by kexuebin** [comment]
> 1.5已修复，相关问题 [＃189](https://github.com/reruin/sharelist/issues/189)。
> 2,3-建议检查是否退出管理员登录。
> 4确实跨域导致的，目前已强制PDF预览代理，此外其他办公类预览时也可能因为远程转码失败导致“无法预览”。

的确是退出管理员的，我在新浏览器是打开，从来没登录过，另外代码是我今天上午更新的2020/6/4

**Comment by reruin** [comment]
> > 1.5已修复，相关问题 [＃189](https://github.com/reruin/sharelist/issues/189)。
> > 2,3-建议检查是否退出管理员登录。
> > 4确实跨域导致的，目前已强制PDF预览代理，此外其他办公类预览时也可能因为远程转码失败导致“无法预览”。
> 
> 的确是退出管理员的，我在新浏览器是打开，从来没登录过，另外代码是我今天上午更新的2020/6/4

 #189 问题有可能导致 passwd 文件读取失败，进而无法校验密码。拉取最新代码， 试下2、3问题（退出管理员）。

**Comment by kexuebin** [comment]
> > > 1.5已修复，相关问题[＃189](https://github.com/reruin/sharelist/issues/189)。
> > > 2,3-建议检查是否退出管理员登录。
> > > 4确实跨域导致的，目前已强制PDF预览代理，此外其他办公类预览时也可能因为远程转码失败导致“无法预览”。
> > 
> > 
> > 的确是退出管理员的，我在新浏览器是打开，从来没登录过，另外代码是我今天上午更新的2020/6/4
> 
> [＃189](https://github.com/reruin/sharelist/issues/189)问题有可能导致passwd文件读取失败，且无法校验密码。拉取最新代码，试下2、3问题（退出管理员）。

我是直接在服务器执行./update.sh，这样说错误的吗？需要下载github上的最新代码上传覆盖安装？

**Comment by Mit2g** [comment]
> > > > 1.5已修复，相关问题[＃189](https://github.com/reruin/sharelist/issues/189)。
> > > > 2,3-建议检查是否退出管理员登录。
> > > > 4确实跨域导致的，目前已强制PDF预览代理，此外其他办公类预览时也可能因为远程转码失败导致“无法预览”。
> > > 
> > > 
> > > 的确是退出管理员的，我在新浏览器是打开，从来没登录过，另外代码是我今天上午更新的2020/6/4
> > 
> > 
> > [＃189](https://github.com/reruin/sharelist/issues/189)问题有可能导致passwd文件读取失败，且无法校验密码。拉取最新代码，试下2、3问题（退出管理员）。
> 
> 我是直接在服务器执行./update.sh，这样是错误的吗？需要下载github上的最新代码上传覆盖安装？

运行`update.sh` 更新即可

**Comment by kexuebin** [comment]
> > > > > 1.5已修复，相关问题[＃189](https://github.com/reruin/sharelist/issues/189)。
> > > > > 2,3-建议检查是否退出管理员登录。
> > > > > 4确实跨域导致的，目前已强制PDF预览代理，此外其他办公类预览时也可能因为远程转码失败导致“无法预览”。
> > > > 
> > > > 
> > > > 的确是退出管理员的，我在新浏览器是打开，从来没登录过，另外代码是我今天上午更新的2020/6/4
> > > 
> > > 
> > > [＃189](https://github.com/reruin/sharelist/issues/189)问题有可能导致passwd文件读取失败，且无法校验密码。拉取最新代码，试下2、3问题（退出管理员）。
> > 
> > 
> > 我是直接在服务器执行./update.sh，这样是错误的吗？需要下载github上的最新代码上传覆盖安装？
> 
> 运行`update.sh` 更新即可

1确定解决了，5还是没解决依然500错误，打开文件经常出现forbidden和unauthorized

**Comment by reruin** [comment]
> 打开文件经常出现forbidden和unauthorized
那是因为 下载链接 已经过期了。
后台管理 将 【下载链接有效期】设置为0 或者 设置一个较大的数字。

**Comment by kexuebin** [comment]
> 你好作者，感谢你对shareliat做出的贡献，目前我是天翼云账户密码挂载的，今天更新最新版，还是遇到了以前的问题，不知道是不是我不会操作，请指教，十分感谢。
> 1、README.md放在那个文件夹，那个文件夹出现500错误。
> 2、下载了源码中的.passwd，放在任意文件夹下，无加密功能。
> 3、pdf后台按照#191的方法：(?<!(doc|docx|pdf))$不能禁止下载，依然可以点击下载按钮下载。
> 4、pdf在线预览报错，
> An error occurred while loading the PDF，PDF.js v2.6.4 (build: 96ad60f1)
> Message: NetworkError when attempting to fetch resource. 不知道是不是因为pdf.js跨域的问题，如果是跨域问题，需要把pdfjs里面的viewer.js里面验证跨域的代码注释掉，if (fileOrigin !== viewerOrigin) {throw new Error('file origin does not match viewer's');}
> 5、打开txt文件报５００错误，
> Looks like something broke!
> Error: options.uri is a required argument
> at Request.init (/www/wwwroot/pan.xxx.com/node_modules/request/request.js:234:31)
> at new Request (/www/wwwroot/pan.xxx.com/node_modules/request/request.js:130:8)
> at request (/www/wwwroot/pan.xxx.com/node_modules/request/index.js:54:10)
> at /www/wwwroot/pan.xxx.com/app/utils/http.js:13:7
> at new Promise ()
> at http (/www/wwwroot/pan.xxx.com/app/utils/http.js:12:12)
> at fetchData (/www/wwwroot/pan.xxx.com/plugins/drive.189cloud.js:327:20)
> at Object.file (/www/wwwroot/pan.xxx.com/plugins/drive.189cloud.js:419:22)
> at
> at process._tickCallback (internal/process/next_tick.js:189:7)
> 6、刷新文件目录之后，后面就访问不了文件了，出现Unauthorized的错误提示。
> 注：我已经更新的最新代码，为什么1和5还是不行，我是在服务器执行的./update.sh，不能这样更新吗？是不是要重新下载github的文件上传覆盖吗。
