### ISSUE TITLE
小白目前遇到的问题汇总

### ISSUE THREAD

**Issue by kexuebin** [reruin/sharelist#203]
你好作者，感谢你对shareliat做出的贡献，目前我是天翼云账户密码挂载的，今天更新最新版，还是遇到了以前的问题，不知道是不是我不会操作，请指教，十分感谢。
1、README.md放在那个文件夹，那个文件夹出现500错误。（测试已解决）
2、下载了源码中的.passwd，放在任意文件夹下，无加密功能。
3、pdf后台按照#191的方法：(?<!(doc|docx|pdf))$的方法，可行。（测试已解决），希望删除PDF的下载按钮，这样由后台控制文档让不让下载。
4、pdf在线预览经常报错，有时候还打不开。
An error occurred while loading the PDF，PDF.js v2.6.4 (build: 96ad60f1)
Message: NetworkError when attempting to fetch resource. 
5、打开txt文件报５００错误，（测试已解决，txt文件需要另存为utf-8格式）
Looks like something broke!
Error: options.uri is a required argument
at Request.init (/www/wwwroot/pan.xxx.com/node_modules/request/request.js:234:31)
at new Request (/www/wwwroot/pan.xxx.com/node_modules/request/request.js:130:8)
at request (/www/wwwroot/pan.xxx.com/node_modules/request/index.js:54:10)
at /www/wwwroot/pan.xxx.com/app/utils/http.js:13:7
at new Promise ()
at http (/www/wwwroot/pan.xxx.com/app/utils/http.js:12:12)
at fetchData (/www/wwwroot/pan.xxx.com/plugins/drive.189cloud.js:327:20)
at Object.file (/www/wwwroot/pan.xxx.com/plugins/drive.189cloud.js:419:22)
at
at process._tickCallback (internal/process/next_tick.js:189:7)
6、刷新文件目录之后，后面就访问不了文件了，会出现Unauthorized或者forbidden的错误提示。
注：我已经更新的最新代码，2-6还是有问题。（测试已经解决）
（不好意思，手机上点错了，那个issue误关闭了，重开一个；）

**Comment by kexuebin** [comment]
6/15/10:40，更新代码，
1问题解决了，
2、3问题还是不行，
4问题报错如下：PDF.js v2.6.8 (build: 7aa1b2d4)
信息：The browser/environment lacks native support for critical functionality used by the PDF.js library (e.g. `ReadableStream` and/or `Promise.allSettled`); please use an ES5-compatible build instead
5问题还是500错误，
6问题，后台设置了0，还是会出现Unauthorized提示。
：）

**Comment by reruin** [comment]
> 6/15/10:40，更新代码，
> 1问题解决了，
> 2、3问题还是不行，
> 4问题报错如下：PDF.js v2.6.8 (build: 7aa1b2d4)
> 信息：The browser/environment lacks native support for critical functionality used by the PDF.js library (e.g. `ReadableStream` and/or `Promise.allSettled`); please use an ES5-compatible build instead
> 5问题还是500错误，
> 6问题，后台设置了0，还是会出现Unauthorized提示。
> ：）

方便把config.json 发我么，很多问题无法定位。

**Comment by kexuebin** [comment]
{"port":33001,"proxy_enable":0,"preview_enable":1,"index_enable":1,"webdav_path":"/webdav/","max_age_dir":900000,"max_age_file":900000,"max_age_download":0,"skin":"default","ignore_file_extensions":"","ignore_files":".passwd","readme_enable":1,"ignore_paths":{"__root__":["/readme.md"],"lb":[]},"max_age_download_sign":"sl_1589335553685","anonymous_uplod_enable":0,"anonymous_enable":1,"anonymous_download":"(?<!(doc|docx|pdf))$","plugin_option":[{"key":"plugin_preview_media___video_previewable_formats","value":{"value":"mp4,ogg,webm,mpeg,m4v","label":"支持预览的视频后缀","placeholder":"文件扩展名，多个用逗号分隔"}},{"key":"plugin_preview_media___video_previewable_player","value":{"value":"default","label":"视频预览播放器","options":[{"label":"默认","value":"default"},{"label":"DPlayer","value":"dplayer"}]}}],"custom_style":"","custom_script":"","proxy_paths":[""],"proxy_server":"","ocr_server":"","token":"我是token","title":"ShareList","path":[{"name":"ctcc","path":"ctcc://我是账号/313013950168170?password=我是密码"}],"language":""}

**Comment by kexuebin** [comment]
> 
> 
> > 6/15/10:40，更新代码，
> > 1问题解决了，
> > 2、3问题还是不行，
> > 4问题报错如下：PDF.js v2.6.8 (build: 7aa1b2d4)
> > 信息：The browser/environment lacks native support for critical functionality used by the PDF.js library (e.g. `ReadableStream` and/or `Promise.allSettled`); please use an ES5-compatible build instead
> > 5问题还是500错误，
> > 6问题，后台设置了0，还是会出现Unauthorized提示。
> > ：）
> 
> 方便把config.json 发我么，很多问题无法定位。

{"port":33001,"proxy_enable":0,"preview_enable":1,"index_enable":1,"webdav_path":"/webdav/","max_age_dir":900000,"max_age_file":900000,"max_age_download":0,"skin":"default","ignore_file_extensions":"","ignore_files":".passwd","readme_enable":1,"ignore_paths":{"root":["/readme.md"],"lb":[]},"max_age_download_sign":"sl_1589335553685","anonymous_uplod_enable":0,"anonymous_enable":1,"anonymous_download":"(?<!(doc|docx|pdf))$","plugin_option":[{"key":"plugin_preview_media___video_previewable_formats","value":{"value":"mp4,ogg,webm,mpeg,m4v","label":"支持预览的视频后缀","placeholder":"文件扩展名，多个用逗号分隔"}},{"key":"plugin_preview_media___video_previewable_player","value":{"value":"default","label":"视频预览播放器","options":[{"label":"默认","value":"default"},{"label":"DPlayer","value":"dplayer"}]}}],"custom_style":"","custom_script":"","proxy_paths":[""],"proxy_server":"","ocr_server":"","token":"我是token","title":"ShareList","path":[{"name":"ctcc","path":"ctcc://我是账号/313013950168170?password=我是密码"}],"language":""}

**Comment by reruin** [comment]
> > > 6/15/10:40，更新代码，
> > > 1问题解决了，
> > > 2、3问题还是不行，
> > > 4问题报错如下：PDF.js v2.6.8 (build: 7aa1b2d4)
> > > 信息：The browser/environment lacks native support for critical functionality used by the PDF.js library (e.g. `ReadableStream` and/or `Promise.allSettled`); please use an ES5-compatible build instead
> > > 5问题还是500错误，
> > > 6问题，后台设置了0，还是会出现Unauthorized提示。
> > > ：）
> > 
> > 
> > 方便把config.json 发我么，很多问题无法定位。
> 
> {"port":33001,"proxy_enable":0,"preview_enable":1,"index_enable":1,"webdav_path":"/webdav/","max_age_dir":900000,"max_age_file":900000,"max_age_download":0,"skin":"default","ignore_file_extensions":"","ignore_files":".passwd","readme_enable":1,"ignore_paths":{"root":["/readme.md"],"lb":[]},"max_age_download_sign":"sl_1589335553685","anonymous_uplod_enable":0,"anonymous_enable":1,"anonymous_download":"(?<!(doc|docx|pdf))$","plugin_option":[{"key":"plugin_preview_media___video_previewable_formats","value":{"value":"mp4,ogg,webm,mpeg,m4v","label":"支持预览的视频后缀","placeholder":"文件扩展名，多个用逗号分隔"}},{"key":"plugin_preview_media___video_previewable_player","value":{"value":"default","label":"视频预览播放器","options":[{"label":"默认","value":"default"},{"label":"DPlayer","value":"dplayer"}]}}],"custom_style":"","custom_script":"","proxy_paths":[""],"proxy_server":"","ocr_server":"","token":"我是token","title":"ShareList","path":[{"name":"ctcc","path":"ctcc://我是账号/313013950168170?password=我是密码"}],"language":""}

更新后再试下，4\5\6 已复现，2/3无法复现。

**Comment by kexuebin** [comment]
> 
> 
> > > > 6/15/10:40，更新代码，
> > > > 1问题解决了，
> > > > 2、3问题还是不行，
> > > > 4问题报错如下：PDF.js v2.6.8 (build: 7aa1b2d4)
> > > > 信息：The browser/environment lacks native support for critical functionality used by the PDF.js library (e.g. `ReadableStream` and/or `Promise.allSettled`); please use an ES5-compatible build instead
> > > > 5问题还是500错误，
> > > > 6问题，后台设置了0，还是会出现Unauthorized提示。
> > > > ：）
> > > 
> > > 
> > > 方便把config.json 发我么，很多问题无法定位。
> > 
> > 
> > {"port":33001,"proxy_enable":0,"preview_enable":1,"index_enable":1,"webdav_path":"/webdav/","max_age_dir":900000,"max_age_file":900000,"max_age_download":0,"skin":"default","ignore_file_extensions":"","ignore_files":".passwd","readme_enable":1,"ignore_paths":{"root":["/readme.md"],"lb":[]},"max_age_download_sign":"sl_1589335553685","anonymous_uplod_enable":0,"anonymous_enable":1,"anonymous_download":"(?<!(doc|docx|pdf))$","plugin_option":[{"key":"plugin_preview_media___video_previewable_formats","value":{"value":"mp4,ogg,webm,mpeg,m4v","label":"支持预览的视频后缀","placeholder":"文件扩展名，多个用逗号分隔"}},{"key":"plugin_preview_media___video_previewable_player","value":{"value":"default","label":"视频预览播放器","options":[{"label":"默认","value":"default"},{"label":"DPlayer","value":"dplayer"}]}}],"custom_style":"","custom_script":"","proxy_paths":[""],"proxy_server":"","ocr_server":"","token":"我是token","title":"ShareList","path":[{"name":"ctcc","path":"ctcc://我是账号/313013950168170?password=我是密码"}],"language":""}
> 
> 更新后再试下，4\5\6 已复现，2/3无法复现。

2)、目录还是没加密，可以浏览任意文件，换了新浏览器，也清了cookie和缓存。
3)、已解决，这种隐藏下载只对我这种小白起作用，右键查看元素，真实地址全暴露，有折中的解决方案吗，重要的文档不能下载，非常感谢你。
4)、PDF偶尔能打开，偶尔不能，第一次打开提示：嗯...无法访问此页面，尝试此操作，请确保你已获取正确的网址: http://mozilla.github.io，（多按几次F5刷新后，再点PDF，可以打开灰黑背景，里面没内容，但是也是报错，PDF.js v2.6.8 (build: 7aa1b2d4)
Message: Setting up fake worker failed: "Cannot load script at: http://mozilla.github.io/pdf.js/es5/build/pdf.worker.js".），再过一会刷新，又能正常打开了，加载慢慢，哈哈哈
5)、打开txt文件乱码：�𾴵��������û�����ã������ƾ����Ķ����й����������Ķ�
6)、已解决

**Comment by reruin** [comment]
1. 请知晓预览即代表可下载，sharelist已为 docx、pptx等文档格式转码为pdf预览（防下载），但pdf本身除外。
2. 说下你使用的浏览器， 以及 网盘地址。

**Comment by kexuebin** [comment]
>     1. sharelist已为 docx、pptx等文档格式转码为pdf预览

网盘地址我发你邮箱，浏览器使用的谷歌、Edge

**Comment by reruin** [comment]
> > ```
> > 1. sharelist已为 docx、pptx等文档格式转码为pdf预览
> > ```
> 
> 网盘地址我发你邮箱，浏览器使用的谷歌、Edge

已收到邮件。
1. passwd无效已复现（根目录校验失败导致，等待修复）。
2. txt文件乱码问题是由于中文 ansi编码问题导致，请将txt另存为utf8保存。
3. pdf 的问题 我这边显示ok。

**Comment by kexuebin** [comment]
> > > ```
> > > 1. sharelist已为 docx、pptx等文档格式转码为pdf预览
> > > ```
> > 
> > 
> > 网盘地址我发你邮箱，浏览器使用的谷歌，Edge
> 
> 已收到邮件。
> 
> 1. passwd无效已复现（根目录错误失败导致，等待修复）。
> 2. txt文件乱码问题是由于中文ansi编码问题导致的，替换txt另存为utf8保存。
> 3. 预览加密文件内部pdf的问题暂时无法解决，后续考虑加入浏览器原生预览可选项。

老大，PDF菜单里面的下载按钮也删除一下。

**Comment by reruin** [comment]
> > > > ```
> > > > 1. sharelist已为 docx、pptx等文档格式转码为pdf预览
> > > > ```
> > > 
> > > 
> > > 网盘地址我发你邮箱，浏览器使用的谷歌，Edge
> > 
> > 
> > 已收到邮件。
> > 
> > 1. passwd无效已复现（根目录错误失败导致，等待修复）。
> > 2. txt文件乱码问题是由于中文ansi编码问题导致的，替换txt另存为utf8保存。
> > 3. 预览加密文件内部pdf的问题暂时无法解决，后续考虑加入浏览器原生预览可选项。
> 
> 
> 老大，PDF菜单里面的下载按钮也删除一下。

那是组件自带的。。sharelist 初衷是作为个人向的网盘挂载工具， 文档预览插件也是方便之用，不会过多适配功能，还请谅解。

**Comment by kexuebin** [comment]
> > > > > ```
> > > > > 1. sharelist已为 docx、pptx等文档格式转码为pdf预览
> > > > > ```
> > > > 
> > > > 
> > > > 网盘地址我发你邮箱，浏览器使用的谷歌，Edge
> > > 
> > > 
> > > 已收到邮件。
> > > 
> > > 1. passwd无效已复现（根目录错误失败导致，等待修复）。
> > > 2. txt文件乱码问题是由于中文ansi编码问题导致的，替换txt另存为utf8保存。
> > > 3. 预览加密文件内部pdf的问题暂时无法解决，后续考虑加入浏览器原生预览可选项。
> > 
> > 
> > 老大，PDF菜单里面的下载按钮也删除一下。
> 
> 共享列表初衷是作为个人向的网盘挂载工具，文档预览插件也是方便之用，不会过多适配功能，还请谅解。

后台既然加了禁止下载功能，pdf的下载按钮也删除一下吧，这样和谐一点，哈哈，感谢感谢
