### ISSUE TITLE
install页面瞎填如何重置

### ISSUE THREAD

**Issue by BevalZ** [reruin/sharelist#205]
如题...瞎几把填了之后再次回到页面提示not found
另...可否有图片说明教程

**Comment by reruin** [comment]
1. 如果记得密码，可访问 ```/manage```页面，里面可重新配置。
2. 密码也乱填，去代码目录 ```cache```下，删除```config.json```，之后重启sharelist。

如何重启:
1. docker: 重启容器
2. bash 部署： ``` pm2 restart all ``` 重启

**Comment by BevalZ** [comment]
好大，谢谢大佬
