### ISSUE TITLE
挂载天翼云文件夹配置老是丢失

### ISSUE THREAD

**Issue by dwf135** [reruin/sharelist#206]
天翼云配置文件    //账户/文件夹ID?password=密码
经常过两天就变成了//账户?password=密码

**Comment by reruin** [comment]
更新下sharelist。
相关 https://github.com/reruin/sharelist/issues/187。

**Comment by dwf135** [comment]
> 更新下sharelist。
> 相关 [https://github.com/reruin/sharelist/issues/187。](https://github.com/reruin/sharelist/issues/187%E3%80%82)

感谢回复   更新后访问目录密码也解决了
