### ISSUE TITLE
挂载天翼云盘会出现多人共用账号的情况

### ISSUE THREAD

**Issue by xrgzs** [reruin/sharelist#207]
今天早上发现天翼云盘的下载速度慢，询问客服后回应：
您好，经排查，用户的账号存在多人共用账号的情况。根据天翼云盘用户服务协议（协议地址： https://cloud.189.cn/licence/service_agreement.html ），用户违反用户协议中，3.7使用本软件及本协议项下服务所禁止的行为第（4）点——为商业运营目的安装、使用、运行本软件；转让、出租、销售或使用本软件系统进行商业经营活动；转售、分发、作商业用途、作为分时或服务处使用或用于经营网站或利用服务牟利，包括但不限于针对本软件、账号和相关服务进行正常使用之外的增值商业行为，如易名和重新包装销售、在商业活动中作为免费赠品、培训、商业评估以及任何形式的再次租赁。故限制用户单个文件下载速度限制为50KB/s。

**Comment by reruin** [comment]
天翼网盘会根据下载文件的ip数量来识别盗链机制，多个ip下载文件，会被限速到100KB。
