### ISSUE TITLE
能开发一个挂载ftp的目录索引吗？

### ISSUE THREAD

**Issue by eicky** [reruin/sharelist#208]
能开发一个挂载ftp的目录索引吗？

**Comment by reruin** [comment]
之前有写过 [drive.ftp.js](https://github.com/reruin/sharelist/blob/d3d6b69868a8cdb872076908b8730a84eeef7a70/plugins/drive.ftp.js)，但是因为性能问题移除了。

**Comment by eicky** [comment]
请教一下具体是什么问题呢？

**Comment by reruin** [comment]
交互指令太多，速度慢。

**Comment by eicky** [comment]
了解了，感谢
