### ISSUE TITLE
请问世纪互联的重定向如何填写呢？

### ISSUE THREAD

**Issue by stopSlander** [reruin/sharelist#209]
一直提示这个

抱歉，我們無法將您登入。
AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'c97034c7-dc92-48a5-a55c-0b0ef702b7c0'.

**Comment by reruin** [comment]
假设你挂载的名称为 ```abc```
1. 如果是通过https访问，填写 https://域名/abc
2. 如果只是在本地使用，填写 http://localhost:33001/abc
2. 如果是通过http访问，填写 https://reruin.github.io/redirect/onedrive.html
