### ISSUE TITLE
cf-worker中转问题

### ISSUE THREAD

**Issue by hulifox** [reruin/sharelist#210]
[cf-worker问题 #177](https://github.com/reruin/sharelist/issues/177)
这个问题与我的类似，但是好像并没有解决。
使用CF中转流量，GD是使用分享文件夹ID挂载，OD是使用API，但是按照readme配置后，发现视频无法播放，提示等待cf-worker的域名的响应，直接打开cf-worker的域名显示404。尝试使用浏览器直接用cf-worker的域名下载文件，发现提示401错误，用idm下载会弹出登录对话框。检查了cf-worker中的域名和密码，确定没有问题。
另外，关于中转路径的填写的问题，我尝试中转OD，但是在中转路径里填写目录名称，发现并不能中转流量，依然走的是OD自己的流量。
请大佬帮忙看看。谢谢。

**Comment by reruin** [comment]
1. #177 提问者是因为token填写错误导致中转失败。
2. cf-worker不会对目录进行代理，故直接访问域名显示404；回源获取请求时，当身份验证失败时会返回401。
3. 中转路径 相当于 url 的 pathname 部分，以此issue对应url为例，应填写 ```/reruin/sharelist/issues/210``` 。

如果要详细定位原因，最好发下```cache/config.json```。

**Comment by hulifox** [comment]
谢谢作者的回答。
1.身份验证失败仅可能是token错误吗？
2.我按照pathname填写了中转路径，od依然没有中转，除非我开全局中转。
3.config.json私发给你可以吗？
谢谢

**Comment by reruin** [comment]
> 谢谢作者的回答。
> 1.身份验证失败仅可能是token错误吗？
> 2.我按照pathname填写了中转路径，od依然没有中转，除非我开全局中转。
> 3.config.json已发到邮箱。
> 谢谢

401 只可能是身份验证失败，请检查 host 和 token 无误。

中转路径有一处 bug 已修复。

**Comment by hulifox** [comment]
> > 谢谢作者的回答。
> > 1.身份验证失败仅可能是token错误吗？
> > 2.我按照pathname填写了中转路径，od依然没有中转，除非我开全局中转。
> > 3.config.json已发到邮箱。
> > 谢谢
> 
> 401 只可能是身份验证失败，请检查 host 和 token 无误。
> 
> 中转路径有一处 bug 已修复。

1.自己又排查了一下，发现token中如果含有特殊符号，cf-worker会把特殊符号及之后的字符自动忽略，修改后cf-worker已经可以正常工作。
2.update后，填写的中转路径已可正常工作。
谢谢作者。
