### ISSUE TITLE
在线播放无法加载avi文件

### ISSUE THREAD

**Issue by hulifox** [reruin/sharelist#213]
作者好，
尝试使用默认播放器无法播放avi文件，改为本机中转后尝试使用dplayer，无法加载文件。
请问是程序不支持在线播放avi文件吗？
谢谢

**Comment by reruin** [comment]
h5 video 不支持 avi。

**Comment by Mit2g** [comment]
dplayer可能也不支持 与是否中转无关 但是文档中没有提到相关格式支持 所以无法准确判断
