### ISSUE TITLE
希望支持解析cloudreve的分享链接

### ISSUE THREAD

**Issue by xrgzs** [reruin/sharelist#214]
现在国内有许多网盘使用cloudreve搭建，比如白熊云盘，希望sharelist能够支持解析cloudreve的分享链接

**Comment by nuyoahaoyun** [comment]
> 现在国内有许多网盘使用cloudreve搭建，比如白熊云盘，希望sharelist能够支持解析cloudreve的分享链接

自己搭建一个cloudreve 不就行了……

**Comment by xrgzs** [comment]
> > 现在国内有许多网盘使用cloudreve搭建，比如白熊云盘，希望sharelist能够支持解析cloudreve的分享链接
> 
> 自己搭建一个cloudreve 不就行了……

不是那个意思，我要的是直链解析，就像解析蓝奏的分享链接那样，直接解析出直链
