### ISSUE TITLE
heroku容器中一段时间后自动格式化

### ISSUE THREAD

**Issue by yenpou** [reruin/sharelist#216]
首先感谢开发者的无偿付出，让我们有幸使用到这么好的程序；其次，我发现了了一些小小的问题：就是在heroku容器中，该程序会在一段时间后自动格式化，重新安装，且网路上没有具体的解决办法；我也看了一些其他人使用heroku容器运行的此程序，发现他们也有此类问题，目前还不知道究竟是heroku的锅还是程序抑或是设置的问题，期待并感谢开发者的解答

**Comment by Mit2g** [comment]
免费用户的限制
https://github.com/reruin/sharelist/issues/90#issuecomment-571860129
