### ISSUE TITLE
建议增加分享直链

### ISSUE THREAD

**Issue by jgpgtg** [reruin/sharelist#217]
例如当下载时自动缩短网址为域名加6位码，缓存在本地，时间自定，看看可行否

**Comment by Mit2g** [comment]
增加短链功能似乎需要借助数据库 这增加了搭建成本 而且不适用于搭建在免费容器的用户

**Comment by reruin** [comment]
sharelist定位为个人向网盘工具，暂不考虑此功能。

**Comment by jgpgtg** [comment]
好的额，明白了，谢谢您了
