### ISSUE TITLE
使用HeroKu部署sharelist，挂载onedriveforbussiness时，最后一步显示not found

### ISSUE THREAD

**Issue by WaldeinCheng** [reruin/sharelist#218]

**Comment by reruin** [comment]
odb的挂载内容处应填写为 分享url，形如 
https://xxx-my.sharepoint.com/:f:/g/personal/xxx 。

**Comment by Mit2g** [comment]
可能为账号问题 可以排除为程序问题
https://github.com/reruin/sharelist/issues/222 为类似情况
