### ISSUE TITLE
webdav使用中的一些问题

### ISSUE THREAD

**Issue by 666wcy** [reruin/sharelist#219]
在播放器链接webdav后，不使用中转的存储器无问题，可正常播放
下面这强制中转的三种类型，可显示列表，但无法下载或播放
在开关代理和设置中转服务器后出现同样问题，直接用网页浏览无异常
![image](https://user-images.githubusercontent.com/40867688/86315371-8b66ba80-bc5c-11ea-99a8-d32bbc5b0866.png)
![image](https://user-images.githubusercontent.com/40867688/86315449-bf41e000-bc5c-11ea-840d-87245991e717.png)
![image](https://user-images.githubusercontent.com/40867688/86315527-eef0e800-bc5c-11ea-9c11-f9662a302523.png)

**Comment by reruin** [comment]
使用 PotPlayer / FileExplorer(移动端) + 本机代理 / cf-worker 测试未复现。

如果你使用的cf-worker 代理，可考虑更新下 https://github.com/reruin/sharelist/blob/master/proxy/cf-worker.js

**Comment by 666wcy** [comment]
cf-worker更换后问题得到解决，感谢
