### ISSUE TITLE
老哥，有一些小问题。

### ISSUE THREAD

**Issue by tangxuchao** [reruin/sharelist#221]
因为heroku一段时间后会重置，这个配置如何备份，可以下一次不用那么麻烦的配置直接搞定。
还有除了heroku，还能能用什么云服务器搭建这个sharelist吗？

**Comment by tangxuchao** [comment]
再就是能添加文件删除功能吗？

**Comment by Mit2g** [comment]
> 因为heroku一段时间后会重置，这个配置如何备份，可以下一次不用那么麻烦的配置直接搞定。


免费用户的限制
#duplicate https://github.com/reruin/sharelist/issues/90#issuecomment-571860129

> 还有除了heroku，还能能用什么云服务器搭建这个sharelist吗？
可以参考PR中 在Kubesail上搭建 模板可以自建 甚至无需PR中提到的存储 只需类似于Heroku形式的参数保存

**Comment by tangxuchao** [comment]
好的，我试试

**Comment by tangxuchao** [comment]
> > 因为heroku一段时间后会重置，这个配置如何备份，可以下一次不用那么麻烦的配置直接搞定。
> 
> 免费用户的限制
> #duplicate [#90 (comment)](https://github.com/reruin/sharelist/issues/90#issuecomment-571860129)
> 
> > 还有除了heroku，还能能用什么云服务器搭建这个sharelist吗？
> 
> 可以参考PR中 在Kubesail上搭建 模板可以自建 甚至无需PR中提到的存储 只需类似于Heroku形式的参数保存

好的我试试

**Comment by tangxuchao** [comment]
> > [和，]，]，]，
> 
> •
> [#duplicate#90（评论）](https://github.com/reruin/sharelist/issues/90#issuecomment-571860129)
> 
> > [英雄，] 共享列表？
> 
> [pr] [库贝赛] [英雄]
试了一会 搞不成
