### ISSUE TITLE
通过OD API挂载后，显示not found

### ISSUE THREAD

**Issue by zjboy1984** [reruin/sharelist#222]
应该不是个人账户，因为是原来用教育邮箱注册的onedrive，名称也是显示的广厚设计学校

**Comment by LongStudy** [comment]
我老的账户以前正常，今天进去也是notfound了

**Comment by Mit2g** [comment]
有同样情况 已重新绑定/注册 均无法正确显示 同时客户端经常性提示网络问题 非所有号有此情况 初步判断为账户问题

**Comment by reruin** [comment]
教育系列 测试正常。可先登录web onedrive 检查下账号。

**Comment by zjboy1984** [comment]
我是教育账号，登录web onedrive 没问题，用其他列表程序也不显示 内容了，初步判断是API的规则改了，google的绑定也是显示not found
