### ISSUE TITLE
关于文件预览的几个问题

### ISSUE THREAD

**Issue by mydyx** [reruin/sharelist#225]
1. 所有格式的文档类文件，如 pdf, doc, ppt等，都无法打开

- doc, ppt 直接显示“无法预览”
- pdf 是 “Unexpected server response (403) while retrieving PDF”

2. 能不能在列表页加一个下载按钮，目前似乎是必须先预览才可以下载？

3. 以及，能不能自定义对哪些类型的文件进行预览？

**Comment by reruin** [comment]
1. 预览doc/ppt/xls 时，sharelist会使用ms的接口转码成pdf预览，此过程需访问外网，如果外网无法联通会显示 无法预览。
2. 后台管理处有统一的 【预览功能 启用/禁用】 选项，禁用后，在列表点击 即可直接下载。
3. 文档类预览插件 暂不支持 自定义预览类型。

**Comment by kexuebin** [comment]
> 1. 预览doc / ppt / xls时，sharelist会使用ms的接口转码成pdf预览，此过程需访问外网，如果外网无法联通会显示无法预览。
> 2. 后台管理处有统一的【预览功能启用/扩展】选项，替换后，在列表中单击即可直接下载。
> 3. 文档类预览插件暂不支持自定义预览类型。

希望可以加一个禁止/允许下载开关

**Comment by reruin** [comment]
可在```后台管理 - 下载设置``` 中设置 禁止下载的文件。
此项支持正则表达式。
示例：
1. 禁止所有文件下载 ```^$```
2. doc、pdf文件禁止下载：```(?<!(doc|pdf))$```
3. abc 路径下的文件禁止下载  ```^((?!abc).)*$```
4. 允许 def 路径下的文件下载 ```def(?=\/)```

**Comment by kexuebin** [comment]
> 可在`后台管理 - 下载设置` 中设置 禁止下载的文件。
> 此项支持正则表达式。
> 示例：
> 
> 1. 禁止所有文件下载 `^$`
> 2. doc、pdf文件禁止下载：`(?<!(doc|pdf))$`
> 3. abc 路径下的文件禁止下载  `^((?!abc).)*$`
> 4. 允许 def 路径下的文件下载 `def(?=\/)`

按照这样操作了还是有下载的按钮

**Comment by reruin** [comment]
> > 可在`后台管理 - 下载设置` 中设置 禁止下载的文件。
> > 此项支持正则表达式。
> > 示例：
> > 
> > 1. 禁止所有文件下载 `^$`
> > 2. doc、pdf文件禁止下载：`(?<!(doc|pdf))$`
> > 3. abc 路径下的文件禁止下载  `^((?!abc).)*$`
> > 4. 允许 def 路径下的文件下载 `def(?=\/)`
> 
> 按照这样操作了还是有下载的按钮

1. 先尝试更新代码。
2. 如果更新代码后还是无效，可以私发一下 网站地址 和 管理密码么，我进去看下。
