### ISSUE TITLE
关于蓝奏云的问题

### ISSUE THREAD

**Issue by Slistkubesail** [reruin/sharelist#226]
1.挂载蓝奏云单目录只显示前50个文件，能否实现显示文件夹内的所有文件
https://wwa.lanzous.com/b02n6c6qb
2.能否实现显示子文件夹，使用自定义链接挂载（蓝奏云会员功能）
子文件夹https://wwa.lanzous.com/b02n6c66b
自定义链接https://wwa.lanzous.com/s/zdy333

**Comment by reruin** [comment]
1.  已更新，如果目录内文件过多，首次访问时加载时间会边长。
2.  之前用普通账号测试，即使分享的文件夹内有子文件夹，lanzou也不会显示出；此次更新已可以显示 会员分享文件夹中的 子文件夹。
附带实现了lanzou的目录密码功能（如 b02n6c66b 下 2222 文件夹），此功能会导致该目录下的 .passwd 密码形式失效。
3.  如你提供的自定义链接，挂载内容填写为 ```s/zdy333```即可。

**Comment by Slistkubesail** [comment]
感谢！已更新，遇到如下问题

1. 未更新前挂载s/zdy333，目录内文件可以显示前50个。更新后访问此目录显示Not Found
2. lanzou的目录密码功能，会导致不能直接下载文件，必须输入目录密码才会下载。
文件夹b02n6c66b设置密码为0000，挂载路径填b02n6c66b或0000@b02n6c66b，访问此目录都必须输入密码。
其实禁用目录索引就很好，游客既不能浏览目录又能下载文件，就不需要目录密码功能了，能否去除此功能

**Comment by reruin** [comment]
更新再试试。
对于2 ，sharelist将自动关联挂载密码。
注意，如果子目录包含密码，那直接下载文件时，仍然会要求输入密码。

**Comment by Slistkubesail** [comment]
1.更新了，自定义链接还是显示Not Found（无所谓，主要是2、3条）

2.举个例子
挂载路径b02n6c66b，蓝奏文件夹0000设置了密码，所有子文件夹都未设置密码
游客直接打开https://xxxx.com/0000/3333/初音.MP4 需要输入密码，才能下载
使用video标签无法播放
<video标签 src="https://xxxx.com/0000/1111/初音.MP4" controls="controls" autoplay="autoplay"></video标签>
**能否实现在url链接加入密码就可以直接打开文件**
比如这样https://xxxx.com/passwd@0000/3333/初音.MP4
或有其它解决办法么。谢谢！

3.如果没了蓝奏会员， 子文件夹会无法显示。
我需要挂载上万个路径，虚拟路径可以支持翻页么（每页100个路径）？

**Comment by reruin** [comment]
> 1.更新了，自定义链接还是显示Not Found（无所谓，主要是2、3条）
> 
> 2.举个例子
> 挂载路径b02n6c66b，蓝奏文件夹0000设置了密码，所有子文件夹都未设置密码
> 游客直接打开[https://xxxx.com/0000/3333/初音.MP4](https://xxxx.com/0000/3333/%E5%88%9D%E9%9F%B3.MP4) 需要输入密码，才能下载
> 使用video标签无法播放
> <video标签 src="[https://xxxx.com/0000/1111/初音.MP4](https://xxxx.com/0000/1111/%E5%88%9D%E9%9F%B3.MP4)" controls="controls" autoplay="autoplay"></video标签>
> **能否实现在url链接加入密码就可以直接打开文件**
> 比如这样[https://xxxx.com/passwd@0000/3333/初音.MP4](https://xxxx.com/passwd@0000/3333/%E5%88%9D%E9%9F%B3.MP4)
> 或有其它解决办法么。谢谢！
> 
> 3.如果没了蓝奏会员， 子文件夹会无法显示。
> 我需要挂载上万个路径，虚拟路径可以支持翻页么（每页100个路径）？

这些问题 我确定是解决了的。要不清除缓存再试试。
1.  请参考 https://sharelist.reruin.net/lz1 f428251
2. 请参考 https://sharelist.reruin.net/0000/3333/初音.mp4?preview
3. 不支持翻页，会加载完所有后显示。
![image](https://user-images.githubusercontent.com/7403780/87224001-11e56f80-c3b4-11ea-99d1-e464261bc6ec.png)

**Comment by Slistkubesail** [comment]
删除sharelist重新远程安装，成功了！

我用bash /root/sharelist/update.sh，提示更新成功，出现以上错误
https://sharelist.reruin.net/lz1/20200711223510.jpg?preview
安装在这里/root/sharelist，请问正确的执行更新方法是什么

**Comment by reruin** [comment]
一般用 bash update.sh 就可以了。我就是拿这个更新的 ~

**Comment by Slistkubesail** [comment]
我用bash update.sh
提示bash: update.sh: No such file or directory
不行以后更新我就删除重装吧。
感谢您这几天的耐心回答！

**Comment by reruin** [comment]
> 我用bash update.sh
> 提示bash: update.sh: No such file or directory
> 不行以后更新我就删除重装吧。
> 感谢您这几天的耐心回答！

在 /root/sharelist/ 目录里 bash update.sh，也就是 之前你提到的 bash /root/sharelist/update.sh。
不成功可能是缓存的问题，下次更新完 去后台清理一次缓存。
