### ISSUE TITLE
世纪互联无法挂载，求教

### ISSUE THREAD

**Issue by qingchencjg** [reruin/sharelist#228]
![image](https://user-images.githubusercontent.com/65435648/87238078-83fb9a00-c430-11ea-8f45-a085917c9e1d.png)
![image](https://user-images.githubusercontent.com/65435648/87238085-9aa1f100-c430-11ea-8e13-02fba5c5d116.png)
![image](https://user-images.githubusercontent.com/65435648/87238094-b1484800-c430-11ea-82dd-01c7fbe04b18.png)
![image](https://user-images.githubusercontent.com/65435648/87238101-c7560880-c430-11ea-8bed-41cb74fea6be.png)
报错网页地址
https://login.partner.microsoftonline.cn/common/oauth2/authorize?client_id=4b8a6529-d095-42d7-95cc-5f4b880d2724&scope=offline_access%20files.readwrite.all&response_type=code&redirect_uri=https%3A%2F%2Freruin.github.io%2Fredirect%2Fonedrive.html&state=http%3A%2F%2Fv.qcxitong.top%2Fsj1

**Comment by reruin** [comment]
将重定向URI设置为 ```https://reruin.github.io/redirect/onedrive.html```。

**Comment by qingchencjg** [comment]
可以了，谢谢
还有一个问题是密码
我给一个目录加密了，文件夹里放了.passwd文件
名称111111密码22222
但是验证的时候点确定没有反应，
不知道是我网卡还是程序出bug了，我以前是可以用的

**Comment by qingchencjg** [comment]
> 将重定向URI设置为`https://reruin.github.io/redirect/onedrive.html`。

可以了，谢谢
还有一个问题是密码
我给一个目录加密了，文件夹里放了.passwd文件
名称111111密码22222
但是验证的时候点确定没有反应，
不知道是我网卡还是程序出bug了，我以前是可以用的

**Comment by reruin** [comment]
有个小bug，修复了下。你更新再试。

**Comment by zjboy1984** [comment]
Error
Looks like something broke!

        
TypeError: Cannot read property 'map' of undefined
    at Object.folder (/root/sharelist/plugins/drive.od.api.js:398:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by zjboy1984** [comment]
挂载时出现这个

**Comment by reruin** [comment]
> 挂载时出现这个

拉取新代码试试。

**Comment by wapssc** [comment]
组织名是怎么填写的？

**Comment by zjboy1984** [comment]
> 组织名是怎么填写的？

什么组织名?

**Comment by wapssc** [comment]
挂载的时候机密和id下面要填组织名称啊

**Comment by wapssc** [comment]
> > 组织名是怎么填写的？
> 
> 什么组织名?

挂载的时候机密和id下面要填组织名称啊

**Comment by zjboy1984** [comment]
> > > 组织名是怎么填写的？
> > 
> > 
> > 什么组织名?
> 
> 挂载的时候机密和id下面要填组织名称啊

额，不是直接写od吗

**Comment by lbzt2017** [comment]
> > > 组织名是怎么填写的？
> > 
> > 
> > 什么组织名?
> 
> 挂载的时候机密和id下面要填组织名称啊

没有看到有地方写组织名称[http://01.027cgb.com/633378/QQ%E6%88%AA%E5%9B%BE20201020165439.jpg](url)

**Comment by shuzheforandroid** [comment]
> > 挂载时出现这个
> 
> 拉取新代码试试。

大佬我在挂架OD 也出现了
Error
Looks like something broke!

TypeError: Cannot read property 'map' of undefined
at Object.folder (/root/sharelist/plugins/drive.od.api.js:398:36)
at
at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by shuzheforandroid** [comment]
> > > > 组织名是怎么填写的？
> > > 
> > > 
> > > 什么组织名?
> > 
> > 
> > 挂载的时候机密和id下面要填组织名称啊
> 
> 额，不是直接写od吗

解决没有？ 俺也一样遇到这个问题了

**Comment by wapssc** [comment]
> > > > > 组织名是怎么填写的？
> > > > 
> > > > 
> > > > 什么组织名?
> > > 
> > > 
> > > 挂载的时候机密和id下面要填组织名称啊
> > 
> > 
> > 额，不是直接写od吗
> 
> 解决没有？ 俺也一样遇到这个问题了
就是文件下载地址的前边几个字母，不知道的话我这里写的有教程http://m.80226.cn/post-39.html
