### ISSUE TITLE
和彩云突然无法挂载

### ISSUE THREAD

**Issue by dwf135** [reruin/sharelist#232]
提示错误：timeout  已更新最新版本
![QQ截图20200716135618](https://user-images.githubusercontent.com/9071816/87632717-8893bb80-c76c-11ea-92b1-79cdfc34bd11.png)

**Comment by dwf135** [comment]
貌似是网盘的问题 网页也登录不上
![2020-07-16_140132](https://user-images.githubusercontent.com/9071816/87633263-a1e93780-c76d-11ea-8fad-980e848f8719.jpg)

**Comment by reruin** [comment]
你尝试下 用手机4G 登录官网试试。
