### ISSUE TITLE
请问WebDAV路径要怎么填

### ISSUE THREAD

**Issue by xiaodiaoz** [reruin/sharelist#233]
我是通过群晖上的docker安装的，挂载了天翼云盘，想通过WebDAV挂载到nplayer上，不会设置。。。

**Comment by reruin** [comment]
默认是： http://ip:33001/webdav

**Comment by sady2014** [comment]
> 默认是： http://ip:33001/webdav

请问账户密码怎么配置？不然的话，只需要知道Ip就直接挂到电脑上了

**Comment by xiaodiaoz** [comment]
> 默认是： http://ip:33001/webdav

感谢老哥，解决了！！

**Comment by reruin** [comment]
> > 默认是： http://ip:33001/webdav
> 
> 请问账户密码怎么配置？不然的话，只需要知道Ip就直接挂到电脑上了

webdav 与 页面访问 保持一致的权限。你可加 passwd设定权限，这样
