### ISSUE TITLE
彩云视频播放时效过期

### ISSUE THREAD

**Issue by YiMioffice** [reruin/sharelist#234]
如题，彩云播放视频到一半，会显示视频播放失败，不知道是不是token过期，有解决办法吗

**Comment by reruin** [comment]
播放多久出现的失败，能否发下链接。

**Comment by YiMioffice** [comment]
![TIM截图20200720102951](https://user-images.githubusercontent.com/50079226/87893989-0957fd80-ca74-11ea-9073-3dde263f4fe9.png)
https://list.fbk.ink/cmcc/cmcc/rain.mp4?preview
进度条什么都不跳，有几率会播放失败，使用的是dplayer

**Comment by youwen233** [comment]
> ![TIM截图20200720102951](https://user-images.githubusercontent.com/50079226/87893989-0957fd80-ca74-11ea-9073-3dde263f4fe9.png)
> https://list.fbk.ink/cmcc/cmcc/rain.mp4?preview
> 进度条什么都不跳，有几率会播放失败，使用的是dplayer

我这貌似没啥问题，能顺利从头播到尾，一次成功

**Comment by YiMioffice** [comment]
可能浏览器不同？我用的是新版edge

**Comment by youwen233** [comment]
> 可能浏览器不同？我用的是新版edge

我的也是

**Comment by reruin** [comment]
确实是链接有效期造成的，播放器在播放时并不会一次性加载完，目前没有什么好的解决方法。
