### ISSUE TITLE
请问能支持天翼家庭云吗？

### ISSUE THREAD

**Issue by MasterOfStar** [reruin/sharelist#238]
>>可以提供一个小号供研究
>>
>已发送至gmail邮箱

_https://github.com/reruin/sharelist/issues/157#issuecomment-641417259_
上次已经提供了账号来着

**Comment by reruin** [comment]
可以支持。使用 密码账号 挂载即可。

**Comment by MasterOfStar** [comment]
> 可以支持。使用 密码账号 挂载即可。

似乎仍只能挂载个人云和企业云
![image](https://user-images.githubusercontent.com/21274896/89269930-2fcd8980-d66d-11ea-9705-f29ca176583d.png)

**Comment by reruin** [comment]
天翼云 账号登陆版

**Comment by reruin** [comment]
> 天翼云 账号登陆版 兼容。

**Comment by MasterOfStar** [comment]
> > 天翼云 账号登陆版 兼容。

似乎还是不行 挂载后列出的文件还是天翼个人云里面的文件
我在个人云中建立的“个人云”文件夹被列出，但家庭云中的“家庭云”文件夹并没有列出...

![image](https://user-images.githubusercontent.com/21274896/89278351-90ae8f00-d678-11ea-9dd9-1f2775544eb1.png)

**Comment by reruin** [comment]
更新后 用家庭云插件。
