### ISSUE TITLE
服务器占用和错误问题

### ISSUE THREAD

**Issue by youwen233** [reruin/sharelist#239]
- 服务器占用问题
我使用的是阿里云轻量应用服务器，内存只有2G，单核CPU，但发现带Sharelist压力山大，如图所示:![image.png](https://i.loli.net/2020/07/23/rdF6gWC3lAMt7Vx.png)
 - 网页错误问题
挂载天翼云后，输入完账号密码，网页便开始加载，最后无法加载，就提示了Nginx连接超时界面，此时只能访问管理界面
![image.png](https://i.loli.net/2020/07/23/4eJdIEyVuxrwato.png)

**Comment by youwen233** [comment]
![Number2](https://i.loli.net/2020/07/25/MVFusRjEOqlXz5i.png)

**Comment by youwen233** [comment]
经核实，是验证码挂了，导致一直在尝试验证码，最后服务器炸裂

**Comment by reruin** [comment]
可用moeclub家的验证码服务，https://api.moeclub.org/SampleCode#Base64=image&Type=Default&$noscheme=1&$output=raw

**Comment by youwen233** [comment]
> 可用moeclub家的验证码服务，https://api.moeclub.org/SampleCode#Base64=image&Type=Default&$noscheme=1&$output=raw

嗯，当晚用的也是这个，不知道是什么原因，可能当时出了点问题，目前已恢复正常，感谢帮助
