### ISSUE TITLE
设置好cf中转后文件无法下载

### ISSUE THREAD

**Issue by r1172464137** [reruin/sharelist#240]
部署在docker
视频可以正常播放，但文件无法正常下载，如果走的是服务器流量文件和视频都能正常下载或观看。
![批注 2020-07-25 115925](https://user-images.githubusercontent.com/29038520/88448266-7271b380-ce6e-11ea-9d45-eac0f5bbeaab.jpg)

**Comment by youwen233** [comment]
一样的症状，使用IDM却可以下载，未知原因

**Comment by reruin** [comment]
此问题已修复，请更新cfworker。
