### ISSUE TITLE
Heroku休眠再开机，就要重新安装

### ISSUE THREAD

**Issue by Way445** [reruin/sharelist#242]

**Comment by Mit2g** [comment]
免费用户的限制
#duplicate https://github.com/reruin/sharelist/issues/90#issuecomment-571860129

**Comment by Way445** [comment]
付费用户重启也要重新安装，希望加入挂载盘信息写入环境变量中.

**Comment by Mit2g** [comment]
> 付费用户重启也要重新安装，希望加入挂载盘信息写入环境变量中.

按照上一条comment提供的链接操作 将信息以变量形式存储 就可以达成你要的

**Comment by Way445** [comment]
**感谢，已解决**
