### ISSUE TITLE
和彩云选择挂载目录后无显示

### ISSUE THREAD

**Issue by Way445** [reruin/sharelist#243]
![Screenshot_20200730-143058](https://user-images.githubusercontent.com/64531014/88888684-5d7f9080-d271-11ea-9e02-e50df7d9910c.png)

**Comment by Way445** [comment]
![Screenshot_20200730-142559](https://user-images.githubusercontent.com/64531014/88888834-a0416880-d271-11ea-85ce-ff802fcde57e.jpg)

**载打错了**

**Comment by reruin** [comment]
已修复，请按照一下方式进行挂载。
```
//用户名/初始文件夹ID?password=密码 
```
更多 请参考readme。

**Comment by Way445** [comment]
> 已修复，请按照一下方式进行进行载。
> 
> ```
> //用户名/初始文件夹ID?password=密码 
> ```
> 
> 更多请参考自述文件。

**初始文件夹id指的是起始文件夹吗？
//用户名/Root?password=密码，这样写，sharelist显示空白
![image](https://user-images.githubusercontent.com/64531014/89659544-9a4b2780-d902-11ea-81bb-7f548754623f.png)
 这样//用户名/初始文件夹ID?password=密码，则正常显示根目录**
