### ISSUE TITLE
webdav显示NO FOUND

### ISSUE THREAD

**Issue by Qa7060123** [reruin/sharelist#246]
NO FOUND

**Comment by reruin** [comment]
用webdav客户端访问。浏览器访问是不会显示的。

**Comment by reruin** [comment]
暂不支持。可考虑在根目录加密码（passwd文件），之后用 token做密码登录webdav(用户名随意)。

**Comment by Mit2g** [comment]
> 暂不支持。可考虑在根目录加密码（passwd文件），之后用 token做密码登录webdav(用户名随意)。

还有一个疑问 目前WebDAV仅可用于挂载不可用于管理或者是上传吗？

**Comment by reruin** [comment]
> > 暂不支持。可考虑在根目录加密码（passwd文件），之后用 token做密码登录webdav(用户名随意)。
> 
> 还有一个疑问 目前WebDAV仅可用于挂载不可用于管理或者是上传吗？

是的。当前各插件的上传功能还未完善。

**Comment by Mit2g** [comment]
> > > 暂不支持。可考虑在根目录加密码（passwd文件），之后用 token做密码登录webdav(用户名随意)。
> > 
> > 
> > 还有一个疑问 目前WebDAV仅可用于挂载不可用于管理或者是上传吗？
> 
> 是的。当前各插件的上传功能还未完善。

感谢回答

**Comment by qian9008** [comment]
用 Windows 添加忘了地址并没有提示让输入 用户名和后台的密码  直接就显示内容
