### ISSUE TITLE
挂载GoogleDrive后显示NotFound

### ISSUE THREAD

**Issue by wssfxtx** [reruin/sharelist#247]
账号没问题，安装应该也没问题，因为挂载OneDrive和天翼云都正常

**Comment by reruin** [comment]
API方式 还是 文件ID方式？

**Comment by wssfxtx** [comment]
API方式，设置设置应该没问题的

**Comment by reruin** [comment]
测试 未发现异常。注意 路径的挂载名称 不要命名为 gd / gda / googledrive 这些。

**Comment by wssfxtx** [comment]
解决了，就是名称的问题，谢谢
