### ISSUE TITLE
天翼云账号密码挂载失败

### ISSUE THREAD

**Issue by nocturnegraden** [reruin/sharelist#248]
[截图1](https://ftp.bmp.ovh/imgs/2020/08/5723f2022efdb042.png)
账号密码输入无误,报错 500Error
[截图2](https://ftp.bmp.ovh/imgs/2020/08/c75b19ca1a1b2d99.png)
求解决方法

**Comment by reruin** [comment]
你本地网络可能有点问题，尝试 ```ping  cloud.189.cn```，或者 访问 ```http://cloud.189.cn```，看看是否正常。

**Comment by cjameslynn** [comment]
确实不能用，每次向导过后只能用几秒钟，后面就又不行了

**Comment by reruin** [comment]
后台管理，将验证码识别接口改成 ```https://api.moeclub.org/SampleCode#Base64=image&Type=Default&$noscheme=1&$output=raw``` 试一试。

**Comment by nocturnegraden** [comment]
> 后台管理，将验证码识别接口改成 `https://api.moeclub.org/SampleCode#Base64=image&Type=Default&$noscheme=1&$output=raw` 试一试。

好的
