### ISSUE TITLE
OD API不能连接

### ISSUE THREAD

**Issue by zjboy1984** [reruin/sharelist#249]
个人账号，后台虚拟路径怎样设置，不论是填写onedrive的文件夹路径，还是/，都不能连接，同时重定向 URI不论是填自己域名还是中转域名，都不行，请问下怎样设置，确认账号没问题，因为我用其他列表程序都正常使用中，谢谢！

**Comment by reruin** [comment]
1. 填写 ```/```，进目录后 自动开启向导，按提示操作即可。
2. 个人账户获取 应用机密 和 应用ID 参考https://github.com/reruin/sharelist/issues/75
3. 另外 挂载路径名 不能设置为 od 、onedrive。

**Comment by zjboy1984** [comment]
我是有用https的

**Comment by Mit2g** [comment]
> 我是有用https的

例如你挂载od的路径为 `abc` 地址栏显示的为`https://domain.com/abc` 则api内填写的地址即为https://domain.com/abc

**Comment by zjboy1984** [comment]
那还要加那个挂载路径名写的“/”吗？

**Comment by zjboy1984** [comment]
出现这个：Request Id: 69f44441-f4c9-4b6b-ac15-1414cb135602
Correlation Id: 6ebc47c2-da74-4489-8a4d-d1bb9a777e28
Timestamp: 2020-08-27T05:19:08Z
Message: AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: '249c9e0c-1826-4512-bc7c-a699e5c32166'.

**Comment by zjboy1984** [comment]
> > 那假如挂载路径名是写了/，那我个人账户获取那里，重定向URL填什么呢？是填中转页面的地址，还是https://domain.com/
> 
> 填写你在挂载向导界面时 地址栏显示的地址
> 若无https 那么请参考作者的回复

挂载向导里地址栏显示的是https://domain.com/uuy，然后我把这个地址填到了微软API的那个重定向URL地址里面，不知道这样对不对？那我在sharelist后台那里，虚拟路径这一项是填/就行，还是/uuy呢？

**Comment by zjboy1984** [comment]
终于可以了
