### ISSUE TITLE
如何初始化

### ISSUE THREAD

**Issue by jixiang-wang** [reruin/sharelist#251]
![image](https://user-images.githubusercontent.com/31286734/90901247-3560f880-e3fd-11ea-8264-1fb5b8ba08e1.png)
这些要怎么填？试了几次都失败了

**Comment by jixiang-wang** [comment]
> 新密码必填，其余替代即可。

新口令是什么？如何获取？

**Comment by reruin** [comment]
> > 新密码必填，其余替代即可。
> 
> 新口令是什么？如何获取？

口令 即 后台登录密码，下次 访问 ```/manage``` 时，用此口令登录。

**Comment by jixiang-wang** [comment]
> > > 新密码必填，其余替代即可。
> > 
> > 
> > 新口令是什么？如何获取？
> 
> 口令 即 后台登录密码，下次 访问 `/manage` 时，用此口令登录。
后台登录密码是登录onedrive账户的密码吗？还是下面证书与密码里的密码？
![image](https://user-images.githubusercontent.com/31286734/91000473-d74e3400-e5fb-11ea-8176-39946ee8e9ce.png)

**Comment by reruin** [comment]
sharelist自带了后台，此处的口令 就是登录sharelist后台用的。并非 onedrive 账户密码 。

**Comment by jixiang-wang** [comment]
> sharelist自带了后台，此处的口令 就是登录sharelist后台用的。并非 onedrive 账户密码 。

就是说这里的口令其实就是设置sharelist的登录密码，对吗？可以设置为任意字符，是吗？有限制长度、字符数字特殊字符这些吗？

**Comment by jixiang-wang** [comment]
![image](https://user-images.githubusercontent.com/31286734/91008319-b3491d80-e610-11ea-8fb2-e1d9c9646ace.png)
上面是我初始化填的，然后加上失败了；
![image](https://user-images.githubusercontent.com/31286734/91008371-d542a000-e610-11ea-8bd2-567036131a87.png)
