### ISSUE TITLE
cloudflare workers启用中转后，下载文件时提示失败-未发现文件

### ISSUE THREAD

**Issue by ctq333** [reruin/sharelist#254]
这个怎么解决？

**Comment by Mit2g** [comment]
由于你的源站没有正确地被在80/443端口映射 导致cf无法正常代理 遂导致的转发失败
经测试Heroku可以正常转发 所以转发没有问题

**Comment by aumk** [comment]
和我问题相同啊
我是在线播放甚至直链引用都没问题，就是Chrome不能下载
Firefox和Safari正常
[问题](https://github.com/reruin/sharelist/issues/263#issue-693632781)
