### ISSUE TITLE
docker和heroku都部署失败了

### ISSUE THREAD

**Issue by jixiang-wang** [reruin/sharelist#257]
![image](https://user-images.githubusercontent.com/31286734/91122278-81958c80-e6cc-11ea-8cb4-149922f49224.png)
重定向那里也已经添加了：https://reruin.github.io/redirect/onedrive.html
所以，这里要如何设置？

**Comment by reruin** [comment]
提示里的 回调URL 是你自己的域名吗，是否已支持 https

**Comment by jixiang-wang** [comment]
> 提示里的 回调URL 是你自己的域名吗，是否已支持 https

回调URL是做什么用的？
如果没有域名要填什么？

**Comment by reruin** [comment]
1. 回调URL 即 重定向URL
2. OneDrive个人版，获取 应用机密 和 应用ID，及如何填写 【重定向URL】，参考 https://github.com/reruin/sharelist/issues/75。
3. heroku 给的地址是 https 的，重定向URL 填写  heroku地址即可。
4. docker部署的，最好是反代出来以方便挂载，当然也可选择以从另一个已挂载的sharelist里复制挂载参数（例如heroku里）。

**Comment by jixiang-wang** [comment]
> 1. 回调URL 即 重定向URL
> 2. OneDrive个人版，获取 应用机密 和 应用ID，及如何填写 【重定向URL】，参考 [https://github.com/reruin/sharelist/issues/75。](https://github.com/reruin/sharelist/issues/75%E3%80%82)
> 3. heroku 给的地址是 https 的，重定向URL 填写  heroku地址即可。
> 4. docker部署的，最好是反代出来以方便挂载，当然也可选择以从另一个已挂载的sharelist里复制挂载参数（例如heroku）。
heroku 的部署成功了，不过加载速度很慢，话说这个没有目录吗？只能一层一层返回？

**Comment by reruin** [comment]
国内访问heroku 是有点慢。
没有给每一级设 链接，你可以浏览器 url 里直接定位到 地址。
