### ISSUE TITLE
阿里云的主机部署后不能访问33001端口   阿里的工单说是没有监听到端口

### ISSUE THREAD

**Issue by Cuiyim** [reruin/sharelist#259]
![image](https://user-images.githubusercontent.com/51844650/91529888-b14acb80-e93c-11ea-950b-c563e97942e5.png)
阿里防火墙跟宝塔都放行了33001的端口
很奇怪
![image](https://user-images.githubusercontent.com/51844650/91529973-d17a8a80-e93c-11ea-800f-80b850a38b39.png)

**Comment by reruin** [comment]
发一下 执行结果的 截图 。

**Comment by Cuiyim** [comment]
![image](https://user-images.githubusercontent.com/51844650/91609627-5780ea80-e9aa-11ea-9e35-6ac2bd79baed.png)

**Comment by Cuiyim** [comment]
换了三台服务器  一台韩国的aws  系统是 ubuntu   一台阿里轻量  系统是 阿里的linux   一台是阿里的2h4g的 系统是contes

**Comment by Cuiyim** [comment]
![image](https://user-images.githubusercontent.com/51844650/91609763-97e06880-e9aa-11ea-979b-3a240e51b2f5.png)
也试过百度，百度上没找到解决的方法。

**Comment by Cuiyim** [comment]
![image](https://user-images.githubusercontent.com/51844650/91609851-bd6d7200-e9aa-11ea-96c0-9204be147ac8.png)
![image](https://user-images.githubusercontent.com/51844650/91609892-d118d880-e9aa-11ea-97de-db7e33a7236c.png)

**Comment by reruin** [comment]
方便将其中某一台机器的 root 账号密码 私发我邮箱，我上去看一眼。

**Comment by Cuiyim** [comment]
可以的


| |
ins888
|
|
ins888@126.com
|
签名由网易邮箱大师定制
在2020年8月31日 21:23，Ting<notifications@github.com> 写道：

方便将其中某一台机器的 root 账号密码 私发我邮箱，我上去看一眼。

**Comment by wssfxtx** [comment]
同样的问题，安装好了以后好像没有启动起来，也不知道怎么手工启动或者查看启动日志

**Comment by reruin** [comment]
> 同样的问题，安装好了以后好像没有启动起来，也不知道怎么手工启动或者查看启动日志

该题主的问题 已解决，是因系统版本过低 导致 nodejs版本无法支持。 
建议检查下 系统，如果你也是 阿里云，请选用 常见的 Linux 发行版。
