### ISSUE TITLE
天翼云能不能加入视频链接防盗链

### ISSUE THREAD

**Issue by star112** [reruin/sharelist#261]
网盘的链接都是明文的，路径一目了然。
视频链接被别人获取了随便调用。搞不了几下就被限速了。128K的龟速

**Comment by star112** [comment]
要是能设置伪静态什么的也可以啊，这样直接暴露目录，文件名太骚了吧

**Comment by Lord2333** [comment]
好兄弟能说一下怎么挂载天翼么，我一直挂载失败

**Comment by reruin** [comment]
> 好兄弟能说一下怎么挂载天翼么，我一直挂载失败

默认的验证码识别接口有问题，后台管理 将其设置为  ```https://api.moeclub.org/SampleCode#Base64=image&Type=Default&$noscheme=1&$output=raw```
