### ISSUE TITLE
关于流量中转GD的疑问

### ISSUE THREAD

**Issue by SKIYET** [reruin/sharelist#265]
尊敬的开发者：

你好，请问流量中转google drive对于vps的硬盘大小是否有容量的要求？

**Comment by reruin** [comment]
没有要求。

**Comment by SKIYET** [comment]
> 没有要求。

请问倘若流量中转的文件大小超过了vps硬盘，是否会出现问题呢？

**Comment by reruin** [comment]
> > 没有要求。
> 
> 请问倘若流量中转的文件大小超过了vps硬盘，是否会出现问题呢？

一般不会。流量直接转发，并非在vps上完全下载完再中转。

**Comment by SKIYET** [comment]
谢谢！
