### ISSUE TITLE
Lack of empathy.

### ISSUE THREAD

**Issue by ps4jpacce** [reruin/sharelist#267]
Only put unimportant and vague things at the beginning

**Comment by ps4jpacce** [comment]
I mean readme.md.Just ask anyone to build your project from scratch, and you'll find a bunch of problem

**Comment by Mit2g** [comment]
> beginning I mean README.md.
> .Just ask anyone to build your project from scratch, and you'll find a bunch of problem

Use the one-key shell and u will get the sharelist.
BTW
