### ISSUE TITLE
使用过程中遇到的两个问题。

### ISSUE THREAD

**Issue by 1424753988** [reruin/sharelist#27]
1.蓝奏云分享链接没有找到形如：`bxxxxxx`部分 。
蓝奏云"个人中心"里面的外链后缀部分是`账户名`。即便是单个文件的分享链接也不是`bxxxxxx`形式
2.进入加密文件夹老是提示：

> 验证失败

，我不太清楚这个密码对是怎么用的？可能是我操作不对。

**Comment by reruin** [comment]
外链的文件夹是 bxxxxx 格式
