### ISSUE TITLE
程序不能开机自启吗？

### ISSUE THREAD

**Issue by 1058972062** [reruin/sharelist#270]
如题   重启vps后发现sharelist没有启动，如果无法开机自启，请问如何手动启动此程序？

**Comment by WASD8102** [comment]
pm2 start app.js

**Comment by 1058972062** [comment]
> pm2启动app.js

成功解决了，感谢

**Comment by sbwml** [comment]
sharelist 是pm2进程守护，开机启动只需要执行

`pm2 startup`

即可
