### ISSUE TITLE
和彩云挂载使用有问

### ISSUE THREAD

**Issue by sbwml** [reruin/sharelist#271]
第一次接触 sharelist，我想挂载和彩云，但是没有测试成功，却又以下几个疑点望解答！！

1、例如官方和彩云登录信息为：账号13888888888  密码888888  需要获取的目录是 123，我是否需要把 123 目录设置为分享状态？

2、按照 sharelist 文档，挂载方式如下
`挂载标示：cy
挂载内容：  
    //用户名/初始文件夹ID?password=密码
    /`

我在后台的 虚拟路径 添加的信息应该如何填写？

3、在不写任何挂载信息为 `/` 的时候，会进入账号密码登录挂载向导，输入账号和密码后，程序返回 500 状态，并打印以下日志
`Error
Looks like something broke!

        
TypeError: Cannot read property 'join' of undefined
    at Manager.create (/opt/sharelist/plugins/drive.caiyun.js:217:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)`

服务器坐标：国内，运营商：河南电联，该网络环境登录和彩云并下载文件均正常
系统环境：全新 Centos 7.8 Minimal
系统安装后执行过的所有指令
cd /opt/
yum install git -y
git clone https://github.com/reruin/sharelist --depth=1
cd sharelist
bash install.sh

bash install.sh 过程没有出现任何错误，直至完成 pm2 进程启动，到 ip:33001 的访问都没有出现任何错误

**Comment by reruin** [comment]
1. 无需设置分享。
2. 由于彩云官方改版，导致目前没法直接获取 文件夹ID。
3. 你用的可能是老版本，最近插件有重新适配，请用 bash update.sh 更新下，然后用```/```挂载试试。

2 的问题在想办法解决。

**Comment by sbwml** [comment]
> 1. 无需设置分享。
> 2. 由于彩云官方改版，导致目前没法直接获取 文件夹ID。
> 3. 你用的可能是老版本，最近插件有重新适配，请用 bash update.sh 更新下，然后用`/`挂载试试。
> 
> 2 的问题在想办法解决。

感谢回复！

我执行了 “3” 操作，更新了程序，并使用 / 挂载。

我依旧遇到了问题

[](https://cdn.cooluc.com/github/1.png)
[](https://cdn.cooluc.com/github/2.png)
[](https://cdn.cooluc.com/github/3.png)

**Comment by reruin** [comment]
有个解析bug，已修复，再更新下。

**Comment by sbwml** [comment]
> 有个解析bug，已修复，再更新下。

是的，现在它工作了

**Comment by Penghaiku** [comment]
https://github.com/reruin/sharelist/issues/271#issuecomment-694246869
## 关于获得**和彩云目录ID** 的问题
和彩云文件下载链接中有几个参数，是否可以提取出目录 ID 呢？
```
https://download4.caiyun.feixin.10086.cn/storageWeb/servlet/pcDownloadFile?code=1B11akoxh0WU01920201124201101f3310017pG1ptfYc&contentID=1B11akoxh0WU01920201124201101f33&dom=D972&oprChannel=10000034&filename=6Yec5bGx6KGMMu+8muWNiuWymy7kuK3oi7HnibnmlYjlrZfluZXniYgubXA0
```
例如：contentID=1B11akoxh0WU01920201124201101f33
将这个目录 ID 按照天翼云盘的方式填写 到 ？前面，不生效
