### ISSUE TITLE
请问怎么样支持家庭云

### ISSUE THREAD

**Issue by GinNide** [reruin/sharelist#274]
家庭云账号密码登陆没有显示索引目录
看issues里面有人提到家庭云插件 
但是这个插件的接口好像失效并且这个接口貌似付费？
问一下开发者有没有其他手段挂载天翼云家庭云

**Comment by reruin** [comment]
sharelist直接支持，选择挂载类型为 【家庭云 账号密码版】。

**Comment by GinNide** [comment]
我试过了显示不出索引目录空白页面

**Comment by reruin** [comment]
清除缓存后，重新挂载试试，账号填写手机号，不要填写```@189.cn```部分，我这边测试ok。
![03](https://user-images.githubusercontent.com/7403780/93841892-982d0480-fcc7-11ea-8256-1abf07d033b8.png)

**Comment by GinNide** [comment]
没用，我在隐私模式下挂载的也显示不出挂载目录

**Comment by 328508474** [comment]
手机天翼网盘app登录后，文件-家庭共享-家庭管理-家庭名称，修改“家庭名称”为英文或数字，不要用中文，名称尽量是短名（最好不要有空格，未测试）；再挂载。
