### ISSUE TITLE
不好意思，我想问个没有营养的问题

### ISSUE THREAD

**Issue by sbwml** [reruin/sharelist#275]
sharelist 能否对获取的目录列表按照文件夹排序的？

比如  a-z  A-Z
中文按拼音 a-z

**Comment by reruin** [comment]
点 顶部的【文件名】，可按 ascii 排序。需要更新下代码。

**Comment by sbwml** [comment]
> 点 顶部的【文件名】，可按 ascii 排序。需要更新下代码。

成功了

**Comment by sbwml** [comment]
为了不新开更多的issues，我这里再问一个问题

当我同时挂载和彩云和天翼云后，忽略路径 功能似乎不工作了

如果我只挂载一个云盘，它是工作的

比如我只挂载一个 和彩云，它文件会变成根目录。我直接填写 “/手机视频” 就可以隐藏 /手机视频 目录。

但是挂载多一个天翼云盘后，它不会隐藏了，我的标识写的是    和彩云  ，我尝试使用 “/手机视频” 和 "/和彩云/手机视频"  均无法隐藏这个目录

**Comment by yushangcl** [comment]
@sbwml  hello  问一下 你是怎么解决 多个挂载，忽略路径不生效的问题

**Comment by sbwml** [comment]
最后没有解决，目前我挂载的时候只挂载指定文件夹，里面不包含不希望展示的目录

**Comment by yushangcl** [comment]
> 最后没有解决，目前我挂载的时候只挂载指定文件夹，里面不包含不希望展示的目录

我出现了一个更神奇的事情，就是 挂载目录无论填写什么 ，都显示 同步盘下面的内容，清除缓存，重新挂载都一样

**Comment by yushangcl** [comment]
> > 最后没有解决，目前我挂载的时候只挂载指定文件夹，里面不包含不希望展示的目录
> 
> 我出现了一个更神奇的事情，就是 挂载目录无论填写什么 ，都显示 同步盘下面的内容，清除缓存，重新挂载都一样

临时找了一个解决方案 

修改 drive.189cloud.js，第400 行 后面增加一个判断，过滤掉想要过滤的数据，需要清除缓存 重新启动
``
 if( item.type === 'folder' ){
          // item.name === '同步盘' || item.name === '我的图片' || item.name === '我的音乐' || item.name === '我的视频' || item.name === '我的文档' || item.name === '我的应用'
          if (item.name === '同步盘'){
            continue
          }
        }
```
