### ISSUE TITLE
视频在线播放，多次拖动进度条的话会消耗服务器的大量下载流量

### ISSUE THREAD

**Issue by aria001** [reruin/sharelist#276]
这是我服务器的流量图，可以肯定的是，9月20一天我只播放了一部7g的视频并且多次点击和拖动进度条，并且没有其他人访问
![image](https://user-images.githubusercontent.com/17241830/93706630-a7db0a80-fb5a-11ea-91f3-b22ded62861a.png)
只挂载了gd团队盘，其他网盘并没有测试

**Comment by Mit2g** [comment]
因使用的是gd 其流量可能通过你的服务器进行中转 而或使用了你服务器上的代理工具进行访问 可以尝试挂载天翼云 OneDrive等进行测试

**Comment by aria001** [comment]
> 因使用的是gd 其流量通过你的服务器进行中转 相关[#223 (comment)](https://github.com/reruin/sharelist/issues/223#issuecomment-653881229)
> 可以尝试挂载天翼云 OneDrive等进行测试 此类服务并未消耗本机流量

会通过服务器中转这个我是知道的，主要是7g的文件会跑出200多g的流量，这一点我感到很疑惑。而且多次拖动进度条似乎会使服务器cpu和io等跑到非常高以致docker容器直接停止运行。

**Comment by Mit2g** [comment]
> > 因使用的是gd 其流量通过你的服务器进行中转 相关[#223 (comment)](https://github.com/reruin/sharelist/issues/223#issuecomment-653881229)
> > 可以尝试挂载天翼云 OneDrive等进行测试 此类服务并未消耗本机流量
> 
> 会通过服务器中转这个我是知道的，主要是7g的文件会跑出200多g的流量，这一点我感到很疑惑。而且多次拖动进度条似乎会使服务器cpu和io等跑到非常高以致docker容器直接停止运行。

流量问题还需要再观察
U的占用主要是视频的解码在服务器上完成 属于正常情况 IO可能是缓存
