### ISSUE TITLE
cf中转问题

### ISSUE THREAD

**Issue by w1915591935** [reruin/sharelist#277]
我使用的是宝塔面板，通过反带的方式运行。但看作者中转方法，修改运行端口80|443，结果无法加速。请问作者如何开启cf加速

**Comment by reruin** [comment]
1. 将sharelist做域名解析，并运行在 80 或 443端口（建议反代出来）。
2. 在 cf 里配置 HOST 为上述地址。
3. sharelist后台, 常规配置->中转服务器处 配置 cf worker地址。

**Comment by w1915591935** [comment]
是的，我已修改运行端口，可是无法访问从33001修改为80
环境为宝塔面板。

**Comment by Mit2g** [comment]
> 是的，我已修改运行端口，可是无法访问从33001修改为80
> 环境为宝塔面板。

修改 app.js 内的运行端口
建议使用nginx 仅需在宝塔的nginx中添加
```
location / {
   proxy_pass http://127.0.0.1:33001;
}
```

**Comment by reruin** [comment]
> 是的，我已修改运行端口，可是无法访问从33001修改为80
> 环境为宝塔面板。

不要将sharelist的启动端口修成80，这样大概率会与已有的nginx/apache冲突。
最好是用 @Mit2g 所述的方式 反代一下

**Comment by w1915591935** [comment]
了解啦

**Comment by w1915591935** [comment]
[https://cdn.jsdelivr.net/gh/w1915591935/yimuapp.cn@latest/20200927113153(1).png](url) 看看这应该是运行端口（小白不懂大牛勿喷）

**Comment by reruin** [comment]
是的。默认从 cache/config.json 读取已配置的端口，若没有 则取 80。

**Comment by w1915591935** [comment]
好的
