### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by ASTWY** [reruin/sharelist#278]
docker部署，无论是用ip访问，还是域名访问，都无法登陆天翼云挂载，返回的错误代码为500，即使在后台按照参数填写，也会报挂载失败，密码改过，手机号换过，服务器也换过，均无法解决，特来求助

**Comment by ASTWY** [comment]
附上错误信息

```
Error: getaddrinfo EAI_AGAIN cloud.189.cn:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
```

**Comment by reruin** [comment]
提示 cloud.189.cn 解析失败。docker 部署在境内 还是国外？

**Comment by ASTWY** [comment]
已经解决了，docker部署在国内阿里云不行，后来换了手动安装就好了
