### ISSUE TITLE
请问如何适配世纪互联的Sharepoint

### ISSUE THREAD

**Issue by am-abudu** [reruin/sharelist#279]
很多世纪互联无法创建应用，只能使用Site-id对接sharepoint，使用Onemanager就可以实现，请问是否有适配世纪互联sharepoint的打算

**Comment by reruin** [comment]
能否提供下你的Sharepoint网站的空间地址。

**Comment by qian9008** [comment]
https://s-i-i-t.sharepoint.cn/sites/12

**Comment by reruin** [comment]
已适配。
