### ISSUE TITLE
跪求大佬更新下和彩云

### ISSUE THREAD

**Issue by myitcloud** [reruin/sharelist#280]
和彩云挂载后只能显示根目录
麻烦大佬更新下子目录的挂载啊

**Comment by ASTWY** [comment]
填目录名是没用的，需要的是目录ID，和彩云的目录ID获取需要抓包

**Comment by myitcloud** [comment]
> 填目录名是没用的，需要的是目录ID，和彩云的目录ID获取需要抓包

大佬求教怎么抓

**Comment by reruin** [comment]
等更新下插件，或者 参考以下方法自行获取。

1. 进入和彩云官网，浏览到要挂载的目录。
2. 按F12打开chrome 控制台，点击 Network 选项卡。
3. 刷新当前页面。查看 Network下 Name 为 【getDisk】的请求。此请求的Headers ->  Request Payload 里 catalogID 字段即是目录ID。
![截屏2020-09-30 下午7 17 51](https://user-images.githubusercontent.com/7403780/94678902-d1ade180-0351-11eb-9413-6fecf4157ddd.png)

**Comment by reruin** [comment]
> 和彩云挂载后只能显示根目录
> 麻烦大佬更新下子目录的挂载啊

插件已更新，在挂载向导处 填写挂载目录，例如： ```/abc/def```。

**Comment by myitcloud** [comment]
> 等更新下插件，或者参考以下方法自行获取。
> 
> 1. 进入和彩云官网，浏览到要挂载的目录。
> 2. 按F12打开chrome控制台，点击Network选项卡。
> 3. 刷新当前页面。查看网络下名称为【getDisk】的请求。此请求的标头->请求有效载荷里catalogID指向即是目录ID。
>    ![截屏2020-09-30下午7 17 51](https://user-images.githubusercontent.com/7403780/94678902-d1ade180-0351-11eb-9413-6fecf4157ddd.png)

感谢大佬

**Comment by myitcloud** [comment]
> > 和彩云挂载后只能显示根目录
> > 麻烦大佬更新下子目录的挂载啊
> 
> 插件已更新，在挂载向导处填写挂载目录，例如：`/abc/def`。


感谢大佬
