### ISSUE TITLE
关于天翼云和和彩云挂载后下载问题

### ISSUE THREAD

**Issue by ASTWY** [reruin/sharelist#281]
挂载是没问题的，能预览，不能直接下载，返回的链接不是真实的下载链接，IDM下载时需要提示需要账户及密码。
能不能用本人的cookie获取真正的下载链接？

**Comment by ASTWY** [comment]
发现了问题所在，下载器并不会跳转，下载器认为这就是真实地址，用浏览器的"链接另存为"就没问题。
### 更新建议

1. 在文件项上加上右键菜单

- 预览
- 下载（返回真实链接）

2. 左键点击判断文件类型，能预览就预览，不能预览就跳转真实链接下载

**Comment by reruin** [comment]
确认下下载的地址是形如 ```caiyun.feixin.10086.cn```这样的地址，还是以你站点为链接的地址。

默认获取的就是真实地址，除非后台开启了中转。
