### ISSUE TITLE
能否支持多个中转服务器

### ISSUE THREAD

**Issue by benzBrake** [reruin/sharelist#291]
CF Workers 免费版本请求次数不太够用，可不可以增加支持同时使用多个中专服务器的功能。

**Comment by reruin** [comment]
已支持。
支持配置每个中转服务器的轮换权重。例如：   
```https://upstream.com/|1;https://upstream2.com/|2```   
上述表达式表示配置```upstream```和```upstream2```两台中转服务器，并按1:2分配请求。
