### ISSUE TITLE
onedrive重定向URL描述错误

### ISSUE THREAD

**Issue by gtgc2005** [reruin/sharelist#292]
重定向已经改为https://reruin.github.io/redirect/onedrive.html  但挂载向导依然是https://reruin.github.io/sharelist/redirect.html

**Comment by qian9008** [comment]
还是你的链接管用。

**Comment by reruin** [comment]
此问题已修复。当前两者都可以，建议 ```https://reruin.github.io/sharelist/redirect.html```
