### ISSUE TITLE
在Debian10上安装完成无法访问33001

### ISSUE THREAD

**Issue by SKIYET** [reruin/sharelist#293]
![r1](https://user-images.githubusercontent.com/49865295/96683958-6e8df880-13ad-11eb-88f2-848ae7723bc9.PNG)
![r2](https://user-images.githubusercontent.com/49865295/96684010-7ea5d800-13ad-11eb-853e-7e2933f17f0e.PNG)
能否请作者帮我查看下？

**Comment by emengweb** [comment]
防火墙端口开放了么？查看下pm2 list 列表有没有sharelist的服务，是不是正常启动？

**Comment by SKIYET** [comment]
> 防火墙端口开放了么？查看下pm2 list 列表有没有sharelist的服务，是不是正常启动？

已解决，在debian最小化安装时，脚本没有安装npm，需要执行apt install npm
