### ISSUE TITLE
是否有小伙伴尝试过用linux的davfs2挂载过webdav

### ISSUE THREAD

**Issue by fantasyjqc** [reruin/sharelist#296]
是否有小伙伴尝试过用linux的davfs2挂载过webdav，我这边是用docker部署的，然后想用davfs2挂载到本地。

mount -t davfs http://127.0.0.1:33001/webdav/ /srv/webdav

挂载可以成功，但是里面是空的，只有一个这个
![image](https://user-images.githubusercontent.com/4988150/96850856-e7628280-1489-11eb-98d1-d4d4477d2859.png)

有没有其他小伙伴成功的？

**Comment by phnxwang** [comment]
同样的问题，
但好像在windows里能挂的上， 也有内容， 看来是和DAVFS2不兼容？

**Comment by reruin** [comment]
兼容问题，等待修复。
