### ISSUE TITLE
世纪互联挂不上还请问有没有详细教程

### ISSUE THREAD

**Issue by yanqing365** [reruin/sharelist#300]

**Comment by reruin** [comment]
请截图说明你遇到的问题。

**Comment by qian9008** [comment]
登录
抱歉，登录时遇到问题。

AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'c45345345453c96c'.

**Comment by reruin** [comment]
用新版Onedrive V2 插件挂载试试，目前我没有世纪互联账号做测试（原先的翻车了。。。）。

**Comment by zwsn** [comment]
我也遇到同样问题，如果需要我可以提供账号

**Comment by zwsn** [comment]
OD世纪互联和one drive V2都试了

**Comment by reruin** [comment]
> OD世纪互联和one drive V2都试了

用的是自己的 app id 和 app secret 挂载吗？

**Comment by zwsn** [comment]
是的

**Comment by reruin** [comment]
> 是的

更新代码后再试下，请按照要求设置下 回调链接。

**Comment by zwsn** [comment]
> > 是的
> 
> 更新代码后再试下，请按照要求设置下补充链接。

谢谢，已经解决
