### ISSUE TITLE
和彩云webdav导出，部分文件缺失

### ISSUE THREAD

**Issue by Way445** [reruin/sharelist#304]
**和彩云webdav的导出文件显示不全**
webdav导出文件会少一两个
比如这样
![Screenshot_20201108-213901](https://user-images.githubusercontent.com/64531014/98468035-a1d8e000-2213-11eb-8824-9c77654b47de.png)
![Screenshot_20201108-213852](https://user-images.githubusercontent.com/64531014/98468110-e95f6c00-2213-11eb-9da8-728c95a1bbc6.png)

webdav明显少了b.歌单文件夹
①更换文件管理器后依然如此，小文件也会出现这种情况，无法显示文件夹在官方web打开明显偏慢。  
②与文件夹大小无关  
③sharelist浏览器打开正常
④Webdav输入路径访问正常打开

**Comment by reruin** [comment]
你使用的是哪个 webdav 客户端？

**Comment by Way445** [comment]
mixplorer

**Comment by Way445** [comment]
> 你使用的是哪个 webdav 客户端？

用的是mixplorer

**Comment by reruin** [comment]
老bug了，已修复。

**Comment by Way445** [comment]
> 老bug了，已修复。

**已解决/感谢**

**Comment by Way445** [comment]
> 老bug了，已修复。

webdav最多只能显示两百个文件是客户端限制吗
