### ISSUE TITLE
如何挂载本地磁盘

### ISSUE THREAD

**Issue by sady2014** [reruin/sharelist#306]
利用docker部署的。
有一块1T 硬盘，挂载在 `/data1`，添加本地路径下时候`/data1/`结果提示不存在该路径

**Comment by reruin** [comment]
docker 要映射磁盘.
```docker run -d -v /etc/sharelist:/sharelist/cache -v /data1:/data1 -p 33001:33001 --name="sharelist" reruin/sharelist```

**Comment by sady2014** [comment]
> docker 要映射磁盘.
> `docker run -d -v /etc/sharelist:/sharelist/cache -v /data1:/data1 -p 33001:33001 --name="sharelist" reruin/sharelist`

多谢，了解了下docker ，已经解决了
