### ISSUE TITLE
README注释失败

### ISSUE THREAD

**Issue by Way445** [reruin/sharelist#307]
![IMG_20201111_190338](https://user-images.githubusercontent.com/64531014/98806751-a2ac8480-2454-11eb-8689-5e6cd06c816c.jpg)
![IMG_20201111_193208](https://user-images.githubusercontent.com/64531014/98806757-a4764800-2454-11eb-8bed-33cb0fc15f9b.jpg)

**已在README注释掉了图片，依然显示。**

**Comment by reruin** [comment]
已修复。
