### ISSUE TITLE
您好！請問可以支援Teambition嗎？

### ISSUE THREAD

**Issue by cooluc** [reruin/sharelist#308]
Teambition 目前已經已經逐漸對内測用戶發放激活序列號。請問sharelist程式後面會考慮對 Teambition 網絡硬盤的支援嗎？

Teambition 測試下，中國大陸以及國際地區（測試西班牙、德國、印度尼西亞）速度均可達到30兆字節以上，Teambition 的全球CDN非常快速。如果對其做支援將會是一個非常好的事情！

感謝偉大的開源項目！

**Comment by Cuiyim** [comment]
已经获得了Teambition的内测账号，同咨询Teambition的支持意向
感谢伟大的开源项目！

**Comment by reruin** [comment]
我没有teambition账号... 😂

**Comment by Cuiyim** [comment]
我的发给你，方便加微信或者qq吗。我可以拉你进teambition官方内测群
| |
ins888
|
|
ins888@126.com
|
签名由网易邮箱大师定制
在2020年11月17日 20:00，Ting<notifications@github.com> 写道：

我没有teambition账号... 😂

**Comment by star112** [comment]
> 我没有teambition账号... 😂

希望可以支持阿里云盘，可以提供账号

**Comment by Mit2g** [comment]
reruin.github.io/sharelist/docs/#/zh-cn/plugins/teambition

**Comment by reruin** [comment]
已适配中国版Teambition。
