### ISSUE TITLE
反代出现问题，CSS和文件报404错误

### ISSUE THREAD

**Issue by emmmm333** [reruin/sharelist#309]
反代出现问题，CSS和文件报404错误

**Comment by sbwml** [comment]
**location /** {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Range $http_range;
      proxy_set_header If-Range $http_if_range;
      proxy_no_cache $http_range $http_if_range;
      proxy_pass http://127.0.0.1:33001/;
}

**Comment by sbwml** [comment]
如果 location / 目录不是根目录，自行看浏览器的调试 404 的路径，再单独做路径的反代理规则，如果是直接反代跟目录直接使用我上面贴的规则即可

**Comment by emmmm333** [comment]
用二级域名后正常，出问题的是用三级域名的情况下

**Comment by reruin** [comment]
参考下 #317 的解决方法。
