### ISSUE TITLE
webdav 如何使用？

### ISSUE THREAD

**Issue by ferocknew** [reruin/sharelist#31]
例如： https://url ... /webdav/
并不支持webdav

**Comment by ferocknew** [comment]
按照说明，url ... /WebDAV 提示 Not Found

**Comment by reruin** [comment]
最近在调整webdav目录。你可拉取最新代码再试一下。

**Comment by ferocknew** [comment]
已拉取，最新，依旧如此

**Comment by reruin** [comment]
sharelist演示地址  https://sharelist.reruin.net/webdav

**Comment by ferocknew** [comment]
在 mac os，使用 finder 链接此 webdav，提示：

![image](https://user-images.githubusercontent.com/2178683/52995611-183d1980-3456-11e9-819d-aee336996167.png)

选择 “客人” 以后，提示：

![image](https://user-images.githubusercontent.com/2178683/52995631-2723cc00-3456-11e9-99b7-c5f221b9e4d1.png)

**Comment by reruin** [comment]
webdav 的兼容性问题正在处理，近期内解决。

**Comment by reruin** [comment]
已完成。[@030c74](https://github.com/reruin/sharelist/tree/030c74d895069381d60ab2dbd6b2992e49519b4b)

**Comment by ferocknew** [comment]
通过 linux 访问 webdav ，app logs 提示：

```
Error: options.uri is a required argument
0|app  |       at Request.init (/www/wwwroot/default/sharelist/node_modules/request/request.js:234:31)
0|app  |       at new Request (/www/wwwroot/default/sharelist/node_modules/request/request.js:130:8)
0|app  |       at request (/www/wwwroot/default/sharelist/node_modules/request/index.js:54:10)
0|app  |       at http (/www/wwwroot/default/sharelist/app/utils/http.js:27:10)
0|app  |       at sendHTTPFile (/www/wwwroot/default/sharelist/app/utils/sendfile.js:84:27)
0|app  |       at WebDAV.http_get (/www/wwwroot/default/sharelist/app/controllers/webdav.js:346:13)
0|app  |       at <anonymous>

```

链接失败，macos finder 现在已可以链接了。

**Comment by emengweb** [comment]
mac finder依然报错，无法连接。。。

**Comment by reruin** [comment]
近期对webdav做了调整。
1. sharelist会通过客户端useragent判断来源是否为webdav client，但强烈推荐设置webdav路径以提高识别率。
2. 此功能支持列目录和下载。
3. 匿名用户访问加密目录，需输入后台管理密码（用户名随意），而非目录密码。

**Comment by lsyyktv** [comment]
> 近期对webdav做了调整。
> 
> 1. sharelist会通过客户端useragent判断来源是否为webdav client，但强烈推荐设置webdav路径以提高识别率。
> 2. 此功能支持列目录和下载。
> 3. 匿名用户访问加密目录，需输入后台管理密码（用户名随意），而非目录密码。

拉的最新代码   还是提示not found

**Comment by hopeknow** [comment]
请问sharelist安装成功了，但就是webdav显示Not Found，该怎么办？
