### ISSUE TITLE
如何实现仅加密列表？

### ISSUE THREAD

**Issue by benzBrake** [reruin/sharelist#311]
就是有个目录我想输入密码才能看到列表，获取到的文件链接不需要授权就能下载。

需求就是：加密以后无法直接添加到NAS下载

**Comment by Mit2g** [comment]
复议 但我认为下载时添加密码参数来请求 会是一个更好的方案 兼顾了加密与加密后的下载
类似于 nginx的 ```auth_basic```模块的方式 在使用wget请求时 附带密码参数
```wget --http-user=admin --http-passwd=123 https://github.com/reruin/sharelist/download/123.txt```

**Comment by reruin** [comment]
严格意义上 目录加密 是需要保证 子目录及文件的加密性的。可考虑将【目录索引】设置为 禁用 来实现你的需求（管理员始终可见）。
@Mit2g  sharelist 是支持 ?token=xxxx 的形式来获得管理权限（cf 中转即使用了此方法）。

**Comment by Mit2g** [comment]
> 严格意义上 目录加密 是需要保证 子目录及文件的加密性的。可考虑将【目录索引】设置为 禁用 来实现你的需求（管理员始终可见）。
> @Mit2g sharelist 是支持 ?token=xxxx 的形式来获得管理权限（cf 中转即使用了此方法）。

确实可行 只是分享时这样做似乎会泄露后台密码😂
@benzBrake 在nas下载时 将你的链接后加入 ```token=***```即可直接下载 ***为你的后台管理密码
即为 ```https://github.com/reruin/sharelist/download/123.txt?token=***```

**Comment by benzBrake** [comment]
> 
> 
> > 严格意义上 目录加密 是需要保证 子目录及文件的加密性的。可考虑将【目录索引】设置为 禁用 来实现你的需求（管理员始终可见）。
> > @Mit2g sharelist 是支持 ?token=xxxx 的形式来获得管理权限（cf 中转即使用了此方法）。
> 
> 确实可行 只是分享时这样做似乎会泄露后台密码😂
> @benzBrake 在nas下载时 将你的链接后加入 `token=***`即可直接下载 ***为你的后台管理密码
> 即为 `https://github.com/reruin/sharelist/download/123.txt?token=***`

解决办法可以是使用token来解决密码泄露啊，只是我不会nodejs。
不过我是朋友间分享，密码他们也知道的

**Comment by reruin** [comment]
> > 严格意义上 目录加密 是需要保证 子目录及文件的加密性的。可考虑将【目录索引】设置为 禁用 来实现你的需求（管理员始终可见）。
> > @Mit2g sharelist 是支持 ?token=xxxx 的形式来获得管理权限（cf 中转即使用了此方法）。
> 
> 确实可行 只是分享时这样做似乎会泄露后台密码😂
> @benzBrake 在nas下载时 将你的链接后加入 `token=***`即可直接下载 ***为你的后台管理密码
> 即为 `https://github.com/reruin/sharelist/download/123.txt?token=***`

是的。sharelist 是作为个人向的挂载工具，在分享这块没有设计太多。
