### ISSUE TITLE
楼主，求问下使用nat中转到问题

### ISSUE THREAD

**Issue by GillianJiao** [reruin/sharelist#313]
我是用vps搭建的程序，域名已经反代了可以直接用域名访问了，使用的是宝塔，
vps的网络速度不行，现在想用nat中转OneDrive的下载，求教一下大佬，改怎么设置

**Comment by reruin** [comment]
暂只支持 本机中转 和 cloudflare 中转，不支持指定机器。 后续会考虑开发sharelist-proxy组件 适用于任意机器中转。

**Comment by GillianJiao** [comment]
等大佬的更新

**Comment by Mit2g** [comment]
暂时解决方法 可以考虑
Nat上使用端口转发 转发到vps 端口80/443 使用```nat的ip:端口``` 理论上应该可以正常访问sharelist了 此时的下载应该已经完成了转发
建议在vps上开启本机中转 此时流量是 od -  vps - nat - 本机理论可行 如果没有开启本机中转 可能会无法转发流量

***以上仅理论 由于手里没有nat无法测试***

**Comment by GillianJiao** [comment]
> 臨時解決方法可以考慮
> 使用Nat上級使用端口轉發到vps範圍80/443使用`nat的ip:端口`理論上應該可以正常訪問共享列表了此時的下載應該已經完成了轉發
> 建議在vps上開啟本機中轉此時流量是od-vps -nat-本機理論可行如果沒有開啟本機中轉可能會無法轉發流量
> 
> _**以上僅理論由於試圖沒有nat無法測試**_

如果大佬愿意搞搞  我可以提供给大佬玩玩，给个tg联系方式

**Comment by reruin** [comment]
> 等大佬的更新

已支持 sharelist-proxy，[参考文档](https://reruin.github.io/sharelist/docs/#/zh-cn/advance?id=sharelist-proxy%e4%b8%ad%e8%bd%ac)。
