### ISSUE TITLE
无扩展名文件缺失！

### ISSUE THREAD

**Issue by d4renk** [reruin/sharelist#314]

**Comment by Way445** [comment]
![Screenshot_20201128-130629](https://user-images.githubusercontent.com/64531014/100494210-945fa780-317a-11eb-8935-ea8d1e0f63ca.png)

![Screenshot_20201128-125853](https://user-images.githubusercontent.com/64531014/100494154-e6ec9400-3179-11eb-8d2b-2e12b8e745b3.png)
**在sharelist里仅显示了一个.encfs6.xml**  
**文件是由encf加密生成，sharelist无法下载**

**Comment by reruin** [comment]
测试了 未复现。将sharelist更新到 最新版后再试试。 
![image](https://user-images.githubusercontent.com/7403780/100587443-8604bd80-332b-11eb-912e-b2e449f1a4da.png)

**Comment by Way445** [comment]
> 测试了 未复现。将sharelist更新到 最新版后再试试。
> ![image](https://user-images.githubusercontent.com/7403780/100587443-8604bd80-332b-11eb-912e-b2e449f1a4da.png)

**是最新版，刚刚试了od，od没问题，和彩云不全**

**Comment by reruin** [comment]
可能与 和彩云 的文件设置有点关系，方便给一下和彩云的 挂载路径吗?

**Comment by Way445** [comment]
> 可能与 和彩云 的文件设置有点关系，方便给一下和彩云的 挂载路径吗?

**/0g11YUlzL0bo03020200323134646t01/h.%E4%BB%A3%E5%AD%98/newdown.encfs
是指文件路径嘛，挂载的文件夹id是0g11YUlzL0bo03020200323134646t01**

**Comment by d4renk** [comment]
> 可能与 和彩云 的文件设置有点关系，方便给一下和彩云的 挂载路径吗?

**需要域名来调试吗**

**Comment by reruin** [comment]
> > 可能与 和彩云 的文件设置有点关系，方便给一下和彩云的 挂载路径吗?
> 
> **需要域名来调试吗**

方便的话，把地址、登录密码发下我邮箱。

**Comment by d4renk** [comment]
> > > 可能与 和彩云 的文件设置有点关系，方便给一下和彩云的 挂载路径吗?
> > 
> > 
> > **需要域名来调试吗**
> 
> 方便的话，把地址、登录密码发下我邮箱。

链接: https://caiyun.139.com/m/i?0g5CfnfKoHH51  提取码:xcJs  和彩云云盘保存了个人信息，保存此文件无法显示

**Comment by d4renk** [comment]
> > > 可能与 和彩云 的文件设置有点关系，方便给一下和彩云的 挂载路径吗?
> > 
> > 
> > **需要域名来调试吗**
> 
> 方便的话，把地址、登录密码发下我邮箱。

**拿heroku新部署了一个一样**

**Comment by reruin** [comment]
链接: https://caiyun.139.com/m/i?0g5CfnfKoHH51 中只有两个文件。

![截屏2020-12-13 下午10.50.42.png](https://i.loli.net/2020/12/13/ZWzmvTjQGUOub4Y.png)
![截屏2020-12-13 下午10.46.34.png](https://i.loli.net/2020/12/13/l9dNHTFBe2VxzmS.png)

**Comment by d4renk** [comment]
> > > 可能与 和彩云 的文件设置有点关系，方便给一下和彩云的 挂载路径吗?
> > 
> > 
> > **需要域名来调试吗**
> 
> 方便的话，把地址、登录密码发下我邮箱。

已发送

**Comment by d4renk** [comment]
> 链接: https://caiyun.139.com/m/i?0g5CfnfKoHH51 中只有两个文件。
> 
> ![截屏2020-12-13 下午10.50.42.png](https://camo.githubusercontent.com/67677e2b9e0be32a6905fcb7edee3a1ac387931d3fe249a55b2dcc3c5fe73c9d/68747470733a2f2f692e6c6f6c692e6e65742f323032302f31322f31332f5a577a6d76546a5147554f756234592e706e67)
> ![截屏2020-12-13 下午10.46.34.png](https://camo.githubusercontent.com/c2a6db6de01a37e190ee9b77017e1824969de10e849849d5115f83efa1033708/68747470733a2f2f692e6c6f6c692e6e65742f323032302f31322f31332f6c39644e48544642653256787a6d532e706e67)

webdav下不显示文件

**Comment by d4renk** [comment]
webdav下然无法显示
