### ISSUE TITLE
请问SBM服务应该如何使用

### ISSUE THREAD

**Issue by WASD8102** [reruin/sharelist#316]

**Comment by reruin** [comment]
***SMB暂时只能工作在1.0的协议下，它可能不支持KODI。***
1. 如何使用：设置共享路径设置为 SL，默认端口为8445，使用 guest 匿名登录。
2. KODI下可使用webdav代替，sharelist已支持服务申明，依次进入 文件管理->添加源->zeroconf浏览器，选择 ShareList WebDAV 即可。

**Comment by WASD8102** [comment]
谢谢
