### ISSUE TITLE
Nginx不能反代端口

### ISSUE THREAD

**Issue by foolcs** [reruin/sharelist#317]
我想通过自定义路径的方式访问，结果访问是有问题的，我看目录跳转好像是通过直接修改url的方式，把我前面的自定义路径部分也修改了

**Comment by reruin** [comment]
能具体提供下演示么。

**Comment by foolcs** [comment]
就是原本访问是ip:33001，我想通过nginx改为 ip/file/ 代理33001端口，但是我进入主目录跳转的时候，会发生错误，如：
原本是ip:33001/dir/a，更改后预期是 ip/file/dir/a，实际结果是ip/dir/a，找不到路径报错了

**Comment by Mit2g** [comment]
> 就是原本访问是ip:33001，我想通过nginx改为 ip/file/ 代理33001端口，但是我进入主目录跳转的时候，会发生错误，如：
> 原本是ip:33001/dir/a，更改后预期是 ip/file/dir/a，实际结果是ip/dir/a，找不到路径报错了

你需要进行rewrite 覆写请求路径为实际路径
可以参考 https://www.cnblogs.com/woshimrf/p/nginx-proxy-rewrite-url.html 提到的rewrite写法

**Comment by reruin** [comment]
> 就是原本访问是ip:33001，我想通过nginx改为 ip/file/ 代理33001端口，但是我进入主目录跳转的时候，会发生错误，如：
> 原本是ip:33001/dir/a，更改后预期是 ip/file/dir/a，实际结果是ip/dir/a，找不到路径报错了

nginx 为例，加上这些
```
  sub_filter 'href="//' 'href="https://';
  sub_filter 'href="/' 'href="/file/';
  sub_filter 'src="/' src="/file/';
  sub_filter_once off;
```
