### ISSUE TITLE
蓝奏云无法挂载

### ISSUE THREAD

**Issue by benzBrake** [reruin/sharelist#318]
看了一下日志无法连接服务器
```
 Error: connect ETIMEDOUT 117.21.225.196:443
```
是因为服务器在香港的原因？

**Comment by benzBrake** [comment]
尝试把域名从www.lanzous.com修改为pc.woozooo.com解决问题

**Comment by reruin** [comment]
暂时没收到此类报告，后续我会再跟踪下。

**Comment by benzBrake** [comment]
> 
> 
> 暂时没收到此类报告，后续我会再跟踪下。

今天我又遇到了，是在我香港的vps上发生的，pc.woozooo.com用不了了，换回lanzous.com又可以用了，对比国内的一直没出现问题。

**Comment by reruin** [comment]
lanzou 在海外可能动态dns，这个目前没什么解决方法。
