### ISSUE TITLE
關於Teambition 細節有小建議

### ISSUE THREAD

**Issue by cooluc** [reruin/sharelist#320]
感謝項目對Teambition的支援，已經成功使用中國服務器賬戶挂載Teambition網絡文件。

但是目前在使用過程中有兩個小建議，希望可以加以完善。

1、目錄列表不被緩存，每一次對目錄做點擊事件它都會在Teambition上獲取。這對訪問速度有非常大的障礙。（ps：目前個人臨時解決方案是通過反代理sharelist端口，在nginx 上產生緩存。但這僅僅是曲綫救國，希望程序本身上開啓Teambition的目錄緩存）

2、文件最後修改時間建議簡化處理。當前格式是：2020-12-11T22:39:49+08:00
如果簡化為：2020-12-11 22:39:49 會更加直觀。

以上兩點均屬於個人小建議，希望采納！

sharelist是一個非常好的項目，感謝偉大的開源項目！

**Comment by reruin** [comment]
1. 缓存bug 已修复。
2. 期望显示为***用户所在时区***，开发时遇到些问题，后期再处理。

**Comment by cooluc** [comment]
> 1. 缓存bug已修复。
> 2. 期望显示为_**用户所在时区**_，开发时遇到一些问题，后续再处理。

非常感謝所作的一切！
