### ISSUE TITLE
如何挂载国际版Sharepoint?

### ISSUE THREAD

**Issue by justhy** [reruin/sharelist#323]
如题，请问是否支持挂载国际版Sharepoint？如果支持该如何挂载？

**Comment by reruin** [comment]
选择 OneDrive V2 方式挂载，并在挂载向导页面 选择**分享链接挂载**类型。
参考 https://reruin.github.io/sharelist/docs/#/zh-cn/plugins/onedrive

**Comment by justhy** [comment]
> 选择 OneDrive V2 方式挂载，并在挂载向导页面 选择**分享链接挂载**类型。
> 参考 https://reruin.github.io/sharelist/docs/#/zh-cn/plugins/onedrive

测试了，不行。是否要求sharepoint是公开的？
