### ISSUE TITLE
无扩展名文件在挂载webdav后不显示

### ISSUE THREAD

**Issue by 328508474** [reruin/sharelist#324]
最新更新修复无扩展名文件不显示的问题，在用浏览器打开本机33001网站可以看见并可以下载。用webdav客户端登录后还是无显示。我挂载的是天翼网盘个人版，本机webdav客户端为rclone。

**Comment by reruin** [comment]
已修复了。

**Comment by 328508474** [comment]
> 已修复了。

我昨天下载最新版，全新安装的，就有这问题，今天也没看见再更新，我这里是有这问题的。

**Comment by reruin** [comment]
没有提交，现在再试试。

**Comment by 328508474** [comment]
> 没有提交，现在再试试。

更新后正常了，感谢修复
