### ISSUE TITLE
并将重定向URI设置为 https://reruin.github.io/sharelist/redirect.html

### ISSUE THREAD

**Issue by qian9008** [reruin/sharelist#327]
在哪里设置呢？？？

**Comment by qian9008** [comment]
这个是在新建应用里填写，我会了 ，但是还是挂载失败

**Comment by Mit2g** [comment]
> 这个是在新建应用里填写，我会了 ，但是还是挂载失败

如果搭建的服务没有使用域名或没有使用ssl 请填写该地址 具体参考置顶issue关于OneDrive挂载的内容
