### ISSUE TITLE
世纪互联怎么挂载

### ISSUE THREAD

**Issue by qian9008** [reruin/sharelist#328]
用其他目录程序成功挂载了，用了相同的id 在这里添加就是一直出错

**Comment by Mit2g** [comment]
提出issue前建议自行搜索是否有人之前提过相关问题 相信这些内容足以回答你的问题 https://github.com/reruin/sharelist/issues?q=%E4%B8%96%E7%BA%AA%E4%BA%92%E8%81%94
如果无法解决 请具体描述问题或者遇到的报错等信息

**Comment by qian9008** [comment]
用了 v2 api  按流程填写了3项（这个没填错）。
登录
抱歉，登录时遇到问题。

AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'cxxxxxxx-703b-473733bc1fc96c'.

**Comment by qian9008** [comment]
中转地址 按页面提示填写了 ，现在是用ip访问的

**Comment by qian9008** [comment]
定向URL 改为这个就正常了  ，页面上的是错误的
