### ISSUE TITLE
OneDrive V2 插件在分享链接模式下无法正常刷新token

### ISSUE THREAD

**Issue by aoyouer** [reruin/sharelist#329]
挂载Teambition后，可以获取到目录中的文件信息，但是无法下载文件，或是查看文件内容。
![image](https://user-images.githubusercontent.com/32638818/102492173-428cac00-40ac-11eb-9ba5-dff64b9423f2.png)
尝试下载文件的时候返回
![image](https://user-images.githubusercontent.com/32638818/102492211-53d5b880-40ac-11eb-9fc4-0273e376ca12.png)

**Comment by reruin** [comment]
官方修改了下载链接校验，相关 #332 。

**Comment by aoyouer** [comment]
赞
另外，我还遇到了一个小问题，我使用了onedrive 分享链接挂载的方式，但是每隔一段时间，获得的链接就不可用。
访问sharelist返回 *There has been an error authenticating the request.* ，但是分享的链接依旧是可以直接打开的。
我的onedrive是 OneDrive for business （学校邮箱申请的）
![image](https://user-images.githubusercontent.com/32638818/102634843-64aa2b00-418d-11eb-8601-ea4687379e96.png)

**Comment by reruin** [comment]
这里可能有处bug, 刷新token的时机有点问题。等待观察修复。

**Comment by aoyouer** [comment]
![image](https://user-images.githubusercontent.com/32638818/102681934-69f48d80-4200-11eb-9e8e-c6416e563799.png)
补充一下报错信息

**Comment by reruin** [comment]
@aoyouer 此问题已修复。更新后重新挂载。

**Comment by aoyouer** [comment]
出现了新的问题，一段时间后报错
There has been an error authenticating the request.
![image](https://user-images.githubusercontent.com/32638818/103137081-cd028a80-4700-11eb-9ae7-8e21dbcd9220.png)
