### ISSUE TITLE
Google Drive 掛載問題

### ISSUE THREAD

**Issue by rexx0520** [reruin/sharelist#33]
目前使用 Google Drive 掛載
有些目錄可以掛載（僅第一層），第二層後無法拉取文件，目錄顯示為空。
有些目錄則從第一層開始便無法掛載。
需要詳細資訊的話可以 PM 給您網址與分享網址。

謝謝。

**Comment by reruin** [comment]
可能是字符转义导致。请email我 shareid。

**Comment by rexx0520** [comment]
已發，請查收。

**Comment by rexx0520** [comment]
> 可能是字符转义导致。请email我 shareid。

今天再重新安裝一次，發現可以使用
但是好像無法顯示 >50 個的資料夾或檔案

**Comment by reruin** [comment]
是的，shareid 挂载有此先天缺陷。请等待后续的api版本。
