### ISSUE TITLE
目录密码和webdav功能有冲突

### ISSUE THREAD

**Issue by qian9008** [reruin/sharelist#330]
webdav应该可以绕过密码，webdav需要登陆使用。

**Comment by Mit2g** [comment]
并非使用目录加密中的密码 该密码仅作为目录访问时使用
访问加密的WebDAV参考https://github.com/reruin/sharelist/issues/286#issuecomment-705431355

**Comment by qian9008** [comment]
1.webdav没有设置  用户密码的选项
2.设置过密码的目录，webdav无法访问。
我的意思是 目录密码只对网页访问生效，webdav方式访问需要单独的账号，并且无视目录密码。

**Comment by Mit2g** [comment]
> 1.webdav没有设置 用户密码的选项
> 2.设置过密码的目录，webdav无法访问。
借用后台管理密码 没有单独的选项 在上面提到的issue里已经说的很清楚了 按照其设置可以访问

> 我的意思是 目录密码只对网页访问生效，webdav方式访问需要单独的账号，并且无视目录密码。
目前是这样的 但WebDAV属于借用管理员权限 且有视目录加密 不使用管理员权限无法访问加密目录

**Comment by reruin** [comment]
webdav 只存在两种情况。
1. 匿名时，访问权限等同于匿名web访问。
2. 使用后台口令作为密码，可见所有文件。
