### ISSUE TITLE
日前Teambition 對下載鏈接安全策略做出了改變，導致sharelist無法正確下載文件。

### ISSUE THREAD

**Issue by cooluc** [reruin/sharelist#332]
Teambition 爲了阻止用戶通過下載文件鏈接方式共享文件給其他人員，并針對下載鏈接作出新的策略，文件下載鏈接為一次有效，當第二次請求時將會返回錯誤信息。導致sharelist無法正確下載文件。

sharelist 有辦法在下載文件的時候永遠在 Teambition 上獲取地址嗎？哪怕放棄緩存功能

**Comment by reruin** [comment]
1. 当前Teambition下载时强制校验 referer ，因而**Teambition临时链接**将无法直接下载，必须使用中转模式。
而中转模式将无法享受官方的高速下载。

2. 如果仅个人使用，可考虑创建**本地代理转发**（类似cf-worker性质，非服务器转发），相关工具已在开发。

3. 对外公开访问，处了强制中转（服务器或者cf-worker）外，没有很好的解决方法。

**Comment by zwsn** [comment]
网上看到一个相关Teambition的，我测试了发现，链接是固定的但是直链不是按照文件夹路径来的。不知道对作者有没有帮助，链接https://www.52pojie.cn/thread-1320716-1-1.html

**Comment by reruin** [comment]
> 网上看到一个相关Teambition的，我测试了发现，链接是固定的但是直链不是按照文件夹路径来的。不知道对作者有没有帮助，链接https://www.52pojie.cn/thread-1320716-1-1.html

参考上一条回复。

**Comment by cooluc** [comment]
> 1. 当前Teambition下载时强制校验 referer ，因而**Teambition临时链接**将无法直接下载，必须使用中转模式。
>    而中转模式将无法享受官方的高速下载。
> 2. 如果仅个人使用，可考虑创建**本地代理转发**（类似cf-worker性质，非服务器转发），相关工具已在开发。
> 3. 对外公开访问，除了强制中转（服务器或者cf-worker）外，没有很好的解决方法。



> 1. 当前Teambition下载时强制校验 referer ，因而**Teambition临时链接**将无法直接下载，必须使用中转模式。
>    而中转模式将无法享受官方的高速下载。
> 2. 如果仅个人使用，可考虑创建**本地代理转发**（类似cf-worker性质，非服务器转发），相关工具已在开发。
> 3. 对外公开访问，除了强制中转（服务器或者cf-worker）外，没有很好的解决方法。

明白，這個消息太令人遺憾了。

**Comment by sottboy** [comment]
> 1. 当前Teambition下载时强制校准参照人，而**Teambition临时链接**将无法直接下载，必须使用中转模式。
>    而中转模式将无法享受官方的高速下载。
> 2. 如果仅个人使用，可考虑创建**本地代理转发**（类似cf-worker性质，非服务器转发），相关工具已在开发。
> 3. 对外公开访问，除了强制中转（服务器或cf-worker）外，没有很好的解决方法。

还没有开始用就不能用了？

**Comment by reruin** [comment]
sharelis-proxy 已开发完成，适用于个人用途的本机代理。[参考文档](https://reruin.github.io/sharelist/docs/#/zh-cn/advance?id=sharelist-proxy%e4%b8%ad%e8%bd%ac)。
