### ISSUE TITLE
除了本地挂载之外，其他都看不到上传按钮。只有本地才有上传功能？

### ISSUE THREAD

**Issue by gimgoo** [reruin/sharelist#339]
如题，除了本地挂载之外，其他都看不到上传按钮。像蓝奏云，已经挂载成功了，整个页面都看不到上传按钮，拖文件到窗口也不行。

**Comment by reruin** [comment]
适配上传功能的插件 比较少。

**Comment by gimgoo** [comment]
另外再问一下大佬，部署以后，首页看不到下载文件夹的按钮是什么情况？

**Comment by gimgoo** [comment]
![image](https://user-images.githubusercontent.com/31849284/102684445-8ea63080-4213-11eb-863e-27b3a400bfc4.png)

**Comment by gimgoo** [comment]
![image](https://user-images.githubusercontent.com/31849284/102684458-b1384980-4213-11eb-9a21-a1f7774b593e.png)

**Comment by sottboy** [comment]
> ![image](https://user-images.githubusercontent.com/31849284/102684458-b1384980-4213-11eb-9a21-a1f7774b593e.png)
> 

你这个是哪个网站的

**Comment by gimgoo** [comment]
就sharelist的，我自己改了样式而已

**Comment by reruin** [comment]
> 另外再问一下大佬，部署以后，首页看不到下载文件夹的按钮是什么情况？

不是所有挂载源 都支持文件夹下载。

**Comment by gimgoo** [comment]
teambition不支持文件夹下载吗？大佬，我看到有个人也是用teambition的，它的支持诶

**Comment by gimgoo** [comment]
> > 另外再问一下大佬，部署以后，首页看不到下载文件夹的按钮是什么情况？
> 
> 不是所有挂载源 都支持文件夹下载。
Teambition不支持文件夹下载吗？大佬，我看到有个人也是用sharelist搭建的，它的支持文件夹下载

**Comment by reruin** [comment]
Teambition官方 都不支持文件夹下载吧。
![image](https://user-images.githubusercontent.com/7403780/102861051-ee961480-4469-11eb-9d5f-8f9433577d39.png)

**Comment by gimgoo** [comment]
被你这么一说我去看了下，我模仿样式的那个站，发现下载链接是download.mcloud.139.com。只是样式什么的改成teambition，看来不是teambition的

**Comment by reruin** [comment]
。。没问题的哈 关下issue
