### ISSUE TITLE
dplayer视频加载失败

### ISSUE THREAD

**Issue by qian9008** [reruin/sharelist#341]
gd 视频加载失败，浏览器已翻。

**Comment by reruin** [comment]
先用默认播放器试下 能不能播放。

**Comment by zjboy1984** [comment]
确实都无法播放，无论是默认的还是dplayer

**Comment by Mit2g** [comment]
> 确实都无法播放，无论是默认的还是dplayer

请指明你所播放的格式 如果方便 请提供该资源来源

**Comment by zjboy1984** [comment]
> > 确实都无法播放，无论是默认的还是dplayer
> 
> 请指明你所播放的格式 如果方便 请提供该资源来源
> ![mkv测试](https://user-images.githubusercontent.com/50163397/103149180-34244b80-47a2-11eb-9fd5-293bce86176e.jpg)
> 
> 该测试资源为mkv

格式为MP4，资源来源是teambition自己上传的视频

**Comment by reruin** [comment]
> > > 确实都无法播放，无论是默认的还是dplayer
> > 
> > 
> > 请指明你所播放的格式 如果方便 请提供该资源来源
> > ![mkv测试](https://user-images.githubusercontent.com/50163397/103149180-34244b80-47a2-11eb-9fd5-293bce86176e.jpg)
> > 该测试资源为mkv
> 
> 格式为MP4，资源来源是teambition自己上传的视频

是否使用中转？

**Comment by zjboy1984** [comment]
> > > > 确实都无法播放，无论是默认的还是dplayer
> > > 
> > > 
> > > 请指明你所播放的格式 如果方便 请提供该资源来源
> > > ![mkv测试](https://user-images.githubusercontent.com/50163397/103149180-34244b80-47a2-11eb-9fd5-293bce86176e.jpg)
> > > 该测试资源为mkv
> > 
> > 
> > 格式为MP4，资源来源是teambition自己上传的视频
> 
> 是否使用中转？

没有使用中转

**Comment by Mit2g** [comment]
> > > 确实都无法播放，无论是默认的还是dplayer
> > 
> > 
> > 请指明你所播放的格式 如果方便 请提供该资源来源
> > ![mkv测试](https://user-images.githubusercontent.com/50163397/103149180-34244b80-47a2-11eb-9fd5-293bce86176e.jpg)
> > 该测试资源为mkv
> 
> 格式为MP4，资源来源是teambition自己上传的视频

![image](https://user-images.githubusercontent.com/50163397/103270281-7217ae80-49f2-11eb-81e1-0b5fd5f71e17.png)
MP4格式 正常播放 无中转 视频存放于GD
由于Teambition资格一直没对我发放 无法在测试其是否有差异
