### ISSUE TITLE
onedrive无法挂载

### ISSUE THREAD

**Issue by gimgoo** [reruin/sharelist#346]
如题，onedrive无法挂载，用的是开发者E5版本，重定向写自己域名或者https://reruin.github.io/sharelist/redirect.html都没用，总是报错
```
Sorry, but we’re having trouble signing you in.

AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'c5de461e-c200-404b-ab24-4f67daa2a488'.
```

**Comment by r1172464137** [comment]
同问

**Comment by reruin** [comment]
用的是哪个插件？ Onedrive V2 吗？

**Comment by reruin** [comment]
暂时先填这个 ```https://reruin.github.io/redirect/onedrive.html```

**Comment by gimgoo** [comment]
对，OneDrive V2, 那些租户id什么的都填对了，就说url有问题

**Comment by zjboy1984** [comment]
> 对，OneDrive V2, 那些租户id什么的都填对了，就说url有问题

是的，我也是一样的出现错误，找不到 reruin.github.io 的网页找不到与以下网址对应的网页：https://reruin.github.io/sharelist/redirect.html?code=0.AAAAAoaEJim6IEy7JtMnLEQVmkfHu9yXIZ9HhKPgrbm97SZJAGE.AQABAAIAAABeStGSRwwnTq2vHplZ9KL4bIw2WgLKCB5dgRMAJJHNa_R9kN3zViPNCzG1jN2jg5wAEcGTxeQbMVmRLdk4VlFrVrX6-qf71dHFPtZ2FbbDdbImvXGM9GqvHmYutOxna4lR7xssQ8aT65GqLwguBYRgwiVnrd7a1Ou5EfyPRmAqgeEYw7k7mteQq3CAzjKjfD6SS-lkZRK39H-gJJ5Hyd-lNsvrXYev30B6p5vkdvhgmkKDlq-kX3w-NNXIht5_djPAbyqMP_NWJ8VvbhKVyrUf6JQAkIoMJ2N2UFVmOLRu7m23tf4O-KnqC_by_1UDv3Ja-DLUH1phPrid48AT4fhQENy823KCkDNd6kL4wV0e3rFiO8aO3mrEGkezqhSj2Y0UrPUX0rhF0SqyNPFn6YGrb2SAoP9gtbyyrv_Y8aspbOu8Wmb5s3i4wBekIQU48wXMnfyTbWUtn6qgNrIcqrBQLoET-5kadHUf7COc1DrbBYOAlzpNjNr3rmnOCgvxRLLXPrNuY6Um7hdVb324PvhJzfuy144ReTvwwYXa7ulBxlcNtcZcmJV2LpUK6l7_we9CHg0xJpavj97w9rLom2Yyp-Atsk9ajJcKGOgpnMRhLtWP1LEloEus4amIGCltfW0ChJZPSiwA9X8tx9RjKIQBIAA&state=http%3a%2f%2fcloud.lbzt.art%2fuuy&session_state=9b920fcb-1e3e-4cb3-abf6-e49e15a4432f#
HTTP ERROR 404
