### ISSUE TITLE
chromium内核浏览器，cloudflare worker中转下载会显示“未发现文件”

### ISSUE THREAD

**Issue by tomoyo233** [reruin/sharelist#347]
docker搭建
IE浏览器可以正常中转下载

测试有问题的浏览器以及版本：
Google Chrome 已是最新版本
版本 87.0.4280.88（正式版本） （64 位）
Microsoft Edge 是最新版本。
版本 87.0.664.66 (官方内部版本) (64 位)

相同的问题
https://github.com/reruin/sharelist/issues/263
https://github.com/reruin/sharelist/issues/254

**Comment by reruin** [comment]
中转的文件 是哪个挂载源？

**Comment by tomoyo233** [comment]
> 中转的文件是哪个挂载源？

onedrive v2

**Comment by reruin** [comment]
已修复。

**Comment by yourber** [comment]
你好，我是部署在windows上，IIS10配合Application Request Routing Cache做的反向代理，其他都正常，但是文件直连的时候真实的链接地址应该是 https://dev95.baidupan.com/060111bb/2021/05/28/e17620b41a203d00d5f263a1bc39d4da.pptx 但是https://dev95.baidupan.com 域名的部分会替换成我设置的反向代理的域名，报404的错误，请问有办法解决吗？？

**Comment by HanHan233** [comment]
> 你好，我是部署在windows上，IIS10配合Application Request Routing Cache做的反向代理，其他都正常，但是文件直连的时候真实的链接地址应该是 https://dev95.baidupan.com/060111bb/2021/05/28/e17620b41a203d00d5f263a1bc39d4da.pptx 但是https://dev95.baidupan.com 域名的部分会替换成我设置的反向代理的域名，报404的错误，请问有办法解决吗？？

将`Application Request Router`里的`Reverse rewrite host in response headers`关闭即可

**Comment by yourber** [comment]
> > 你好，我是部署在windows上，IIS10配合Application Request Routing Cache做的反向代理，其他都正常，但是文件直连的时候真实的链接地址应该是 https://dev95.baidupan.com/060111bb/2021/05/28/e17620b41a203d00d5f263a1bc39d4da.pptx 但是https://dev95.baidupan.com 域名的部分会替换成我设置的反向代理的域名，报404的错误，请问有办法解决吗？？
> 
> 将`Application Request Router`里的`Reverse rewrite host in response headers`关闭即可

方法可用 多谢 多谢~
