### ISSUE TITLE
分享一个sharelist美化教程

### ISSUE THREAD

**Issue by gimgoo** [reruin/sharelist#348]
美化后的样式：
![image](https://cdn.jsdelivr.net/gh/isyume/blog_images/20201225103937.png)

教程地址：[ William's Blog - https://blog.iyume.top/ ](https://blog.iyume.top/frontend/46.html)

**Comment by zjboy1984** [comment]
> 美化后的样式：
> ![image](https://user-images.githubusercontent.com/31849284/102871093-f4dfbd00-4478-11eb-841b-4248d662f38a.png)
> 
> 教程地址：[William's Blog](https://blog.iyume.top/frontend/46.html)

请问下大佬，你的onedrive是怎样挂载上的

**Comment by justhy** [comment]
对于使用heroku搭建的，如何进行美化？

**Comment by Penghaiku** [comment]
不错，感谢分享
