### ISSUE TITLE
大佬 文件夹出错

### ISSUE THREAD

**Issue by FemalePresident** [reruin/sharelist#35]
Error
Looks like something broke!

        
SyntaxError: Unexpected token x in JSON at position 21539
    at JSON.parse (<anonymous>)
    at Object.folder (/root/gdlist-master/models/googledrive.js:34:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by reruin** [comment]
你使用的老版本有字符转义的问题，使用最新版即可解决。

**Comment by FemalePresident** [comment]
大佬，我用别人的一键脚本完成安装。有没有办法使用脚本后升级到最新版的程序？
如果有，能说明一下方法吗？

一键脚本地址：https://www.94ish.me/1714.html

**Comment by reruin** [comment]
按顺序执行以下shell 
`rm -rf /root/gdlist-master` 
`cd /root  `
`wget https://github.com/reruin/sharelist/archive/master.zip -O sharelist.zip `
`unzip sharelist.zip  `
`cd sharelist-master  `
`npm install  `
`pm2 restart all  `

**Comment by FemalePresident** [comment]
执行npm install后提示如下错误：
npm WARN deprecated swig@1.4.2: This package is no longer maintained
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.

> nodemon@1.18.10 postinstall /root/sharelist-master/node_modules/nodemon
> node bin/postinstall || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate


npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

执行pm2 restart all后提示如下 ：

Use --update-env to update environment variables
[PM2] Applying action restartProcessId on app [all](ids: 0)
[PM2] [www](0) ✓
┌──────────┬────┬─────────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬──────┬──────────┐
│ App name │ id │ version │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user │ watching │
├──────────┼────┼─────────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼──────┼──────────┤
│ www      │ 0  │ N/A     │ fork │ N/A │ errored │ 1       │ 0      │ 0%  │ 0 B    │ root │ disabled │
└──────────┴────┴─────────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app

用一键脚本绑定的网址打开提示502，用IP:33001提示找不到页面。

大佬 这情况是npm出问题了吗？

**Comment by reruin** [comment]
killall node ，然后 进到 /root/sharelist-master 运行 npm run start 看下有没有报错

**Comment by FemalePresident** [comment]
太感谢了，看错误好像是npm没有启动 。

root@GoogleDrive:~# killall node
node: no process found
root@GoogleDrive:~# /root/sharelist-master
-bash: /root/sharelist-master: Is a directory
root@GoogleDrive:~# cd /root/sharelist-master
root@GoogleDrive:~/sharelist-master# npm run start

> sharelist@0.1.0 start /root/sharelist-master
> set NODE_ENV=dev && node app.js

Load Plugins:  auth.basic
Load Plugins:  drive.fs
Load Plugins:  drive.http
Load Plugins:  drive.https
Load Plugins:  drive.sld
Load Plugins:  drive.91
Load Plugins:  drive.gd
Load Plugins:  drive.gda
Load Plugins:  drive.lanzou
Load Plugins:  drive.od
Load Plugins:  drive.odb
Load Plugins:  drive.openload
Load Plugins:  format.url
2019-03-13T11:57:22.349Z
App is running at http://127.0.0.1:33001/


现在可以访问。
还有我想一下  这个程序需要添加开机启动吗？我重启后是不是需要运行npm run start这条命令？

**Comment by FemalePresident** [comment]
在我关闭或者crtl+c结束npm run start这条命令后 网页就无法正常打开了...

**Comment by reruin** [comment]
npm run prd

**Comment by FemalePresident** [comment]
运行后如下：

root@GoogleDrive:~/sharelist-master# npm run prd

> sharelist@0.1.0 prd /root/sharelist-master
> pm2 start app.js --name sharelist --env prod


>>>> In-memory PM2 is out-of-date, do:
>>>> $ pm2 update
In memory PM2 version: 3.4.0
Local PM2 version: 2.10.4

[PM2] Starting /root/sharelist-master/app.js in fork_mode (1 instance)
[PM2] Done.
┌───────────┬────┬──────┬───────┬─────────┬─────────┬────────┬─────┬──────────┬──────┬──────────┐
│ App name  │ id │ mode │ pid   │ status  │ restart │ uptime │ cpu │ mem      │ user │ watching │
├───────────┼────┼──────┼───────┼─────────┼─────────┼────────┼─────┼──────────┼──────┼──────────┤
│ sharelist │ 1  │ fork │ 27657 │ online  │ 0       │ 0s     │ 0%  │ 9.3 MB   │ root │ disabled │
│ www       │ 0  │ fork │ N/A   │ errored │ 1       │ 0      │ 0%  │ 0 B      │ root │ disabled │
└───────────┴────┴──────┴───────┴─────────┴─────────┴────────┴─────┴──────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app

**Comment by reruin** [comment]
好着呢。

**Comment by FemalePresident** [comment]
谢谢。

程序需要开机启动吗？

**Comment by reruin** [comment]
执行 pm2 save  保存运行状态即可

**Comment by FemalePresident** [comment]
谢谢你了。

大佬 还有个问题就是如果程序有升级的话，是不是还得继续这样弄一次？

**Comment by reruin** [comment]
代码覆盖后 重启即可
