### ISSUE TITLE
Onedrive分享链接挂载出现There has been an error authenticating the request.

### ISSUE THREAD

**Issue by aoyouer** [reruin/sharelist#350]
学校的Onedrive for Business 通过 分享链接挂载，刚挂在上是可用的，过一段时间后提示
There has been an error authenticating the request，删掉当前的配置重新输入之前的分享链接才能继续使用。
![image](https://user-images.githubusercontent.com/32638818/103151692-51194880-47bb-11eb-9eee-d6c8450b703f.png)

**Comment by reruin** [comment]
最近收到此类 access denied 的报告，正在分析是否token过期导致的问题。近期会修复。

**Comment by shenlanAZ** [comment]
家宽也会, aria2下载会500， 过段时间就可以继续下载了, 查看分享内容也是正常的.

**Comment by wf09** [comment]
对开发者表示感谢！
由于我使用的onedrive for business 账户域内无管理员，只能使用SharePoint分享链接进行分享。这个功能很棒！
Bug复现：
使用OneDrive V2挂载的**SharePoint 分享链接** 大概一个小时左右就会失效，再次输入原来的挂载连接即可成功挂载。

![image-20210313145710150](https://s3.ax1x.com/2021/03/13/6dy7TJ.png)
