### ISSUE TITLE
目录索引 开启无反应

### ISSUE THREAD

**Issue by myitcloud** [reruin/sharelist#351]
目录索引 开启无反应
使用的网盘 天翼云 和和彩云
跪求大佬修复

**Comment by reruin** [comment]
此功能默认开启。禁用时 将无法列目录，但可以通过链接直接下载。

**Comment by myitcloud** [comment]
> 此功能默认开启。局部时将无法列出目录，但可以通过链接直接下载。

好吧，感谢大佬，我理解错了这个功能，我以为是文件搜索功能
