### ISSUE TITLE
请教一下，github是如何挂载的呀。文档中没看到相关介绍？

### ISSUE THREAD

**Issue by Cuiyim** [reruin/sharelist#356]
![image](https://user-images.githubusercontent.com/51844650/103356422-d702ff80-4aeb-11eb-9c91-5ee9518ab6d5.png)

**Comment by reruin** [comment]
填 username 或者 username/repo

**Comment by Cuiyim** [comment]
好嘞，大佬这么晚还在呀  哈哈
