### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by qian9008** [reruin/sharelist#358]
root@VM-0-9-debian:~# wget --no-check-certificate -qO-  https://raw.githubusercontent.com/reruin/sharelist/master/netinstall.sh | bash
+============================================================+
|                    ShareList Netinstaller                  |
|                                                            |
|                                         <reruin@gmail.com> |
|------------------------------------------------------------|
|                                         https://reruin.net |
+============================================================+

|  ShareList is installing ...
|
|  Download ShareList Package ...
mv: cannot move 'sharelist-master' to 'sharelist/sharelist-master': Directory not empty
|
|  Install Dependents ...
|
|  Success: ShareList has been installed

**Comment by qian9008** [comment]
这是重复安装出错吗？反正没安装成功 pm2管理器里也没有，手动添加app.js也无法启动

**Comment by reruin** [comment]
用的是哪个系统。

**Comment by qian9008** [comment]
debian 10     还是不行

**Comment by qian9008** [comment]
|  ShareList is installing ...
|
|  Download ShareList Package ...
|
|  Install Dependents ...
|
|  Success: ShareList has been installed

**Comment by reruin** [comment]
> | ShareList is installing ...
> |
> | Download ShareList Package ...
> |
> | Install Dependents ...
> |
> | Success: ShareList has been installed

方便的话私发下 服务器ip 账号密码。
