### ISSUE TITLE
文档404

### ISSUE THREAD

**Issue by 407477** [reruin/sharelist#367]
如题

**Comment by reruin** [comment]
https://reruin.github.io/sharelist/docs/#/zh-cn/

**Comment by 407477** [comment]
打开 404

**Comment by reruin** [comment]
此页面可能需要科学上网。 
稍后会建个镜像页面。

**Comment by 407477** [comment]
已科学上网，非常喜欢你的程序，由于本人小白想美化sharelist打开文件不存在的提示Not Found错误页面，但是搜索全文也没找到关键词，哈哈！研究了几个小时就是找不到！

**Comment by reruin** [comment]
目前还不能自定义404。需要的话可以写个中间件。

**Comment by reruin** [comment]
@407477 sharelist现已支持自定义主题。可修改 theme/default/views/404.pug 实现自定义404页。

更多请参考文档。
