### ISSUE TITLE
使用虚拟目录如何挂载带密码的蓝奏云

### ISSUE THREAD

**Issue by benzBrake** [reruin/sharelist#368]
尝试使用
```
lanzou:密码@目录Id
```
不管用

**Comment by reruin** [comment]
后台挂载不要加```lanzou:```这个协议前缀。直接使用 ```密码@目录Id```即可，经测试 是可以的。

**Comment by benzBrake** [comment]
不是后台挂载，而是我在文件夹里新建 目录.d.ln 文件的方式挂载，挂载不了带密码的

**Comment by reruin** [comment]
虚拟文件 ```lanzou:密码@目录ID``` 测试ok。目录ID是```https://wwi.lanzous.com/bxxxxxxx``` 中 ```bxxxxxx```的部分。不要使用自定义外链。

**Comment by benzBrake** [comment]
不行 https://www.lanzous.com/b00o7nrxa 密码355，挂载显示空白
挂载演示 https://wget.pm/oddo/%E6%89%8B%E5%8A%BF%E4%BD%93%E6%84%9F
