### ISSUE TITLE
希望webdav可以支持负载均衡

### ISSUE THREAD

**Issue by joseph-cheung** [reruin/sharelist#369]
希望webdav可以支持负载均衡，达到和在线列表一样效果。
现阶段负载均衡文件夹在webdav下打不开，被负载均衡文件夹都可见。

**Comment by reruin** [comment]
webdav 是默认支持的。请先确认 被负载均衡文件夹 可以正常访问。

建议更新到最新的sharelist 再试。

**Comment by joseph-cheung** [comment]
刚刚重新安装后重试过，依然是只能显示原来单独的被负载均衡的文件夹，而尝试打开配置好的负载均衡文件夹，会卡顿然后空白。
以及在很多情况下，webdav在每个路径均会出现"._"名字的空文件夹
被负载均衡的是三个OneDrive v2 世纪互联

**Comment by reruin** [comment]
是用什么客户端连接webdav的？

**Comment by joseph-cheung** [comment]
rclone、raidrive、安卓ES文件浏览器、kodi均如此
rclone 为例
`[root@localhost webdav]# ls`
`Node1  Node2  Node3  Storage`
GUI下能看到还有个._文件夹在每一层目录出现，Storage是负载均衡文件夹，打开为空

**Comment by joseph-cheung** [comment]
以上我多次重试无果，在windows自带的webdav上又出现了偶发"此页面无法在WebDAV中显示"文件的现象
