### ISSUE TITLE
批量下载

### ISSUE THREAD

**Issue by lingnan888** [reruin/sharelist#372]
好多文件要一个一个下，

**Comment by joseph-cheung** [comment]
可以尝试使用webdav

**Comment by reruin** [comment]
使用下方的自定义脚本可实现 **批量复制**。
```js
<script>
//快捷复制
"use strict";window.jQuery&&!location.pathname.startsWith("/manage")&&$(function(){function e(e){var t=!1,c=document.createElement("textarea"),n=document.activeElement;document.body.appendChild(c),c.value=e,c.focus(),c.setSelectionRange?c.setSelectionRange(0,c.value.length):c.select();try{t=document.execCommand("copy")}catch(e){t=!1}return document.body.removeChild(c),n.focus(),t}var t=[];if($(".list").find("a i:not(.ic-folder)").each(function(){t.push(location.origin+decodeURIComponent($(this).parents("a.clearfix").attr("href").replace(/\?.*/g,"")))}),t.length>0){var c=$('<a><svg class="ic" style="width: 22px;height: 22px;vertical-align: middle;fill: currentColor;overflow: hidden;" viewBox="0 0 1024 1024"><path d="M662.528 255.488c56.166 0 101.734 45.517 101.734 101.734v457.933c0 56.218-45.568 101.735-101.785 101.735H204.544A101.786 101.786 0 0 1 102.81 815.155V357.222c0-56.217 45.568-101.785 101.734-101.785h457.933z m0 61.03H204.493c-20.48 0-37.837 15.258-40.397 35.584l-0.307 5.12v457.933c0 20.48 15.257 37.837 35.635 40.397l5.12 0.307h457.882c20.53 0 37.888-15.257 40.448-35.635l0.256-5.12v-457.83c0-20.532-15.258-37.888-35.584-40.448l-5.12-0.256zM815.104 102.81c56.269 0 101.786 45.568 101.786 101.734v457.933c0 56.217-45.568 101.785-101.735 101.785v-61.081c20.48 0 37.837-15.258 40.397-35.584l0.307-5.12V204.544c0-20.48-15.257-37.837-35.635-40.397l-5.12-0.307h-457.83c-20.532 0-37.888 15.258-40.448 35.635l-0.256 5.12h-61.133c0-56.217 45.568-101.785 101.785-101.785h457.933z"></path></svg></a>');$(".upload-menu").append(c),c.on("click",function(){e(t.join("\n")),alert("复制成功 共"+t.length+"条")})}});
</script>
```

**Comment by hzzhy1987** [comment]
> 使用下方的自定义脚本可实现 **批量复制**。
> 
> ```js
> <script>
> //快捷复制
> "use strict";window.jQuery&&!location.pathname.startsWith("/manage")&&$(function(){function e(e){var t=!1,c=document.createElement("textarea"),n=document.activeElement;document.body.appendChild(c),c.value=e,c.focus(),c.setSelectionRange?c.setSelectionRange(0,c.value.length):c.select();try{t=document.execCommand("copy")}catch(e){t=!1}return document.body.removeChild(c),n.focus(),t}var t=[];if($(".list").find("a i:not(.ic-folder)").each(function(){t.push(location.origin+decodeURIComponent($(this).parents("a.clearfix").attr("href").replace(/\?.*/g,"")))}),t.length>0){var c=$('<a><svg class="ic" style="width: 22px;height: 22px;vertical-align: middle;fill: currentColor;overflow: hidden;" viewBox="0 0 1024 1024"><path d="M662.528 255.488c56.166 0 101.734 45.517 101.734 101.734v457.933c0 56.218-45.568 101.735-101.785 101.735H204.544A101.786 101.786 0 0 1 102.81 815.155V357.222c0-56.217 45.568-101.785 101.734-101.785h457.933z m0 61.03H204.493c-20.48 0-37.837 15.258-40.397 35.584l-0.307 5.12v457.933c0 20.48 15.257 37.837 35.635 40.397l5.12 0.307h457.882c20.53 0 37.888-15.257 40.448-35.635l0.256-5.12v-457.83c0-20.532-15.258-37.888-35.584-40.448l-5.12-0.256zM815.104 102.81c56.269 0 101.786 45.568 101.786 101.734v457.933c0 56.217-45.568 101.785-101.735 101.785v-61.081c20.48 0 37.837-15.258 40.397-35.584l0.307-5.12V204.544c0-20.48-15.257-37.837-35.635-40.397l-5.12-0.307h-457.83c-20.532 0-37.888 15.258-40.448 35.635l-0.256 5.12h-61.133c0-56.217 45.568-101.785 101.785-101.785h457.933z"></path></svg></a>');$(".upload-menu").append(c),c.on("click",function(){e(t.join("\n")),alert("复制成功 共"+t.length+"条")})}});
> </script>
> ```

用不了啊
