### ISSUE TITLE
和彩云无法正常登陆

### ISSUE THREAD

**Issue by zxq1998** [reruin/sharelist#373]
![image](https://user-images.githubusercontent.com/16048692/105453227-b8db8a00-5cba-11eb-95f6-738cd08234ba.png)
在挂载界面输入账号和密码后点击验证后，网页会刷新，但是刷新后又会回到这个界面，无法成功挂载，可以帮忙看下是什么原因吗，谢谢

**Comment by reruin** [comment]
和彩云最近要求短信二次验证，等待后续更新。

**Comment by Penghaiku** [comment]
我本来挂载上了，更新后cookie没了，就登不上了，哭辽

**Comment by reruin** [comment]
已更新。@zxq1998 @Penghaiku 彩云官方的cookie有效期只有30天了。哭
