### ISSUE TITLE
百度云盘挂载失败

### ISSUE THREAD

**Issue by Penghaiku** [reruin/sharelist#374]
![image](https://user-images.githubusercontent.com/46412151/105503349-6d000380-5d01-11eb-9554-73b1a6691f2f.png)
![image](https://user-images.githubusercontent.com/46412151/105503376-77220200-5d01-11eb-85ce-e9a296f02b81.png)
![image](https://user-images.githubusercontent.com/46412151/105503421-830dc400-5d01-11eb-8be4-da01fb8a82c6.png)

如上图，配置应该没有问题，报错如上

**Comment by Penghaiku** [comment]
![image](https://user-images.githubusercontent.com/46412151/105503641-cd8f4080-5d01-11eb-90f8-3249468f5c9c.png)

疑似api未开启

**Comment by Penghaiku** [comment]
![image](https://user-images.githubusercontent.com/46412151/105504051-468e9800-5d02-11eb-82b3-5e87e1dbc6c6.png)
- 无法开启权限

**Comment by goldcome** [comment]
我也遇到了 不过后面多试几次就成功了 也不清楚原因 还有就是下载小文件 有时候出现：`{"error_code":31326,"error_msg":"user is not authorized, hitcode:109","error_info":"","request_id":2074145283459534030}`问题 概率挺大

**Comment by reruin** [comment]
> 我也遇到了 不过后面多试几次就成功了 也不清楚原因 还有就是下载小文件 有时候出现：`{"error_code":31326,"error_msg":"user is not authorized, hitcode:109","error_info":"","request_id":2074145283459534030}`问题 概率挺大

如果可以，能否提供下 你所下载文件的大小。

官方对大文件限制直链下载，但中转可规避。sharelist 对大于50M的文件强制中转 。你所反映的情况可能表明实际值可能小于50M。稍后会调整这个值。

**Comment by goldcome** [comment]
@reruin 我测试貌似和大小无关 从几百k到几十M都有这种情况 而且有些文件还会出现`{ "error_code":31326, "error_msg":"anti hotlinking" } ` 这个 不知道是否是百度那边的问题 这个还看其他人使用反馈

**Comment by reruin** [comment]
@goldcome 31326是触发了防盗链，原因不明。官方那边的下载地址dlink 会302到实际链接，sharelist返回（中转）的是此地址。

**Comment by reruin** [comment]
@Penghaiku 不要直接在 开发者服务管理 那创建工程。从网盘开发平台创建应用。

**Comment by reruin** [comment]
@goldcome 刚发现一处 遗漏更新。更新下 再试试。

**Comment by goldcome** [comment]
@reruin 完美  目前没有发现问题

**Comment by reruin** [comment]
@Penghaiku 更新后再试试。
