### ISSUE TITLE
Heroku部署，休眠后需要重新配置

### ISSUE THREAD

**Issue by carey036** [reruin/sharelist#379]
Heroku部署30分钟左右系统会休眠，休眠以后需要重新进行Install，希望可以把配置写到文件，确保唤醒后可以自动读取配置进行Install

**Comment by reruin** [comment]
参考下 https://github.com/reruin/sharelist/issues/90#issuecomment-571860129

**Comment by carey036** [comment]
谢谢，没有问题了，文档中好像没有说明

> 参考下 [#90 (comment)](https://github.com/reruin/sharelist/issues/90#issuecomment-571860129)
