### ISSUE TITLE
希望可以增加直链提取功能

### ISSUE THREAD

**Issue by yimshing** [reruin/sharelist#38]
![1.png](https://i.loli.net/2019/05/30/5cef32fd7070151988.png)
![2.png](https://i.loli.net/2019/05/30/5cef32fda0df372360.png)

像这种情况 要下载全部文件的话 只能每一个文件慢慢点 这样效率太低了

**Comment by reruin** [comment]
会增加 【取消预览】功能，之后在页面使用 批量下载即可。

有一个临时方法：
将 `/app/controllers/sharelist.js` 第11行修改为
`const isPreview = false;`

**Comment by reruin** [comment]
已完成。
