### ISSUE TITLE
webdav显示404

### ISSUE THREAD

**Issue by Qa70601234** [reruin/sharelist#386]
![image](https://user-images.githubusercontent.com/74185784/106161932-818d4180-61c2-11eb-9961-a6a48be7e9e8.png)
为什么显示404呢

**Comment by reruin** [comment]
webdav 需要用客户端链接 才能看到内容。

**Comment by irainerc** [comment]
用了客户端也不行。。

![image](https://user-images.githubusercontent.com/55922227/109119883-38f48400-7780-11eb-9202-68b268d2457e.png)

**Comment by irainerc** [comment]
> webdav 需要用客户端链接 才能看到内容。

用了raidrive也不行，计算机积极拒绝怎么搞。。

**Comment by xixky** [comment]
> > webdav 需要用客户端链接 才能看到内容。
> 
> 用了raidrive也不行，计算机积极拒绝怎么搞。。

raidrive我没有试过，Mountain Duck挂载是可以的
