### ISSUE TITLE
阿里云盘所有视频无法预览

### ISSUE THREAD

**Issue by LimeZky** [reruin/sharelist#388]
阿里云盘所有视频无法预览播放 页面一直在加载，但播放区全黑并且未获取到视频长度

**Comment by LimeZky** [comment]
![image](https://user-images.githubusercontent.com/31511420/106425104-4d55a180-649e-11eb-8fc6-2d3dcbacb9b9.png)

**Comment by liumingye** [comment]
`<meta name="referrer" content="never">`
放到 自定义样式 里保存
![](https://ae01.alicdn.com/kf/H5e87d41844674d2e928fa23bcf6ae4d0l.jpg)

**Comment by LimeZky** [comment]
好的 谢谢您 请问有没有重新做默认主题的想法

**Comment by reruin** [comment]
@LimeZky 暂时没有时间。可参考文档开发，https://reruin.net/sharelist-docs/#/zh-cn/advance?id=%e4%b8%bb%e9%a2%98%e5%bc%80%e5%8f%91
