### ISSUE TITLE
如何添加其他播放器

### ISSUE THREAD

**Issue by Rainforestwind** [reruin/sharelist#391]

**Comment by reruin** [comment]
编辑 https://github.com/reruin/sharelist/blob/master/plugins/preview.media.js 文件。

1. 在此行注册新的播放器。
https://github.com/reruin/sharelist/blob/66dfc62051d42144c7f2072673f8bb2d6ef4e88e/plugins/preview.media.js#L32

2. 在此行编写新播放器的代码。
https://github.com/reruin/sharelist/blob/66dfc62051d42144c7f2072673f8bb2d6ef4e88e/plugins/preview.media.js#L50
