### ISSUE TITLE
跪求sharelist-proxy中转服务器设置方法和多网盘readme.md首页显示

### ISSUE THREAD

**Issue by chenfengnet** [reruin/sharelist#392]
sharelist-proxy中转服务器具体应该怎么设置呢，
下载对应版本的中转程序。以 -t [TOKEN] -h [HOST] 参数启动后，服务器已经在监听33009端口了，举例说明，b.com为中转服务器，a.com为sharelist站，123为a.com的后台密码，a.com后台的中转参数需要填写b.com:33009端口吗，或者需要填写http吗，比如http://b.com:33009，求具体中转写发，第二个问题是挂载了两个或者多个网盘的时候主页是以文件夹的形式展现的，这个时候应该怎样在主页显示readme.md呢

**Comment by reruin** [comment]
1. 中转服务器 填写 ```http://b.com:33009``` 即可。
2. 添加个【本地文件】挂载，挂载名为 readme.md，路径为实际readme路径；添加 忽略路径 /readme.md，参考 #88 。

**Comment by aofengqiqi** [comment]
> 1. 中转服务器填写`http://b.com:33009`即可。
> 2. 添加一个【本地文件】挂载，挂载称为readme.md，路径为实际readme路径；添加忽略路径/readme.md，参考[＃88](https://github.com/reruin/sharelist/issues/88)。

老大中转服务器可以使用nginx的https代理吗

**Comment by reruin** [comment]
可以。

**Comment by aofengqiqi** [comment]
> 可以。

感谢老大耐心回复
