### ISSUE TITLE
挂载世纪互联OneDrive好像不成功

### ISSUE THREAD

**Issue by peng4740** [reruin/sharelist#393]
我试了一下，挂载完成实际是Sharepoint

**Comment by reruin** [comment]
截图看一下你的实际操作。

**Comment by peng4740** [comment]
> 截图看一下你的实际操作。

我想重新配置截个图，配置完OneDrive后，发现变为SharePoint无效了(指配置SharePoint实则为OneDrive)，后台重新配置为"/"到前台重新配置登录，都依然是OneDrive而不是SharePoint。是在2月3号使用Docker部署的"reruin/sharelist:lastest"。
配置用的是**OneDrive V2**，我用**OD 世纪互联**配置不成功。

![https://developer-forum-online.cdn.bcebos.com/27662065-f985-4321-9286-aeedb3aa8618.jpg](https://developer-forum-online.cdn.bcebos.com/27662065-f985-4321-9286-aeedb3aa8618.jpg)

![https://developer-forum-online.cdn.bcebos.com/6ac98804-546f-4c0b-8c30-9fee519275b4.jpg](https://developer-forum-online.cdn.bcebos.com/6ac98804-546f-4c0b-8c30-9fee519275b4.jpg)

**Comment by reruin** [comment]
**没有使用自己的ID和机密**，选择Sharepoint挂载，填写站点地址后，挂载成功显示的是 onedrive ？
删除掉挂载，清除缓存后 再试一下。
