### ISSUE TITLE
使用 OneDrive V2 插件如何挂载某个子目录？

### ISSUE THREAD

**Issue by maobowen** [reruin/sharelist#395]
如题，OneDrive API版可以通过`/folder->`前缀来只挂载名为 folder 的子目录，求问用 OneDrive V2 插件或者 Google Drive API 如何做到？

**Comment by reruin** [comment]
OneDrive
1. 成功挂载后，进入后台管理处，修改挂载路径，在**?client_secret**前面加上子目录。例如：实际挂载挂载目录为 abc/123 文件夹。
原始的挂载路径可能如下：
```//00cdbfd5-****-****-****-75e8eddd8fa8.proxy.1612687476353?client_secret=....```
修改为 
```//00cdbfd5-****-****-****-75e8eddd8fa8.proxy.1612687476353/abc/123/?client_secret...```
注意 123后需加  / 
2. 清除缓存，并重启。

GoogleDrive 稍有不同
1. 先获取目录ID ：访问gd官方页面，进到要挂载的目录，链接里**folders/**后面的部分即是目录ID。 ```https://drive.google.com/drive/u/0/folders/*********```。
2. 之后进入后台管理，原始的挂载路径可能如下：
```//xxxxx.apps.googleusercontent.com/root?client_secret=....```
修改为 
```//xxxxx.apps.googleusercontent.com/目录ID?client_secret=....```
3. 清除缓存，并重启

**Comment by maobowen** [comment]
OneDrive 成功了，Google Drive 等过几天再试。非常感谢！
建议加到产品文档里，可能其他用户也有类似需求。
