### ISSUE TITLE
IOS上不能播放视频

### ISSUE THREAD

**Issue by Tiger-zero** [reruin/sharelist#398]
老哥，我在安装完这个之后，安卓打开网页能播放视频，而在苹果手机上播放视频就会提示加载失败。我尝试过切换默认播放器和dplayer但都没有解决ios上网页播放的问题
![image](https://user-images.githubusercontent.com/57404601/107314788-64187b80-6ad0-11eb-9055-2686c0a6157b.png)
![image](https://user-images.githubusercontent.com/57404601/107314819-7b576900-6ad0-11eb-9fcf-20e13a84a9ec.png)
我反代是使用的caddy,
```
echo "https://share.huhushangdian.xyz {
 tls admin@share.huhushangdian.xyz
 proxy / 101.32.46.237:33001 {
    header_upstream Host {host}
    header_upstream X-Real-IP {remote}
    header_upstream X-Forwarded-For {remote}
    header_upstream X-Forwarded-Port {server_port}
    header_upstream X-Forwarded-Proto {scheme}
  }
 log /var/log/caddy.log
 gzip
}" > /usr/local/caddy/Caddyfile
```这是我的配置文件
  下面这是文件链接，老哥可以测试一下：https://share.huhushangdian.xyz/%E5%92%8C%E5%BD%A9%E4%BA%91/%E6%9D%A5%E8%87%AA%E9%93%BE%E6%8E%A5%E5%88%86%E4%BA%AB/%E8%BF%9B%E5%87%BB%E7%9A%84%E5%B7%A8%E4%BA%BA/1/%E8%BF%9B%E5%87%BB%E7%9A%84%E5%B7%A8%E4%BA%BA%E7%AC%AC1%E5%AD%A301.mp4?preview
  麻烦老哥有空的时候，帮忙看一下

**Comment by reruin** [comment]
可能视频编码Safari不支持。

**Comment by Tiger-zero** [comment]
> 可能视频编码Safari不支持。

在ios上用QQ浏览器打开能播放了

**Comment by reruin** [comment]
我下去检测下。ios第三方浏览器都用的ios给的内核，很少有不一致的行为。

**Comment by sbwml** [comment]
是和彩云视频文件元数据无法读取导致iOS & Mac Safari上无法播放。问题不在sharelist，比如你使用天翼云、teambition 等空间，视频播放就无此问题。

**Comment by Tiger-zero** [comment]
> 是和彩云视频文件元数据无法读取导致iOS & Mac Safari上无法播放。问题不在sharelist，比如你使用天翼云、teambition 等空间，视频播放就无此问题。

好呢，是这样嘛
