### ISSUE TITLE
和彩云挂载的网盘提示ip受限重新挂载提示无法获取公钥

### ISSUE THREAD

**Issue by disonwei** [reruin/sharelist#405]
求解 怎么办 
![image](https://user-images.githubusercontent.com/55089487/108028685-2f279e00-7067-11eb-84a9-2699066c8a48.png)

**Comment by disonwei** [comment]
更新到最新版后 获取手机验证码 提示 ip受限   请问怎么办

**Comment by reruin** [comment]
> ip受限

部署在境外？

**Comment by disonwei** [comment]
不是> > ip受限
> 
> 
> 
> 部署在境外？
