### ISSUE TITLE
挂载google drive后下载文件出问题

### ISSUE THREAD

**Issue by twtmactt** [reruin/sharelist#406]
显示如下
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "cannotDownloadAbusiveFile",
    "message": "This file has been identified as malware or spam and cannot be downloaded."
   }
  ],
  "code": 403,
  "message": "This file has been identified as malware or spam and cannot be downloaded."
 }
}

**Comment by reruin** [comment]
更新代码再试试。

**Comment by twtmactt** [comment]
> 更新代码再试试。

更新后可以了
