### ISSUE TITLE
会支持Teambition 项目吗

### ISSUE THREAD

**Issue by carey036** [reruin/sharelist#409]
文件请求url： https://www.teambition.com/api/works?_parentId={文件夹id}&_projectId={项目id}
文件夹请求url : https://www.teambition.com/api/collections?_parentId={文件夹id}&_projectId={项目id}
可选参数: &order=updatedDesc&count=50&page=1&_=1614213363305
请求时需要cookie

**Comment by reruin** [comment]
一直都支持的。你可更新下试试。

**Comment by carey036** [comment]
> 一直都支持的。你可更新下试试。

我是说tb的项目，不是网盘

**Comment by reruin** [comment]
更新后 支持。
