### ISSUE TITLE
Dplayer视频加载失败

### ISSUE THREAD

**Issue by Rainforestwind** [reruin/sharelist#410]
阿里云盘挂载以后，使用dplayer播放视频，视频加载失败

**Comment by koukouxiaoyao** [comment]
也是遇到同样问题，不知道你的解决了没有呢，如何处理的

**Comment by reruin** [comment]
阿里云盘的直链会验证referer，目前的解决方法：
1. 开启中转，并将阿里云的路径添加到**中转目录**中。
2. 使用手机端的 refresh_token，参考 #445 (此方法未证实)。
