### ISSUE TITLE
挂载teambition项目提示error

### ISSUE THREAD

**Issue by yimshing** [reruin/sharelist#411]
Centos7 docker 容器安装的
网盘没问题，就是项目报错，换了几个账号了

Error
Looks like something broke!

        
Error: certificate has expired
    at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:643:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38)

**Comment by luoyuu77** [comment]
阿里云盘也这样，怀疑官方做了限制

**Comment by reruin** [comment]
@yimshing
teambition项目 实测没问题。初始项目 需填写为 类似这样的地址 ```https://www.teambition.com/project/xxxxxx/works/xxxxxx``` 
![image](https://user-images.githubusercontent.com/7403780/109766553-48b51200-7c31-11eb-9ad4-f82279d2cde5.png)

**Comment by yimshing** [comment]
@reruin 我尝试重新搭建了，用的docker，项目的地址也是类似上图的，我甚至把ssl都取消了，但依然绑定失败，错误提示跟之前的一样

**Comment by reruin** [comment]
非docker部署时 有出现此问题吗？

**Comment by yimshing** [comment]
> 非docker部署时 有出现此问题吗？

非docker部署问题不存在，现在我已经改用手动安装那个形式了，体验很好
