### ISSUE TITLE
3月2日晚更新最新版本之后出现的问题

### ISSUE THREAD

**Issue by Cuiyim** [reruin/sharelist#412]
1.文件名多了个小黑点，没有旧版本的好看
![image](https://user-images.githubusercontent.com/51844650/109664268-ec59e000-7ba7-11eb-8bbe-fc26f4d79410.png)
2.上次大佬给的快捷复制链接按钮失效了
![image](https://user-images.githubusercontent.com/51844650/109664357-01cf0a00-7ba8-11eb-9bb5-47d46e83dd4e.png)
![image](https://user-images.githubusercontent.com/51844650/109664426-13b0ad00-7ba8-11eb-9ae5-8d8e600cb103.png)
本来这里有个蓝色的小方块，点一下就会复制当前文件夹的文件链接
3.aliyun drive  文件夹文件索引不全  
![image](https://user-images.githubusercontent.com/51844650/109664777-799d3480-7ba8-11eb-860d-54bec2591273.png)
目录文件有1800+，旧版本是可以都索引出来的，上图所示
新版本如下图：
![image](https://user-images.githubusercontent.com/51844650/109664986-b36e3b00-7ba8-11eb-8c4b-6f7303557467.png)

**Comment by reruin** [comment]
样式问题，刷新下 /style/main.css 页面。
![image](https://user-images.githubusercontent.com/7403780/109765917-7057aa80-7c30-11eb-8607-a3c290999069.png)
![image](https://user-images.githubusercontent.com/7403780/109765947-7cdc0300-7c30-11eb-89cc-0c9a0bd4c201.png)

**Comment by reruin** [comment]
一键复制的脚本如下:
```
<script>
//快捷复制
"use strict";window.jQuery&&!location.pathname.startsWith("/manage")&&$(function(){function e(e,k){var t=!1,c=document.createElement("textarea"),n=document.activeElement;k.appendChild(c),c.value=e,c.focus(),c.setSelectionRange?c.setSelectionRange(0,c.value.length):c.select();try{t=document.execCommand("copy")}catch(e){t=!1}return k.removeChild(c),n.focus(),t}var t=[];if($(".node-list__body").find("a[target='_blank']").each(function(){t.push(location.origin+decodeURIComponent($(this).attr("href").replace(/\?.*/g,"")))}),t.length>0){var c=$('<a><svg class="ic" style="width: 22px;height: 22px;vertical-align: middle;fill: currentColor;overflow: hidden;" viewBox="0 0 1024 1024"><path d="M662.528 255.488c56.166 0 101.734 45.517 101.734 101.734v457.933c0 56.218-45.568 101.735-101.785 101.735H204.544A101.786 101.786 0 0 1 102.81 815.155V357.222c0-56.217 45.568-101.785 101.734-101.785h457.933z m0 61.03H204.493c-20.48 0-37.837 15.258-40.397 35.584l-0.307 5.12v457.933c0 20.48 15.257 37.837 35.635 40.397l5.12 0.307h457.882c20.53 0 37.888-15.257 40.448-35.635l0.256-5.12v-457.83c0-20.532-15.258-37.888-35.584-40.448l-5.12-0.256zM815.104 102.81c56.269 0 101.786 45.568 101.786 101.734v457.933c0 56.217-45.568 101.785-101.735 101.785v-61.081c20.48 0 37.837-15.258 40.397-35.584l0.307-5.12V204.544c0-20.48-15.257-37.837-35.635-40.397l-5.12-0.307h-457.83c-20.532 0-37.888 15.258-40.448 35.635l-0.256 5.12h-61.133c0-56.217 45.568-101.785 101.785-101.785h457.933z"></path></svg></a>');$(".upload-menu").append(c),c.on("click",function(){e(t.join("\n"),c[0]),alert("复制成功 共"+t.length+"条")})}});
</script>
```

**Comment by Cuiyim** [comment]
好奇怪，刷新之后还是有小点点


| |
ins888
|
|
ins888@126.com
|
签名由网易邮箱大师定制
在2021年3月3日 14:57，Ting<notifications@github.com> 写道：

样式问题，刷新下 /style/main.css 页面。

**Comment by Cuiyim** [comment]
样式还是有一点点问题
