### ISSUE TITLE
启用cf wokrer 404了

### ISSUE THREAD

**Issue by fengzhao** [reruin/sharelist#414]
https://sharelist.fengzhao.workers.dev

**Comment by reruin** [comment]
cf wokrer 只用作流量中转，不作为页面代理。

**Comment by fengzhao** [comment]
挂载了gdrive盘，下载报错

![image](https://user-images.githubusercontent.com/6206340/110101743-ec8ff080-7dde-11eb-92f6-b08e8e772b85.png)

**Comment by reruin** [comment]
应该是这个问题 #406，sharelist更新下再试试。
