### ISSUE TITLE
请问webdav连接是直连还是走vps？

### ISSUE THREAD

**Issue by dzhl** [reruin/sharelist#415]
我用下来，感觉像是走vps而不是直连，是这样的吗？

**Comment by reruin** [comment]
走vps，很多客户端不支持跳转直链。

**Comment by dzhl** [comment]
> 走vps，很多客户端不支持跳转直链。

你的意思是客户端本身问题，限制了sharelist只能走vps?

**Comment by reruin** [comment]
是的 为了兼容。后期我考虑下加个webdav配置项。

**Comment by dzhl** [comment]
> 是的 为了兼容。后期我考虑下加个webdav配置项。

期待

**Comment by iso-lib** [comment]
不是走vps吧,,我的vps是5m口香港的,webdav也可以在线看天翼云的电影啊

**Comment by dzhl** [comment]
> 不是走vps吧,,我的vps是5m口香港的,webdav也可以在线看天翼云的电影啊

大佬都明说是走vps了，还能有错
