### ISSUE TITLE
teambition排序问题

### ISSUE THREAD

**Issue by yimshing** [reruin/sharelist#417]
![2021-03-09_210056](https://user-images.githubusercontent.com/19247568/110474419-9abad380-811a-11eb-8987-e3116e87f22f.png)
看了之前的issue说是支持排序了 但是点击上面的文件名 大小 修改时间没任何反应 目前仍是混乱的状态

**Comment by reruin** [comment]
更新后再试试。

**Comment by yimshing** [comment]
> 更新后再试试。

亲测好用，sharelist牛逼
