### ISSUE TITLE
OneDrive V2子目录挂载一段时间后会失效

### ISSUE THREAD

**Issue by H0uzC** [reruin/sharelist#420]
**参照 #395 挂载OneDrive V2的子目录**
过一段时间后已点击保存的子目录挂载会失效，变回根目录挂载

即挂载路径 `.../Path/?client_secret=...` 会变回 `...?client_secret=...`

**Comment by reruin** [comment]
已修复。

**Comment by H0uzC** [comment]
非常感谢！

**Comment by H0uzC** [comment]
路径丢失的问题已经解决了，但是现在会自动添加README.md后缀
由`.../Path/?client_secret=...`变成`.../Path/README.md?client_secret=...`

**Comment by hzzhy1987** [comment]
> 路径丢失的问题已经解决了，但是现在会出现当根目录存在README.md文件时会自动添加README.md后缀的情况
> 由`.../Path/?client_secret=...`变成`.../Path/README.md?client_secret=...`

我也遇到了这个情况
