### ISSUE TITLE
请问挂载阿里云网盘时该如何选择挂载的目录

### ISSUE THREAD

**Issue by aoyouer** [reruin/sharelist#423]
当前挂载阿里云网盘的时候显示的是网盘中所有的文件，请问有没有办法指定只显示一个目录的文件

**Comment by reruin** [comment]
填写初始地址。
参考 https://reruin.github.io/sharelist/docs/#/zh-cn/plugins/teambition

**Comment by reruin** [comment]
稍后加上。

**Comment by maomiblog** [comment]
同请

**Comment by maomiblog** [comment]
同求方法

**Comment by cooluc** [comment]
> 稍后加上。

這個功能似乎已被遺忘，還望作者能儘快增加自定義目錄支持！

**Comment by reruin** [comment]
@cooluc 已完成。最近忙其他事了。

**Comment by cooluc** [comment]
> @cooluc 已完成。最近忙其他事了。

❤最爲期待的功能終於實現了！感謝開發者的付出！！
