### ISSUE TITLE
创建多级目录

### ISSUE THREAD

**Issue by Tasle** [reruin/sharelist#426]
请问可以自己创建多级目录后再挂载其他云盘吗？
比如
/name1/name2  
/name1/name3

在name2下挂载onedrive 
在name3下挂载gd

**Comment by reruin** [comment]
可以用下述方式实现
1. 先将od挂载到根目录，挂载名称为 /a
2. 创建使用 ShareListDrive,  content 为 /a 的挂载内容
```
[{"name":"OneDriveLink.d.ln","content":"onedrive://xxxx"}]
```

**Comment by Tasle** [comment]
> 可以用下述方式实现
> 
> 1. 先将od挂载到根目录，挂载名称为 /a
> 2. 创建使用 ShareListDrive,  content 为 /a 的挂载内容
> 
> ```
> [{"name":"OneDriveLink.d.ln","content":"onedrive://xxxx"}]
> ```

非常感谢。现在又遇到一个问题，用OneDrive v2挂载两个账号的时候，如果是用的自己的api，那两个最后点开会指向同一个。如果用的是自带的api或者每个账号建立个独立的api挂载，一开始可以用，过一会变成点击文件夹的时候随机下载一个文件，试了很多次都是这样。举个例子 
onedrive A挂载在 OD1路径下 ，onedrive B挂载在OD2路径下。刚挂载完OD1和OD2能点开没问题，过一会点击OD1就变成直接下载OD1目录下的某个文件。

**Comment by reruin** [comment]
更新下代码，清除缓存 试试。

**Comment by Tasle** [comment]
> 更新下代码，清除缓存 试试。

更新后测试依旧这样，可以看下https://drive.taslee.com/
挂载的是这两个网盘，目录应该是这样的
![od.png](https://i.loli.net/2021/03/16/aoTEsrO7GnijNVA.png)
![od2.png](https://i.loli.net/2021/03/16/aenFB1NQhtY9DZj.png)
