### ISSUE TITLE
希望sharelist允許定義阿里雲盤共享目錄

### ISSUE THREAD

**Issue by cooluc** [reruin/sharelist#429]
目前阿里雲盤只能夠把根目錄作爲共享對象，請問能否像Teambition那樣由用戶選擇指定目錄進行文件共享呢？

感謝開源項目的所有貢獻！

**Comment by reruin** [comment]
已经有相关提议 #423，近期会更新。

**Comment by cooluc** [comment]
> 已经有相关提议 #423，近期会更新。

好的，非常期待！
