### ISSUE TITLE
关于OneDrive V2 挂载目录变化

### ISSUE THREAD

**Issue by WASD8102** [reruin/sharelist#431]
使用**OneDrive V2** 挂载sharepoint或onedrive根目录，一段时间后**挂载目录会发生变化**，会变成挂载子目录或者为子目录下的文件。

使用的是**默认的应用ID和机密**挂载（不知道为啥自己的会出错），**国际版和世纪互联**均出现这种情况，由于世纪互联根目录下没有子目录和视频文件，也不常访问，目前挂载未改变。

一般我是使用**nplayer挂载webdav**观看，**目录变化会根据我的观看变化**，具体表现为挂载视频文件所在的目录或者我所观看的视频文件。

**Comment by Tasle** [comment]
同，我也是这样

**Comment by reruin** [comment]
更新下代码 试试。近期修复过一个子目录挂载的问题。

**Comment by hzzhy1987** [comment]
> 更新下代码 试试。近期修复过一个子目录挂载的问题。

heroku上部署了还是有这种情况啊，是不是没更新heroku

**Comment by WASD8102** [comment]
> 更新下代码 试试。近期修复过一个子目录挂载的问题。

更新完了还是会跳，好像和我登录后台有关，我一登陆后台他就变了

我这这是挂载在33005端口，只了修改app.js里的端口，然后重启

**Comment by cloudflyz** [comment]
同样出现这个问题，使用onedrive v2 共享根目录文件，结果2小时后出现变成了其他非根目录

**Comment by ferocknew** [comment]
同样出现这个问题，另，如何查看当前应用版本号？

**Comment by hejiadong0608** [comment]
@reruin 
我也遇到了相同的情况，最新代码，使用自己的ID挂在世纪互联，挂在的目录自动变成了子目录。

**Comment by ferocknew** [comment]
暂时的解决办法是：

1. 定时任务 cp config.json 覆盖错误的配置
2. 通过api 重启应用
3. 通过api 清除缓存

麻烦作者关注一下这个问题

**Comment by reruin** [comment]
进度会统一在 #476 下回复。
