### ISSUE TITLE
heroku 部署这个必须要验证信用卡？

### ISSUE THREAD

**Issue by hzzhy1987** [reruin/sharelist#435]
部署时候报错，提示要验证信用卡啊

**Comment by jizizr** [comment]
您是不是已经在heroku上部署了5个app，heroku的免费用户最多只能创建5个app，请删除掉一些无用的app后重试

**Comment by hzzhy1987** [comment]
> 您是不是已经在heroku上部署了5个app，heroku的免费用户最多只能创建5个app，请删除掉一些无用的app后重试

部署过，但是都删了，最后是重置了账号解决了。
