### ISSUE TITLE
主题扩展支持的建议

### ISSUE THREAD

**Issue by sbwml** [reruin/sharelist#436]
目前最新源码已经支持自主添加主题样式
但是主题中的 [fileType](https://github.com/reruin/sharelist/blob/master/theme/default/script/upload.js#L1) 似乎并不生效，如果单纯靠主题目前无法添加更多的文件类型 icon。文件类型依然取决于 https://github.com/reruin/sharelist/blob/master/app/utils/base.js#L43

希望能把文件类型迁移到主题中实现，这样方便扩展更多的文件类型图标。

**Comment by sbwml** [comment]
另一建议，希望能把 webp 格式作为 [preview.media.js](https://github.com/reruin/sharelist/blob/master/plugins/preview.media.js#L130) 媒体预览，目前主流浏览器均支持 webp 图片阅读，Safari 目前也默认支持 webp 图像格式浏览。

**Comment by reruin** [comment]
1. 可以自行通过文件后缀判断类型。
2. 后期考虑将 预览交由主题来实现，后端不再保留预览处理。
