### ISSUE TITLE
加密文件夹的网站标题

### ISSUE THREAD

**Issue by 404gods** [reruin/sharelist#438]
发现个小问题：即使已经自定义了网站标题，但进入加密文件夹的登陆界面，网站标题又会变成默认的“ShareList”
![捕获](https://user-images.githubusercontent.com/50573302/112632313-eb4c6380-8e72-11eb-81da-57b257ae9195.PNG)

**Comment by cloudflyz** [comment]
是的 问题复现

**Comment by liumingye** [comment]
theme\default\view\auth.pug
第9行
`      a.home(href='/') ShareList`
改成
`      a.home(href='/')= _config_('title')`
