### ISSUE TITLE
关于Onedrive Api的问题

### ISSUE THREAD

**Issue by gitLinan** [reruin/sharelist#44]
你好，如题当我使用最新版代码部署完成后，访问站点
![image](https://user-images.githubusercontent.com/33097694/59427740-f2c18a80-8e0d-11e9-8c87-81498217affb.png)
当我正常访问到以上页面的时候，点击访问此链接，就会收到以下报错
![image](https://user-images.githubusercontent.com/33097694/59427792-11278600-8e0e-11e9-9831-d86de501e03c.png)

请问如何解决？

首先，我的OD账号是有注册应用ID权限的，如下 是我手动注册的
![image](https://user-images.githubusercontent.com/33097694/59428352-8f385c80-8e0f-11e9-899d-9ce8b5e5600f.png)
但是页面跳转的链接注册的时候报错，提示应用程序ID的URI不合法！

**Comment by reruin** [comment]
od对回调地址有要求，必须是安全地址。例如 https://xxx.com。  
稍后会更新一个代理地址用作 中转。

**Comment by reruin** [comment]
已启用中转处理，可试一下，

**Comment by wekingchen** [comment]
Onedrive API没问题了，出现127.0.0.1的地址时，把127.0.0.1:XXXX替换成自己的网址就可以了，谢谢大大：）

希望Google Driver的API能早日搞定！
