### ISSUE TITLE
阿里云盘列表失效

### ISSUE THREAD

**Issue by cuddykko** [reruin/sharelist#445]
你好，阿里云盘列表已失效，无法下载，可能是官方开启了防盗链，建议更改reffer

**Comment by toolor** [comment]
你的问题解决了嘛？具体怎么设置？

**Comment by cooluc** [comment]
修复阿里云盘 https://github.com/reruin/sharelist/pull/446
二进制：https://media.cooluc.com/source/Sharelist-prebuilt

**Comment by reruin** [comment]
已修复。

**Comment by MasterOfStar** [comment]
阿里云盘能获取列表，无法下载文件

**Comment by reruin** [comment]
@MasterOfStar 阿里系的云盘对下载的策略是在变化的，有时候需要校验 referer，可在【后台管理】处开启【中转】，并将 对应挂载目录 填入【中转路径】中。

**Comment by Gyx200911** [comment]
> referer

有空更新下文档呗emm 现在卡在设置中转这 好像设置中转了还是没用
但是用其他方式获取的reftoken可以正常下载文件
但是手机端的reftoken还是没法识别

**Comment by reruin** [comment]
@Gyx200911 方便描述下手机端 refresh_token  的获取过程么。

**Comment by Gyx200911** [comment]
> @Gyx200911 方便描述下手机端 refresh_token 的获取过程么。

我看一下怎么解释这个问题 隔壁alist那边说 手机reftoken是不验证防盗链的
大概是如图
`https://i.loli.net/2021/05/20/omQRfZg8bLsKM2c.jpg`
APP:https://pan.iwso.cn/s/0QOsq

**Comment by sbwml** [comment]
> @Gyx200911 方便描述下手机端 refresh_token 的获取过程么。

https://media.cooluc.com/source/sharelist/%E5%AE%98%E6%96%B9%E6%96%87%E6%A1%A3/%E6%8C%82%E8%BD%BD%E6%BA%90-Aliyun%20Drive

**Comment by Gyx200911** [comment]
> > @Gyx200911 方便描述下手机端 refresh_token 的获取过程么。
> 
> https://media.cooluc.com/source/sharelist/%E5%AE%98%E6%96%B9%E6%96%87%E6%A1%A3/%E6%8C%82%E8%BD%BD%E6%BA%90-Aliyun%20Drive

你应该回复作者的 有一说一我这边手机的reftoken 提示token有误就很奇怪

**Comment by sbwml** [comment]
> > > @Gyx200911 方便描述下手机端 refresh_token 的获取过程么。
> > 
> > 
> > https://media.cooluc.com/source/sharelist/%E5%AE%98%E6%96%B9%E6%96%87%E6%A1%A3/%E6%8C%82%E8%BD%BD%E6%BA%90-Aliyun%20Drive
> 
> 你应该回复作者的 有一说一我这边手机的reftoken 提示token有误就很奇怪

好像是点错回复对象。手机的token肯定是没问题的，不建议使用app辅助获取。因为 安卓阿里盘客户端会在目录产生很多个log文件，不确定通过辅助app获取的是否为最新日期的，如果这个app没有根据最新时间生成的日志文件读取token，它自然是提示token 有误。

**Comment by Gyx200911** [comment]
> > > > @Gyx200911 方便描述下手机端 refresh_token 的获取过程么。
> > > 
> > > 
> > > https://media.cooluc.com/source/sharelist/%E5%AE%98%E6%96%B9%E6%96%87%E6%A1%A3/%E6%8C%82%E8%BD%BD%E6%BA%90-Aliyun%20Drive
> > 
> > 
> > 你应该回复作者的 有一说一我这边手机的reftoken 提示token有误就很奇怪
> 
> 好像是点错回复对象。手机的token肯定是没问题的，不建议使用app辅助获取。因为 安卓阿里盘客户端会在目录产生很多个log文件，不确定通过辅助app获取的是否为最新日期的，如果这个app没有根据最新时间生成的日志文件读取token，它自然是提示token 有误。

确认app辅助获取的没问题 我重登后能正常取到上次登录时间 应该是其他蜜汁情况
