### ISSUE TITLE
PDF预览报错

### ISSUE THREAD

**Issue by api81244390** [reruin/sharelist#447]
PDF.js v2.8.320 (build: ca7f54682)
Message: file origin does not match viewer's

**Comment by reruin** [comment]
请先更新下sharelist。

pdf.js插件有升级。

**Comment by api81244390** [comment]
更新完了仍然报错：
An error occurred while loading the PDF.Less InformationClose
详情：
PDF.js v2.9.79 (build: ae48d0758)
Message: file origin does not match viewer's

**Comment by api81244390** [comment]
> 请先更新下sharelist。
> 
> pdf.js插件有升级。

更新完了仍然报错：
An error occurred while loading the PDF.Less InformationClose
详情：
PDF.js v2.9.79 (build: ae48d0758)
Message: file origin does not match viewer's

**Comment by Konveksa** [comment]
使用最新版本，有同样问题。
PDF.js v2.9.79 (build: ae48d0758)
信息：file origin does not match viewer's
