### ISSUE TITLE
proxy_set_header Host $http_host;

### ISSUE THREAD

**Issue by lsyyktv** [reruin/sharelist#45]
刚刚找到反向代理的配置文件,里面貌似已经有这条代码了
可是API申请还是报以下错误

暂时出现问题
应用程序 ID URI 必须是有效的 URI。
![新建位图图像 (2)](https://user-images.githubusercontent.com/39065858/59984181-edf4a600-9659-11e9-9d18-300885caad47.jpg)

**Comment by lsyyktv** [comment]
![新建位图图像 (2)](https://user-images.githubusercontent.com/39065858/59984087-f39dbc00-9658-11e9-8081-20951ce0cc82.jpg)

刚刚找到反向代理的配置文件,里面貌似已经有这条代码了
可是API申请还是报以下错误

暂时出现问题
应用程序 ID URI 必须是有效的 URI。

**Comment by reruin** [comment]
使用以下配置试试  
```
        proxy_set_header Host  $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
```

**Comment by lsyyktv** [comment]
按照你的配置,可以通过验证了,谢谢!
可是验证完了之后出现这个错误
![新建位图图像 (2)](https://user-images.githubusercontent.com/39065858/60000258-6b3e0c00-9696-11e9-803f-5015f32d57b9.jpg)

**Comment by reruin** [comment]
方便把 cache/config.json 内容私发与我么

**Comment by lsyyktv** [comment]
已经发到你邮箱了

**Comment by reruin** [comment]
标识id有误，应按照 ```OneDrive路径->应用ID|应用机钥|回调地址|refresh_token```  
此处的```OneDrive路径```不是id，而是实际文件路径。  
修改后的配置文件，见回复邮件附件。

**Comment by lsyyktv** [comment]
刚开始是填写的分享链接里面的ID,原来是要填写ondrive的真实路径...
现在已经没有问题了..感谢大大耐心的指教
