### ISSUE TITLE
阿里云报错

### ISSUE THREAD

**Issue by yuehun** [reruin/sharelist#450]
![微信截图_20210406092600](https://user-images.githubusercontent.com/24507941/113645792-255f0600-96ba-11eb-846b-e7f6f6a8fcf8.png)
隔几天就这样了，重新配置一下就好了，是有时效的嘛

**Comment by wjpang69** [comment]
我也出现了这个问题

**Comment by wjpang69** [comment]
我感觉是因为每次更新access_token的时候没有更新refresh_token 实际上refresh_token也会过期的
