### ISSUE TITLE
更新heroku部署

### ISSUE THREAD

**Issue by 1299172402** [reruin/sharelist#452]
### 1. 登入heroku账号，进入控制台
![Screenshot_20210406_155309](https://user-images.githubusercontent.com/29673994/113677583-522e1000-96f0-11eb-8f83-f6d3e9307a34.jpg)

### 2. 进入你创建的应用
![Screenshot_20210406_155615](https://user-images.githubusercontent.com/29673994/113677889-a46f3100-96f0-11eb-8b6a-461681ee4a59.jpg)

### 3. 如图所示点击，Connect to Github之后跳转到github输入密码并授权
![Screenshot_20210406_155737](https://user-images.githubusercontent.com/29673994/113678084-d4b6cf80-96f0-11eb-8784-867ad3963d5e.jpg)

### 4. 返回github，fork此仓库 https://github.com/reruin/sharelist-heroku
**注意*不是*https://github.com/reruin/sharelist 仓库**
### 5. 如图，搜索并链接到此仓库。
![Screenshot_20210406_160320](https://user-images.githubusercontent.com/29673994/113679055-e9479780-96f1-11eb-88a2-0b3b273b5737.jpg)

### 6. 单击Deploy Branch，等待其完成即可
![Screenshot_20210406_160727](https://user-images.githubusercontent.com/29673994/113679859-cff31b00-96f2-11eb-8a8c-c2391e6b08b8.jpg)

**Comment by Dragon-son** [comment]
没有heroku.yml文件

**Comment by 1299172402** [comment]
## 注意fork和链接的是 https://github.com/reruin/sharelist-heroku 仓库

而不是当前https://github.com/reruin/sharelist 仓库

如果你提示的是`没有heroku.yml文件`的话

**Comment by sztuxp** [comment]
出错：
-----> Building on the Heroku-20 stack
-----> Determining which buildpack to use for this app
 !     No default language could be detected for this app.
			HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.
			See https://devcenter.heroku.com/articles/buildpacks
 !     Push failed

**Comment by sztuxp** [comment]
直接fork后，在github点上一键部署可以成功
