### ISSUE TITLE
添加多个天翼云文件夹冲突

### ISSUE THREAD

**Issue by info-CH** [reruin/sharelist#454]
添加多个天翼云文件夹后是不是文件夹id冲突。
比如添加文件夹A/B/C；
时不时的A的文件夹ID路径会变成C的ID路径。后台有过清理缓存

**Comment by info-CH** [comment]
无人遇到？

**Comment by EearlyDew** [comment]
有，我也遇到了，添加A文件和B文件的路径保存后，过了一会后刷新一下它自己变成B文件的路径不知道是不是冲突，主页的A文件B文件正常来说A文件是显示A文件里的但是打开后会变成B文件里的内容B文件却没有事路径是正常的，打开后台原来的A文件夹的路径变成了B文件夹的路径，重启和清理缓存过会后有又重演了，无奈只能先用一个文件等修了

**Comment by info-CH** [comment]
> 有，我也遇到了，添加A文件和B文件的路径保存后，过了一会后刷新一下它自己变成B文件的路径不知道是不是冲突，主页的A文件B文件正常来说A文件是显示A文件里的但是打开后会变成B文件里的内容B文件却没有事路径是正常的，打开后台原来的A文件夹的路径变成了B文件夹的路径，重启和清理缓存过会后有又重演了，无奈只能先用一个文件等修了
> 
> Yes, I also encountered, add a file and B file path after saving, after a while to refresh itself into a B file path do not know if it is conflict, a file on the home page, B file, normally, a file shows what’s in a file, but when you open it, it becomes what’s in B file, and B file doesn’t have a problem, open the background of the original a folder path into the B folder path, restart and clean up the cache after the meeting and again, but can only use a file and so on

是的、我遇到过很多次 每次前台进去都是从A进到B里面 后台进去一看就是A的路径变成了B的 不知道怎么回事、应该是个bug。
