### ISSUE TITLE
阿里云盘出现故障

### ISSUE THREAD

**Issue by toolor** [reruin/sharelist#455]
文件夹可以正常被访问
但是文件无法访问
出现一下错误
InvalidArgument At least one of AdditionalHeaders is not in request headers. 60701D337E6CAA3832433B47 bj29.cn-beijing.data.alicloudccp.com

**Comment by 1299172402** [comment]
发生同样的错误。  
无法在线预览视频或者查看readme.md
> `InvalidArgument` At least one of AdditionalHeaders is not in request headers. 60702F31F3E0F83134A8A12B bj29.cn-beijing.data.alicloudccp.com

**Comment by yimshing** [comment]
一样的问题

**Comment by Netskao** [comment]
在浏览器网页登录，登录时有个https://passport.aliyundrive.com/newlogin/sms/login.do，返回值有个bizExt，base64解码后最底下有个refresh_token，用那个token重新引导一次暂时恢复

**Comment by Netskao** [comment]
在浏览器网页登录，登录时有个https://passport.aliyundrive.com/newlogin/sms/login.do
返回值json中有个bizExt，base64解码后最底下有个refresh_token，用那个refresh_token重新引导一次暂时恢复

**Comment by 1299172402** [comment]
@Netskao 我尝试之后仍然是不行，不知道是什么问题。

**Comment by toolor** [comment]
web端token已失效，/sdcard/Android/data/com.alicloud.databox/files/logs/trace/阿里云id/yunpan/ 
文件夹log文件，搜索一下refreshToken，里面的refresh_token可以用，亲测成功！

**Comment by CialloAlone** [comment]
> web端token已失效，/sdcard/Android/data/com.alicloud.databox/files/logs/trace/阿里云id/yunpan/
> 文件夹log文件，搜索一下refreshToken，里面的refresh_token可以用，亲测成功！

@toolor 在log中并没有搜索到具体的refresh Token值

**Comment by CialloAlone** [comment]
已解决，通过网页登陆，在https://auth.aliyundrive.com获取的refrensh Token暂时可用

**Comment by EXStevens** [comment]
https://passport.aliyundrive.com/newlogin/sms/login.do
https://auth.aliyundrive.com
网站都已经不可用

重新获取的refresh_token无效

**Comment by EXStevens** [comment]
> web端token已失效，/sdcard/Android/data/com.alicloud.databox/files/logs/trace/阿里云id/yunpan/
> 文件夹log文件，搜索一下refreshToken，里面的refresh_token可以用，亲测成功！

refreshToken有多个，均不可用
400
{"code":"InvalidParameter.RefreshToken","message":"The input parameter refresh_token is not valid. Please refer to document."}
