### ISSUE TITLE
设置密码访问无效

### ISSUE THREAD

**Issue by lsyyktv** [reruin/sharelist#46]
https://sl.lsyy.tk/gz
用户名密码都是123456
输入用户名密码,没有任何反应

**Comment by reruin** [comment]
拉新代码试一下。

**Comment by lsyyktv** [comment]
不好意思,不知道去哪里找新代码
我用的就是你提供的代码
type: basic
data:
  - 123456:123456

**Comment by reruin** [comment]
就是现在库里的代码，重新拉起部署下。先前有bug修复。

**Comment by lsyyktv** [comment]
重新部署后没有问题了,谢谢及时修复
