### ISSUE TITLE
虚拟路径 下拉显示空白

### ISSUE THREAD

**Issue by GeekMakerSun** [reruin/sharelist#460]
![图像 3](https://user-images.githubusercontent.com/20056211/114381159-645ef100-9bbd-11eb-889b-bfa794b077c2.jpg)

**Comment by reruin** [comment]
没有读取到插件？ 你用的是什么环境？

**Comment by GeekMakerSun** [comment]
> 没有读取到插件？ 你用的是什么环境？

可以了
