### ISSUE TITLE
[功能请求]天翼家庭云-账号多家庭问题

### ISSUE THREAD

**Issue by MasterOfStar** [reruin/sharelist#465]
天翼家庭云，同一天翼账号可加入多个家庭，此时默认只会加入其中一个家庭，退出该家庭后再次挂载方可挂载另一家庭。
建议添加允许自选家庭ID的功能

**Comment by reruin** [comment]
此功能 因缺少测试条件无法进一步开发。

**Comment by MasterOfStar** [comment]
closed
