### ISSUE TITLE
[错误反馈]天翼云设置允许播放flv视频时，出现跨域问题

### ISSUE THREAD

**Issue by Youwenqwq** [reruin/sharelist#466]
`…… has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
如上，在使用dplayer播放flv文件时，由于跨域问题导致视频无法加载播放

**Comment by reruin** [comment]
请发一下链接，测试没发现跨域问题。

**Comment by Youwenqwq** [comment]
> 请发一下链接，测试没发现跨域问题。

https://dl.welain.com/CT/%E6%96%87%E8%B1%AA%E9%87%8E%E7%8A%AC%20%E7%AC%AC%E4%B8%89%E5%AD%A3%20Bilibili%E6%BA%90-1080P%2B/

前几天在学校，没来得及回复，看一下

**Comment by reruin** [comment]
个人猜测：DPlayer 依赖 flv.js 解析播放flv文件，文件fetch到本地处理时，触发跨域。
解决方法：开启中转，将flv 那个文件夹路径加入 **中转路径**中。

**Comment by Youwenqwq** [comment]
> 个人猜测：DPlayer 依赖 flv.js 解析播放flv文件，文件fetch到本地处理时，触发跨域。
> 解决方法：开启中转，将flv 那个文件夹路径加入 **中转路径**中。

好的，谢谢啦😄
