### ISSUE TITLE
请问把清理缓存添加到宝塔定时任务要用什么指令

### ISSUE THREAD

**Issue by lsyyktv** [reruin/sharelist#47]
请问把清理缓存添加到宝塔定时任务要用什么指令

**Comment by reruin** [comment]
缓存文件位于 ./cache/db.json 
定时清理即可。

**Comment by lsyyktv** [comment]
https://github.com/reruin/sharelist/issues/2
我和他的情况一样,删除db.json没有效果
如果用curl  --data "a=clear_cache" "http://localhost:33001/manage/:token"
会提示not found

**Comment by reruin** [comment]
由于较新版本的后台管理已取消token验证的方式，因而原先清除的方式已无效。  
请等待修复。

**Comment by reruin** [comment]
已更新。请注意url路径以及端口。  
 ```curl --data "a=clear_cache" "http://localhost:33001/manage/api/:token"```

**Comment by lsyyktv** [comment]
重新部署后可以了,谢谢
