### ISSUE TITLE
后台登录不了

### ISSUE THREAD

**Issue by abu3d** [reruin/sharelist#474]
口令什么的，都是对的，就是登录不进去！大佬可以帮忙看看啊！

**Comment by BeUnhappy** [comment]
![image](https://user-images.githubusercontent.com/45932017/115502440-846e6e80-a2a7-11eb-992e-3f12e3f6b717.png)

如果是密码不知道的话，可以从源码查看你的后台token，其次，图片也没一张，提示也没有说明，帮你看不了

**Comment by reruin** [comment]
最好提供一下具体的信息，比如截图。

**Comment by abu3d** [comment]
就是点击没任何反应，
密码知道在conifg.json可以查看，但是不知道咋的，点击没任何反应！
输入正确的口令后，点登录 并没进入后台管理，昨天晚上后来可以进的，但是无法保存后台设置的内容！今天又进不去了！
进不去后台，自动打开一个新的登录窗口！

**Comment by abu3d** [comment]
> 最好提供一下具体的信息，比如截图。

提示一个S什么的单词，太快，没办法截图，
就是点击没任何反应，
密码知道在conifg.json可以查看，但是不知道咋的，点击没任何反应！
输入正确的口令后，点登录 并没进入后台管理，昨天晚上后来可以进的，但是无法保存后台设置的内容！今天又进不去了！
进不去后台，自动打开一个新的登录窗口！

**Comment by abu3d** [comment]
> 最好提供一下具体的信息，比如截图。

![image](https://user-images.githubusercontent.com/35095551/115548910-9b7a8400-a2da-11eb-987b-1d6578c69371.png)
这个日志可以不？

**Comment by abu3d** [comment]
现在又可以登录了，但是无法修改后台配置，不知道什么情况！
![image](https://user-images.githubusercontent.com/35095551/115555726-6b36e380-a2e2-11eb-93fe-5e3e7db6e5d3.png)

**Comment by BeUnhappy** [comment]
控制台看下返回的数据

**Comment by reruin** [comment]
@abu3d 有链接么，发出来看下。
