### ISSUE TITLE
请问部署在heroku上，能用cf中转吗？

### ISSUE THREAD

**Issue by sztuxp** [reruin/sharelist#478]
我用一键部署到heroku后，cf中转是403

**Comment by reruin** [comment]
检查下 TOKEN 和 HOST 填写是否正确。

**Comment by GreenTeodoro839** [comment]
套cdn？没信用卡验证的账户没法绑定自己的域名

**Comment by sztuxp** [comment]
token 是管理密码，HOST也没问题，为了怕heroku休眠引起，对原连接做了刷新处理

**Comment by sztuxp** [comment]
是不是heroku一键部署，没有安装nginx之类引起的？

**Comment by yoval** [comment]
cf中转指的是下载中转，用的是<http://cdn.bizha.gq/cloudflareworks/sharelist_proxy.js> 不能直接访问。

cf反代用的是指的是更换域名，用的是<http://cdn.bizha.gq/cloudflareworks/heroku_sharelist.js> 可以直接访问。

demo:<https://share.bizha.ml/>

用的双 herku + Cloudfare Works 。

**Comment by sztuxp** [comment]
补充一下，我挂载的GOOGLE DRIVE的团队盘，cf 的work代码是 https://github.com/reruin/sharelist/blob/master/proxy/cf-worker.js

**Comment by sztuxp** [comment]
> cf中转指的是下载中转，用的是https://cdn.bizha.gq/cloudflareworks/sharelist_proxy.js 不能直接访问。
> 
> cf反代用的是指的是更换域名，用的是https://cdn.bizha.gq/cloudflareworks/heroku_sharelist.js 可以直接访问。
> 
> demo:https://share.bizha.ml/
> 
> 用的双 herku + Cloudfare Works反代 。

用你的反代，第二种，可以访问了
