### ISSUE TITLE
目录加密可以跳过

### ISSUE THREAD

**Issue by lsyyktv** [reruin/sharelist#48]
在主目录添加.passwd加密后，子目录“TERA”，通过 http://域名/TERA 依然可以不用密码进入，有没有办法让访问者无法跳过密码呢?

**Comment by reruin** [comment]
主要是两个问题。
1. 多个父级目录使用不同的密码时，如何显示界面。
2. 实时校验所有父级的passwd 使得缓存变得没有意义。

所以现在看到的目录加密只是个简单的功能。

由于父级目录的
