### ISSUE TITLE
怎么更新？

### ISSUE THREAD

**Issue by RbClimber** [reruin/sharelist#49]
how to update

**Comment by reruin** [comment]
先更新代码```git pull origin master```  ，之后 bash update.sh

**Comment by lsyyktv** [comment]
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

**Comment by reruin** [comment]
下载 https://github.com/reruin/sharelist/blob/master/update.sh 到 share list 目录，然后执行 bash update.sh
