### ISSUE TITLE
【BUG】最新版挂载teambiton项目报错

### ISSUE THREAD

**Issue by gimgoo** [reruin/sharelist#496]
如题，已升级到最新版，挂载teambition最新版报错。我已经挂载了teambiton网盘里的一个文件夹，想着再挂载一个项目试一下，发现挂载不了。总是报错，有显示错误500

**Comment by reruin** [comment]
请留意挂载项目时 需填写**初始地址**:
```
https://www.teambition.com/project/xxxxxx/works/xxxxxx
```
