### ISSUE TITLE
docker  部署错误500

### ISSUE THREAD

**Issue by bbhxwl** [reruin/sharelist#498]
Error
Looks like something broke!

        
Error: read ECONNRESET
    at TLSWrap.onread (net.js:622:25)

**Comment by bbhxwl** [comment]
解决了，不过不会上传呢。

**Comment by reruin** [comment]
上传还未完全支持。

**Comment by itttttta** [comment]
@bbhxwl  这个问题怎么解决的，我发现用户量打的时候就会出现
