### ISSUE TITLE
阿里云盘挂载后存放的视频大于500M无法在手机进行播放

### ISSUE THREAD

**Issue by qingfengjiang** [reruin/sharelist#501]
RT，请问有解决办法吗

**Comment by reruin** [comment]
能否给个 500M 的视频文件地址，我复测下。

**Comment by qingfengjiang** [comment]
> 能否给个 500M 的视频文件地址，我复测下。

https://pan.woriqq.com/%E5%BD%B1%E8%A7%86%E6%94%B6%E8%97%8F/%E5%8A%A8%E6%BC%AB/%E3%80%8A%E5%92%92%E6%9C%AF%E5%9B%9E%E6%88%98%E3%80%8B/%E5%92%92%E6%9C%AF%E5%9B%9E%E6%88%98%E7%AC%AC07%E9%9B%86.mp4?preview

**Comment by reruin** [comment]
有试过原生播放器吗？

**Comment by qingfengjiang** [comment]
> 有试过原生播放器吗？

刚才试了一下，也是不行

**Comment by reruin** [comment]
明天白天我再测一下。

**Comment by qingfengjiang** [comment]
> 明天白天我再测一下。

非常感谢，辛苦了

**Comment by reruin** [comment]
是否使用了手机端的 refresh_token ?

**Comment by reruin** [comment]
可能原因：从阿里云盘请求大于500M的文件时，返回的Content-type会设置为application/oct-stream，Safari在播放视频文件时会综合判断文件后缀以及Content-type类型。

测试过程：
content-type|连接后缀|结果|
| ---- | ---- | ---- |
|application/oct-stream|.mp4|正常|
|application/oct-stream|-|无法播放|
|video/mp4|-|正常|
