### ISSUE TITLE
阿里云盘

### ISSUE THREAD

**Issue by 1361217459** [reruin/sharelist#504]
挂载阿里云盘之后下载不了

**Comment by 1361217459** [comment]
但是teambiton挂载可以下载

**Comment by 1361217459** [comment]
https://clpan.herokuapp.com/%E4%B8%AA%E4%BA%BA%E7%9B%98(%E6%97%A0%E6%B3%95%E4%BD%BF%E7%94%A8)/%E6%B8%B8%E6%88%8F/%E6%B8%B8%E6%88%8F/%E4%B8%8D%E5%8F%8A%E4%BD%A0%E4%B8%80%E7%AC%91.apk

**Comment by cooluc** [comment]
裝載阿里雲網盤，需要使用移動客戶端令牌才能使其正常工作。具體方法可以參考此鏈接：
https://media.cooluc.com/source/sharelist/%E5%AE%98%E6%96%B9%E6%96%87%E6%A1%A3/%E6%8C%82%E8%BD%BD%E6%BA%90-Aliyun%20Drive
