### ISSUE TITLE
Webdav 加密方式？

### ISSUE THREAD

**Issue by at2008** [reruin/sharelist#505]
请教：
1. Webdav加密方式，Basic？ Digest？
2. Webdav方式，可以下载文件吗？

我这遇到问题，无法下载图片，不知道是加密方式的问题，还是不支持？

**Comment by reruin** [comment]
1. basic，使用admin/后台token 做验证，忽略层级密码(.passed形式)。
2. 可以。

**Comment by at2008** [comment]
> 1. basic，使用admin/后台token 做验证，忽略层级密码(.passwd形式)。
> 2. 可以。

多谢回复，我再测试一下
