### ISSUE TITLE
Sharelist 二進制程序 & Office、PDF 文檔閲讀支援

### ISSUE THREAD

**Issue by cooluc** [reruin/sharelist#507]
### 程序地址：[https://media.cooluc.com/source/sharelist](https://media.cooluc.com/source/sharelist)

Office 文檔閲讀説明：Office 文檔閲讀采用Microsoft 365 网页版接口，支援 **Word、Excel、PowerPoint**在綫閲讀，但由於 Office Online 工作是：**Office Online接口 -> Office Online加載Office檔案 ->转码内容回傳**  方式實現，所以你的sharelist **必須部署在公網IP**上并且已绑定**域名**。否則將無法正常在綫閲讀文檔内容。

PDF 閲覽説明：PDF 閲覽預覽采用 [**PDF.js v2.7.570**](https://mozilla.github.io/pdf.js/getting_started/#download) 工具實現。無論你的sharelist 是否部署在公網IP，它都能正確閲讀PDF内容，因爲它的一切工作都在瀏覽器中實現。

### 效果演示地址：[https://test.cooluc.com/](https://test.cooluc.com/)

**Comment by cooluc** [comment]
#458 #502 #468 #447 #418

**Comment by reruin** [comment]
Nice. 
注意下使用MS的公开接口有个缺陷：不适用于加密文件夹内的文档。

**Comment by x2658y** [comment]
缺失Reference请求头![image](https://user-images.githubusercontent.com/47146890/122640108-30112f00-d130-11eb-8718-9b057a9c3b46.png)
