### ISSUE TITLE
MKV格式视频无法播放

### ISSUE THREAD

**Issue by l1zheng** [reruin/sharelist#510]
插件配置里将预览播放器换成了dplayer，也手动添加了mkv，但是网页中mkv格式的视频点击后会变成下载，无法在线预览。
![Snipaste_2021-05-26_18-10-32](https://user-images.githubusercontent.com/41247584/119643034-e2194c00-be4d-11eb-9775-e4d96b748b68.png)

**Comment by reruin** [comment]
设置好后 重启下。

**Comment by l1zheng** [comment]
> 设置好后 重启下。

可以了，感谢！
