### ISSUE TITLE
Heroku部署怎么使用Webdav功能？

### ISSUE THREAD

**Issue by l1zheng** [reruin/sharelist#514]
作者您好，请问heroku部署的sharelist怎么使用webdav功能？
我想在potplayer通过webdav连接，但由于用的是Heroku部署没有IP地址，在RailDrive尝试了用“xxx.herokuapp.com:33001”"/webdav"连接，无法连接。在potplayer里尝试"xxx.herokuapp.com/webdav:33001"，显示出错。请问该如何使用webdav功能呢？谢谢！
![Snipaste_2021-05-28_23-05-34](https://user-images.githubusercontent.com/41247584/120004520-7380ed80-c009-11eb-845b-6f7078ae57d0.png)
![Snipaste_2021-05-28_23-05-58](https://user-images.githubusercontent.com/41247584/120004528-767bde00-c009-11eb-9abe-09ed400b6de3.png)
![Snipaste_2021-05-28_23-08-13](https://user-images.githubusercontent.com/41247584/120004651-9a3f2400-c009-11eb-8026-00124133cd4a.png)

**Comment by l1zheng** [comment]
用服务器搭建的sharelist，把webdav路径更改为我挂载的谷歌云盘，通过potplayer连接成功了。那Heroku该怎么设置呢？

**Comment by reruin** [comment]
https://xxx.herokuapp.com/webdav

**Comment by l1zheng** [comment]
> https://xxx.herokuapp.com/webdav

您好，尝试了还是不行。我的网站是“l1zheng.herokuapp.com”，用herokua部署，后台导出配置里显示port：10397，WebDAV路径设置的是/Webdav。
我尝试用WinSCP连接Webdav，主机名设置：l1zheng.herokuapp.com/Webdav ，端口号设置：10397，提示错误：列出'Webdav:10397’的目录项时出错，404 Not Found。
您能帮我试一下吗？

**Comment by reruin** [comment]
实测成功。注意webdav 要小写。

**Comment by l1zheng** [comment]
> 实测成功。注意webdav 要小写。
> ![933E734B-5766-4F06-82DA-829156B23487](https://user-images.githubusercontent.com/7403780/120089312-8e4b8300-c12b-11eb-82ac-0f3d4acd20b2.png)

成功了！谢谢您！

**Comment by l1zheng** [comment]
> 实测成功。注意webdav 要小写。
> ![933E734B-5766-4F06-82DA-829156B23487](https://user-images.githubusercontent.com/7403780/120089312-8e4b8300-c12b-11eb-82ac-0f3d4acd20b2.png)

还想请问下，您用来访问WebDAV的这款软件叫什么名字？

**Comment by reruin** [comment]
iOS版 FE文件管理器

**Comment by l1zheng** [comment]
谢谢
