### ISSUE TITLE
视频加载失败，下载文件报错403，有办法解决吗？

### ISSUE THREAD

**Issue by l1zheng** [reruin/sharelist#515]
视频加载失败，下载文件报错403。之前报错403提示的是

> Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded

现在报错的是

> This file has not been flagged for abuse

上网查了资料后，这种情况好像是文件下载限额了，那有办法恢复吗？如果放着不管他，他会不会自己恢复？谢谢！

![Snipaste_2021-06-01_15-10-06](https://user-images.githubusercontent.com/41247584/120281498-9b16d500-c2eb-11eb-960e-8dc75f48b224.png)

**Comment by reruin** [comment]
24小时后再试下。
