### ISSUE TITLE
排序Bug

### ISSUE THREAD

**Issue by RealKiro** [reruin/sharelist#517]
![image](https://user-images.githubusercontent.com/33367701/120826220-c5d38880-c58c-11eb-9479-d43b060d4724.png)
- [ ] 如图，当存在`数字编号`而非`字母编号`时排序有问题

![image](https://user-images.githubusercontent.com/33367701/120826592-32e71e00-c58d-11eb-8e6f-416e3a875d9f.png)
- [x] RaiDrive本地打开是没问题的

**Comment by reruin** [comment]
默认是ascii 排序。不清楚windows 资源管理器的排序逻辑。
