### ISSUE TITLE
希望可以支持github

### ISSUE THREAD

**Issue by jsonlog** [reruin/sharelist#52]
如果能通过github api把github任意repo的任意指定的文件夹目录也像网盘的文件夹那样挂载,不走服务器流量,那样就很方便,毕竟github程序员分享的东西那么多~_~

**Comment by reruin** [comment]
已添加GitHub的支持。挂载方式：
```github:username``` 或者   
```github:username/repo```

**Comment by jsonlog** [comment]
额,貌似代码还是没变,没看到楼主最近有相关的commit
测试支持如下:

1.在演示目录添加github.d.ln文件 --> github:reruin或者github:jsonlog/music
Error: ENOTDIR: not a directory, scandir './example/github-music.d.ln'

2.在[配置文件](cache/config.json)添加 "path": "github:reruin/sharelist"
500 TypeError: Cannot read property 'drive' of undefined

**Comment by reruin** [comment]
哈 忘记push了。再试试。需重启服务。

**Comment by jsonlog** [comment]
closed issue:谢谢完美支持~_~
要是能支持隐私仓库就更好了~只需要加个token=xxx

**Comment by reruin** [comment]
分支、私库、压缩下载以后再考虑。
