### ISSUE TITLE
阿里云盘 error 500

### ISSUE THREAD

**Issue by uorzen** [reruin/sharelist#521]
Error

Looks like something broke!

        
TypeError: Cannot read property 'body' of undefined
    at Driver.path (/root/sharelist/plugins/drive.aliyundrive.js:402:17)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

**Comment by iskycc** [comment]
同楼主一样的错误，楼主找到解决办法了吗

**Comment by ningQAQ** [comment]
楼主找到方法了吗 同样是错误500

**Comment by uorzen** [comment]
没有  等修复吧。  我暂时用alist呢！

**Comment by cooluc** [comment]
目前可以使用我構建的版本進行使用，可解決該問題：https://media.cooluc.com/source/sharelist

**Comment by qingfengjiang** [comment]
一样的问题

**Comment by reruin** [comment]
已修复。
