### ISSUE TITLE
阿里雲盤挂載問題報告2

### ISSUE THREAD

**Issue by cooluc** [reruin/sharelist#526]
目錄下文件數量大於200文件數量時，非管理員登錄狀態無法訪問，會返回404錯誤。管理員登錄狀態下列表加載正常

**Comment by reruin** [comment]
未测出。更新下 清除缓存试试。

**Comment by cooluc** [comment]
> 未测出。更新下 清除缓存试试。

非常抱歉，也許是我本地因爲主題緣故，清除sharelist 緩存與瀏覽器緩存后，300文件列表、1000文件列表均加載正常。此問題不存在。
