### ISSUE TITLE
one drive个人版挂载后无法拉取文件列表

### ISSUE THREAD

**Issue by jsonlog** [reruin/sharelist#53]
如题，经测试，普通的one drive个人版挂载后无法拉取文件列表，一直显示为空。普通的个人版google drive能够正常挂载。演示目录的[onedrive](https://1drv.ms/f/s!Apo33BTbGqqHhx3q6Gtb62WI6p59)文件夹也是为空,是我个人的问题吗?望修复

**Comment by reruin** [comment]
测试演示目录的onedrive 可以正常访问。清理下缓存再尝试下。
