### ISSUE TITLE
一个服务器上安装两个sharelist

### ISSUE THREAD

**Issue by star112** [reruin/sharelist#536]
一个可以正常启动，另一个无法启动，已修改为不同的端口。还需要修改哪些地方可以启动成功？

**Comment by reruin** [comment]
1. 修改一下 pm2 启动的任务名。
a、 package.json 文件 scripts -> prd 这一行，--name sharelist 改为 --name sharelist2。
b、或者手动运行 pm2 start app.js --name sharelist2 --env prod

2. 使用docker
