### ISSUE TITLE
mkv不能播放

### ISSUE THREAD

**Issue by wekingchen** [reruin/sharelist#54]
以前在chrome浏览器里，mkv文件可以通过播放器播放，现在最新版不能播了，链接点之后变成下载了。不知是不是个bug？

**Comment by reruin** [comment]
可编辑[/reruin/sharelist/blob/master/plugins/preview.media.js#L42](插件的第42行)，增加你需要的支持的后缀格式。

浏览器播放视音频依赖具体播放文件的编码方式，由于后缀不能反映最终编码， [/reruin/sharelist/blob/master/plugins/preview.media.js](多媒体预览插件) 只是按照经验进行了设置。     
ogg = Theora 视频编码 + Vorbis 音频编码
mp4/m4v = H.264 视频编码 + AAC 音频编码
webm = VP8 视频编码 +  Vorbis 音频编码

mkv 由于经常出现不支持的音频编码，导致播放无声，因而未列出。
