### ISSUE TITLE
docker buildx 构建的 ARM 版镜像无法使用

### ISSUE THREAD

**Issue by stilleshan** [reruin/sharelist#540]
拿甲骨文 ARM 架构的 Linux 直接 build 为镜像可以使用..

但是使用 GitHub action 使用 buildx 构建多版,其中有 linux/arm64 .也能成功构建..但是拉取下来使用确直接退出了..

排查了下也没找到原因,不知道有没有人知道如何解决.

**Comment by benzBrake** [comment]
没有用 QEMU 构建吧

**Comment by stilleshan** [comment]
> 没有用 QEMU 构建吧

谢谢
