### ISSUE TITLE
天翼个人云盘如何加密目录

### ISSUE THREAD

**Issue by soulersyy** [reruin/sharelist#553]
VPS使用了天翼云账户密码的挂载方式，挂载成功访问没有问题。现在希望可以加密目录。
通过查看指引，“在需加密目录内新建 .passwd 文件，type为验证方式，data为验证内容。”但天翼个人云盘的目录下不允许建立文件名为空的.passwd文件，麻烦问下如何加密目录？谢谢。

**Comment by q240627995** [comment]
本地win创建这个1.passwd文件 ，然后用cmd用rename命令修改文件为.passwd文件名，然后上传到你要加密的文件夹就可以了
