### ISSUE TITLE
打包成 appimage 或编写 pkckage 来增加分发方式。

### ISSUE THREAD

**Issue by xwulin** [reruin/sharelist#558]
如题，能不能增加像 aur ， appimage 等更多分发方式。或者直接提供通用分发平台方式或打包到 aur 或直接提供平台安装包。

便于在更多平台直接使用包管理器安装，即 2 次打包，易于维护（通过类似 aur 直接分发的方式，即 aur 助手，或将 appimage 再打包成个发行版的包。（ npm 好像不能打包成 appimage ？ 

把 npm 打成包也好，对不会的人会友好一些。

还有脚本里好像是用了 apt-get 和 yum ，但没有说明，建议注明一下防止不使用相关包管理器的人执行了脚本。（不会 shell 不知道是不是

**Comment by reruin** [comment]
新版已支持。
