### ISSUE TITLE
天翼网盘个人云提示Error Looks like something broke!           TypeError: Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by qiaofuya** [reruin/sharelist#559]
Error
Looks like something broke!

        
TypeError: Cannot read property 'join' of undefined

**Comment by a13720943940** [comment]
我的也挂了
Error
Looks like something broke!

        
TypeError: Cannot read property 'body' of undefined
    at Driver.path (/sharelist/plugins/drive.aliyundrive.js:402:17)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

**Comment by a13720943940** [comment]
无论天翼还是阿里，都挂了

**Comment by reruin** [comment]
请参考 #551
