### ISSUE TITLE
百度授权错误

### ISSUE THREAD

**Issue by czahoi** [reruin/sharelist#564]
```
https://openapi.baidu.com/oauth/2.0/authorize?client_id=QsrT0UR8FVvYEduUaGH5q89FdNy16aid&scope=basic%2Cnetdisk&response_type=code&redirect_uri=https%3A%2F%2Freruin.github.io%2Fsharelist%2Fredirect.html&state=http%3A%2F%2F5.252.165.215%3A33001%2F%25E7%2599%25BE%25E5%25BA%25A6%25E4%25BA%2591
```
错误代码：redirect_uri_mismatch
错误信息：Invalid redirect uri
详细描述：授权回调页地址错误，具体内容请开发者参考“redirect uri”验证方式

**Comment by reruin** [comment]
进入 "应用详情" - “安全设置” ， 将 OAuth授权回调页 设置为```https://reruin.github.io/sharelist/redirect.html```

**Comment by seamusic** [comment]
注意，要在这里修改 https://pan.baidu.com/union/console/
不是 http://developer.baidu.com/console#app/project 这里修改。
还是有点不一样。

**Comment by seamusic** [comment]
额……两个地方都不行。我有点晕。

**Comment by seamusic** [comment]
重新创建一个应用，然后先直接配置好授权页，这样就可以了。但是，授权返回时报错了。

![image](https://user-images.githubusercontent.com/172009/130337787-0a60e0c0-e381-47b8-912a-53a745ab01ab.png)

**Comment by reruin** [comment]
> 重新创建一个应用，然后先直接配置好授权页，这样就可以了。但是，授权返回时报错了。
> 
> ![image](https://user-images.githubusercontent.com/172009/130337787-0a60e0c0-e381-47b8-912a-53a745ab01ab.png)

优先修改```https://pan.baidu.com/union/console```，早先只有 ``` http://developer.baidu.com```这一处地方，默认前者会覆盖后者。

截图引用错误是个bug，等待修复。
