### ISSUE TITLE
希望可以支持文件列表分页和图片模式

### ISSUE THREAD

**Issue by snioer** [reruin/sharelist#57]
大佬这个项目用起来的确好用
中转Gdrive之后很多东西分享起来很方便
可是有的时候分享出去的文件有点多
能不能加一个文件列表的分页选项
每页显示30个左右就可以

另外可不可以加上图片模式
开启后直接在本页显示列表内的图片
方便看Gdrive里的漫画-，-

**Comment by reruin** [comment]
分页可以加。
图片模式，需要研究下现有接口是否支持。

**Comment by snioer** [comment]
下午自己改了一下
一头雾水...............
开始想着可能调一下detail的data.body就可以实现列表看图了
还是想简单了.............

**Comment by emengweb** [comment]
> 分页可以加。
> 图片模式，需要研究下现有接口是否支持。

我记得之前php上用的一个gd的api接口有个参数，可以直接获取到缩略图。

**Comment by emengweb** [comment]
搜索了下，大概是这个接口，可以获取到文件的缩略图，估计除了图片外，还可以支持视频、pdf、txt等文档的缩略图，官方接口：https://drive.google.com/thumbnail?authuser=0&sz=w320&id=[fileid]

**Comment by emengweb** [comment]
Try this: https://stackoverflow.com/questions/25648388/permanent-links-to-thumbnails-in-google-drive-api
