### ISSUE TITLE
windows版本第一次打开没有弹出设置界面

### ISSUE THREAD

**Issue by seamusic** [reruin/sharelist#571]
### 问题描述 / Describe the bug

下载exe版本，第一次运行，没有异常提示。但是打开浏览器没有看到设置的界面。同时在cache目录下，没有任何文件。
显示的窗口IP显示有问题。

### 复现链接 / Reproduction

![Uploading image.png…]()

**Comment by seamusic** [comment]
![image](https://user-images.githubusercontent.com/172009/129753451-02b5dce7-888c-4074-aa91-c98ca97ce54a.png)

**Comment by dzoer** [comment]
一样的问题，Centos 8.2

![Screenshot_20210818-165257](https://user-images.githubusercontent.com/42781101/129868768-c37147c9-3ac5-4006-9e12-d442fd2496e2.png)

**Comment by reruin** [comment]
默认初始化密码 sharelist 登陆后直接配置。

**Comment by seamusic** [comment]
可以了。谢谢~
