### ISSUE TITLE
aliyun进入目录出错

### ISSUE THREAD

**Issue by seamusic** [reruin/sharelist#575]
### 问题描述 / Describe the bug

windows 10，使用最新刚发布的版本，以页面进入已经配置好的阿里云网盘时，提示出错。

### 复现链接 / Reproduction

![image](https://user-images.githubusercontent.com/172009/130337367-ca7974d2-749f-453e-9ae8-4ba45992d854.png)

**Comment by reruin** [comment]
聪截图来看，初始文件夹ID 设置的有问题。
