### ISSUE TITLE
旧版和彩云失效了

### ISSUE THREAD

**Issue by qingtian110** [reruin/sharelist#576]
### 问题描述 / Describe the bug

旧版和彩云无法使用验证码登录了，新版本可以使用cookie可以登录 ，但是一时之间用不习惯新版本，作者可以考虑下修复旧版本的和彩云登录接口吗？

跪谢！！！

**Comment by reruin** [comment]
旧版的登陆正在适配。

**Comment by reruin** [comment]
已修复。
