### ISSUE TITLE
二进制文件启动以后，默认的管理密码是多少？

### ISSUE THREAD

**Issue by ferocknew** [reruin/sharelist#580]
### 问题描述 / Describe the bug

二进制文件启动以后，默认的管理密码是多少？

**Comment by ferocknew** [comment]
明白了，把v0.1 版的config.json 拷贝过来就可以了

**Comment by 0honus0** [comment]
没有这个config.json怎么办

**Comment by ferocknew** [comment]
> 没有这个config.json怎么办

让作者提供一个模板

**Comment by 0honus0** [comment]
> > 没有这个config.json怎么办
> 
> 让作者提供一个模板

我看到代码里面有一个，我下载下来放进去了，可以用了

**Comment by reruin** [comment]
@ferocknew 默认密码 sharelist
