### ISSUE TITLE
阿里云盘 移动端 token 无法正常挂载

### ISSUE THREAD

**Issue by HtnrxUNc** [reruin/sharelist#589]
### 问题描述 / Describe the bug

我今日从"github"拉取仓库之后使用
“docker run -d -v /etc/sharelist:/sharelist/cache -p 33001:33001 --name="sharelist" reruin/sharelist:next”
方式跑起了程式
版本应该是最新版
我使用相同的token在alist成功获取了网盘列表
我无找到日志所在的文件夹(请告知我日志的位置
目前我关闭了“展开单一挂载盘”并开启了“快速模式”
剩下的设置为几乎没有动过

### Sharelist 版本 / Sharelist Version

v0.2

**Comment by HtnrxUNc** [comment]
我想要挂载的盘为“阿里网盘”

**Comment by 1715819** [comment]
我挂载阿里网盘也出现了同样的问题

**Comment by reruin** [comment]
是否使用的手机版token？

**Comment by HtnrxUNc** [comment]
> 是否使用了手机版token？

是的，我使用Android版本的app获取到的token(阿里网盘)
我确定token完全无误
我无法找到日志文件，所以也无法提供确定的日志报错
以上是我目前所能提供的信息
