### ISSUE TITLE
关于onedrive API的问题

### ISSUE THREAD

**Issue by Tiw1590** [reruin/sharelist#59]
出现Error - 500问题
使用的跳转地址是 https://reruin.github.io/redirect/onedrive.html
跳转后页面显示的如图 前面填写步骤都是正确的
![CO02SGN}50T){2B`O_UAOOG](https://user-images.githubusercontent.com/23412006/64111310-f33b4300-cdb6-11e9-8378-409540b8fbb2.png)

**Comment by reruin** [comment]
同#55号 issue。目测确实存在bug，待解决后再通知。
可尝试重绑一次。

**Comment by reruin** [comment]
./cache/config.json 可否发一份来看一下

**Comment by Tiw1590** [comment]
我尝试了重新绑定以及删掉源文件重新搭建 依旧是出现之前截图的错误提示

[cache.zip](https://github.com/reruin/sharelist/files/3566203/cache.zip)

**Comment by reruin** [comment]
已修复。

**Comment by Tiw1590** [comment]
大佬我这边依旧提示这个错误

![9FNWIG `09RBCEY$6SRDQKU](https://user-images.githubusercontent.com/23412006/64218115-ed4a7c80-cef2-11e9-9c66-57442054277e.png)

**Comment by reruin** [comment]
清除缓存(cache/db.json)，后再试下。这边自测是过了。

**Comment by dissipator** [comment]
我安按照以上步骤操作了。
并且把console.log(res.headers)打印出来，发现没有set-cookie
以下为打印内容
{ 'cache-control': 'private',
  'content-length': '372',
  'content-type': 'text/html; charset=utf-8',
  location:
   '/_forms/default.aspx?ReturnUrl=%2fpersonal%2fdissip
ator_t_odmail_cn%2f_layouts%2f15%2fonedrive.aspx%3fid%3
d%252Fpersonal%252Fdissipator%255Ft%255Fodmail%255Fcn%2
52FDocuments%252Fpublic&id=%2Fpersonal%2Fdissipator%5Ft
%5Fodmail%5Fcn%2FDocuments%2Fpublic',
  p3p:
   'CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA
 PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR
UNI"',
  'x-sharepointhealthscore': '5',
  sprequestguid: '27d4009f-603f-0000-2e5f-f30463098032'
,
  'request-id': '27d4009f-603f-0000-2e5f-f30463098032',

  'ms-cv': 'nwDUJz9gAAAuX/MEYwmAMg.0',
  'strict-transport-security': 'max-age=31536000',
  'x-aspnet-version': '4.0.30319',
  sprequestduration: '28',
  spiislatency: '2',
  'x-powered-by': 'ASP.NET',
  microsoftsharepointteamservices: '16.0.0.19221',
  'x-content-type-options': 'nosniff',
  'x-ms-invokeapp': '1; RequireReadOnly',
  'x-msedge-ref':
   'Ref A: A6BB93549F494FAFA357440970FCA201 Ref B: HK2E
DGE0820 Ref C: 2019-09-04T07:03:13Z',
  date: 'Wed, 04 Sep 2019 07:03:13 GMT',
  connection: 'close' }

**Comment by dissipator** [comment]
补充 我的是od就报错
Error
Looks like something broke!

        
TypeError: Cannot read property 'join' of undefined
    at getCookie (D:\git\sharelist\sharelist\plugins\drive.odb.js:39:46)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by reruin** [comment]
> 补充 我的是od就报错
> Error
> Looks like something broke!
> 
> TypeError: Cannot read property 'join' of undefined
> at getCookie (D:\git\sharelist\sharelist\plugins\drive.odb.js:39:46)
> at process._tickCallback (internal/process/next_tick.js:68:7)

此条讨论drive.od.api ，drive.odb请重开一条issue，将挂载标识发出来。

**Comment by dissipator** [comment]
可以挂载onedrive的目录了，但是只能显示当前目录下的文件，不能显示目录下的文件夹

**Comment by reruin** [comment]
发下你的挂载标识。

**Comment by dissipator** [comment]
oneb.d.ln

odb:https://jxjjxy-my.sharepoint.com/:f:/g/personal/dissipator_t_odmail_cn/Et0xBazwgndCtD3fTAutjYkBEdLS-5KARozlKLBuvCYDpA?e=yGauEh

**Comment by reruin** [comment]
@dissipator 修复清除缓存后 odb 显示异常bug。拉取新代码后再试试。

**Comment by wekingchen** [comment]
我原本是挂载成功的，昨天抓取最新代码后，原本正常抓取的目录直接变成OneDrive 挂载向导页面了。清空路径重新绑定，在输入完应用机密 和 应用ID后，完成微软页面验证后，回调页面又跳回原来的OneDrive 挂载向导页面了。
重复操作一直都这样循环，无法完成绑定。

**Comment by reruin** [comment]
@wekingchen 更新下。
最近重写onedrive的oauth2，测试没覆盖到位。

**Comment by wekingchen** [comment]
更新后ok了，谢谢！

**Comment by Tiw1590** [comment]
![@S@L(N{VB$U6 TSG45~2D%9](https://user-images.githubusercontent.com/23412006/66201371-ca6bdd80-e6d5-11e9-9546-ae6baf4dcbba.png)
我还是用不了TVT

**Comment by Tiw1590** [comment]
![A}AS_UIIX25` 2LV}X FXBU](https://user-images.githubusercontent.com/23412006/66201455-ff783000-e6d5-11e9-8466-5b02a2173b9c.png)
原图

**Comment by reruin** [comment]
请用最新的代码再试试。

**Comment by wekingchen** [comment]
今天因为测试重新安装了一遍最新代码，OneDrive确实像上面的截图一样无法再挂载成功，错误信息和上面一样。

**Comment by songtianlun** [comment]
> 可以挂载onedrive的目录了，但是只能显示当前目录下的文件，不能显示目录下的文件夹

同问，我也出现同样的问题，如何解决？

**Comment by wekingchen** [comment]
老大能处理一下这个问题吗？快两个月了一直都不能绑定成功。

**Comment by reruin** [comment]
现在还有此问题吗。

**Comment by vbqgyy** [comment]
用了3月8号的代码 还是有问题。挂载 OneDrive 失败

AADSTS500112: The reply address 'http://***********:33001/sdodapi' does not match the reply address 'https://reruin.github.io/redirect/onedrive.html' provided when requesting Authorization code.
