### ISSUE TITLE
新版本挂载和彩云的CAIYUN_TOKEN在哪里获取

### ISSUE THREAD

**Issue by lbyxiaolizi** [reruin/sharelist#594]
### 问题描述 / Describe the bug

新版本挂载和彩云的CAIYUN_TOKEN在哪里获取

### Sharelist 版本 / Sharelist Version

v0.2

**Comment by rongwing** [comment]
同求答案

**Comment by reruin** [comment]
caiyun 官方更新了 cookie的内容，现在的已经不用 CAIYUN_TOKEN 做验证了。
0.1 版修复了此问题。
0.2 已适配等待发布。

**Comment by reruin** [comment]
caiyun官方登录后，从浏览器中获取cookeis
