### ISSUE TITLE
旧版还维护吗？新版使用下来很诡异啊

### ISSUE THREAD

**Issue by ferocknew** [reruin/sharelist#599]
### 问题描述 / Describe the bug

旧版还维护吗？新版使用下来很诡异啊
添加了 OneDrive 网盘，然后再添加一个阿里云盘，然后删了OneDrive 网盘，挂载盘就全没了。。。

这都不敢修改挂载信息了，

### Sharelist 版本 / Sharelist Version

v0.2

**Comment by rongwing** [comment]
Windows版同样出现这种现象加！

**Comment by ferocknew** [comment]
旧版，阿里云盘，下载问题提示

```xml
<Error>
<Code>InvalidArgument</Code>
<Message>At least one of AdditionalHeaders is not in request headers.</Message>
<RequestId>61383FF8898E52393440D993</RequestId>
<HostId>bj29.cn-beijing.data.alicloudccp.com</HostId>
</Error>
```

**Comment by reruin** [comment]
旧版 还维护的。@ferocknew aliyun driver用的是web版token吗？

**Comment by ferocknew** [comment]
> 旧版 还维护的。@ferocknew aliyun driver用的是web版token吗？

是的，求教其他获取token 的方式

**Comment by ferocknew** [comment]
另外，我自己写了一个ipfs 的驱动，是否愿意采纳？如何提供？或者合并给你？适配 v0.1 版

**Comment by ferocknew** [comment]
> 旧版 还维护的。@ferocknew aliyun driver用的是web版token吗？

已通过安卓客户端获取token 解决，建议增加此说明。


**另一个bug，v0.1 版，指定目录ID 无效。添加以后，任然定位到根目录。**
