### ISSUE TITLE
老哥文件不全啊

### ISSUE THREAD

**Issue by shirakun** [reruin/sharelist#6]
https://g-drive.herokuapp.com/anime
https://drive.google.com/drive/u/2/folders/0BwfTxffUGy_GNF9KQ25Xd0hMVXM

**Comment by reruin** [comment]
已重现。等待修复。

**Comment by jasonwwww** [comment]
教育邮箱的好像不能共享

**Comment by shirakun** [comment]
@jasonwwww 可以共享啊

**Comment by Cloudiver** [comment]
@shirakun 教育版无限容量的GD可以共享？？
我分享的链接，文件没有列出来。。

**Comment by 5wszxt** [comment]
同，教育版共享别人访问需要申请权限，gdlist文件夹还是空白。。。

**Comment by reruin** [comment]
教育版本可尝试按照下述步骤 修改访问权限。  
![01](https://user-images.githubusercontent.com/7403780/42855523-81056aae-8a73-11e8-99a4-ac1ef32ded49.png)
![02](https://user-images.githubusercontent.com/7403780/42855528-849134e6-8a73-11e8-88e5-dcb86baebf65.png)

**Comment by 0080004** [comment]
Heroku部署 配置文件(JSON字符串 或 http远程文件)填什么呢

**Comment by lmly9193** [comment]
請問一下Heroku部署 配置文件應該填入什麼呢?

**Comment by JERE-MIAH** [comment]
希望这个问题修复下，只能显示 50 个文件。

**Comment by reruin** [comment]
此bug已在 [@a6f10f](https://github.com/reruin/sharelist/tree/a6f10f724905a1205f42efe52ff5fbbb777a9b3d) 中修复。
