### ISSUE TITLE
测试了阿里网盘和百度网盘，网盘添加和删除文件后，sharelist不会同步。

### ISSUE THREAD

**Issue by rongwing** [reruin/sharelist#600]
### 问题描述 / Describe the bug

网盘添加和删除文件后，sharelist不会同步，依然还是显示的之前的文件列表！

### Sharelist 版本 / Sharelist Version

v0.2

**Comment by ferocknew** [comment]
检查缓存，可以清缓存以后重启应用

**Comment by rongwing** [comment]
> 检查缓存，可以清缓存以后重启应用

清除浏览器缓存重启应用也不行，我把程序和配置拷贝到另一个电脑也是一样。

**Comment by rongwing** [comment]
> 检查缓存，可以清缓存以后重启应用
我后来测试是v1.0版，也是在Windows下安装的，就正常。

**Comment by rongwing** [comment]
> 检查缓存，可以清缓存以后重启应用

右上角“垃圾桶”图标清除缓存之后可以了，谢谢！

**Comment by YIMUYIGUO** [comment]
你的阿里云盘是正常的吗  我的报错500
