### ISSUE TITLE
加密功能可否添加退出功能？还有新版如何加密？

### ISSUE THREAD

**Issue by rongwing** [reruin/sharelist#601]
### 需求描述 / Description of the feature

文件夹加密后，输入密码之后，如果我在客户电脑下载完后，无法退出登录，需要把浏览器全部关掉重新打开才能需要重新输入密码。而有时候客户打开了很多网页又不方便关闭。另外2.0版本如何给文件夹加密？按照1.0版本方法貌似不行。

### 实现思路 / Suggested solution

用nginx https反向代理打开web加密同样的这样的情况，需要关闭浏览器重新打开才需要重新输入密码；唯一的好处就是可以通过https webdav在外网也可以加密挂载。测试除了百度云是服务器中转，天翼云、和彩云和阿里云都是直链传输。用webdav挂载看电影就很爽了！

**Comment by reruin** [comment]
0.1 文件加密的验证信息会写入 会话期的cookie中，可以控制台清除掉。
0.2 的采用单一密码验证，passwd 文件请参考 https://github.com/reruin/sharelist/blob/master/packages/sharelist/example/secret_folder/.passwd

**Comment by rongwing** [comment]
> 0.1 文件加密的验证信息会写入 会话期的cookie中，可以控制台清除掉。
> 0.2 的采用单一密码验证，passwd 文件请参考 https://github.com/reruin/sharelist/blob/master/packages/sharelist/example/secret_folder/.passwd

感谢大佬，我试试！

**Comment by cheng-hunter** [comment]
0.2 的采用单一密码验证，passwd 文件请参考 https://github.com/reruin/sharelist/blob/master/packages/sharelist/example/secret_folder/.passwd
这个只支持 本地文件的挂载方式，不支持如百度网盘,和彩云盘等虚拟目录webdav加密访问，存在数据安全问题。
导致网盘变成了公开的webdav.

**Comment by rongwing** [comment]
> 0.2 的采用单一密码验证，passwd 文件请参考 https://github.com/reruin/sharelist/blob/master/packages/sharelist/example/secret_folder/.passwd
> 这个只支持 本地文件的挂载方式，不支持如百度网盘,和彩云盘等虚拟目录webdav加密访问，存在数据安全问题。
> 导致网盘变成了公开的webdav.

加密之后webdav不是需要sharelist后台管理密码才能登陆吗？会不安全吗？那用nginx https反向代理basic加密是否相对安全可靠呢？
