### ISSUE TITLE
进入管理提示需要密码？

### ISSUE THREAD

**Issue by LINJIE9865** [reruin/sharelist#603]
### 问题描述 / Describe the bug

之前曾经用过这软件，之后因为挂载天翼云失败就没删除了源文件。
现在使用新的windows版，进入页面后选择管理提示需要密码，但我不知道密码。该怎么办？可以重置密码吗？

### Sharelist 版本 / Sharelist Version

v0.2

**Comment by lm379** [comment]
密码是sharelist
