### ISSUE TITLE
百度网盘无法挂载

### ISSUE THREAD

**Issue by xuange-dada** [reruin/sharelist#605]
### 问题描述 / Describe the bug

挂载百度网盘按照向导创建完，并设置了授权回调页，确定授权的时候显示与百度连接错误，授权回调页地址错误

### Sharelist 版本 / Sharelist Version

v0.2

**Comment by xuange-dada** [comment]
错误代码：redirect_uri_mismatch
错误信息：Invalid redirect uri
详细描述：授权回调页地址错误，具体内容请开发者参考“redirect uri”验证方式

**Comment by xuange-dada** [comment]
使用的是旧版

**Comment by michealhansun** [comment]
我使用新版一样的情况
