### ISSUE TITLE
目录加密bug

### ISSUE THREAD

**Issue by penjune** [reruin/sharelist#61]
https://github.com/reruin/sharelist/tree/71430f2a17595d16b910402c353db438e73ebfca
十一天前的旧版本可以正常目录加密

现行的版本目录加密后
帐密输入正确不会跳转至当前路径的页面
(输入正确且按下确认键后会维持在登陆页面不动)

挂载的是google drive，部署在heroku上

**Comment by reruin** [comment]
已修复。

**Comment by penjune** [comment]
感谢 测试已恢复正常
