### ISSUE TITLE
在线播放无法拖动进度条

### ISSUE THREAD

**Issue by wekingchen** [reruin/sharelist#62]
采用新版顺利使用google drive api挂载成功，但是在线播放时无法拖动进度条。而同样源盘在旧的分享文件夹ID方式下播放可以拖动进度条。

**Comment by reruin** [comment]
已修复。

**Comment by wekingchen** [comment]
感谢，确认已经ok了。
请问后续可以考虑把播放器换成DPlayer吗？

**Comment by reruin** [comment]
后期考虑 ~
