### ISSUE TITLE
mac可以web访问，webdav挂载时帐号密码不通过

### ISSUE THREAD

**Issue by babayun** [reruin/sharelist#620]
### 问题描述 / Describe the bug

启动程序后浏览器打开http://hocalhost:33001可以正常访问挂在的云盘内容，通过WEBDAV连接输入参数提示:COM.SAEMOBILE.LEOWEBDAV.ERROR错误501，新手小白求大佬告知怎么解决，谢谢
![A1](https://user-images.githubusercontent.com/92069684/136312708-83aecfc7-59c0-4329-b534-f3b848df83f1.jpg)
！

### Sharelist 版本 / Sharelist Version

v0.2

**Comment by iso-lib** [comment]
0.2版本还没做webdav,,页面进度不写着的吗不看

0.1版本可以webdav

**Comment by babayun** [comment]
那现在0.2版本如何开启WEBDAV呢？如果启用不了WEBDAV还可以安装0.1版本吗？

**Comment by iso-lib** [comment]
> 那现在0.2版本如何开启WEBDAV呢？如果启用不了WEBDAV还可以安装0.1版本吗？

0.2版本没做webdav,,,没做webdav,,,没做webdav

**Comment by babayun** [comment]
> > > 那现在0.2版本如何开启WEBDAV呢？如果还能不能安装0.1版本的WEBDAV吗？
> > 
> > 
> > 0.2版本没做webdav,,,,没做webdav,,,,没做webdav
> 
> 了，我前几天装的heroku版本，那应该是0.2版本吧，我发现webdav是可以的，但不能给一个惊喜，如果发现了就奇怪了就好像密码不对

难道0.2版本已经推出了WEBDAV了吗？    webdav连接的账号密码是云盘的账号密码吗？

**Comment by babayun** [comment]
期待0.25出来webdav,啥时候才发布呢？

**Comment by reruin** [comment]
webdav 已更新支持。

**Comment by babayun** [comment]
> webdav 已更新支持。

我在今天11点的时候MAC更新v0.33版本，webdav连接，密码不通过。请问默认的账号密码是啥？

**Comment by babayun** [comment]
> > > webdav 已更新支持。
> > 
> > 
> > 我在今天11点的时候MAC更新v0.33版本，webdav连接，密码不通过。请问默认的账号密码是啥？
> 
> webdav 用户名 admin，密码 和 后台密码一致，默认为 sharelist

服务器设置http://hocalhost：33001，账号admin，密码sharelist，挂载提示如图所示。
![27424EDD-347A-460B-8627-FA1F422457C1](https://user-images.githubusercontent.com/92069684/136695983-3bb2311c-c6c6-4a3c-976f-c788adb08c44.jpeg)
![F34A7403-4671-47E1-8C23-C93BC41F261B](https://user-images.githubusercontent.com/92069684/136695992-13729471-3d07-4fd7-b149-c75556c9b972.jpeg)
![2116D121-ED14-4534-9CE0-F20D650EE171](https://user-images.githubusercontent.com/92069684/136695993-9dd19ef8-fb50-4990-91d4-ec8f2ab07324.jpeg)

**Comment by reruin** [comment]
@babayun 给访达 重新做了兼容性适配，0.3.4 试下。

**Comment by babayun** [comment]
> @babayun 如果已解决疑问，请关闭下issue

按照您的指导我去MAC里找到cache这个文件夹，里面啥都没有，我也没动他。
![698124DD-A51B-4450-897C-320E85DE1550](https://user-images.githubusercontent.com/92069684/137590977-08420bec-dcda-4675-b228-edcf5847860b.png)

**Comment by babayun** [comment]
。

**Comment by reruin** [comment]
@babayun 请问问题有没有解决。

**Comment by babayun** [comment]
> @babayun 请问问题有没有解决。

没有。昨天和前天删除重新下载最新版本，下载半小时都没下完 终端显示下载才8M多，进度好像不动了就放弃了，总共好像30多M。
