### ISSUE TITLE
安装脚本已失效，有更新的脚本吗

### ISSUE THREAD

**Issue by wellsyue** [reruin/sharelist#622]
### 问题描述 / Describe the bug

wget --no-check-certificate -qO-  https://raw.githubusercontent.com/reruin/sharelist/master/netinstall.sh | bash

### Sharelist 版本 / Sharelist Version

v0.2

### 复现链接 / Reproduction

执行脚本没有反应，脚本链接已失效

**Comment by reruin** [comment]
旧版已移至 `wget --no-check-certificate -qO-  https://raw.githubusercontent.com/reruin/sharelist/0.1/netinstall.sh | bash`
