### ISSUE TITLE
天翼云挂载出错

### ISSUE THREAD

**Issue by 11195666** [reruin/sharelist#623]
### 问题描述 / Describe the bug

error 500，挂载后无法访问

### Sharelist 版本 / Sharelist Version

v0.2

**Comment by reruin** [comment]
用最新的sharelist ，重新挂载。天翼云改接口了。

**Comment by FLRen** [comment]
> 用最新的sharelist ，重新挂载。天翼云改接口了。

目前上传功能能用么？开放上传已启用，用RaiDrive映射后，本地文件拖至网盘会报错，是我的设置问题么？

**Comment by reruin** [comment]
@FLRen 从你描述来看，你用的可能是 0.1 版本。换成 最新版。

**Comment by reruin** [comment]
新版解压后 就是可执行文件，windows 下双击运行，linux 下` ./sharelist`。
