### ISSUE TITLE
目录加密小错误

### ISSUE THREAD

**Issue by penjune** [reruin/sharelist#63]
auth.pug的小bug
第15行的placeholder应为'auth_passwd_placeholder'

另外如果在加密页面的地址后加上 "/.passwd"，passwd将会被下载
希望可以新增禁止下载passwd的功能

**Comment by reruin** [comment]
谢谢反馈，已修复。
另增加了 ignore_file_extensions 用于屏蔽特定扩展名。

**Comment by penjune** [comment]
实测已成功禁止passwd被下载
新版本增加的忽略文件类型测试也没问题
感谢作者快速地修复
