### ISSUE TITLE
v0.34只能使用docker安装吗？有么有其他方式

### ISSUE THREAD

**Issue by gtlongt** [reruin/sharelist#630]
### 需求描述 / Description of the feature

v0.34只能使用docker安装吗？有么有其他方式 烦请告知

**Comment by reruin** [comment]
这里有打包好的二进制文件。
https://github.com/reruin/sharelist/releases

**Comment by gtlongt** [comment]
多谢百忙之中回复，使用docker或二进制文件如何更改主题或者美化下前端呢

> 这里有完美的二进制文件。 https://github.com/reruin/sharelist/releases

**Comment by gtlongt** [comment]
> docker 版的默认主题位置/sharelist/theme/default，你可以自己映射修改。
多谢大佬已搞定

**Comment by aoaojiao1987** [comment]
运行win版的exe提示无法定位程序输入点 GetHostNameW 于动态链接库WS2_32.dll上，有没有和我一样的
