### ISSUE TITLE
求更新heroku版挂载天翼云

### ISSUE THREAD

**Issue by xuange-dada** [reruin/sharelist#642]
### 问题描述 / Describe the bug

文档中的一键部署heroku没有更新，依旧无法挂载天翼云，求更新一下heroku版本接口

### Sharelist 版本 / Sharelist Version

v0.2

### 日志 / Logs

```shell
Error
Looks like something broke!

        
TypeError: data.body.data is not iterable
    at Object.folder (/sharelist/plugins/drive.189cloud.js:384:33)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

**Comment by d4renk** [comment]
> 已修复

**termux客戶端如何安裝sharelist，直接啟動二進制報錯**

**Comment by reruin** [comment]
@d4renk 不清楚termux 是否能使用 linux 的二进制包，请尽量使用docker安装。另请重开新issue。
