### ISSUE TITLE
openwrt docker 安装sharelist，挂起阿里云盘和百度网盘正常，挂载天翼云盘，输入账号密码，点击验证后出现错误

### ISSUE THREAD

**Issue by michealhansun** [reruin/sharelist#643]
### 问题描述 / Describe the bug

openwrt docker 安装sharelist，挂起阿里云盘和百度网盘正常，挂载天翼云盘，输入账号密码，点击验证后出现错误

### Sharelist 版本 / Sharelist Version

v0.2

### 复现链接 / Reproduction

无

### 日志 / Logs

```shell
Error
Looks like something broke!

        
TypeError: data.body.data is not iterable
    at Object.folder (/sharelist/plugins/drive.189cloud.js:384:33)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

**Comment by michealhansun** [comment]
> 更新到最新版本试下。

docker run -d -v /etc/sharelist:/app/cache -p 33001:33001 --name="sharelist1" reruin/sharelist 
运行不了

docker run -d -v /etc/sharelist:/sharelist/cache -p 33001:33001 --name="sharelist" reruin/sharelist:next
这个可以运行

好奇怪

**Comment by michealhansun** [comment]
> 后台管理中 启用 `WebDAV 代理`。原因：某些客户端不支持下载时 连接重定向。

昨天使用reruin/sharelist  0.1版本是可以的，不需要webdav代理， 挂载成功后直链的网盘，下载文件不需要绕家里软路由，下载速度好快；
0.2版本如果需要开启webdav代理才能读取文件的话，这样流量都要绕一次家里的软路由，家宽上传速率限制，下载文件时慢多了

请问是否0.2版本只是暂时不支持，还能修复是吗？

**Comment by reruin** [comment]
这个原因比较复杂，webdav是否能直链下载，依赖于两个方面：
1. 对接的**挂载盘是否接受**WebDAV客户端的请求 ，正常的官方服务是针对浏览器（或官方客户端）设计并为此做校验，技术层面上有理由屏蔽其他不兼容客户端。
2. WebDAV**客户端是能处理重定向**以及对应处理逻辑。

用户很难知晓上述细节。

回到问题，RaiDrive在Windows中，匿名登录WebDAV可以重定向下载，但是密码登录会报权限错误(S-1-1-0)。这就是为什么v0.1 可以下载，新版不行。类似的nPlayer连接新版WebDAV确可以正常直链使用。

新版升级支持匿名访问WebDAV就能直链了，但这样安全性就很难保证（WebDAV无视```.passwd```）。
