### ISSUE TITLE
如何使用termux客戶端安裝sharelist

### ISSUE THREAD

**Issue by d4renk** [reruin/sharelist#659]
### 需求描述 / Description of the feature

直接運行二進制報錯

**Comment by d4renk** [comment]
> 提供如下思路。
> 
> 1. 尝试安装nodejs。
> 2. clone代码，安装依赖 `npm install --production`
> 3. 运行 npm run dev

> 2.已安装了cross-env，yarn，nodejs，运行报错

[log](https://github.com/d4renk/update/blob/main/log.txt)

**Comment by reruin** [comment]
1. 进到 packages/sharelist-webdav 运行 npm run build 。
2. 如果要web界面，还需要回到根目录，运行 npm run dev-web 访问地址是 http://localhost:3000

**Comment by d4renk** [comment]
> 改用yarn执行。`yarn dev` 以及 `yarn dev-web`

[log](https://github.com/d4renk/update/blob/main/2021-10-17-17:45.txt)

**Comment by reruin** [comment]
这就已经成功运行了。

**Comment by d4renk** [comment]
> > 贴一下日志。
> 
> [pm2 app-error.log](https://github.com/d4renk/update/blob/main/2021-10-27.txt)
> 
> **已重新构建了webadv，yarn dev提示文件未发生更改，yarn dev未报错，webdav仍未正常运行**

意外执行一次安装脚本，成功进入webdav，我也不知道为啥😂
