### ISSUE TITLE
是否支持虚拟主机Nginx+PHP呢？

### ISSUE THREAD

**Issue by theblack6688** [reruin/sharelist#67]
自己为百度的虚拟主机为Nginx+PHP（https://cloud.baidu.com/doc/BCH/s/kjwvxoxix），请问可以使用吗？

**Comment by theblack6688** [comment]
https://cloud.baidu.com/doc/BCH/s/kjwvxoxix

**Comment by reruin** [comment]
不支持。需要支持nodejs。
你可以用heroku部署，完全免费。
[![Deploy](https://www.herokucdn.com/deploy/button.png)](https://heroku.com/deploy?template=https://github.com/reruin/sharelist-heroku)
