### ISSUE TITLE
webdav能挂载，却不能播放！

### ISSUE THREAD

**Issue by star2k** [reruin/sharelist#675]
### 问题描述 / Describe the bug

![](http://star2k10.3322.org:888/imgs/2021/10/a42a14b81a43d424.jpg)

### Sharelist 版本 / Sharelist Version

latest

**Comment by rongwing** [comment]
建议使用RaiDrive试试

**Comment by star2k** [comment]
> 建议使用RaiDrive试试

尝试了，一样不行，图片可以，视频就是不行，比如阿里云，大小在1.1G，应该不算大，但是无法播放！

**Comment by rongwing** [comment]
> 尝试了，一样不行，图片可以，视频就是不行，比如阿里云，大小在1.1G，应该不算大，但是无法播放！
除了阿里云，其他网盘是否会，并未出现这种问题，3G多的视频也可正常播放，你有可以尝试换播放器看看，比如vlc、PotPlayer，我的环境是最新版，webdav非中转模式，貌似之前用中转模式也没有问题。

**Comment by star2k** [comment]
> 
> 
> > 尝试了，一样不行，图片可以，视频就是不行，比如阿里云，大小在1.1G，应该不算大，但是无法播放！
> > 除了阿里云，其他网盘是否会，并未出现这种问题，3G多的视频也可正常播放，你有可以尝试换播放器看看，比如vlc、PotPlayer，我的环境是最新版，webdav非中转模式，貌似之前用中转模式也没有问题。

webdav端口也是33001吧，很奇怪换了播放器也依旧不行，而且对网盘的内容看似可以删除，但删除后，再次返回来看，却依旧存在。

**Comment by reruin** [comment]
@star2k docker要用 reruin/sharelist:next 这个镜像。

**Comment by star2k** [comment]
> @star2k docker要用 reruin/sharelist:next 这个镜像。 

好的，谢谢我试试，这个是测试版么，稳定性如何？
