### ISSUE TITLE
可以添加支持ssl(https)吗？虽然nginx反向代理能实现，但更耗电量和资源。

### ISSUE THREAD

**Issue by rongwing** [reruin/sharelist#676]
### 需求描述 / Description of the feature

自己是家用软路由虚拟机挂载，通过nginx反向代理，结果发现阿里网盘下载的时候（天翼云和和彩云是直链下载，无此问题，webdav如果是中转模式是全盘nginx代理访问），sharelist会先全速下载资源到本地，此时占用磁盘和电量会相对高10W左右（电源处接了功率测试），下载后完成nginx接着以带宽最大上行30mb上传，此时占用电量会低很多。而如果不适用nginx反向代理，则无此问题，全程低功率下载资源。请看对比图。

### 附件 / Additional context

![2021-10-24_143551](https://user-images.githubusercontent.com/90301975/138584169-3eb74b09-9930-4683-b856-036149db0ced.png)
![2021-10-24_143728](https://user-images.githubusercontent.com/90301975/138584170-9285b46d-c246-4354-93ba-9b35781353d6.png)

**Comment by reruin** [comment]
@rongwing 从描述来看，这应该是**nginx反向代理**配置上的问题。

**Comment by rongwing** [comment]
> @rongwing 从描述来看，这应该是**nginx反向代理**配置上的问题。
感觉大神提供思路，已解决问题
