### ISSUE TITLE
请问，docker还更新吗，因为不能挂载OneDrive for business或者怎么自行升级？

### ISSUE THREAD

**Issue by pirately** [reruin/sharelist#68]
请问，docker还更新吗，因为不能挂载OneDrive for business或者怎么自行升级？

**Comment by pirately** [comment]
我用的是群晖的218

**Comment by reruin** [comment]
已经更新 docker pull reruin/sharelist:latest

**Comment by pirately** [comment]
> 已经更新 docker pull reruin/sharelist:latest

请问，是否只能挂载一级目录？比如我Movie目录下，有很多子文件夹，我挂载后打不开子文件夹，只能打开Movie这个一级目录

**Comment by pirately** [comment]
用的是Onedrive for business，开启中转也是只能访问一级目录

**Comment by pirately** [comment]
演示目录里面，Onedrive挂载报错，然后Onedrive for business也是只能访问一级目录，子目录，比如1，10之类的，打不开

**Comment by pirately** [comment]
请问，是否只能挂在一级目录？我在群晖的docker下安装，不管是演示目录，还是我实际挂载OneDrive for business，都是只能看到一级目录，再进入下一级，进不去。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ting"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月11日(星期一) 晚上7:51
收件人:&nbsp;"reruin/sharelist"<sharelist@noreply.github.com&gt;;
抄送:&nbsp;"pirately"<jinfeng@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [reruin/sharelist] 请问，docker还更新吗，因为不能挂载OneDrive for business或者怎么自行升级？ (#68)




已经更新 docker pull reruin/sharelist:latest

**Comment by reruin** [comment]
已修复。reruin/sharelist:v20191119

**Comment by pirately** [comment]
谢谢。OneDrive for business挂载下级目录没有问题了。但是，主目录下面的文件看不到，就是说，比如movie目录下面即有xxx目录又有xxx.mp4文件，我进xxx目录没有问题，但是movie主目录下面的xxx.mp4之类的文件看不到，子目录下面的文件倒是没有问题。

**Comment by reruin** [comment]
可否分享一个连接 我测试下。

**Comment by pirately** [comment]
请问是什么链接？或者您有微信，qq之类的吗？

**Comment by reruin** [comment]
问题是否依然存在？

**Comment by pirately** [comment]
> 问题是否依然存在？

依然存在。我是用的群晖的docker

**Comment by pirately** [comment]
> 问题是否依然存在？

我知道问题了，我用的是onedrive for business。但是只能挂30个。请问如果用api挂载，怎么操作？

**Comment by reruin** [comment]
参考readme，选择使用API方式挂载。

**Comment by pirately** [comment]
> 参考readme，选择使用API方式挂载。

是的，但是对于怎么从微软获取token，试了几次不太会，Google资料，也不尽相同。

**Comment by reruin** [comment]
请参考 https://github.com/reruin/sharelist/issues/75 

sharelist已通过travis持续集成，Docker版会在每次提交后自动打包。

**Comment by pirately** [comment]
> 请参考 #75
> 
> sharelist已通过travis持续集成，Docker版会在每次提交后自动打包。

OneDrive路径->应用ID|应用机钥|回调地址|refresh_token，请问回调地址应该怎么填？或者说azure后台这个OneDrive路径怎么填？不是填的分享地址？如果不是分享地址，那应该填啥？

**Comment by reruin** [comment]
回调路径是指 sharelist 上对应访问路径，例如 挂载名为 one1 的onedrive 盘，sharelist的访问地址则为 http://sharelist_server/one1，此地址即是回调地址。

**Comment by pirately** [comment]
> 回调路径是指 sharelist 上对应访问路径，例如 挂载名为 one1 的onedrive 盘，sharelist的访问地址则为 http://sharelist_server/one1，此地址即是回调地址。

![image](https://user-images.githubusercontent.com/57277605/79636928-e2a4d500-81ad-11ea-8286-2422a16f263c.png)

首先那个od的api，我在rclone是成功的，但是您这个sharelist我一直不会。rclone那个，azure后台设置的重定向url就是http://localhost，  其他app_id和app_secure步骤是一样的。然后sharelist我设置
![image](https://user-images.githubusercontent.com/57277605/79636999-3d3e3100-81ae-11ea-9080-9609dd55bc5c.png)
这样，可以吗？然后就是验证的时候，报错

**Comment by pirately** [comment]
![image](https://user-images.githubusercontent.com/57277605/79637381-c73bc900-81b1-11ea-9ce6-c01ec6a9dfc7.png)
快速获取ID和机密的话，显示是这个

**Comment by reruin** [comment]
> ![image](https://user-images.githubusercontent.com/57277605/79637381-c73bc900-81b1-11ea-9ce6-c01ec6a9dfc7.png)
> 快速获取ID和机密的话，显示是这个

此问题已解决。

1. 如果使用http 的访问地址，请在重定向处填写```https://reruin.github.io/redirect/onedrive.html```。
2. 如果使用 https ，则填实际地址，比如https://domain.com/one1。
