### ISSUE TITLE
新版本onedrive初始目录ID怎么获取？

### ISSUE THREAD

**Issue by bookmarkies** [reruin/sharelist#680]
### 问题描述 / Describe the bug

使用的是新版本docker安装
`docker run -d -v /etc/sharelist:/app/cache -p 33001:33001 --name="sharelist" reruin/sharelist:next
`
安装完成之后在后台使用向导模式，并没有看到有设置目录的地方：
![image](https://user-images.githubusercontent.com/76272979/139181432-73f7816a-47aa-4428-9fe7-46f4bf92c182.png)

之后把相关的信息填进去，有一个是初始目录ID，直接填目录/share或者/share/名称访问是500的，但是我不知道怎么获取这个/share目录id
![image](https://user-images.githubusercontent.com/76272979/139181563-e5eb3cbe-2f03-4e7e-9507-9ec44f3adf40.png)

### Sharelist 版本 / Sharelist Version

latest

**Comment by reruin** [comment]
登录 onedrive，进入到对应文件夹，地址栏 ```https://onedrive.live.com/?id=*****&cid=```，**id=后面星号那部分**

**Comment by rongwing** [comment]
> 登录 onedrive，进入到对应文件夹，地址栏 `https://onedrive.live.com/?id=*****&cid=`，**id=后面星号那部分**

世纪互联怎么样获取呢？

**Comment by reruin** [comment]
现已支持查看文件夹信息，从中可获取到ID

**Comment by rongwing** [comment]
> 现已支持查看文件夹信息，从中可获取到ID

666方便多了!
