### ISSUE TITLE
挂载阿里云盘，目录能正常获取，文件和视频无法下载和播放

### ISSUE THREAD

**Issue by qingfengjiang** [reruin/sharelist#685]
### 问题描述 / Describe the bug

刚刚提示了要重新挂载，我就去重新获取了refresh_token，现在目录显示正常，文件和视频无法下载和播放了，试了下，v0.3.9和0.1都出现这样的情况

### Sharelist 版本 / Sharelist Version

v0.1

**Comment by ventusoon** [comment]
怎么解决的？
