### ISSUE TITLE
关于在线播放的问题

### ISSUE THREAD

**Issue by aumk** [reruin/sharelist#69]
大佬好像把所有mkv都处理成直接下载了
其实h.264编码的mkv，浏览器是可以解码的（参考了olaindex)
所以视频就交给浏览器去播放好了，毕竟也不知道浏览器能不能播放

**Comment by reruin** [comment]
将提供 视频预览格式的设置项。预计本周更新。

**Comment by aumk** [comment]
多谢大佬

**Comment by reruin** [comment]
已支持。

**Comment by aumk** [comment]
多谢大佬，马上更新尝试

**Comment by aumk** [comment]
完美！
