### ISSUE TITLE
Onedrive Business通过链接挂载是走服务器流量的吗

### ISSUE THREAD

**Issue by aumk** [reruin/sharelist#70]
突然发现是走的服务器流量
中转已经关闭了

**Comment by reruin** [comment]
必须使用cookie才能下载，所以强制使用中转模式。

**Comment by aumk** [comment]
大佬抱歉，那onedrive Linux怎么才能不走服务器流量呢，就像oneindex或者olaindex一样。
好像API挂载也是走的服务器流量？
