### ISSUE TITLE
希望添加支持动态负载及主从同步功能？

### ISSUE THREAD

**Issue by emengweb** [reruin/sharelist#71]
两个功能结合使用，可以防止网盘账号被ban，动态负载可以在多个相同内容的网盘账号下动态切换，提高大量请求时的稳定性，希望可以考虑增加这两种功能，感谢！

**Comment by reruin** [comment]
已在最新的提交中支持 动态负载 ，请参考readme。  
主从同步功能 目前没有开发计划。
