### ISSUE TITLE
挂载阿里云盘视频均无法播放

### ISSUE THREAD

**Issue by xuange-dada** [reruin/sharelist#713]
### 问题描述 / Describe the bug

挂载成功，可以正常显示目录，但是所有都不能在线预览并提示This XML file does not appear to have any style information associated with it. The document tree is shown below

### Sharelist 版本 / Sharelist Version

v0.1

### 复现链接 / Reproduction

https://bj29.cn-beijing.data.alicloudccp.com/yG05eCjL/1804972/618e989da61de9309a144d77b3e3d404d48e4652/618e989dc0ee1ccc324a4575b695711003c261c7?di=bj29&dr=694991&f=61986eec25332ab200f243fabbae012d5eaea401&response-content-disposition=attachment; filename*=UTF-8''Dr.Brain.2021.S01E02.mkv&u=e4fa7b0ba89e4ae5ab8204693d3a3a96&x-oss-access-key-id=LTAIsE5mAn2F493Q&x-oss-additional-headers=referer&x-oss-expires=1637403732&x-oss-signature=F6nWHiXRMhuGgU6HltNdMqawQBSuBwWrVgCBRF/d5io=&x-oss-signature-version=OSS2

### 日志 / Logs

```shell
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>InvalidArgument</Code>
<Message>At least one of AdditionalHeaders is not in request headers.</Message>
<RequestId>6198C8D02EAE0B3131F850B2</RequestId>
<HostId>bj29.cn-beijing.data.alicloudccp.com</HostId>
</Error>
```

**Comment by reruin** [comment]
用手机端提取的token

**Comment by xuange-dada** [comment]
请问一下手机的app抓包请求时哪一个，没有找到refresh token

**Comment by wekingchen** [comment]
> 

https://media.cooluc.com/decode_token/

**Comment by xuange-dada** [comment]
感谢
