### ISSUE TITLE
百度网盘的文件夹id在哪里看

### ISSUE THREAD

**Issue by sw586** [reruin/sharelist#716]
### 问题描述 / Describe the bug

百度网盘的文件夹id在哪里看

### Sharelist 版本 / Sharelist Version

next

### 复现链接 / Reproduction

百度网盘的文件夹id在哪里看

### 日志 / Logs

```shell
百度网盘的文件夹id在哪里看
```

**Comment by lizhongwei-hexo** [comment]
同问
百度网盘的文件夹id在哪里看

**Comment by reruin** [comment]
保持后台登录状态，文件夹后会出现 感叹号，点击可查看 文件夹ID。

**Comment by zhongwei-li** [comment]
> 保持后台登录状态，文件夹后会出现 感叹号，点击可查看 文件夹ID。

sharelist后台还是百度网盘的后台？等了很久没有找到感叹号在哪
