### ISSUE TITLE
安装宝塔的nginx反代端口后，无法支持视频拖动

### ISSUE THREAD

**Issue by emengweb** [reruin/sharelist#72]
直接用33001访问时可以正常拖动视频进度条，使用nginx反代后就无法正常拖动进度了，请教下是什么原因呢？谢谢

**Comment by aumk** [comment]
看下说明里面的反代注意事项
我用的caddy没问题

**Comment by emengweb** [comment]
你好，这是我使用宝塔的nginx加上您附加参数后的效果，依然无法拖动进度条，求指点

dl2.uiday.com/dl/1%20Instalation%20Instructions%20Windows.mp4?preview

**Comment by reruin** [comment]
有可能你使用了旧版本的sharelist， 尝试更新下 bash update.sh。  
我本地测试了google id挂载 和 api挂载 均无此问题。能否将配置文件贴一下，我在本地试试。

**Comment by emengweb** [comment]
使用update.sh后问题依旧，这是nginx的反代配置，用的是宝塔面板安装的nginx 1.15：

server
{
    listen 80;
    server_name dl1.uiday.com;
    index index.php index.html index.htm default.php default.htm default.html;
    root /www/wwwroot/dl1.uiday.com;
    
    #SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
    #error_page 404/404.html;
    #SSL-END
    
    #ERROR-PAGE-START  错误页配置，可以注释、删除或修改
    error_page 404 /404.html;
    error_page 502 /502.html;
    #ERROR-PAGE-END
    
    #PHP-INFO-START  PHP引用配置，可以注释或修改
    #PROXY-START
    location ~ /purge(/.*) { 
        proxy_cache_purge cache_one $host$request_uri$is_args$args;
        #access_log  /www/wwwlogs/dl1.uiday.com_purge_cache.log;
    }
    # 禁止访问后台
    location /manage { 
    }
    # 禁止一切前端api操作
    location /#api { 
    }
    location / 
    {
        # Disable request and response buffering
        proxy_request_buffering off;
        proxy_buffering off;
        proxy_http_version 1.1;
        
        proxy_pass http://127.0.0.1:33001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header REMOTE-HOST $remote_addr;
        
        # 如果server_name不是公网域名，这个地方可以设置成ip
        proxy_set_header X-Forwarded-Host $hostname;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        #这个是设置为0表示不管上传多大的文件都不会报request too large的问题，直接转发过去
        client_max_body_size 0;
                
        #持久化连接相关配置
        #proxy_connect_timeout 30s;
        #proxy_read_timeout 86400s;
        #proxy_send_timeout 30s;
        #proxy_http_version 1.1;
        #proxy_set_header Upgrade $http_upgrade;
        #proxy_set_header Connection "upgrade";
        
        add_header X-Cache $upstream_cache_status;
        
        expires 12h;
    }
    

    #PROXY-END

	include enable-php-00.conf;
    #PHP-INFO-END
    
    #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
    include /www/server/panel/vhost/rewrite/dl1.uiday.com.conf;
    #REWRITE-END
    
    #禁止访问的文件或目录
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }
    
    #一键申请SSL证书验证目录相关设置
    location ~ \.well-known{
        allow all;
    }
    
    access_log  /www/wwwlogs/dl1.uiday.com.log;
    error_log  /www/wwwlogs/dl1.uiday.com.error.log;
}

**Comment by emengweb** [comment]
网上查了些资料，添加了些字段，依然没有解决视频无法拖动的问题。看http头部文件length也有正确返回，很奇怪

**Comment by reruin** [comment]
方便把配置文件 email 给我么。

**Comment by reruin** [comment]
方便把挂载配置（cache/config.json）贴出来看下么。可以email给我。

**Comment by emengweb** [comment]
已经把配置给您email了，请查收

**Comment by emengweb** [comment]
十分感谢您提供的思路！问题已经解决了，我查阅到有资料显示反代时默认nginx是返回200，需要加入这几个参数就好了！

        proxy_set_header Range $http_range;
        proxy_set_header If-Range $http_if_range;
        proxy_no_cache $http_range $http_if_range;

现在测试已经可以正常拖动！再次感谢！
