### ISSUE TITLE
Sharepoint的初始文件夹ID如何获取

### ISSUE THREAD

**Issue by CrueChan** [reruin/sharelist#720]
### 问题描述 / Describe the bug

请问挂载Sharepoint时，初始文件夹ID如何获取？Sharepoint的文件夹链接和OneDrive的文件夹链接区别较大，无法在文件夹连接中了解到文件夹ID。对于Sharepoint的文件夹ID的获取方式不明确。

### Sharelist 版本 / Sharelist Version

next

### 复现链接 / Reproduction

例如根目录下载的pub文件夹的链接形如：https://mycompanyname-my.sharepoint.com/personal/myname_mycompanyname_onmicrosoft_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fmyname%5Fmycompanyname%5Fonmicrosoft%5Fcom%2FDocuments%2Fpub

其中并不包含OneDrive文件夹链接中的ID信息。

**Comment by reruin** [comment]
更新到最新版，文件夹 可查看id。
