### ISSUE TITLE
大佬 新版 teambition 项目无法添加了

### ISSUE THREAD

**Issue by wushuiyin004** [reruin/sharelist#722]
### 问题描述 / Describe the bug

大佬 新版 teambition 项目无法添加了

### Sharelist 版本 / Sharelist Version

next

### 复现链接 / Reproduction

大佬 新版 teambition 项目无法添加了

### 日志 / Logs

```shell
大佬 新版 teambition 项目无法添加了
```

**Comment by reruin** [comment]
自从与aliyudrive 合并后，sharelist就移除了对teambition的支持。
