### ISSUE TITLE
新版 heroku版本配置问题

### ISSUE THREAD

**Issue by uxiaohan** [reruin/sharelist#723]
### 问题描述 / Describe the bug

新版 heroku版本，设置好导出配置并设置好，清除缓存，配置全部失效，恢复默认，怎么解决

### Sharelist 版本 / Sharelist Version

next

**Comment by reruin** [comment]
是从 https://github.com/reruin/sharelist-heroku/tree/next 创建的吗？

**Comment by uxiaohan** [comment]
对的直接点的develop

**Comment by reruin** [comment]
能描述下你的设置过程么。

**Comment by uxiaohan** [comment]
导入，配置页面添加的{}，然后heroku开始搭建，然后进入后台设置，添加onedrive，然后正常使用，然后导出配置，把配置文件上传至我的服务器，更改config为文件地址（文件尝试存在github，直接把JSON数据填入config）保存，然后清缓存，所以设置失效

**Comment by reruin** [comment]
已复现，稍后修复。
