### ISSUE TITLE
webdav 兼容性问题

### ISSUE THREAD

**Issue by OpenSourceUser2021** [reruin/sharelist#733]
### 问题描述 / Describe the bug

经测试发现 以下3个软件
1.QNAP NAS 同步软件，
2.winscp  https://winscp.net/eng/download.php
3. android filemanager   https://apkpure.com/file-manager/com.alphainventor.filemanager
试图连接webdav时会报如下错误
![image](https://user-images.githubusercontent.com/32152540/144950672-5e08724a-9249-4e0a-815a-6191e4af37ed.png)

用RaiDrive 连接则正常
![image](https://user-images.githubusercontent.com/32152540/144950794-185be93d-8446-4dd9-85f3-79fc06b566f3.png)

对比发现似乎是对webdav path处理异常导致，麻烦大佬看看

### Sharelist 版本 / Sharelist Version

next

**Comment by reruin** [comment]
应该是 xml 的解析问题。某些对webdav子路径 支持不太好的，建议将webdav 路径改为空。

**Comment by OpenSourceUser2021** [comment]
0.3.12 修了winscp 跟NAS 的问题 ，但是 android filemanager还是报错，如下为path为空的log

stderr: 
stderr:   Error: non-error thrown: {"code":404,"message":"Can't find [sharelist root] folder"}
stderr:       at Object.onerror (/sharelist/node_modules/koa/lib/context.js:119:31)
stderr:       at onerror (/sharelist/node_modules/koa/lib/application.js:165:32)
stderr:       at processTicksAndRejections (internal/process/task_queues.js:95:5)
stderr: 

下面path为 /webdav时的log
stderr: 
stderr:   Error: non-error thrown: {"code":404,"message":"Can't find [webdav] folder"}
stderr:       at Object.onerror (/sharelist/node_modules/koa/lib/context.js:119:31)
stderr:       at onerror (/sharelist/node_modules/koa/lib/application.js:165:32)
stderr:       at processTicksAndRejections (internal/process/task_queues.js:95:5)
stderr:

**Comment by reruin** [comment]
用0.3.15试试，filemanager 等我找个安卓机做下测试

**Comment by OpenSourceUser2021** [comment]
0.3.15 filemanager 正常了，感谢大佬付出！！！

**Comment by OpenSourceUser2021** [comment]
补充下，NAS path 虽然没问题了，但是连不上
stdout: [WebDAV] PROPFIND /webdav/ <--> ::ffff:192.168.1.79
stdout: [WebDAV] PROPFIND /webdav/ <--> ::ffff:192.168.1.79
stdout: [WebDAV] PROPFIND /webdav/ <--> ::ffff:192.168.1.79
stdout: [WebDAV] PROPFIND /webdav/ <--> ::ffff:192.168.1.79
stdout: [WebDAV] PROPFIND /webdav/ <--> ::ffff:192.168.1.79

![image](https://user-images.githubusercontent.com/32152540/148221051-38d05064-0fab-4f4c-8c89-f77f45fd189e.png)

另外，ARM64 能否提供静态编译版本，我用的openwrt arm64版需要docker 才可以运行，但是arm7 静态编译的则可以直接运行 nodejs 已装
