### ISSUE TITLE
关于和彩云挂载更简单的做法

### ISSUE THREAD

**Issue by yjacks** [reruin/sharelist#736]
### 需求描述 / Description of the feature

iPad网页版本的和彩云(域名http://mcloud.139.com/static/html/ipad.html)可以在无需验证码的情况下进行登录，时效性根据测试，在24h左右

### 实现思路 / Suggested solution

通过实现一个爬虫，捕捉get请求带的新域名，格式https://mcloud.139.com/index.html?
sid=***&
rnd=908&
comefrom=2066&
useInnerWeb=0&
k=3647&
ishttps=1
&fid=1&
clientid=10804
&loginsuccessurl=http%3A%2F%2Fmcloud.139.com%2Findex.html&
auto=1&
artifact=***
&passid=***8&
cguid=***
&mtime=int#/
剩下的貌似都是Post请求

**Comment by hbqjren** [comment]
这个是以前的和彩云网盘网页。连彩云官方都停止维护了。目录获取的问题，网址sid等等问题。我倒是希望有人能弄cloudflare worker
