### ISSUE TITLE
3号更新后OnedriveAPI访问出错

### ISSUE THREAD

**Issue by wekingchen** [reruin/sharelist#74]
上个版本一切正常，更新后显示Error-500，具体信息如下：

Error
Looks like something broke!
 
TypeError: data.children is not iterable
    at Object.index (/root/sharelist/app/controllers/sharelist.js:81:25)
    at <anonymous>

**Comment by reruin** [comment]
能贴下配置吗，私发到 reruin@gmail.com

**Comment by wekingchen** [comment]
好的，请问需要贴哪些内容？

**Comment by reruin** [comment]
已修复。你再试一下。

**Comment by wekingchen** [comment]
更新后ok了，谢谢！
