### ISSUE TITLE
谁能救救我，WIN无法定位程序输入点

### ISSUE THREAD

**Issue by nomoneynolife** [reruin/sharelist#741]
### 问题描述 / Describe the bug

![image](https://user-images.githubusercontent.com/53741948/147072790-9bf13eae-0ee8-4d3f-9dd0-39fe32f0c4a2.png)

### Sharelist 版本 / Sharelist Version

next

### 复现链接 / Reproduction

0.3.11

**Comment by reruin** [comment]
已在 #742  中回复。
