### ISSUE TITLE
exe内的node.js版本过高吗？电脑只支持NODE.JS 13.0.0以下的版本

### ISSUE THREAD

**Issue by nomoneynolife** [reruin/sharelist#742]
### 问题描述 / Describe the bug

Node.js is only supported on Windows 8.1, Windows Server 2012 R2, or higher.
Setting the NODE_SKIP_PLATFORM_CHECK environment variable to 1 skips this
check, but Node.js might not execute correctly. Any issues encountered on
unsupported platforms will not be fixed.

### Sharelist 版本 / Sharelist Version

next

### 复现链接 / Reproduction

大佬怎么办

### 日志 / Logs

```shell
不知道怎么在
WINDOWS 2008 R2 使用
```

**Comment by reruin** [comment]
1. fork此项目到个人库；
2. 修改 ```.github/workflows/ci.yml``` ，将 node-version 修改为14以下，保存。
3. 等待github flow自动构建，完成后去release下载。

**Comment by reruin** [comment]
相关 #759
