### ISSUE TITLE
阿里云token频繁失效

### ISSUE THREAD

**Issue by xuange-dada** [reruin/sharelist#746]
### 问题描述 / Describe the bug

https://media.cooluc.com/decode_token/ 手机浏览器使用此获得token后可以正常挂载，但Heroku休眠后经常失效

### Sharelist 版本 / Sharelist Version

v0.1

### 日志 / Logs

```shell
Teambition 挂载向导
无法获取登录token

点击重新开始
```

**Comment by reruin** [comment]
heroku 休眠会丢失数据，是否设置过CONFIG 变量？
