### ISSUE TITLE
网站标题设置不生效

### ISSUE THREAD

**Issue by benzBrake** [reruin/sharelist#747]
### 问题描述 / Describe the bug

后台设置网站标题后标题仍为 Sharelist

### Sharelist 版本 / Sharelist Version

next

### 复现链接 / Reproduction

https://561234.xyz

**Comment by reruin** [comment]
更新再试试。

**Comment by benzBrake** [comment]
网页左上角没问题了，但 Title 还是没有设置的名称，仅显示 Sharelist

**Comment by YTURING** [comment]
移动端需要把index.0809c3de.js文件里的Sharelist手动改为自己的标题。

**Comment by reruin** [comment]
已修复。
