### ISSUE TITLE
小白请教问题，docker下运行该如何更新程序？谢谢指教！~

### ISSUE THREAD

**Issue by api81244390** [reruin/sharelist#749]
### 问题描述 / Describe the bug

我看二进制运行后还有自定义脚本和自定义样式，网站标题也生效，但docker
部署的就没有自定义脚本和自定义样式，网站标题改了也不生效。谢谢指教。

### Sharelist 版本 / Sharelist Version

next

**Comment by reruin** [comment]
重新拉取镜像。
