### ISSUE TITLE
OneDrive个人账户获取 应用机密 和 应用ID 演示

### ISSUE THREAD

**Issue by reruin** [reruin/sharelist#75]
前往 [Azure管理后台](https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade) 注册应用并获取  app_id 和 app_secret 。  

![b001](https://user-images.githubusercontent.com/7403780/70111071-10203480-168c-11ea-9467-6795f776399d.png)
![b002](https://user-images.githubusercontent.com/7403780/70111072-10203480-168c-11ea-91d8-09047491f100.png)
![b003](https://user-images.githubusercontent.com/7403780/70111073-10b8cb00-168c-11ea-949b-40fbbdc13200.png)
![b004](https://user-images.githubusercontent.com/7403780/70111074-10b8cb00-168c-11ea-97a3-af091dd0a5c0.png)
![b005](https://user-images.githubusercontent.com/7403780/70111075-11516180-168c-11ea-823e-1124f08a3732.png)
![b006](https://user-images.githubusercontent.com/7403780/70111078-11516180-168c-11ea-8bcb-09ababf12552.png)

**Comment by aumk** [comment]
大佬，用API挂载的Onedrive走服务器流量吗

**Comment by reruin** [comment]
Onedrive API版 默认不走服务器流量。

**Comment by reee** [comment]
不太清楚绑定OneDrive的路径那儿怎么写，我老是遇到 invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.

**Comment by ZanderZhao** [comment]
> 不太清楚绑定OneDrive的路径那儿怎么写，我老是遇到 invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.

+ 如果只挂载一个盘，重定向url就写`https://你的域名`，
+ 如果挂载两个盘及以上，就写`https://你的域名/挂载虚拟路径`，
  + `挂载虚拟路径`是后台`OD API版`**后面的那个自定义字段**，不是你的onedrive分享路径

**Comment by coolsd** [comment]
能来个示例吗

**Comment by qian9008** [comment]
图片全挂了
