### ISSUE TITLE
我搭建了 怎么才能上传webdav 我挂的是od

### ISSUE THREAD

**Issue by 821368256** [reruin/sharelist#750]
### 问题描述 / Describe the bug

无法上传 webdav无权限 

### Sharelist 版本 / Sharelist Version

v0.1

**Comment by reruin** [comment]
请用最新版，v0.1 不支持上传。

**Comment by 821368256** [comment]
我用docker直接拉的最新版





------------------ 原始邮件 ------------------
发件人: Ting ***@***.***&gt;
发送时间: 2022年1月1日 14:17
收件人: reruin/sharelist ***@***.***&gt;
抄送: 821368256 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [reruin/sharelist] 我搭建了 怎么才能上传webdav 我挂的是od (Issue #750)

**Comment by reruin** [comment]
最新版用 reruin/sharelist:next 

reruin/sharelist:latest 目前是v0.1 分支

**Comment by 821368256** [comment]
谢谢





------------------ 原始邮件 ------------------
发件人: Ting ***@***.***&gt;
发送时间: 2022年1月1日 14:17
收件人: reruin/sharelist ***@***.***&gt;
抄送: 821368256 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [reruin/sharelist] 我搭建了 怎么才能上传webdav 我挂的是od (Issue #750)






请用最新版，v0.1 不支持上传。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 821368256** [comment]
我重新拉取了新版，挂载了世纪互联后通过webdav同步本地文件到世纪互联速度不稳定刚开始能跑到4MB左右，几分钟后就基本200多kb或者没速度，我同时也在使用cloudreve速度就相对稳定





------------------ 原始邮件 ------------------
发件人: Ting ***@***.***&gt;
发送时间: 2022年1月1日 14:17
收件人: reruin/sharelist ***@***.***&gt;
抄送: 821368256 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [reruin/sharelist] 我搭建了 怎么才能上传webdav 我挂的是od (Issue #750)






请用最新版，v0.1 不支持上传。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 821368256** [comment]
上传无速度时docker终端机显示如下

![image](https://user-images.githubusercontent.com/36266356/147999208-b5e27f3c-9461-4ffd-b919-906dd9b3d8c6.png)

**Comment by 821368256** [comment]
查看了 #733 修改webdav为空速度保持全速上传 但是  群辉cloudsync 全部提示上传失败未找到远程文件 同时一直高速上传日志如下
![image](https://user-images.githubusercontent.com/36266356/148001891-bbd09cf7-e52c-43fc-bd23-cde1b720601c.png)

**Comment by 821368256** [comment]
而且选远程目录时大部分文件夹群辉sync会提示系统错误
@reruin

**Comment by reruin** [comment]
可能需要在 群辉cloudsync 上做进一步测试，但是目前没有此环境。

**Comment by 821368256** [comment]
我可以提供😁怎么联系



------------------ 原始邮件 ------------------
发件人: Ting ***@***.***&gt;
发送时间: 2022年1月4日 13:25
收件人: reruin/sharelist ***@***.***&gt;
抄送: 821368256 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [reruin/sharelist] 我搭建了 怎么才能上传webdav 我挂的是od (Issue #750)






可能需要在 群辉cloudsync 上做进一步测试，但是目前没有此环境。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by reruin** [comment]
@821368256 reruin@gmail.com

**Comment by reruin** [comment]
已解决。

**Comment by daxiaraoming** [comment]
> 已解决。

是什么原因,怎么解决的
