### ISSUE TITLE
小白请教大佬能否增加arm32位的

### ISSUE THREAD

**Issue by 1234wsad** [reruin/sharelist#752]
### 问题描述 / Describe the bug

一些设备不是64位的，比如玩客云，arm64位的无法使用

### Sharelist 版本 / Sharelist Version

next

**Comment by reruin** [comment]
试下 https://github.com/reruin/sharelist/releases/tag/v0.3.13 armv7
缺少测试设备，不能保证可用。

**Comment by 1234wsad** [comment]
> 试下 https://github.com/reruin/sharelist/releases/tag/v0.3.13 armv7 缺少测试设备，不能保证可用。
十分感谢，可以安装使用
