### ISSUE TITLE
webdav上传无速度

### ISSUE THREAD

**Issue by 821368256** [reruin/sharelist#755]
### 问题描述 / Describe the bug

挂载的世纪互联的od 日志如下
![image](https://user-images.githubusercontent.com/36266356/148145970-f5be3e25-0a3e-4e03-9697-d5706e8e0f0a.png)
  

### Sharelist 版本 / Sharelist Version

next

**Comment by reruin** [comment]
0.3.15 试下，修复了od大文件上传失败的问题。

**Comment by GMOogway** [comment]
请问，docker版0.3.15搭建好了，挂载了天翼云盘，网页版列表下载没问题，但上面没有可以上传的地方，在客户端上使用webdav方式挂载后，也是只能列表，但无法上传，这是哪儿配置不对吗。

**Comment by 821368256** [comment]
你用的什么webdav客户端，内网还是外网





------------------ 原始邮件 ------------------
发件人: GMOogway ***@***.***&gt;
发送时间: 2022年1月15日 18:07
收件人: reruin/sharelist ***@***.***&gt;
抄送: 821368256 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [reruin/sharelist] webdav上传无速度 (Issue #755)






请问，docker版0.3.15搭建好了，挂载了天翼云盘，网页版列表下载没问题，但上面没有可以上传的地方，在客户端上使用webdav方式挂载后，也是只能列表，但无法上传，这是哪儿配置不对吗。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GMOogway** [comment]
> 你用的什么webdav客户端，内网还是外网
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: GMOogway ***@***.***&gt; 发送时间: 2022年1月15日 18:07 收件人: reruin/sharelist ***@***.***&gt; 抄送: 821368256 ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [reruin/sharelist] webdav上传无速度 (Issue #755) 请问，docker版0.3.15搭建好了，挂载了天翼云盘，网页版列表下载没问题，但上面没有可以上传的地方，在客户端上使用webdav方式挂载后，也是只能列表，但无法上传，这是哪儿配置不对吗。 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我把配置文件中anonymous_upload_enable改成true了。用群晖，都在同一局域网中，用远程挂载好后，可以看到文件列表，可以下载，可以新建目录，但无法上传文件，说不支持该操作，真的搞不清楚了。

**Comment by GMOogway** [comment]
我试着又挂了个阿里云，新建了一个test目录，然后试着复制一个文件license.lic进去，发生错误：
sharelist_1            | [WebDAV] HEAD /aliyun/test/license.lic <--> ::ffff:10.199.0.23
sharelist_1            | [WebDAV] PROPFIND /aliyun/test/license.lic <--> ::ffff:10.199.0.23
sharelist_1            | [CACHE] 2022-01-15T10:19:58.705Z aliyun://06d64b6d3af6481fba43869678cb8429/root#list
sharelist_1            | [CACHE] 2022-01-15T10:19:58.705Z aliyun://06d64b6d3af6481fba43869678cb8429/61e29faec153e4e27729441a93a5946089267951#list
sharelist_1            | [WebDAV] PROPFIND /aliyun/test/license.lic <--> ::ffff:10.199.0.23
sharelist_1            | [CACHE] 2022-01-15T10:19:58.757Z aliyun://06d64b6d3af6481fba43869678cb8429/root#list
sharelist_1            | [CACHE] 2022-01-15T10:19:58.757Z aliyun://06d64b6d3af6481fba43869678cb8429/61e29faec153e4e27729441a93a5946089267951#list
sharelist_1            | 
sharelist_1            |   Error: non-error thrown: {"code":404,"message":"Can't find [license.lic] folder"}
sharelist_1            |       at Object.onerror (/sharelist/node_modules/koa/lib/context.js:119:31)
sharelist_1            |       at onerror (/sharelist/node_modules/koa/lib/application.js:165:32)
sharelist_1            |       at runMicrotasks (<anonymous>)
sharelist_1            |       at processTicksAndRejections (internal/process/task_queues.js:95:5)
Can't find [license.lic] folder，为啥app把license.lic当成一个目录？

**Comment by 821368256** [comment]
我具体也不清楚，我用群晖sync同步到od正常，





------------------ 原始邮件 ------------------
发件人: GMOogway ***@***.***&gt;
发送时间: 2022年1月15日 18:24
收件人: reruin/sharelist ***@***.***&gt;
抄送: 821368256 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [reruin/sharelist] webdav上传无速度 (Issue #755)






我试着又挂了个阿里云，新建了一个test目录，然后试着复制一个文件license.lic进去，发生错误：
sharelist_1            | [WebDAV] HEAD /aliyun/test/license.lic <--&gt; ::ffff:10.199.0.23
sharelist_1            | [WebDAV] PROPFIND /aliyun/test/license.lic <--&gt; ::ffff:10.199.0.23
sharelist_1            | [CACHE] 2022-01-15T10:19:58.705Z aliyun://06d64b6d3af6481fba43869678cb8429/root#list
sharelist_1            | [CACHE] 2022-01-15T10:19:58.705Z aliyun://06d64b6d3af6481fba43869678cb8429/61e29faec153e4e27729441a93a5946089267951#list
sharelist_1            | [WebDAV] PROPFIND /aliyun/test/license.lic <--&gt; ::ffff:10.199.0.23
sharelist_1            | [CACHE] 2022-01-15T10:19:58.757Z aliyun://06d64b6d3af6481fba43869678cb8429/root#list
sharelist_1            | [CACHE] 2022-01-15T10:19:58.757Z aliyun://06d64b6d3af6481fba43869678cb8429/61e29faec153e4e27729441a93a5946089267951#list
sharelist_1            |
sharelist_1            |   Error: non-error thrown: {"code":404,"message":"Can't find [license.lic] folder"}
sharelist_1            |       at Object.onerror (/sharelist/node_modules/koa/lib/context.js:119:31)
sharelist_1            |       at onerror (/sharelist/node_modules/koa/lib/application.js:165:32)
sharelist_1            |       at runMicrotasks ()
sharelist_1            |       at processTicksAndRejections (internal/process/task_queues.js:95:5)
Can't find [license.lic] folder，为啥app把license.lic当成一个目录？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GMOogway** [comment]
> 我具体也不清楚，我用群晖sync同步到od正常，
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: GMOogway ***@***.***&gt; 发送时间: 2022年1月15日 18:24 收件人: reruin/sharelist ***@***.***&gt; 抄送: 821368256 ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [reruin/sharelist] webdav上传无速度 (Issue #755) 我试着又挂了个阿里云，新建了一个test目录，然后试着复制一个文件license.lic进去，发生错误： sharelist_1 | [WebDAV] HEAD /aliyun/test/license.lic <--&gt; ::ffff:10.199.0.23 sharelist_1 | [WebDAV] PROPFIND /aliyun/test/license.lic <--&gt; ::ffff:10.199.0.23 sharelist_1 | [CACHE] 2022-01-15T10:19:58.705Z aliyun://06d64b6d3af6481fba43869678cb8429/root#list sharelist_1 | [CACHE] 2022-01-15T10:19:58.705Z aliyun://06d64b6d3af6481fba43869678cb8429/61e29faec153e4e27729441a93a5946089267951#list sharelist_1 | [WebDAV] PROPFIND /aliyun/test/license.lic <--&gt; ::ffff:10.199.0.23 sharelist_1 | [CACHE] 2022-01-15T10:19:58.757Z aliyun://06d64b6d3af6481fba43869678cb8429/root#list sharelist_1 | [CACHE] 2022-01-15T10:19:58.757Z aliyun://06d64b6d3af6481fba43869678cb8429/61e29faec153e4e27729441a93a5946089267951#list sharelist_1 | sharelist_1 | Error: non-error thrown: {"code":404,"message":"Can't find [license.lic] folder"} sharelist_1 | at Object.onerror (/sharelist/node_modules/koa/lib/context.js:119:31) sharelist_1 | at onerror (/sharelist/node_modules/koa/lib/application.js:165:32) sharelist_1 | at runMicrotasks () sharelist_1 | at processTicksAndRejections (internal/process/task_queues.js:95:5) Can't find [license.lic] folder，为啥app把license.lic当成一个目录？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我挂了od也不行，一样的错误。。。

**Comment by reruin** [comment]
应该是之前的OneDrive大文件同步bug，已修复。
