### ISSUE TITLE
希望可以添加一個關於Google drive的功能

### ISSUE THREAD

**Issue by ericishere** [reruin/sharelist#76]
希望能在網頁內直接上傳文件到Google Drive

**Comment by ericishere** [comment]
謝謝

**Comment by reruin** [comment]
会在近期实现。

**Comment by emengweb** [comment]
太好了！赞！

**Comment by reruin** [comment]
已此功能的实验性版本，目前支持 本地磁盘、gda、oda的上传。  
使用中可能出现各类问题，待后续完善。

**Comment by ericishere** [comment]
謝謝，因為是私人使用的，所以希望能夠增加免密碼就能直接上傳的功能或選項，進一步增加便利性。

**Comment by reruin** [comment]
> 謝謝，因為是私人使用的，所以希望能夠增加免密碼就能直接上傳的功能或選項，進一步增加便利性。

后台管理 -> 启用匿名上传

**Comment by ericishere** [comment]
感謝
