### ISSUE TITLE
登录后台，或者修改任何东西保存后都出现这个界面

### ISSUE THREAD

**Issue by lsyyktv** [reruin/sharelist#779]
### 问题描述 / Describe the bug

最近几天登录后台，或者修改任何东西保存后都出现这个界面

### Sharelist 版本 / Sharelist Version

v0.1

### 复现链接 / Reproduction

![image](https://user-images.githubusercontent.com/39065858/151938612-6c919de6-ef35-4675-9f8a-c9fec2b96769.png)

**Comment by lsyyktv** [comment]
![image](https://user-images.githubusercontent.com/39065858/151938767-ad33cac9-5d74-4195-a7ec-b0b117e39aed.png)
然后，后台的界面变成这样了
已经重开一台VPS来新装sharelist 0.1版本了，结果还是这样

**Comment by kenviei** [comment]
把主题内theme/default/view/partial/layout.pug文件中'//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css' 替换成' //cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css ' 然后重启pm2项目即可

**Comment by lsyyktv** [comment]
> 

谢谢，按照你的方法成功解决！
