### ISSUE TITLE
在线安装成功完成后未成功启动，33001端口未找到监听进程

### ISSUE THREAD

**Issue by gayhub-dev** [reruin/sharelist#78]
系统Centos7 node版本6.17.1 
安装目录手动执行
pm2 start app.js --name sharelist --env prod
/root/.pm2/pm2.log错误日志:
/usr/lib/node_modules/pm2/node_modules/chokidar/index.js:151
  async remove(item) {
        ^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/Watcher.js:6:16)

**Comment by reruin** [comment]
node 版本需要 >= 8.x  
你是使用 install.sh 脚本安装的吗？

**Comment by gayhub-dev** [comment]
> node 版本需要 >= 8.x
> 你是使用 install.sh 脚本安装的吗？

在线和本地两种方式都试过了,升级node版本之后可以启动了,不过Googledriveapi方式挂载不上,点验证后又返回到验证页面了

**Comment by reruin** [comment]
gd api挂载的bug 已修复。bash update.sh 更新下。

**Comment by gayhub-dev** [comment]
> gd api挂载的bug 已修复。bash update.sh 更新下。

挂上了,下载文件可以不通过服务器代理吗,就返回googleapi直链,或者给个开关啥的,还有为啥我改config.json里端口没有用呢,程序还是监听33001端口

**Comment by reruin** [comment]
[Google Drive API](https://developers.google.com/drive/api/v3/reference/files/get) 官方未提供直连下载功能，因而此插件将强制使用服务器代理。  
在config.json 修改端口后，需重启服务后生效。

**Comment by gayhub-dev** [comment]
> [Google Drive API](https://developers.google.com/drive/api/v3/reference/files/get) 官方未提供直连下载功能，因而此插件将强制使用服务器代理。
> 在config.json 修改端口后，需重启服务后生效。
api是可以直接下载的,在请求URL后面加?alt=media,比如https://www.googleapis.com/drive/v3/files/fileId?alt=media 请求header加authorization:Bearer [access-token] 就可以了;
重启生效那个,这个姿势应该没问题吧, pm2 restart sharelist 可就是死活不生效~

**Comment by reruin** [comment]
你说的没错。我指的是 API没有提供像OD那样的临时链接，可供用户直接访问下载。  

修改端口的问题，最好先停止sharelist ，再修改端口，最后运行sharelist。
