### ISSUE TITLE
希望可以增加链接防盗链开关

### ISSUE THREAD

**Issue by emengweb** [reruin/sharelist#79]
根据设置的密钥自动按照时间生成不可逆的key，请求文件下载前，服务端先校验指定的key，是否与服务端按照密钥+昨日、密钥+当日、密钥+明日的（做有效期校验）匹配，匹配成功后返回文件流。

可以用于反迅雷、反盗链；
进一步扩展：通过加密算法复用，可以修改与网站代码，自动生成密钥用于防盗链。

感觉这一步可以防止服务器被迅雷拉爆、盗链、偷跑流量，做到真正通过本站访问的真实用户，才可以下载到资源。

**Comment by reruin** [comment]
下载有效期确实可以通过加key，进行时间校验来解决。设置较短的有效期（30分钟以内）可以避免被盗链。此功能可以很快实现。

更严格的反盗链，不如开发会员模式。目前没有时间做这块。

目前的开发计划是：上传、迁移（网盘搬家）、sharelist客户端。

**Comment by reruin** [comment]
以实现 链接有效期 。

**Comment by emengweb** [comment]
客户端！NB！强烈支持啊~哈哈

**Comment by emengweb** [comment]
开启了防盗链，不过文件不加防盗码依然可以直接下载。。。
http://dl2.uiday.com/exp/preview/work.docx

**Comment by emengweb** [comment]
另外，使用脚本升级后，之前挂载googleDriveAPI失效，上传凭证重新获取密钥后，再打开就直接报错了

**Comment by reruin** [comment]
这里是有个bug，比预料的要复杂一些，还要排除文件夹的情况。 你再试试。

**Comment by emengweb** [comment]
update.sh之后依然不行。。。

**Comment by reruin** [comment]
链接有效性的问题ok了么。

**Comment by emengweb** [comment]
> 链接有效性的问题ok了么。

依然不行，开启链接有效期功能之后，本地文件加不加t参数都可以正常下载，gd挂载盘的目录访问则提示“ Forbidden”。

但是如果手动把gd盘下目录和文件加上正确的t参数后，是可以正常访问和下载的。 

另外，预览页也无法获取正确视频资源，我看了下应该是缺少t参数导致的。

推测：GD挂载由于没有判定目录类型，导致目录如果不加t参数无法正确浏览内容。本地挂载可能判定t参数的部分有些漏洞，导致缺少t参数就跳过了有效性校验直接返回了元数据。

建议：可以使用文件名(前n位)给t参数加加盐，现在所有文件的加密码都是等同的，根据文件名生成特殊的t参数，放盗链上会更加稳固！

作者大大很给力了！短短几天时间已经实现了这么多功能，大赞！

**Comment by reruin** [comment]
1. 本地文件挂载未发现这个问题，未复现。
2. gd的问题已修复，该问题存在于所有支持缓存的挂载类型中，由于缓存数据的类型被错误的修改，造成此问题。
3. t的生成规则为 md5(salt+timestamp / 链接有效期)，salt 保存在配置文件的 max_age_download_sign 内。同一个目录下列出的文件使用相同的t，每次访问t都会更新。
加入文件相关信息（文件名 或 id）并不会使得链接更安全，所有的信息都是可见的，除了 salt.

**Comment by emengweb** [comment]
> 1. 本地文件挂载未发现这个问题，未复现。
> 2. gd的问题已修复，该问题存在于所有支持缓存的挂载类型中，由于缓存数据的类型被错误的修改，造成此问题。
> 3. t的生成规则为 md5(salt+timestamp / 链接有效期)，salt 保存在配置文件的 max_age_download_sign 内。同一个目录下列出的文件使用相同的t，每次访问t都会更新。
>    加入文件相关信息（文件名 或 id）并不会使得链接更安全，所有的信息都是可见的，除了 salt.

等待commit，稍候我再测试下，谢谢！关于安全的问题特别赞同，毕竟源码都是开源的 TvT，所以如果需要实现更高级别的加密，只能在加密字符串中特定位数添加随机字符这种形式了，哈哈，这只是我自己拍脑门能想到一种方法，不过目前对于防盗链来说相当足够了！

**Comment by emengweb** [comment]
更新最新版本后GD问题通过，加密目录也可以正常浏览文件了；
加密后预览信息可以正确加载！欧耶~！
