### ISSUE TITLE
升级后，无法正确挂载GD API

### ISSUE THREAD

**Issue by emengweb** [reruin/sharelist#80]
旧的配置失效，使用.ln挂载已然失效。
重新获取授权后依旧提示：
挂载 GoogleDrive 失败
失败请重试。原因：Bad Request

点此重新开始

**Comment by reruin** [comment]
gd_api 调整了配置文件，需重新挂载绑定。

**Comment by emengweb** [comment]
我重新在git上下载最新包，安装了下，依然无法挂载。
安装时，添加GDAPI，命名dl，将密钥按照之前挂载时的填好，保存后提示：
挂载 GoogleDrive 失败
失败请重试。原因：Bad Request

点此重新开始

**Comment by emengweb** [comment]
好了，完全按照流程走下来，终于可以正常挂载了，旧版本可以使用以前我为rclone创建的私有key，新的版本看来不支持，所以导致无法挂载，必须重新按照指导里，enable API走一套流程才可以

**Comment by emengweb** [comment]
按照新的gdapi挂载说明，把路径改成root，挂载成功了，之后再改为自定义目录的id，终于正常了，谢谢！
