### ISSUE TITLE
svg格式的文件无法下载，会导致服务器错误

### ISSUE THREAD

**Issue by emengweb** [reruin/sharelist#81]
http://xxx.com/test/14)%20ControlKit/
此目录下的svg文档皆会导致服务器错误，经测试本地和gd皆会导致此问题，前端为nginx反代sharelist。
http://xxx.com/test/14)%20ControlKit/Close.svg?t=09c84c843f5bc7f9795e5a2a998cabfe

**Comment by emengweb** [comment]
自查清楚了，是反代cf导致的问题，暂时无解

**Comment by emengweb** [comment]
另外，升级后gd的文件时间显示不正确，是不是没有处理+8时区？

**Comment by reruin** [comment]
时间的话比较乱，fs/gd/od 使用服务器所在时区，gda/oda 使用 utc。  准备全部统一成utc
感谢你的持续反馈。

**Comment by emengweb** [comment]
这套系统真的很优秀，Nodejs搭配网盘简直绝配！性能Max！
后续如果做成类似NextCloud那种私人网盘系统，绝对NB！其实NextCloud稳定性很差劲，对性能要求也高，集团里配的内部网盘就经常挂。希望Sharelist可以越来越棒！
