### ISSUE TITLE
作者能不能做一下网盘的迁移功能

### ISSUE THREAD

**Issue by huarzone** [reruin/sharelist#812]
### 需求描述 / Description of the feature

最近想把阿里云盘数据迁移到Onedrive但是都没有发现可用的解决方案。

**Comment by goldcome** [comment]
rclone不是很好的解决方案？

**Comment by StefanZhang** [comment]
> ### 需求描述 / Description of the feature
> 最近想把阿里云盘数据迁移到Onedrive但是都没有发现可用的解决方案。
> 
> ### 实现思路 / Suggested solution
> _No response_
> 
> ### 附件 / Additional context
> _No response_

可以找一台 vps中转， 用rclone挂载onedrive, 然后找一个aria2下载完成自动上传的脚本，阿里云用aria2下就可以了

**Comment by huarzone** [comment]
谢谢，今天试一下

**Comment by maryjeck** [comment]
可以用rclone + rsync 做迁移么？？？？
