### ISSUE TITLE
Onedrive API模式，下载不稳定总是被中断，但是在OneDrive官网直接下却是满速，很稳定

### ISSUE THREAD

**Issue by Amarillys** [reruin/sharelist#82]
请问可能的原因是为什么
Edge下载提示：无法下载 - 网络问题
FDM也是一会就断开了，显示：连接被远程服务器关闭

地址：https://restia.misuzu.moe/

**Comment by reruin** [comment]
是否开启了中转模式？

**Comment by Amarillys** [comment]
打开了中转，我关掉试试看

**Comment by Amarillys** [comment]
我明白了，我的主机这边环境不好开了中转导致的，感谢解答，问题解决了
