### ISSUE TITLE
上传功能还有一些问题

### ISSUE THREAD

**Issue by aumk** [reruin/sharelist#86]
onedrive上传大文件时会断开，显示
“上传失败。undefined”
大概是3.6G的文件传到15%左右的时候

上传500M左右的时候进度条可以走到100%
之后会弹框
“上传失败。请求实体太大”

**Comment by reruin** [comment]
是否有使用 nginx 做代理

**Comment by aumk** [comment]
> 是否有使用 nginx 做代理

使用的是caddy反向代理
example.com {
    header / Strict-Transport-Security "max-age=31536000;"
    proxy / http://127.0.0.1:33001 {
        transparent
    }
    tls {
        dns cloudflare
        alpn h2
    }
}

**Comment by reruin** [comment]
修复了一些问题，你再试试，本地测试通过了多个4G左右的文件上传。

**Comment by aumk** [comment]
> 修复了一些问题，你再试试，本地测试通过了多个4G左右的文件上传。

大佬我好像找到原因了
更新完再测试还是不行，我又想了想把cloudflare的CDN关了居然就可以了。
上传一个1G大小的文件成功，看来就是因为CDN了。
上传一个5G大小的文件，传到91%速度变成0不动了，是不是不支持断点续传啊。不过没出现弹框错误

**Comment by reruin** [comment]
sharelist没有对上传的断点续传提供支持。
