### ISSUE TITLE
作者你好，可以增加天翼云盘的支持吗？

### ISSUE THREAD

**Issue by nnnnnccccc** [reruin/sharelist#87]
最近天翼云盘直链的网站源码也出来了，相对来说国内使用天翼云盘速度，稳定性都是最好的，还不需要翻墙。可以顺带把天翼云盘的支持加进去吗？非常感谢。

**Comment by reruin** [comment]
天翼云开发者注册过于繁琐，能否提供一套天翼云开发者账号。

**Comment by nnnnnccccc** [comment]
189CloudLink工具
https://github.com/Srar/189CloudLinkTools



18068566677@189.cn
 
发件人： Ting
发送时间： 2020-01-03 14:01
收件人： reruin/sharelist
抄送： nnnnnccccc; Author
主题： Re: [reruin/sharelist] 作者你好，可以增加天翼云盘的支持吗？ (#87)
天翼云开发者注册过于繁琐，能否提供一套天翼云开发者账号。

**Comment by reruin** [comment]
我指的是天翼云盘需要[注册](http://open.189.cn/)开发者，期间需提供身份证，比较麻烦。

**Comment by 24021438** [comment]
[authentication.zip](https://github.com/reruin/sharelist/files/4203181/authentication.zip)
天翼开放平台认证授权接口示例 for PHP SDK里面包含测试api

**Comment by reruin** [comment]
这个还是要用天翼帐号登录才能用。

**Comment by reruin** [comment]
已支持。
