### ISSUE TITLE
怎么在首页添加说明呢？

### ISSUE THREAD

**Issue by hl668** [reruin/sharelist#88]
我知道可以通过README中的内容来显示当前目录中我想显示指定的内容。如果是首页想显示呢？因为首页都是挂载出来的目录文件夹，没办法放一个README文件来显示内容啊

**Comment by reruin** [comment]
好问题。更新一版。

1. 挂载一个名为 readme.md 的fs路径  
2. 添加 忽略路径 /readme.md

**Comment by hl668** [comment]
![1](https://user-images.githubusercontent.com/47386710/71797121-bbefe200-3087-11ea-851c-dfc81f5a14cd.PNG)
![2](https://user-images.githubusercontent.com/47386710/71797126-c0b49600-3087-11ea-8087-854e8e2b9826.PNG)
请问是这样吗，然后我在LInux根目录添加了一个显示内容的readme.md文件，但是这样挂载的目录怎么显示出来了，并没有忽略啊,也许是我挂载的方式不对，作者你看一下，谢谢了。

**Comment by reruin** [comment]
是这样的。readme.md 显示出来是因为当前处于登录状态，取消登录即可。
登录状态时，所有过滤的文件后缀/目录 均会显示。
