### ISSUE TITLE
有关于CSS加载的问题

### ISSUE THREAD

**Issue by fyuneru0830** [reruin/sharelist#89]
在AWS EC2上无论是远程一键脚本还是git下来install.sh安装完成后无法看到css

出错环境：
Cent 7
Ubuntu
Chrome报错：
Failed to load resource: the server responded with a status of 404 (Not Found)
main.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
font.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
main.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
其余功能都正常。
请问如何解决

**Comment by reruin** [comment]
重启一次sharelist即可。

**Comment by fyuneru0830** [comment]
感谢回复
尝试了：重启Sharelist，清理缓存，重启vps。
都不行。

**Comment by reruin** [comment]
已修复。更新一下试试。
