### ISSUE TITLE
heroku可以直接搭建吗

### ISSUE THREAD

**Issue by tangxuchao** [reruin/sharelist#90]
heroku可以直接搭建吗

**Comment by reruin** [comment]
可以的   
[![Deploy](https://www.herokucdn.com/deploy/button.png)](https://heroku.com/deploy?template=https://github.com/reruin/sharelist-heroku)

**Comment by tangxuchao** [comment]
老哥，他的挂载是类似于oneindex那样子的吗，我一共两个onedrive盘

**Comment by tangxuchao** [comment]
点了那个后 让我填配置文件(JSON字符串 或 http远程文件)   这个填啥

**Comment by tangxuchao** [comment]
![image](https://user-images.githubusercontent.com/42133265/71884490-6f81d080-3173-11ea-81dc-a77a86f1033e.png)

**Comment by tangxuchao** [comment]
老哥 装好了，但是不会挂载onedrive。。

**Comment by reruin** [comment]
1. 免费版的heroku无法保存数据，因而需要自己设定配置项， CONFIG 里填写的便是 ./cache/config.json文件内容。你可以输入 ```{}``` 表示使用默认配置。

待挂载完成后，从sharelist管理后台导出配置文件，重新设置heroku的CONFIG项。
![image](https://user-images.githubusercontent.com/7403780/71944456-ca143e80-31fe-11ea-947a-abd95a2f7484.png)

![image](https://user-images.githubusercontent.com/7403780/71944499-e6b07680-31fe-11ea-865b-3e6207c008fb.png)

2. 挂载onedrive见下图。
![image](https://user-images.githubusercontent.com/7403780/71944336-6db11f00-31fe-11ea-982a-d192da372a5a.png)

**Comment by tangxuchao** [comment]
挂载的账户信息怎么填，因为之前是用的oneindex，而我有两个onedrive，所以想问一下怎么把两个都挂进去

**Comment by tangxuchao** [comment]
挂载失败
AADSTS500112: The reply address 'http://gossoon.herokuapp.com/' does not match the reply address 'https://reruin.github.io/redirect/onedrive.html' provided when requesting Authorization code. Trace ID: 704a9bb1-fc74-4097-9fee-45193a7c7a00 Correlation ID: 2c3616d3-848f-4dd5-88e0-164528c052fb Timestamp: 2020-01-08 06:57:59Z
![image](https://user-images.githubusercontent.com/42133265/71956943-69e5c280-3227-11ea-9217-22a5ebca3ca3.png)

是因为没弄这个吗：待挂载完成后，从sharelist管理后台导出配置文件，重新设置heroku的CONFIG项。

**Comment by reruin** [comment]
访问 https://gossoon.herokuapp.com/ 进行挂载。

**Comment by tangxuchao** [comment]
挂载，然后说失败，要不加Q聊聊？

**Comment by reruin** [comment]
刚测试了下，挂载成功。
你用的是个人版od么。

**Comment by tangxuchao** [comment]
用的是教育版5T那个

**Comment by reruin** [comment]
能把你的od账号密码 发我邮箱，我来挂。

**Comment by ZanderZhao** [comment]
# 情况1：无历史配置首次部署

## 情况1.1: 点击项目文档的deploy按钮

+ 点击项目文档或者项目里面的deploy按钮

+ 配置填`{}`一对英文半角大括号

+ 部署完成填写密码网站信息等

+ 挂载云盘

+ 点击导出配置

+ 在heroku对应app后台Settings>Reveal Config Vars>点击CONFIG后面铅笔表示修改>value填写刚才导出的配置

+ > 则以后每次休眠都会使用此配置

## 情况1.2：fork sharelist-heroku到自己仓库并连接heroku

+ 新建heroapp

+ 在heroku对应app后台Settings>Reveal Config Vars>添加`CONFIG`和`{}`>点击Add

+ 在heroku对应app后台Deploy>Deployment method>connect你的fork项目

+ 在heroku对应app后台Deploy>Manual deploy>选择master和点击Deploy Branch

+ 部署完成填写密码网站信息等

+ 挂载云盘

+ 点击导出配置

+ 在heroku对应app后台Settings>Reveal Config Vars>点击CONFIG后面铅笔表示修改>value填写刚才导出的配置

+ > 则以后每次休眠都会使用此配置

# 情况2：有历史配置需要更新

## 情况2.1直接从项目文档deploy的

+ > 思路按照情况1.1新建一个项目，把历史配置a更改

+ 点击项目文档或者项目里面的deploy按钮

+ 配置填`{}`一对英文半角大括号、

  + > 注意不要在此步直接粘贴老配置a，因为端口不一样，会和没有配置一个效果，只有重新唤醒是不改变端口的，deplay是改变端口的

+ 部署完成填写密码网站信息等

+ 挂载云盘

+ 点击导出新配置b

+ 将老配置a里面的端口换成新配置b里面端口，称换过端口的为配置c

+ 在heroku对应app后台Settings>Reveal Config Vars>点击CONFIG后面铅笔表示修改>value填写刚才导出的配置c

## 情况2.2直接从连接参考deploy更新

+ > 思路和2.1类似

+ 部署完成填写密码网站信息等

+ 点击导出配置b

+ 在heroku对应app后台Settings>Reveal Config Vars>点击CONFIG后面铅笔表示修改>value修改刚才的配置b端口，其他不修改
