### ISSUE TITLE
蓝奏云挂载失败

### ISSUE THREAD

**Issue by hl668** [reruin/sharelist#91]
蓝奏云分享链接https://www.lanzous.com/b0a2mg25i 没有设置密码，后台lanzou 的路径如下：
![1](https://user-images.githubusercontent.com/47386710/71959507-debbfb00-322d-11ea-865b-668637393d33.PNG)
然后打开前台蓝奏目录显示这个
![2](https://user-images.githubusercontent.com/47386710/71959536-ebd8ea00-322d-11ea-9f58-eea6de29a7e0.PNG)
也不知道是不是我挂载设置问题，作者麻烦你看一下，谢谢了

**Comment by reruin** [comment]
挂载内容里 把 / 去掉

**Comment by reruin** [comment]
lanzou的解析方式有所调整，更新代码后再试
