### ISSUE TITLE
docker版后台第一个设置保存不了 也没办法上传本地文件,看不到按钮

### ISSUE THREAD

**Issue by cjiasu** [reruin/sharelist#92]
![image](https://user-images.githubusercontent.com/40857324/71972667-120b8380-3248-11ea-81f7-ed0cb9fd9994.png)

**Comment by reruin** [comment]
你是自己build 还是 dockhub pull 的?

**Comment by cjiasu** [comment]
> 你是自己的建造还是dockhub pull的？

自己git的代码构造的

**Comment by cjiasu** [comment]
我发现挂载OneDrive看视频会跑服务器流量

**Comment by reruin** [comment]
后台关闭中转模式，不会走服务器流量。

**Comment by reruin** [comment]
第一项设置无法保存的问题已复现，此bug已修复。

**Comment by cjiasu** [comment]
> 1. “ docker版后台第一个设置保存不了”未复现此问题。
> 2. 后台关闭中转模式，不会走服务器流量。
![Uploading Screenshot_20200111-012423__01.jpg…]()

我一看视频服务器流网卡流量就爬上去了，中转默认都是关的

**Comment by cjiasu** [comment]
经测试会走服务器流量 大佬

**Comment by reruin** [comment]
能否将连接发出来，可以私发邮箱。

**Comment by cjiasu** [comment]
> 能否将连接发出来，可以私发邮箱。

TG发你  你好久没上线了
