### ISSUE TITLE
默认流量是通过 Server 还是原始地址？

### ISSUE THREAD

**Issue by ceecx** [reruin/sharelist#94]
RT，默认不会用本地 Server 中转网盘流量吧？

**Comment by reruin** [comment]
默认不中转：GoogleDrive、OneDrive API、OneDrive（文件id挂载）、Lanzous、HTTP(S)。  
受限于API限制 需强制使用中转：GoogleDrive API。  
需携带cookies做下一步操作 强制中转：OneDriveBusiness（文件id挂载）。

**Comment by ceecx** [comment]
感谢回复，如果使用服务器 Rclone 挂载 GoogleDrive，然后通过 ShareList 挂载本地文件，这种形式是走服务器流量么？

**Comment by ceecx** [comment]
另外反代的 Headers 是必须的么？因为没有使用 Nginx 和 Caddy，想用 LiteSpeed 做后端。

**Comment by ceecx** [comment]
感谢答疑，回头测试一下。

**Comment by ceecx** [comment]
这个 Issues 没关就直接回这里了。
Invalid parameter value for redirect_uri: Missing scheme: undefined
![image](https://user-images.githubusercontent.com/18570103/72488392-c6f6ff00-384b-11ea-9261-792a40fe1444.png)

信息都是正确获取了的，目前还没有做反代，直接访问的 ip:33001

**Comment by ceecx** [comment]
![image](https://user-images.githubusercontent.com/18570103/72488464-0291c900-384c-11ea-9fed-46c722fa528a.png)

如果使用第二步上传 json 文件，默认的应用机密和应用 ID 是和标注位置相反的，但是无论怎么更换顺序依然报错。。

**Comment by ceecx** [comment]
正确做完三部曲之后，点验证，页面会被刷新，信息清空，无返回任何提示。

**Comment by ceecx** [comment]
挂载 GoogleDrive 标识为 gd，访问会自动打开 GoogleDrive 首页，如果更改为其他标识则跳出上述的挂载 GoogleDrive 页面。

**Comment by reruin** [comment]
按下图添加挂载，之后进 gd1 目录。  
![image](https://user-images.githubusercontent.com/7403780/73132689-37c2c600-4059-11ea-9909-fcac43c9b3b0.png)

**Comment by ceecx** [comment]
> 按下图添加挂载，之后进 gd1 目录。
> ![image](https://user-images.githubusercontent.com/7403780/73132689-37c2c600-4059-11ea-9909-fcac43c9b3b0.png)

指的是进 gd1 的本地目录吗？我想用 Google Drive 方式挂载，并非 Google Drive API，因为用 API 经过服务器中转流量消耗有点大。。

**Comment by reruin** [comment]
普通方式挂载 只需在后台填入分享ID即可。但最近发现这种方式也需要强制中转。
