### ISSUE TITLE
是否可以像 gdindex 一样使用 cloudflare workers 做成流量中转？

### ISSUE THREAD

**Issue by 66508393** [reruin/sharelist#95]
是否可以像 gdindex 一样使用 cloudflare workers 做成流量中转？因为vps的流量有限与在国内访问速度比较慢！

**Comment by reruin** [comment]
sharelist 暂没有cf-worker版的开发计划。你可以使用 heroku 来解决流量的问题。

**Comment by 66508393** [comment]
我已经在 cloudflare workers 里搞了一个 goindex   

 https://nameless-boat-e7d2.timng.workers.dev/VIDEO/

在国内用cloudflare workers 比heroku快点

我的想法是  sharelist 里的 虚拟路径 把这个集成进去！这样子让 cloudflare workers来加速！

**Comment by reruin** [comment]
这个新增一个 cf-worker api版本走中转，目前没有时间，需要等到年后了。

**Comment by ntgeralt** [comment]
cf体验挺好的，不翻的情况下直接看视频速度从500KB/S慢慢到1.4MB/S

**Comment by yumin9822** [comment]
支持开发 cloudflare workers版。

**Comment by liangxinlin** [comment]
大佬，heroku怎么部署，怎么填
CONFIG Required
配置文件(JSON字符串 或 http远程文件)

**Comment by reruin** [comment]
> 大佬，heroku怎么部署，怎么填
> CONFIG Required
> 配置文件(JSON字符串 或 http远程文件)

两种方式
1. 从已有后台导出配置信息，填写进去。
2. 填```{}```，初始化，挂载网盘后，从后台复制出配置信息，前往此App 的 Settings->Reveal Config Vars 处，将配置信息赋给此变量。

**Comment by reruin** [comment]
> 支持开发 cloudflare workers版。

已实现cf-worker中转功能。请查看readme。
