### ISSUE TITLE
分享onedrive报错

### ISSUE THREAD

**Issue by liuquanhao** [reruin/sharelist#96]
设置one drive business后首页访问目录报错

Error
Looks like something broke!

        
TypeError: Cannot read property 'split' of undefined
    at folder (/root/sharelist/plugins/drive.od.js:105:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by liuquanhao** [comment]
已解决，是代码读取错了字段导致
https://github.com/reruin/sharelist/pull/97#issue-364062829

**Comment by liuquanhao** [comment]
这个是我在sharelist/plugins/drive.odb.js 113行打印的i值

`i: { ID: '2',
  PermMask: '0x3008031027',
  FSObjType: '0',
  HTML_x0020_File_x0020_Type: '',
  UniqueId: '{FB1E5DF0-C25F-4CB5-94C8-5821CEDA3F7D}',
  ProgId: '',
  NoExecute: '1',
  File_x0020_Type: 'm3u',
  'File_x0020_Type.mapapp': '',
  'HTML_x0020_File_x0020_Type.File_x0020_Type.mapcon': '',
  'HTML_x0020_File_x0020_Type.File_x0020_Type.mapico': '',
  'serverurl.progid': '',
  ServerRedirectedEmbedUrl: '',
  'File_x0020_Type.progid': '',
  'File_x0020_Type.url': 'FALSE',
  FileRef: '/personal/gglive_air-sama_com/Documents/sharelist/港澳台直播源.m3u',
  FileLeafRef: '港澳台直播源.m3u',
  CheckoutUser: '',
  CheckedOutUserId: '',
  IsCheckedoutToLocal: '0',
  _ComplianceFlags: '',
  _ShortcutUrl: '',
  '_ShortcutUrl.desc': '',
  _ShortcutSiteId: '',
  _ShortcutWebId: '',
  _ShortcutUniqueId: '',
  'Created_x0020_Date.ifnew': '1',
  ContentTypeId: '0x0101007FC4AE0B3726234FA07E27EC05B53EB7',
  Modified: '17/1/2020 下午 2:31',
  'Modified.': '2020-01-17 14:31:26',
  'Modified.FriendlyDisplay': '1|0|6|3',
  PrincipalCount: '2',
  Editor: 
   [ { id: '4',
       title: 'liuxu',
       email: 'gglive@air-sama.com',
       sip: '',
       picture: '' } ],
  FileSizeDisplay: '20532',
  ItemChildCount: '0',
  FolderChildCount: '0',
  ContentVersion: '2',
  DocConcurrencyNumber: '2',
  _VirusStatus: '0',
  '.spItemUrl': 'https://kyarucn-my.sharepoint.com:443/_api/v2.0/drives/b!J9uEgDsojkmGZTz9REwdVeOo5O8KnR9CtUm5wksNUMGoVonfknSMQp-qcvArvMa3/items/01Z4WUCS7QLUPPWX6CWVGJJSCYEHHNUP35?version=Published',
  '.fileType': 'm3u',
  '.hasThumbnail': 'True',
  '.hasVideoManifest': 'False',
  '.hasPdf': 'False',
  '.hasOfficePreview': 'False',
  '.hasBxf': 'False',
  '.hasGlb': 'False',
  '.hasHtml': 'False',
  '.ctag': '"c:{FB1E5DF0-C25F-4CB5-94C8-5821CEDA3F7D},2"',
  '.etag': '"{FB1E5DF0-C25F-4CB5-94C8-5821CEDA3F7D},2"' }
`

**Comment by liuquanhao** [comment]
额外说明，设置显示的文件夹名不能是协议名，如odb,onedrive等等

**Comment by reruin** [comment]
你说得很多，od非api版一直都有此问题。建议用api版本进行挂载。
