### ISSUE TITLE
OneDrive最新发现的Bug

### ISSUE THREAD

**Issue by hl668** [reruin/sharelist#98]
我的是5T的Onedrive账号，如果分享的一个文件夹里面内容过多，就是比如分享的这个文件夹里面子文件有100个，那么显示不了全部100个子文件列表，最多显示30个列表，我数了下，我这个就显示30个列表。剩下的并不能显示。清理过了缓存也是这样。也不知道这算不算是Bug吧，作者你可以看一下。。。

**Comment by reruin** [comment]
用的是 非api挂载么。

**Comment by hl668** [comment]
对，是Onedrive5T账号，后台那里我是把链接整个放上去挂载的。

**Comment by reruin** [comment]
是的。非API挂载一直存在此缺陷，暂无有效方案。建议使用api挂载。
