### ISSUE TITLE
中转似乎不起作用

### ISSUE THREAD

**Issue by DragonFSKY** [reruin/sharelist#99]
开启和不开启中转下载速度和在线播放加载的速度差别不大，用rclone挂载观看倒是挺快(应该不是服务器的问题)

**Comment by reruin** [comment]
可以的话发一下地址。由于api限制，GoogleDrive API 和OneDriveBusiness（文件id挂载）均会强制中转。

**Comment by DragonFSKY** [comment]
http://204.13.154.91:33001/ 是我哪里设置错了吗 顺便问问大佬 如果要挂载团队盘该如何操作

**Comment by reruin** [comment]
如果团队盘支持 api的话，直接api挂载即可。在后台挂载 GoogleDriveAPI :  
```
名称: 随意（不能是gda）
路径:  / 
```
保存后，进入对应目录，会出现挂载向导，按提示操作即可。

**Comment by DragonFSKY** [comment]
> 如果團隊盤支持api的話，直接api掛載即可。在後台掛載GoogleDriveAPI：
> 
> ```
> 名称: 随意（不能是gda）
> 路径:  / 
> ```
> 
> 保存後，進入對應目錄，會出現掛載嚮導，按提示操作即可。

如何操作呢，一路挂载下去并没有出现团队盘的选择，团队盘支持api
